config/crd/bases/workloads.cloudfoundry.org_cfapps.yaml, config/crd/bases/workloads.cloudfoundry.org_cfbuilds.yaml, config/crd/bases/workloads.cloudfoundry.org_cfdroplets.yaml, config/crd/bases/workloads.cloudfoundry.org_cfpackages.yaml, config/crd/bases/workloads.cloudfoundry.org_cfprocesses.yaml
Running `make manifests` caused diffs to appear. This aligns the bases with the CRD code.
Co-authored-by: Akira Wong <wakira@vmware.com>
=> Update manifests from CRD changes.

config/samples/app.yaml
#9 - this PR is to address [acceptance feedback ](https://github.com/cloudfoundry/cf-k8s-controllers/issues/9#issuecomment-909409925)
Remove appGUID label from config/samples/app.yaml file
No
=> Remove appGUID label from app.yaml in the config/samples directory

apis/networking/v1alpha1/cfroute_types.go, config/crd/bases/networking.cloudfoundry.org_cfroutes.yaml
Issue: [#23](https://github.com/cloudfoundry/cf-k8s-api/issues/23)
Remove the unused CFRoute.Port as our initial implementation only supports HTTP routing, which does not allow users to specify a port.
No.
Describe a CFRoute resource and see that it no longer includes a port.
@acosta11
=> Remove unused CFRoute.Port

PROJECT, apis/workloads/v1alpha1/cfapp_webhook.go, apis/workloads/v1alpha1/cfapp_webhook_integration_test.go, apis/workloads/v1alpha1/cfapp_webhook_test.go, apis/workloads/v1alpha1/cfpackage_webhook.go, apis/workloads/v1alpha1/cfpackage_webhook_integration_test.go, apis/workloads/v1alpha1/cfpackage_webhook_test.go, apis/workloads/v1alpha1/shared_types.go, apis/workloads/v1alpha1/webhook_suite_test.go, config/samples/cfpackage.yaml, config/webhook/manifests.yaml, main.go
#25 
Adds a mutating webhook to set `app-guid` label to match `spec.AppRef.name` on cfpackage record
No
Follow acceptance steps on the issue #25 
@Birdrock
=> Set app-guid label on CFPackage resource

README.md, dependencies/kpack/cluster-builder.yaml, dependencies/kpack/release-0.3.1.yaml, dependencies/kpack/serviceaccount.yaml, dependencies/kpack/stack.yaml, dependencies/kpack/store.yaml, hack/install-dependencies.sh
- Added manual kpack install instructions and dependencies
- updated README
Co-authored-by: Andrew Wittrock <awittrock@vmware.com>
closes https://github.com/cloudfoundry/cf-k8s-controllers/issues/45
Add manual instructions for installing and configuring kpack dependencies for app staging.
No
Follow new instructions in README
@Birdrock
=> Add manual kpack install instructions

docs/architecture-decisions/0004-managing-builders.md
https://github.com/cloudfoundry/cf-crd-explorations/issues/77
ADR capturing our initial strategy around the use of kpack builders
NA
Read and confirm it aligns with the team's understanding of builder management.
If accepted, update the status to accepted and merge.
@akrishna90
=> Add ADR for managing builders

README.md, dependencies/contour-1.18.1.yaml, hack/install-dependencies.sh
#56
Add installation instructions for Contour, a dependency for our initial routing implementation.
No
Follow the README installation instructions and see that contour is installed by inspecting the pods created: `kubectl get pods -n projectcontour -o wide`.
cc @davewalter
=> Add installation instructions for Contour

README.md, apis/workloads/v1alpha1/shared_types.go, config/cf/cf_k8s_controllers_config.yaml, config/cf/config.go, config/kpack/service_account.yaml, config/samples/cfbuild.yaml, config/samples/cfpackage.yaml, controllers/workloads/cfbuild_controller.go, controllers/workloads/cfbuild_controller_integration_test.go, controllers/workloads/cfbuild_controller_test.go, controllers/workloads/fake/cfclient.go, controllers/workloads/shared.go, controllers/workloads/testutils/shared_test_utils.go, hack/install-dependencies.sh, reference/cf-k8s-controllers.yaml
#43 
CFBuild Controller can now watch kpack images for completion. Based on the completion status, it now updates CFDroplet fields on CFBuild's status.  
No.
Follow acceptance steps on issue #43
=> Set CFDroplet fields on CFBuild.Status when Kpack Image succeeds

README.md
this is related to #42 
updating readme to fix the broken path for installing kpack dependency
No
Install kpack dependencies should work.
=> Fix path to kpack yaml file in README

apis/workloads/v1alpha1/integration/cfapp_webhook_integration_test.go, apis/workloads/v1alpha1/integration/cfbuild_webhook_integration_test.go, apis/workloads/v1alpha1/integration/cfpackage_webhook_integration_test.go, apis/workloads/v1alpha1/integration/cfprocess_webhook_integration_test.go, apis/workloads/v1alpha1/integration/webhook_suite_integration_test.go, apis/workloads/v1alpha1/webhook_suite_test.go, controllers/networking/cfroute_controller_test.go, controllers/networking/integration/suite_integration_test.go, controllers/networking/suite_test.go, controllers/workloads/cfapp_controller_test.go, controllers/workloads/cfbuild_controller_test.go, controllers/workloads/integration/cfapp_controller_integration_test.go, controllers/workloads/integration/cfbuild_controller_integration_test.go, controllers/workloads/integration/suite_integration_test.go, controllers/workloads/suite_test.go, go.mod, webhooks/workloads/cf_workloads_validation_errors_test.go, webhooks/workloads/cfapp_validation_test.go, webhooks/workloads/integration/cfapp_validation_integration_test.go, webhooks/workloads/integration/suite_integration_test.go, webhooks/workloads/suite_test.go
After converting tests from spec to ginkgo, this PR separates unit and integration tests by moving integration tests to a separate package.
Acceptance:
make test
=> Separate int tests

docs/architecture-decisions/0003-strategy-for-testing-frameworks.md
Created an ADR to document our initial decision to use spec and gomega for our testing framework on cf-on-k8s projects.
Co-authored-by: Matt Royal <mroyal@vmware.com>
=> Add ADR for testing frameworks

docs/architecture-decisions/0004-strategy-for-continuous-integration.md
Created an ADR to document our initial decision to use github actions for our CI on cf-on-k8s projects.
Co-authored-by: Andrew Wittrock <awittrock@vmware.com>
=> Add ADR for Strategy for Continuous Integration

README.md, dependencies/contour-1.18.2.yaml, go.mod, go.sum, hack/install-dependencies.sh
No
Make the GCP service account JSON arg optional when running the install-dependencies script so that it can be used in the setup step for the API's e2e tests. Also, bump Contour to 1.18.2.
No
@acosta11
=> Make the GCP Service Account JSON Arg Optional When Running the Install-Dependencies Script

README.md
#59 
Add Ingress Configuration and Domain Management Instructions to the README.
No
Follow the steps in the README to configure ingress and manually create CFDomain resources.
@acosta11
=> Add Ingress Configuration and Domain Management Instructions to the README

apis/workloads/v1alpha1/cfbuild_types.go, config/crd/bases/workloads.cloudfoundry.org_cfbuilds.yaml, config/samples/cfbuild.yaml, controllers/workloads/cfbuild_controller.go, controllers/workloads/integration/cfbuild_controller_integration_test.go
resolves https://github.com/cloudfoundry/cf-k8s-controllers/issues/77
Set Stack used for building Image on BuildDropletStatus
- modified the CFBuild CR to add a new status field droplet.stack
- enhanced CFBuild controller to take the Status.latestStack from the kpack image and add it to the CFBuild.Status.droplet
no
Follow README instructions to install dependencies and controllers.
kubectl apply -f config/samples/cfapp.yaml
kubectl apply -f config/samples/cfpackage.yaml
kubectl apply -f config/samples/cfbuild.yaml
monitor the kpack images until the build is successful
watch kubectl get images
Then pull the cfbuild and confirm that processTypes and ports are set
k get cfbuilds 1591ee05-e208-4cf3-a662-1c2da42f20a7 -o yaml
@akrishna90
=> Set Stack used for building Image on BuildDropletStatus

config/rbac/role.yaml, config/samples/cfbuild.yaml, controllers/workloads/cfbuild_controller.go, reference/cf-k8s-controllers.yaml
Fixes rejection from https://github.com/cloudfoundry/cf-k8s-controllers/issues/44
Adds RBAC to CFBuild controller to fix issues with the deployment version of the controllers
no
Follow README instructions to install dependencies and controllers.
`kubectl apply -f config/samples/cfapp.yaml`
`kubectl apply -f config/samples/cfpackage.yaml`
`kubectl apply -f config/samples/cfbuild.yaml`
monitor the kpack images until the build is successful
`watch kubectl get images`
Then pull the cfbuild and confirm that processTypes and ports are set
`k get cfbuilds 1591ee05-e208-4cf3-a662-1c2da42f20a7 -o yaml`
@Birdrock
=> Fix RBAC issues with CFBuild Controller

docs/architecture-decisions/0008-merge-cf-k8s-repositories.md
N/A
This PR adds a new ADR recording the decision to merge the `cf-k8s-api` and `cf-k8s-controllers` repositories together. The status of the ADR is `accepted` with the assumption that merging the PR equates to accepting the decision. If we decide not to move forward with this, we should just close the PR.
Yes
Read the ADR and raise any concerns in a review.
=> Add ADR for merging code repositories

controllers/README.md
#119 
Fixes a typo in the readme that sets the eirini-webhooks-certs secret name incorrectly.
No
Follow the readme to install the eirini-controller and validate that the line below matches the create secret line in the readme.
```
kubectl create secret -n eirini-controller generic eirini-webhooks-certs --from-file=tls.crt=./tls.crt --from-file=tls.ca=./tls.crt --from-file=tls.key=./tls.key
```
=> Fixes a typo in the readme for the Eirini secret.

controllers/apis/networking/v1alpha1/cfroute_webhook.go, controllers/apis/workloads/v1alpha1/cfapp_webhook.go, controllers/apis/workloads/v1alpha1/cfbuild_webhook.go, controllers/apis/workloads/v1alpha1/cfpackage_webhook.go, controllers/apis/workloads/v1alpha1/cfprocess_webhook.go, controllers/config/webhook/manifests.yaml, controllers/reference/cf-k8s-controllers.yaml, controllers/webhooks/workloads/cfapp_validation.go, controllers/webhooks/workloads/subnamespaceanchor_validation.go
- https://github.com/cloudfoundry/cf-k8s-controllers/issues/135
Removing references to a domain that we do not control.
- Yes, it will break upgrades by creating duplicate webhooks. Now is a good time to do it though, since we haven't cut a release.
- Tests should pass
@acosta11 @davewalter
=> Rename webhooks to refer to our own domain

api/README.md, api/config/base/ingress.yaml, api/config/overlays/kind/kustomization.yaml, api/reference/cf-k8s-api.yaml, controllers/Makefile, controllers/config/manager/kustomization.yaml, controllers/config/manager/manager.yaml
#136 
This PR adds configuration for a TLS certificate for the API endpoint and updates the README to tell the user how to create the required certificate and secret.
No
See #136 
@acosta11 
Note: This is the same PR as https://github.com/cloudfoundry/cf-k8s-api/pull/202, just moved to the new mono-repo.
=> Add TLS configuration for API endpoint

.github/dependabot.yml
No
This PR adds docker and github-actions sections to the dependabot config
No
Wait for PRs to be created to bump dependencies in the Dockerfiles and github workflow actions.
=> Add docker and github-actions to dependabot config

controllers/main.go
#72 
While running acceptance @PureMunky pointed that a nil pointer exception was being thrown.
We traced the root cause for it to be a uninitialized logger on CFProcessReconciler. 
No.
Repeat acceptance steps from #72 
@davewalter
=> Assign logger while initializing CFProcessReconciler object

controllers/config/manager/manager.yaml, controllers/reference/cf-k8s-controllers.yaml
#116 
This PR removes the command from the controller deployment template as it is provided by the entrypoint of the image.
No
Follow the instructions in the README to deploy the controller manager and see that it starts normally.
=> Remove command from controllers deployment

api/apis/integration/apply_manifest_test.go, api/apis/space_manifest_handler.go, api/apis/space_manifest_handler_test.go, api/docs/api.md, api/main.go, go.mod, go.sum
* https://github.com/cloudfoundry/cf-k8s-controllers/issues/210
Newer CF CLIs hit this endpoint to be able to display a diff of the current state of their app with the manifest that they're applying. We first need to implement the ability to generate manifests before we can implement true diffing, so for now this endpoint will always return an empty diff. For more information check out the issue: https://github.com/cloudfoundry/cf-k8s-controllers/issues/210
Nope
Follow the A/C on the issue.
@matt-royal @gnovv
=> Add minimal space manifest diff endpoint

api/apis/app_handler.go, api/apis/app_handler_test.go, api/docs/api.md
- Issue: https://github.com/cloudfoundry/cf-k8s-controllers/issues/174
Add endpoint for retrieving the droplet currently assigned to an app.
Nope
In general, follow the steps on https://github.com/cloudfoundry/cf-k8s-controllers/issues/174.
I had to do the following to get a suitable `CFBuild` with droplet info in the status:
1. `kubectl apply -f controllers/config/samples/cfapp.yaml`
2. `kubectl apply -f controllers/config/samples/cfbuild.yaml`
3. `kubectl proxy &`
4. Then hit the proxied Kubernetes API with the following to add droplet info to the build:
```console
curl -k -s -X PATCH -H "Accept: application/json, */*" \
-H "Content-Type: application/merge-patch+json" \
http://127.0.0.1:8001/apis/workloads.cloudfoundry.org/v1alpha1/namespaces/default/cfbuilds/1591ee05-e208-4cf3-a662-1c2d …
```
=> Add GET /v3/apps/<guid/droplets/current endpoint

api/apis/fake/cfrole_repository.go, api/apis/role_handler.go, api/apis/role_handler_test.go, api/apis/shared.go, api/config/base/config/role_mappings_config.yaml, api/payloads/role.go, api/presenter/role.go, api/reference/cf-k8s-api.yaml, api/repositories/role_repository.go, api/repositories/role_repository_test.go, api/tests/e2e/roles_test.go, controllers/config/cf_roles/cf_org_manager.yaml, controllers/config/cf_roles/kustomization.yaml, controllers/reference/cf-k8s-controllers.yaml, go.mod, go.sum
Issue: https://github.com/cloudfoundry/cf-k8s-controllers/issues/166
User can create an org level role binding via the API.
No
**GIVEN** an organisation exists
**AND** a user other than the admin exists
**AND** a `ClusterRole` exists
**WHEN** I make the following request:
```sh
curl "https://api.example.org/v3/roles" \
-X POST \
-H "Content-Type: application/json" \
-d '{
"type": "<the ClusterRole name>",
"relationships": {
"user": {
"data": {
"username": "<the username>"
}
},
"organization": {
"data": {
"guid": "<the org GUID>"
}
}
}
}'
```
**THEN** I get the following response:
```
HTTP/1.1 201 Created
Content-Type: application/json
```
```json
{
"guid": "40557c70-d1bd-4976-a2ab-a85f5e882418",
"created_at": "2019-10-10T17:19:12Z",
"updated_at": "2019-10-10T17:19:12Z",
"type": "<the …
```
=> Implement creating an org level role binding in the API

api/Dockerfile, controllers/Dockerfile
No
Introduce a cache for `go mod download` so that building docker files repeatedly speeds up.
No
`make docker-build` works and runs quickly on subsequent occasions
=> Use docker cache volume for go mod download

controllers/controllers/workloads/cfbuild_controller.go, controllers/controllers/workloads/cfbuild_controller_test.go, controllers/controllers/workloads/integration/cfbuild_controller_integration_test.go, controllers/controllers/workloads/testutils/shared_test_utils.go
#69 
Sets owner references on Kpack Image when created by CFBuild controller.
No.
Automation:
* Run tests.
Manual:
* Install/Deploy to cluster.
* Apply CFApp, CFPackage, CFBuild to cluster.
* Describe resulting Kpack image. `kubectl describe image <image-name>`
* Look for `Owner References`
@davewalter @acosta11
=> kpack Image OwnerReferences are set upon creation

controllers/config/samples/cfapp.yaml, controllers/config/samples/cfbuild.yaml, controllers/config/samples/cfdomain.yaml, controllers/config/samples/cfpackage.yaml, controllers/config/samples/cfprocess.yaml, controllers/config/samples/cfroute.yaml, controllers/controllers/workloads/cfbuild_controller.go, controllers/controllers/workloads/cfbuild_controller_test.go, controllers/controllers/workloads/integration/cfbuild_controller_integration_test.go, controllers/docs/architecture-decisions/0006-managing-builders.md, dependencies/kpack/cluster_builder.yaml, dependencies/kpack/service_account.yaml, dependencies/namespace.yaml, scripts/install-dependencies.sh
#229 
Existing installations will need to update the `kpack-service-account` ServiceAccount and `image-registry-credentials` Secret.
Run all tests.
=> Align Kpack and Eirini workloads namespace

api/main.go, api/repositories/authorization/cert_inspector.go, api/repositories/authorization/cert_inspector_test.go, api/repositories/authorization/identity_provider.go, api/repositories/authorization/identity_provider_test.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/orgs_test.go, go.mod, go.sum
https://github.com/cloudfoundry/cf-k8s-controllers/issues/168
When auth uses the ClientCert type, the identity provider can get the username by decoding the passed client certificate and extracting the common name from the subject.
No
1. Deploy the API on kind (`make test-e2e` will do that as a side effect)
2. Build the CF CLI client from https://github.com/eirini-forks/cli (`make build` and use the binary from the `out` dir)
3. `cf api http://localhost`
4. `cf login` and select the entry for kind-e2e -- this now works, rather than failing when listing orgs
5. `cf orgs` -- this also no longer fails, although currently you'll need to create a rolebinding for your user in the cf-k8s-api-system namespace in order to see any orgs (e.g. `kubectl create rolebinding admin --clusterrole …
=> Teach identity provider how to read client certs

controllers/controllers/networking/integration/cfroute_controller_integration_test.go, controllers/controllers/networking/integration/suite_integration_test.go
https://github.com/cloudfoundry/cf-k8s-controllers/issues/120
CFRoutes controller integration tests frequently failed because of their `Eventually` expectations time out. This change gets rid of the 2 second timeout in the test and sets the default eventually timeout in the suite to 10 seconds. Hopefully this would be enough
No
Run tests, they should succeed
=> Fix flaky cfroutes controller flaky tests

api/main.go
https://github.com/cloudfoundry/cf-k8s-controllers/issues/164
We missed registering this handler in https://github.com/cloudfoundry/cf-k8s-controllers/pull/224 😛 
No
Same as:
*  https://github.com/cloudfoundry/cf-k8s-controllers/issues/164
* https://github.com/cloudfoundry/cf-k8s-controllers/pull/224
=> Register JobHandler under /v3/jobs/:guid

api/apis/root_handler_test.go, api/presenter/root.go
Addresses https://github.com/cloudfoundry/cf-k8s-controllers/issues/209
Bumps the presented v3 API version so that the `cf` CLI stops complaining and appends a `+cf-k8s` suffix to the version to disambiguate it from Cloud Controller
No
1. Hit the root `/` endpoint and see the version updated
2. Target the API with the `cf` CLI and see that it doesn't error
=> Bump v3 API Version

api/payloads/domain.go, api/payloads/domain_test.go, api/payloads/payloads_suite_test.go, api/repositories/domain_repository.go, api/repositories/domain_repository_test.go
- https://github.com/cloudfoundry/cf-k8s-controllers/issues/177
Hitting `GET /v3/domains` without a `names` filter would always return an empty list of domains instead of all visible domains. This change adds some tests and improves the param parsing to correctly interpret omitting the `names` param as empty.
No
1. Apply a `CFDomain` CR to the cluster
2. `curl /v3/domains` and see the domain in the response
=> Fix GET /v3/domains names param parsing

api/apis/org_handler.go, api/apis/role_handler_test.go, api/payloads/role.go, api/repositories/role_repository.go, api/repositories/role_repository_test.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/orgs_test.go, api/tests/e2e/roles_test.go, api/tests/e2e/spaces_test.go
No
Now we have proper API endpoints for creating orgs, spaces and role (bindings), we should use them rather than creating the base k8s objects.
Since creating role only supported the `User` kind, we have changed the API to allow setting roles on service accounts by
passing `KubernetesServiceAccount` relationship instead of `User`.
No
`make test-e2e` still works!
@eirini
=> Refactor e2e tests to use API where possible

Makefile, scripts/run-tests.sh
- Replace deprecated ginkgo command line arguments with the new ones
- Set the e2e slow test threshold
- remove the .test file that was accidentally committed
=> Change ginkgo flags to v2 counterparts

api/apis/log_cache_handler.go, api/apis/log_cache_handler_test.go, api/apis/root_handler_test.go, api/docs/api.md, api/main.go, api/presenter/root.go
- https://github.com/cloudfoundry/cf-k8s-controllers/issues/222
Adds basic log-cache endpoints that return hard-coded empty responses to support `cf push`. No logs will be returned, but at least the CLI won't error.
No
Follow the A/C on https://github.com/cloudfoundry/cf-k8s-controllers/issues/222.
=> Add minimal log-cache API endpoints to support cf push

controllers/config/samples/cfroute.yaml
No
This PR updates the sample CFRoute appRef to point at the sample CFApp. This means that applying all of the sample resources should result in a routable workload.
No
Deploy the sample resources to a suitably configured cluster running the API and controllers and verify that the CFRoute resource results in a service that correctly targets the pods for the workload created from the CFApp/CFPackage/CFBuild resources.
=> Update the sample CFRoute appRef to point at the sample CFApp

api/repositories/app_repository.go
No
This PR updates the `app-guid` label applied to the app env var secret to match similar labels applied to other resources.
No
Push an app with an env var and check the label on the secret that is created.
=> Fix the app-guid label applied to the app env var secret

api/config/base/rbac/role.yaml, api/reference/cf-k8s-api.yaml, api/repositories/pod_repository.go
Nope
Pods are actually in the '""' apiGroup. Without this you get an error like this:
```
2021-11-17T23:34:25.840Z	ERROR	ProcessHandler	Failed to fetch process from Kubernetes	{"ProcessGUID": "5a8bae25-47d0-11ec-8560-ce6c6a3b098d", "error": "pods is forbidden: User \"system:serviceaccount:cf-k8s-api-system:cf-k8s-api-cf-admin-serviceaccount\" cannot list resource \"pods\" in API group \"\" in the namespace \"49c31b07-bf89-45c0-8eef-401efd0fa7e5\""}
```
No
The `GET /v3/process/:guid/stats` endpoint should work better with this.
@akrishna90 @Birdrock
=> Fix RBAC for retrieving Pods

controllers/apis/networking/v1alpha1/cfdomain_types.go, controllers/apis/networking/v1alpha1/cfroute_types.go, controllers/config/crd/bases/networking.cloudfoundry.org_cfdomains.yaml, controllers/config/crd/bases/networking.cloudfoundry.org_cfroutes.yaml, controllers/controllers/networking/cfroute_controller.go, controllers/controllers/networking/cfroute_controller_test.go, controllers/controllers/networking/integration/cfroute_controller_integration_test.go, controllers/reference/cf-k8s-controllers.yaml
#101 
This PR updates the CFRoute reconcile loop to set the FQDN and URI status fields
No
See #101
=> Set the FQDN and URI status fields on a CFRoute

.gitignore, controllers/apis/networking/v1alpha1/cfroute_types.go, controllers/config/crd/bases/networking.cloudfoundry.org_cfroutes.yaml, controllers/controllers/networking/cfroute_controller.go, controllers/controllers/networking/cfroute_controller_test.go, controllers/controllers/networking/shared.go, controllers/controllers/networking/suite_test.go, controllers/reference/cf-k8s-controllers.yaml
resolves #102
Adds status fields to CFRoute for whether it is valid or not
No
Follow README to install CRDs and run Controllers
apply `config/samples/cfroute.yaml`
confirm that its status field are set to Valid: false
apply `config/samples/cfdomain.yaml`
confirm that the cfroute status fields are Valid:true
@akrishna90
=> #102 Kubectl user can see whether a CFRoute is valid or invalid

api/repositories/app_repository_test.go
Fixes a flaky test I introduced in https://github.com/cloudfoundry/cf-k8s-controllers/pull/270 😔 
- The order that the apps get returned by the K8s API is
non-deterministic
- Issue https://github.com/cloudfoundry/cf-k8s-controllers/issues/266
@gnovv
=> Fix flaky app filtering test

api/config/base/ingress.yaml, api/reference/cf-k8s-api.yaml
Not specifically, but it was uncovered by https://github.com/cloudfoundry/cf-k8s-controllers/issues/170
- By default Contour/Envoy set a 15 second timeout for the API shim to
respond to requests
- https://projectcontour.io/docs/main/config/api/#projectcontour.io/v1.TimeoutPolicy
- Certain endpoints like app restart and package upload are known to take longer than this
- Eventually we should deal with timeouts more holistically, but for now let's just set it to something high
No
Restarting an app should be less flaky. Prior to this you might see behavior and errors like this:
```
Waiting for app node to start...
REQUEST: [2021-11-18T15:47:52-07:00]
POST /v3/apps/c3147553-5639-4094-8d95-00f789734577/actions/restart HTTP/1.1
Host: api.example.com
Accept: application/json
Authorization: …
```
=> Increase response timeout for the API

README.md, api/config/base/config/cf_k8s_api_config.yaml, api/config/overlays/kind-auth-enabled/config/cf_k8s_api_config.yaml, api/config/overlays/kind/config/cf_k8s_api_config.yaml, api/reference/cf-k8s-api.yaml, scripts/deploy-on-kind.sh, scripts/install-dependencies.sh, scripts/run-tests.sh
#243
Update HNC config script to propagate secrets and not service accounts
No
Install cf dependencies with the install-dependencies.sh script
Install cf on a cluster with auth disabled  using the make deploy target
Configure ingress as necessary
Login to the cf api
Follow instructions in the README.md for `Space Creation` to create a space with image build configured
Apply sample resources as necessary to trigger a build
pair w/ @davewalter
=> Manually propagate kpack service-account

.github/workflows/test-build-push-main.yml, .github/workflows/test-pr.yml, api/tests/e2e/e2e_suite_test.go, scripts/deploy-on-kind.sh
No
1. Contour may take up to 5 minutes to start, so extend the before suite timeout to 5 minutes
2. The controllers and api images need to be loaded into kind when running locally _and_ when running in github actions
3. Unify the *_IMG variable names
No
Locally, `make test-e2e` should work.
Remotely, github actions should work for PRs and on main.
@georgethebeatle, @cloudfoundry/eirini
=> Fix e2e in github actions

api/tests/e2e/e2e_suite_test.go, api/tests/e2e/helpers/fail_handler.go
This introduces a Ginkgo fail handler that will capture logs from `Pod`s we are interested in on end-to-end test failures. This can get quite verbose, so we'll possibly have to tweak the number of lines printed, but it's super useful to understand the reason tests are failing, especially for flakes.
=> Capture Kubernetes logs on e2e failures

Makefile, scripts/deploy-on-kind.sh
#151
Make sure the yaml reference is updated automatically when e2e tests are run. This way we will avoid yaml drift failures.
No
make test-e2e should update the yaml reference 
=> Ensure build-reference gets run so that check always succeeds

api/repositories/role_repository.go, api/repositories/role_repository_test.go, api/tests/e2e/roles_test.go
This was needed as usernames with `@`s in them (which are not allowed in labels) were causing failures. Fixes #280.
=> Remove unused labels from `RoleBinding`s

.github/workflows/test-build-push-main.yml, scripts/run-tests.sh
https://github.com/cloudfoundry/cf-k8s-controllers/issues/286
Publish code coverage report to [codeclimate](https://codeclimate.com/github/cloudfoundry/cf-k8s-controllers)
No
Unfortunately this is one of those changes that you can't really test fully until it makes its way to the `main` branch.
I tried to test as much as possible by doing the same changes to the pr workflow and making sure the actions are
passing.
Here is what should happen after the workflow executes successfully on `main`:
- https://codeclimate.com/github/cloudfoundry/cf-k8s-controllers should display coverage percentage
- https://codeclimate.com/github/cloudfoundry/cf-k8s-controllers/code should display coverage percentage
- In the above page when you click on a file it should visualize line coverage. …
=> Generate and publish code coverage reports

.github/workflows/test-build-push-main.yml, .github/workflows/test-pr.yml
No
Remove dependency of e2e tests to other tests thus making execution more
parallel. Pushing of the docker images now depends on all tests, since
they run in a more parallel fashion.
No
Checks are green.
=> Make checks a bit faster

README.md
#286 
Adding some badges about code quality to the readme
No
There should be three shiny badges on the top of the README.md
=> Add code quality badges to README.md

controllers/webhooks/workloads/integration/cfapp_validation_integration_test.go
https://github.com/cloudfoundry/cf-k8s-controllers/issues/100
Randomize the names of the objects that the test create in order to avoid name collisions during parallel test execution
No
All tests should pass
@mnitchev
=> Make the cfapp validation test more resilient

.codeclimate.yml
https://github.com/cloudfoundry/cf-k8s-controllers/issues/304
Introduce a codeclimate config file with generated code excluded, hopefully codeclimate would pick that up
No
Generated code is excluded from the coverage report. unfortunately can be only verified after the change has been merged into main.
=> Introduce codeclimate config

.codeclimate.yml, .github/workflows/test-build-push-main.yml
#304 
Removes fakes, generated code and vendor from the coverage report, so that we have a more accurate number.
No
1. Open coverage report on codeclimate
2. Notice there are no fakes, generated or vendor in the file paths
=> Remove files that contain fake, vendor or generated from coverage

Makefile, scripts/run-tests.sh
https://github.com/cloudfoundry/cf-k8s-controllers/issues/302
Get rid of limiting Ginkgo nodes (except for controllers tests) during test runs to make running tests faster
No
Run all tests, see them pass
=> Only limit ginkgo nodes for controllers tests

README.md, scripts/install-dependencies.sh
Co-authored-by: Julian Hjortshoj <hjortshojj@vmware.com>
> Thanks for contributing!
>
> We've designed this PR template to speed up the PR review and merge process - please use it.
Fixes #213
Update developer docs and scripts
- Add instructions to manually deploy HNC
- update install-dependencies script to use v0.9.0 in its new location
- fix references to `hack` folder
- updated instructions to reflect current `make` targets
No
Use docs to install cf-k8s controllers and api
@davewalter
=> Update developer docs and scripts

README.md
#213
It updates the manual HNC install instructions to clarify that the HNC plugin needs to be in the $PATH
no
Follow the manual HNC installation instructions.
Verify that you don't see errors when using `kubectl hnc`. 
@davewalter
=> Update HNC manual installation instructions

.github/workflows/test-build-push-main.yml
We have fixed this [issue](https://github.com/codeclimate/test-reporter/issues/479) in our [fork](https://github.com/eirini-forks/test-reporter) of the codeclimate test reporter. We are switching to using it directly until it gets merged and released.
=> Use our fork of the codeclimate test-reporter

api/actions/fake/cfprocess_repository.go, api/actions/scale_app_process.go, api/actions/scale_app_process_test.go, api/actions/shared.go, api/apis/app_handler.go, api/apis/app_handler_test.go, api/apis/fake/cfprocess_repository.go, api/apis/fake/cfroute_repository.go, api/apis/process_handler.go, api/apis/process_handler_test.go, api/apis/route_handler.go, api/apis/route_handler_test.go, api/docs/api.md, api/payloads/app.go, api/payloads/process.go, api/payloads/route.go, api/presenter/process.go, api/repositories/app_repository.go, api/repositories/app_repository_test.go, api/repositories/process_repository.go, api/repositories/process_repository_test.go, api/repositories/route_repository.go, api/repositories/route_repository_test.go
#313 
App developer can view apps in a space using `cf apps`
- add support for order_by=name query parameter on GET /v3/apps
- we have enabled ordering by name as default behaviour
- add support for filtering by app_guids on
- GET /v3/processes endpoint
- GET /v3/routes endpoint
- update api docs
No
- Deploy cf-k8s-api and cf-k8s-controllers
- Use the `cf cli` to push and app
- Run `cf apps` and verify the output
@julian-hj
=> App developer can view apps in a space using `cf apps`

controllers/config/manager/manager.yaml, controllers/reference/cf-k8s-controllers.yaml
Co-authored-by: Ashwin Krishna <krishnaas@vmware.com>
No
Update cf-on-k8s controller deployment to set resource request and limit to more reasonable values to prevent OoM crashloop.
no
deploy the controllers and CRDs, for example:
`kubectl apply -f controllers/reference/cf-k8s-controllers.yaml`
@akrishna90
=> Fix controller deployment resource req and limit

api/apis/app_handler_test.go, api/apis/route_handler_test.go, api/apis/service_route_binding_handler.go, api/apis/service_route_binding_handler_test.go, api/main.go, api/payloads/app.go, api/payloads/route.go, api/presenter/service_route_binding.go, api/repositories/app_repository.go, api/repositories/app_repository_test.go, api/repositories/route_repository.go, api/repositories/route_repository_test.go
#308 
App Developer can run `cf routes` to list routes
No
Follow README to deploy `cf-k8s-api` and `cf-k8s-controllers`
and then follow acceptance steps on #308 
@acosta11 @julian-hj
=> App Dev/Operator can list routes with `cf routes`

Makefile, README.md, controllers/config/base/kustomization.yaml, controllers/config/base/workloads_tls_delegation.yaml, controllers/config/config.go, controllers/config/overlays/kind/controllersconfig/cf_k8s_controllers_config.yaml, controllers/config/overlays/kind/kustomization.yaml, controllers/controllers/networking/cfroute_controller.go, controllers/controllers/networking/cfroute_controller_test.go, controllers/controllers/networking/integration/cfroute_controller_integration_test.go, controllers/controllers/networking/integration/suite_integration_test.go, controllers/main.go, controllers/reference/cf-k8s-controllers.yaml
#148 
Operators can now configure TLS for their workloads. If they leave the default behavior, all routes will respond to HTTP only.  If they follow the new instructions in the readme, then routes will respond to HTTPS requests using the cert they configure, and HTTP requests will be redirected to HTTPS.
No. The behavior is the same by default, and TLS is only enabled if they take manual action.
Follow the README instructions to deploy the app normally, then deploy an app and create a route for it. Confirm that you can curl the app via http, but not via https.
Tear down the cluster from the first part, then deploy a new cluster following the README instructions for adding TLS to workloads. Deploy an app and create a route. Confirm that you can curl the app via HTTPS, and that HTTP …
=> Issue 148 - Configure TLS for workloads ingress

.github/workflows/test-build-push-main.yml
This reverts commit e84f255d11e19b5f2de6d969a14eb16191d0d345.
The fix in the codeclimate test reporter is now released in v0.10.2
so we can use the github action again.
=> Revert "Use our fork of the codeclimate test-reporter"

api/apis/route_handler_test.go, api/payloads/destination.go, api/presenter/route.go, api/repositories/route_repository.go, controllers/config/samples/cfdomain.yaml
#330 
This PR properly handles route destination protocol
- move defaulting of the protocol value from the presenter to the
message
- allow the client to specify a destination protocol
- clean up confusing test values (http vs http1)
- remove label from sample CFDomain resource
No
See #330 
@acosta11
=> Properly handle route destination protocol

README.md, controllers/config/base/controllersconfig/cf_k8s_controllers_config.yaml, controllers/config/config.go, controllers/config/overlays/kind/controllersconfig/cf_k8s_controllers_config.yaml, controllers/controllers/networking/integration/suite_integration_test.go, controllers/controllers/workloads/cfbuild_controller.go, controllers/controllers/workloads/integration/cfbuild_controller_integration_test.go, controllers/controllers/workloads/integration/suite_integration_test.go, controllers/reference/cf-k8s-controllers.yaml
#329 
This change allows the platform operator to specify a different cluster builder to be used for kpack builds.
No
Follow acceptance on #329 
@acosta11
=> Platform Operator can configure name of ClusterBuilder

api/apis/route_handler.go, api/apis/route_handler_test.go, api/docs/api.md, api/payloads/route.go, api/presenter/route.go, api/repositories/route_repository.go, api/repositories/route_repository_test.go
#309
This PR implements filtering by domain_guids, hosts and paths for the GET /v3/routes endpoint as required for the `cf map-route` command.
No
See #309
@julian-hj
=> Implement filtering for GET /v3/routes

api/repositories/route_repository.go, api/repositories/route_repository_test.go, controllers/apis/networking/v1alpha1/cfroute_types.go, controllers/config/crd/bases/networking.cloudfoundry.org_cfroutes.yaml, controllers/controllers/networking/integration/cfroute_controller_integration_test.go, controllers/controllers/workloads/integration/cfbuild_controller_integration_test.go, controllers/reference/cf-k8s-controllers.yaml
#330 
This PR adds the route destination protocol field to the CFRoute CRD and sets/gets it in the API.
No
See #330
@julian-hj
=> Add protocol to CFRoute CRD

dependencies/kpack/cluster_store.yaml
No
This PR temporarily pins the buildpacks in the `cf-default-buildpacks` clusterstore to versions that are known to work with kpack v0.4.1.
No
Deploy as normal with the `scripts/install-dependencies.sh` script and verify that you can successfully push an app.
=> Temporarily pin buildpacks

README.md, api/apis/fake/cfrole_repository.go, api/apis/org_handler.go, api/apis/org_handler_test.go, api/apis/role_handler.go, api/apis/role_handler_test.go, api/apis/space_handler.go, api/apis/space_handler_test.go, api/config/base/rbac/role.yaml, api/main.go, api/payloads/org.go, api/payloads/role.go, api/payloads/space.go, api/reference/cf-k8s-api.yaml, api/repositories/fake/cforg_repository.go, api/repositories/fake/cfspace_repository.go, api/repositories/org_repository.go, api/repositories/org_repository_test.go, api/repositories/repositories_suite_test.go, api/repositories/role_repository.go, api/repositories/role_repository_test.go
#264
Automatically create the service accounts necessary for builds in new cf space namespaces
No
Install the API and dependencies according to the README, install cf cli v8, follow test cases listed in the acceptance criteria on related issue.
paired w/ @julian-hj @akrishna90
=> Issue 264 create space service accounts

controllers/apis/workloads/v1alpha1/cfapp_types.go, controllers/apis/workloads/v1alpha1/cfapp_webhook.go, controllers/apis/workloads/v1alpha1/cfapp_webhook_test.go, controllers/apis/workloads/v1alpha1/integration/cfapp_webhook_integration_test.go, controllers/apis/workloads/v1alpha1/integration/webhook_suite_integration_test.go, controllers/apis/workloads/v1alpha1/shared_types.go, controllers/config/crd/bases/workloads.cloudfoundry.org_cfapps.yaml, controllers/controllers/workloads/cfapp_controller.go, controllers/controllers/workloads/cfapp_controller_test.go, controllers/controllers/workloads/cfprocess_controller.go, controllers/controllers/workloads/cfprocess_controller_test.go, controllers/controllers/workloads/integration/cfapp_controller_integration_test.go, controllers/controllers/workloads/integration/cfprocess_controller_integration_test.go, controllers/controllers/workloads/integration/suite_integration_test.go, controllers/controllers/workloads/shared.go, controllers/controllers/workloads/testutils/shared_test_utils.go, controllers/reference/cf-k8s-controllers.yaml
#260 
Implements the logic to enable `cf restart <app>` 
No
Follow instruction in README to deploy `cf-k8s-api` and `cf-k8s-controller`
Push an app using CF CLI
Try restarting the app using `cf restart <app-name>` and verify if new pods are created
@gnovv @Birdrock @julian-hj @davewalter
=> Implements `cf restart` (using controllers)

api/apis/app_handler.go, api/apis/app_handler_test.go, api/apis/build_handler.go, api/apis/domain_handler.go, api/apis/domain_handler_test.go, api/apis/droplet_handler.go, api/apis/job_handler.go, api/apis/org_handler.go, api/apis/org_handler_test.go, api/apis/package_handler.go, api/apis/process_handler.go, api/apis/process_handler_test.go, api/apis/role_handler.go, api/apis/root_handler.go, api/apis/route_handler.go, api/apis/service_route_binding_handler.go, api/apis/shared.go, api/apis/space_handler.go, api/apis/space_handler_test.go, api/apis/whoami_handler.go, api/presenter/app.go, api/presenter/domain.go, api/presenter/org.go, api/presenter/process.go, api/presenter/route.go
fixes #324
Fixed pagination links in list responses
- pagination links previously included ?page=1 querystring parameters,
which would cause failures when followed
- some links also did not include the querystring parameters from the
request, which would lead to incorrect results if used.
- we also noticed that our json serialization html encoded string
values, leading to incorrect URLs. We added a utility method to
marshal json without encoding it, and inserted that everywhere.
no
see issue #324
@davewalter
=> Fixed pagination links in list responses

api/apis/app_handler_test.go, api/apis/authentication_middleware.go, api/apis/authentication_middleware_test.go
* https://github.com/cloudfoundry/cf-k8s-controllers/issues/362
Right now the CF CLI is omitting the authorization header for the log-cache endpoints for some reason. I've got an open Slack thread about that and will link the issue for it once it exists.
As a mitigation this change omits our hard-coded log-cache endpoints in the `AuthenticationMiddleware`.
- `/api/v1/info` is a discovery endpoint and doesn't require
authentication in general
- `/api/v1/read/<app-guid>` eventually will require authentication, but
doesn't right now since we are returning a hard-coded empty list of
envelopes. Eventually we will want Auth here.
No
Follow the A/C on https://github.com/cloudfoundry/cf-k8s-controllers/issues/362 or try to `cf push` an app. You shouldn't see `401` errors anymore while trying to …
=> Skip AuthenticationMiddleware for log-cache endpoints

api/apis/build_handler.go, api/apis/build_handler_test.go, api/apis/package_handler.go, api/apis/package_handler_test.go, api/payloads/build.go, api/payloads/package.go, api/repositories/build_repository.go, api/repositories/build_repository_test.go, api/repositories/package_repository.go, api/repositories/package_repository_test.go, controllers/controllers/shared/index.go, controllers/controllers/workloads/cfapp_controller.go, controllers/controllers/workloads/integration/cfapp_controller_integration_test.go
[fixes #336]
Add ownerReference fields to CFApp owned objects
- When a CFApp CR is deleted, all derivative objects should also be
deleted.
- CFProcess, CFBuild, and CFPackage were missing owner references and
not getting cleaned up.
- This commit fixes that.
no.
See #336
@akrishna90
=> Add ownerReference fields to CFApp owned objects

api/apis/app_handler_test.go, api/apis/job_handler.go, api/apis/job_handler_test.go, api/presenter/job.go
[#335](https://github.com/cloudfoundry/cf-k8s-controllers/issues/335)
Add a minimal implementation of the GET jobs endpoint for app delete jobs.
No
See related issue.
paired with @Birdrock
=> Implement minimal GET app delete job

api/actions/fetch_process_stats.go, api/actions/fetch_process_stats_test.go, api/repositories/app_repository.go, api/repositories/app_repository_test.go, api/repositories/pod_repository.go, api/repositories/pod_repository_test.go, api/repositories/shared.go
#352 
Adds an additional label selector (eirini version label) when fetching pods. 
This fix keeps `cf restart` from existing early. 
No
Push an app using `cf push`
Try restarting the app using `cf restart`
`cf restart` should exit only when new pods become available.
@davewalter
=> Use eirini version label selector when fetching pods for app

Makefile, api/config/overlays/kind-local-registry/apiconfig/cf_k8s_api_config.yaml, api/config/overlays/kind-local-registry/kustomization.yaml, controllers/config/overlays/kind-local-registry/controllersconfig/cf_k8s_controllers_config.yaml, controllers/config/overlays/kind-local-registry/kustomization.yaml, controllers/config/overlays/kind/controllersconfig/cf_k8s_controllers_config.yaml, controllers/config/samples/cfdomain.yaml, dependencies/kpack/cluster_builder.yaml, scripts/deploy-on-kind.sh
Nope
It adds a local container registry option to the deploy-on-kind developer script.
- `deploy-on-kind.sh` can now take a second argument that tells it to
deploy and use a local container registry.
- this requires some hackery to get the registry address to work from
within the kind node, but saves us from having to specify an external
registry.
no
To use it:
```
./scripts/deploy-on-kind.sh cluster local
```
The existence of the second argument tells the script to wire up the local registry.
Once the script is done, create a CFDomain object, and your cluster will be ready to push and run apps.
@Birdrock @tcdowney @PureMunky PTAL
=> Add dev support for local container registry

.github/pull_request_template.md
No, this came out of a Retro action item
Make the instructions in the PR template into HTML comments so they can be left in without being visible in the PR
No
After merging, start a PR and confirm that the preview doesn't show any of the instructions
@julian-hj
=> Make notes to the submitter HTML comments

api/apis/app_handler.go, api/apis/app_handler_test.go, api/apis/fake/pod_repository.go, api/apis/process_handler.go, api/repositories/pod_repository.go, api/repositories/pod_repository_test.go, dependencies/kpack/cluster_builder.yaml
#391 
Fixes subsequent `cf push` behavior. Was hanging on watching for pod deletion. This updates the implementation as a result of changes from #260.
No.
Follow steps in #391
@akrishna90
=> Re-pushing a running app fails - does not restart

controllers/controllers/workloads/cfprocess_controller.go, controllers/controllers/workloads/cfprocess_controller_test.go, controllers/controllers/workloads/integration/cfprocess_controller_integration_test.go
#331
Previously, we were not setting the PORT, VCAP_APP_PORT, VCAP_APP_HOST environment variables when creating an LRP, leaving some apps to choose their own port, which didn't work.
This change adds the standard environment variables.
If there is an existing route with a destination that matches our app
and a port set, we use that port. Otherwise we use port 8080
No
See #331 
@acosta11
=> Expose PORT, VCAP_APP_PORT, VCAP_APP_HOST env to app

Makefile, go.mod, go.sum, scripts/run-tests.sh
Remove ginkgo installation from run-tests and keep it solely in the
makefile
No
The makefile and run-tests script kept installing ginkgo v2.0.0-rc1. We have changed the invocation to use the v2 version and pick up latest in that module version. We've also removed the duplication ginkgo installation in the run-tests script, which was unnecessary.
No
See tests run in parallel successfully again, and view the new v2 output.
=> Make sure we install latest ginkgo v2

scripts/install-dependencies.sh
No
installations using gcr.io and local registry require different tags for
the kpack configuration. This change swaps in the hostname of the
docker registry instead of gcr.io if it has been set in the
DOCKER_SERVER environment variable.
no
- `./scripts/deploy-on-kind.sh kind local`
- Check the status of your clusterbuilder. You should see that it becomes ready
- Do the same thing, only using gcr (omit the last arg to the script)
@akrishna90
=> Install dependencies works for different environments

api/actions/fetch_process_stats.go, api/repositories/pod_repository.go, api/repositories/pod_repository_test.go
#378 
Fixes pod status fetch to only retrieve pods associated with process.
No.
* Run tests as normal.
* Follow steps in #378
@acosta11
=> Fetch process stats properly fetches pods

controllers/controllers/workloads/cfapp_controller.go, controllers/controllers/workloads/integration/cfapp_controller_integration_test.go, controllers/controllers/workloads/integration/cfbuild_controller_integration_test.go
#374
This change ensures that a `web` process is always present, even when none is created as part of staging. This solves problems for go apps, which name their processes after the package being compiled.
This is a behavior change for apps of some languages, such as go, but it brings the behavior in line with cf-for-vms and cf-for-k8s so I wouldn't consider it breaking. Apps that worked before this change should work after it, and some apps that didn't work should work now.
Follow the steps in the issue
=> Ensure there is always a "web" process

api/repositories/k8s_client.go, api/tests/integration/user_client_factory_test.go, scripts/run-tests.sh
#437
When testing authorization for creating apps, we noticed some tests were flaky when run in parallel. Further investigation showed the authenticated user names were being mixed up. One test would appear to be using the user from another test.
The problem is in the user client factory. It takes a pointer to rest.Config, and although it copies this on instantiation, it mutates the same pointer when producing clients. This means if clients are produced simultaneously, there is a potential race condition and their identities can be mixed up. The fix is to clone the config before producing the client.
The mitigation to stop future races is to turn the `--race` flag on in ginkgo. This PR also does that.
No
New test is green. I don't think you could easily reproduce this manually. …
=> Clone config before creating new k8s user client and introduce --race flag to ginkgo tests

api/apis/package_handler_test.go, api/payloads/package.go, api/repositories/package_repository.go, api/repositories/package_repository_test.go
#407 
Adds support to `states` query parameter to the List Package endpoint.
We also implemented `Order_by` support to the endpoint
- support for only `created_at` and `-created_at`
- default order is ascending i.e. `created_at`
No
Follow acceptance steps on #407 
@matt-royal
=> Adds functionality to support `cf restage`

api/apis/app_handler.go, api/apis/app_handler_test.go, api/apis/integration/apply_manifest_test.go, api/apis/integration/create_app_test.go, api/apis/integration/integration_suite_test.go, api/apis/package_handler_test.go, api/repositories/app_repository.go, api/repositories/app_repository_test.go, api/repositories/package_repository.go, api/repositories/package_repository_test.go, api/repositories/repositories_suite_test.go, api/tests/e2e/apps_test.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/orgs_test.go, api/tests/e2e/roles_test.go, api/tests/e2e/spaces_test.go, controllers/config/cf_roles/cf_space_developer.yaml, controllers/reference/cf-k8s-controllers.yaml
#173 
We should use the user client in the app repository for create apps. Then the 'create' permission is required on cfapp for the CreateApp call. Add this permission to the space-developer role.
Users without the space-developer role can no longer create apps.
1. Deploy cf on a k8s cluster
2. Create and target an org and a space
3. Create a non-privileged user
4. Assign that user a role such as space-manager on the space
5. `cf create-app bob` logged in as that user. See the request fail
6. Assign the space-developer role to that user. Repeat the request and see it pass.
=> Require space-developer role for create app

api/tests/e2e/apps_test.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/orgs_test.go, api/tests/e2e/spaces_test.go
No
It is only necessary to wait for spaces to be deleted before deleting the org, so we can parallelise most deletions to speed up e2e tests
No
e2e tests are green
=> Delete namespaces in parallel in e2e tests

scripts/create-new-user.sh
The script makes it easy to create new users for testing or acceptance purposes.
It does so by:
- generating a new RSA private key;
- creating a CertificateSigningRequest;
- approving it;
- extracting the generated certificate from the CSR;
- adding the new user to $KUBECONFIG using the generated certificate and key.
=> Introduce `scripts/create-new-user.sh`

api/apis/buildpack_handler.go, api/apis/buildpack_handler_test.go, api/config/base/apiconfig/cf_k8s_api_config.yaml, api/config/config.go, api/config/overlays/kind-auth-enabled/apiconfig/cf_k8s_api_config.yaml, api/config/overlays/kind-local-registry/apiconfig/cf_k8s_api_config.yaml, api/config/overlays/kind/apiconfig/cf_k8s_api_config.yaml, api/main.go, api/reference/cf-k8s-api.yaml
#400 
Default ClusterBuilder is configurable.
`cf_k8s_api_config.yaml` will need to specify the cluster builder name. The base config file does this.
Run tests.
@acosta11
=> Issues 400 configure default clusterbuilder

api/apis/buildpack_handler.go, api/authorization/caching_identity_provider.go, api/authorization/caching_identity_provider_test.go, api/authorization/info.go, api/main.go, api/repositories/repositories_suite_test.go, go.mod, go.sum
#442 
Use an expiring cache with TTL of 2 minutes.
The identity provider is used to determine the ID given an auth token or
client certificate. In both cases, the code goes to the cluster to
obtain the identity, and this is a slow operation. It makes sense to
cache the results for a short time.
No
1. use time to record cf operations (for example create-space, create-org and push)
1. redeploy with these changes
1. use time again for the same operations
1. notice that the times are significantly lower
@kieron-dev
=> Cache identities in new  CachingIdentityProvider

api/docs/architecture-decisions/0001-cf-resource-guid-format.md, api/docs/architecture-decisions/0004-resource-name-prefixes.md
No. (we failed to copy it over from Jira) 
It records a decision we made in team forum to prefix guids with strings so that the resulting k8s objects would also be decorated.
@tcdowney PTAL
=> New ADR for resource name prefixes

go.mod, go.sum
No
To clear security warnings from dependabot in our github repo.
It doesn't seem like there is an actual vulnerability afoot, since we don't spawn containers from our executables, but the warning is annoying, and it's dangerous to get used to ignoring warnings.
no
none
@davewalter @tcdowney
=> Bump github.com/containerd/containerd to 1.5.9

api/config/base/rbac/role.yaml, api/reference/cf-k8s-api.yaml, api/repositories/buildpack_repository.go, controllers/config/cf_roles/cf_space_developer.yaml, controllers/reference/cf-k8s-controllers.yaml
fixes missing rbac in #349 
`cf buildpacks` fails due to missing kubebuilder rbac annotation
no
see issue
@Birdrock
=> add RBAC to api and space dev

api/tests/e2e/e2e_suite_test.go, api/tests/e2e/orgs_test.go, api/tests/e2e/spaces_test.go
No
This changes multiple org and space creations to be done in parallel, using a wait group to synchronise.
It shaves around 30 seconds off the running time of the tests from 3 mins to 2 mins 30 on my machine.
No
e2e tests remain green and run a bit faster
=> Make org and space creation async in e2e tests

api/tests/e2e/e2e_suite_test.go, controllers/config/cf_roles/cf_admin.yaml, controllers/config/cf_roles/kustomization.yaml, controllers/reference/cf-k8s-controllers.yaml, dependencies/cf-setup.yaml, dependencies/namespace.yaml, scripts/deploy-on-kind.sh, scripts/install-dependencies.sh, scripts/run-tests.sh
Use the new scripts/create-new-user.sh script to create a
user with name admin and bind this user to the cf-k8s-controllers-admin
role. This role is a clone of the cf-k8s-controllers-space-developer
to begin with and should be incrementally granted more permissions as we
add new endpoints to the api. The goal is to eventually have and admin
role that is just as powerful as needed, but not as powerful as the k8s
admin user.
#466 
Use the new scripts/create-new-user.sh script to create a
user with name admin and bind this user to the cf-k8s-controllers-admin
role. This role is a clone of the cf-k8s-controllers-space-developer
to begin with and should be incrementally granted more permissions as we
add new endpoints to the api. The goal is to eventually have and admin
role that is just as …
=> Add an admin user on kind deployment

api/apis/app_handler.go, api/apis/app_handler_test.go, api/repositories/app_repository.go, api/repositories/app_repository_test.go, api/repositories/repositories_suite_test.go, api/tests/e2e/apps_test.go, controllers/config/cf_roles/cf_space_developer.yaml, controllers/reference/cf-k8s-controllers.yaml
#234 
Use the user authenticated client to perform the Get of the cfapp resource from kubernetes.
At the moment we still retrieve the app by guid in an inefficient way, going through the entire list of apps retrieved by a privileged client looking for the matching guid. Then we use the user client to perform a `Get` once we know the namespace and name.
This need to be fixed in a generic way using some kind of cache.
No
1. Create org and space
2. Target org and space
2. `cf create-app bob`
3. `cf app bob --guid` and copy the guid
4. Create new user
5. Login as new user
6. `cf curl /v3/apps/{guid}`
7. Expect Not Found response
@gcapizzi
=> Authorize GET /v3/apps/{guid}

scripts/deploy-on-kind.sh, scripts/run-tests.sh
This changes `scripts/deploy-on-kind.sh` to always use the current `$KUBECONFIG` instead of exporting its own one. This allows users to create development clusters using their default config, while `scripts/run-tests.sh` can deploy test clusters with a separate config just by exporting a different `$KUBECONFIG` _before_ calling `scripts/deploy-on-kind.sh`.
=> Setup KUBECONFIG outside of deploy-on-kind scripts

controllers/config/base/controllersconfig/cf_k8s_controllers_config.yaml, controllers/config/overlays/kind-local-registry/controllersconfig/cf_k8s_controllers_config.yaml, controllers/config/overlays/kind/controllersconfig/cf_k8s_controllers_config.yaml, controllers/reference/cf-k8s-controllers.yaml
Co-authored-by: Akira Wong <wakira@vmware.com>
#492 
Update the default memory and disk limits for apps
No
Deploy the api/controllers with default configuration, then push and app without any scaling configuration. View the app info and see that the memory and disk requests are now 1024MB.
paired w/ @gnovv
=> Set default memory limit to 1024

api/apis/space_handler.go, api/apis/space_handler_test.go, api/repositories/errors.go, api/repositories/org_repository.go, api/repositories/org_repository_test.go, api/repositories/repositories_suite_test.go, api/tests/e2e/spaces_test.go, controllers/config/cf_roles/cf_admin.yaml, controllers/reference/cf-k8s-controllers.yaml
https://github.com/cloudfoundry/cf-k8s-controllers/issues/235
Allow space creation to users that have the `cf-admin` role assigned.
The implementation would use the user k8s client (instead the privileged one) in the space repository to create the space subnamespace anchor. This means that the user has to be assigned to the `cf-admin` role which is the only one allowing subnamespace anchor creation.
No (or sort of - from now on regular users would not be able to create spaces :) )
0. Deploy on kind and `cf api` the cluster 
1. login as `admin`
2. `cf create-org o`
3. `cf create-space -o o s`
4. Make sure the commands above caused no errors
1. `./scripts/create-new-user.sh nonadmin`
2. Assign the `organization-user` role to `nonadmin`
```
cat <<EOF | kubectl apply -f -
apiVersion: …
```
=> Allow cf-admins only to create spaces

api/presenter/process_stats.go, controllers/controllers/workloads/cfbuild_controller.go, controllers/controllers/workloads/cfpackage_controller.go, controllers/controllers/workloads/cfpackage_controller_test.go, controllers/controllers/workloads/cfprocess_controller.go, controllers/controllers/workloads/integration/cfbuild_controller_integration_test.go, controllers/controllers/workloads/integration/cfpackage_controller_integration_test.go, controllers/controllers/workloads/integration/cfprocess_controller_integration_test.go, controllers/controllers/workloads/integration/suite_integration_test.go, controllers/main.go
#471 
#472 
#477 
Sets CFApp as owner on CFPackage, CFBuild and CFProcess. This results in them being deleted when CFApp is deleted.
No
Follow AC on the issues
@matt-royal
=> Set Owner References on CFPackage, CFBuild and CFProcess

api/tests/e2e/orgs_test.go, api/tests/e2e/whoami_test.go, api/tests/helpers/cert_auth_header.go, api/tests/integration/user_client_factory_test.go
#483 
Since we are using a middleware for parsing the authentication header,
we should just test that in one place, instead of on every endpoint.
This should eliminate a lot of duplication.
Additionally add some missing tests to the user client factory.
No
Look at the tests 👀 
@kieron-dev
=> Move authentication tests to the whoami endpoint

api/apis/apis_suite_test.go, api/apis/app_handler.go, api/apis/app_handler_test.go, api/repositories/app_repository.go, api/repositories/app_repository_test.go, api/repositories/repositories_suite_test.go, api/tests/e2e/apps_test.go, api/tests/e2e/e2e_suite_test.go, controllers/config/cf_roles/cf_admin.yaml, controllers/config/cf_roles/cf_space_developer.yaml, controllers/config/cf_roles/cf_space_manager.yaml, controllers/controllers/services/integration/suite_test.go, controllers/reference/cf-k8s-controllers.yaml
#446 
This adds cfapp patch permissions to space-developer and admin roles and uses the 'user client' to perform the patch.
We also added get permission to space-manager as a readonly user helped in the e2e test.
No
See you can set current droplet on an app as admin or spacedeveloper, but not as any other role.
=> Implement authz on set current droplet endpoint

controllers/controllers/workloads/cfpackage_controller_test.go
#539 
Fix test flake.
The variable `cfPackageUpdateError` is not initialized, so when the test setting it in "patch CFPackage returns an error" has run, subsequent happy path tests will fail.
No
`ginkgo --randomize-all --until-it-fails controllers/controllers/workloads` succeeds for as long as you can wait.
=> Reset error to nil to stop test interference

api/apis/app_handler.go, api/apis/app_handler_test.go, api/apis/integration/app_test.go, api/tests/e2e/apps_test.go
#447 
Return 404 error if user is not authorized to list app processes. This currently equates to permissions to get the app, so no change has been made to the process repo code to not use the privileged k8s client.
No
See story
=> Return 404 if not authorized to list app processes

.github/dependabot.yml
No
This PR updates the Dependabot configuration to run the checks daily instead of weekly.
No
Dependabot PRs are opened on any day of the week, not just Monday.
=> Run dependabot checks daily

api/tests/e2e/e2e_suite_test.go, api/tests/e2e/orgs_test.go, api/tests/e2e/spaces_test.go
https://github.com/cloudfoundry/cf-k8s-controllers/issues/443
Replace the ginkgo matcher with a utility function that can return an
error. This error is either expected not to occur (sync create
org/space), or sent over the error channel in the async counterpart.
No
E2E tests are green
=> Ensure admin role when creating orgs/spaces asynchronously

api/tests/e2e/e2e_suite_test.go, api/tests/e2e/helpers/fail_handler.go
https://github.com/cloudfoundry/cf-k8s-controllers/issues/551
Ginkgo's default fail handler (the one the E2EFailHandler delegates to)
uses the `callerSkip` argument to skip stack frames when printing the
error line. As we wrap the standard fail handler with a custom one, we
should increase the `callerSkip` argument with one (wrapping the default
handler adds one stack frame) so that the error message points to the
actual failure.
This fix also works well with `ExpectWithOffset`. Being on the subject,
the offsets in `createRole` have been adjusted to `2` which is the
correct value.
No
* all e2e tests are green
* if an e2e test is made to fail deliberately, ginkgo's error message should refer to the line of failure
=> Fix line numbers in ginkgo error output in E2E tests

api/apis/integration/app_test.go, api/apis/integration/apply_manifest_test.go, api/apis/integration/get_app_env_test.go, api/apis/integration/integration_suite_test.go, api/apis/integration/route_test.go, api/main.go, api/repositories/app_repository.go, api/repositories/app_repository_test.go, api/repositories/buildpack_repository.go, api/repositories/buildpack_repository_test.go
No
Correct the usage of userClientFactory in the app and buildpack repos
We shouldn't pass the authEnabled flag in, and we should trust that main has injected the correct client factory.
No
Green CI
=> Use userClientFactory correctly in repo code

scripts/run-tests.sh, scripts/test
No
The vim test integration executes `scripts/test` if it exists. We want this to run on the current suite, not any suites in sub-directories.
To enable this, we add another env option `NON_RECUSIVE_TEST` to run-tests.sh, and set this in `script/test` before invoking `run-tests.sh`. When not set, ginkgo is executed with the `-r` flag, otherwise without it.
No
In vim, with the eirini team's configuration, press `<space>ts` from a test in `api/apis`, and see only the apis suite runs, not the apis/integration suite too.
=> Do not run ginkgo recursively when invoked from vim

api/repositories/buildpack_repository.go, api/repositories/buildpack_repository_test.go
Issue: https://github.com/cloudfoundry/cf-k8s-controllers/issues/575
The Stack/ClusterStack name in a Builder's Spec is often something generic like "default" or "base". This change uses the Stack ID from the Builder's Status which typically includes more meaningful information for developers (typically something like `io.buildpacks.stacks.bionic`) that conveys details about the base OS.
No
1. Deploy and run `cf buildpacks`. Should see something like this:
```
11:52 $ cf buildpacks
Getting buildpacks as tdowney...
position   name                         stack                         enabled   locked   filename
1          paketo-buildpacks/java       io.buildpacks.stacks.bionic   true      false    paketo-buildpacks/java@6.7.1
2          paketo-buildpacks/go …
```
=> Use Stack ID from Builder's Status when listing Buildpacks

api/apis/route_handler_test.go, api/payloads/app.go, api/payloads/app_test.go, api/payloads/domain.go, api/payloads/domain_test.go, api/payloads/package.go, api/payloads/process.go, api/payloads/route.go, api/payloads/shared.go, api/repositories/route_repository_test.go
#567
Fixes query param filtering for list endpoints.
* Setup cf-k8s-controllers
* Create Route with empty string path
* Create Route with populated path
* List Routes with param `cf curl /v3/routes?paths=`
* See that only empty string path Route is returned.
@davewalter @akrishna90 @gnovv
=> Fix query param filtering to allow empty strings

scripts/create-new-user.sh
No
This PR adds output to the `create-new-user` script to tell the user how to grant space developer permissions to the new user.
No
Create a cluster, run the `create-new-user` script, and see the output with the sample `cf set-space-role` command.
=> Add helpful instruction to create-new-user script

api/apis/app_handler.go, api/apis/app_handler_test.go, api/apis/integration/app_test.go, api/repositories/app_repository.go, api/repositories/app_repository_test.go, api/tests/e2e/apps_test.go, api/tests/e2e/e2e_suite_test.go
#449 
Use the user client factory to obtain a user authenticated client for the `SetAppDesiredState()` call.
No
See #449
=> Implement authz for restart app endpoint

api/repositories/app_repository.go, api/repositories/build_repository.go, api/repositories/droplet_repository.go, api/repositories/package_repository.go, api/repositories/process_repository.go, api/repositories/route_repository.go, scripts/create-new-user.sh
No
Use client.MatchingFields to find resource by name instead of doing it manually as it is also probably more efficient and we can eventually take advantage of controller-runtime cache.
No
N/A
@kieron-dev
=> Use client.MatchingFields to find resources by name

api/tests/e2e/apps_test.go, api/tests/e2e/builds_test.go, api/tests/e2e/droplets_test.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/orgs_test.go, go.mod, go.sum
https://github.com/cloudfoundry/cf-k8s-controllers/issues/484
Tidying up the e2e tests by using a rest client library. This makes the tests more explicit and more readable.
No
Green tests
=> Clean up the apps end-to-end tests

api/apis/app_handler.go, api/apis/app_handler_test.go, api/apis/build_handler.go, api/apis/build_handler_test.go, api/apis/integration/app_test.go, api/apis/integration/apply_manifest_test.go, api/apis/integration/build_test.go, api/apis/integration/get_app_env_test.go, api/apis/integration/route_test.go, api/apis/org_handler.go, api/apis/org_handler_test.go, api/apis/package_handler.go, api/apis/package_handler_test.go, api/apis/process_handler.go, api/apis/process_handler_test.go, api/apis/role_handler.go, api/apis/role_handler_test.go, api/apis/route_handler.go, api/apis/route_handler_test.go, api/apis/service_instance_handler.go, api/apis/service_instance_handler_test.go, api/apis/shared.go, api/apis/space_handler.go, api/apis/space_handler_test.go, api/apis/space_manifest_handler.go, api/apis/space_manifest_handler_test.go, api/main.go
https://github.com/cloudfoundry/cf-k8s-controllers/issues/289
Use a singleton instance of payload validator instead of creating a new one on every HTTP request thus making use of the singleton validator cache.
No
Green tests
@mnitchev
=> Use single payload validator in all handles

api/apis/package_handler.go, api/apis/package_handler_test.go, api/repositories/package_repository.go, api/repositories/package_repository_test.go, api/repositories/shared.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/package_test.go, controllers/config/cf_roles/cf_admin.yaml, controllers/config/cf_roles/cf_space_developer.yaml, controllers/reference/cf-k8s-controllers.yaml
https://github.com/cloudfoundry/cf-k8s-controllers/issues/544
Enable authz for the `create package` endpoint
`create package` now requires the `space developer role` to be assigned to the user
See the story
@georgethebeatle 
@mnitchev
=> Add authz to the create package endpoint

api/tests/e2e/apps_test.go, api/tests/e2e/builds_test.go, api/tests/e2e/droplets_test.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/orgs_test.go, api/tests/e2e/package_test.go, api/tests/e2e/roles_test.go, api/tests/e2e/spaces_test.go, api/tests/e2e/whoami_test.go, api/tests/helpers/cert_auth_header.go
#484 
- helper functions now return GUIDs not present objects
- use structs in the e2e package for test payloads and results
- replace deleteSubnamespace with deleteOrg
- increase eventually timeout to 4 minutes
- increase eventually polling interval to 2 seconds
- remove all use of httpReq, replacing with resty
No
Green e2e tests
=> Clean up e2e tests

api/apis/package_handler.go, api/apis/package_handler_test.go, api/repositories/package_repository.go, api/repositories/package_repository_test.go, api/repositories/shared.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/package_test.go, controllers/config/cf_roles/cf_admin.yaml, controllers/config/cf_roles/cf_space_developer.yaml, controllers/config/cf_roles/cf_space_manager.yaml, controllers/reference/cf-k8s-controllers.yaml
#545 
This introduces authentication to the package upload endpoint. Some notes:
* This actually leverages RBAC on package updates, and it does not actually prevent unauthorised users to upload packages. The endpoint will return an error _after_ the upload and leave the package unchanged. We have opened bug #613 to figure out how to address this issue, as access to the container registry is not subject to Kubernetes RBAC.
* This also fixes the error returned when trying to create a package for an app the user doesn't have access to: the correct error is `422 Unprocessable Entity` and not `404 Not Found`.
=> Authenticate package uploading

api/actions/fake/cfapp_repository.go, api/actions/shared.go, api/apis/app_handler.go, api/apis/app_handler_test.go, api/apis/fake/cfapp_repository.go, api/apis/integration/app_test.go, api/apis/integration/apply_manifest_test.go, api/apis/integration/build_test.go, api/apis/integration/droplet_test.go, api/apis/integration/get_app_env_test.go, api/apis/integration/integration_suite_test.go, api/apis/integration/route_test.go, api/apis/package_handler.go, api/apis/package_handler_test.go, api/apis/route_handler.go, api/apis/route_handler_test.go, api/apis/service_instance_handler.go, api/apis/service_instance_handler_test.go, api/apis/space_handler.go, api/apis/space_handler_test.go, api/main.go, api/repositories/app_repository.go, api/repositories/app_repository_test.go, api/repositories/domain_repository.go, api/repositories/domain_repository_test.go, api/repositories/errors.go, api/repositories/org_repository.go, api/repositories/org_repository_test.go, api/tests/e2e/apps_test.go, docs/architecture-decisions/0013-repo-errors.md
https://github.com/cloudfoundry/cf-k8s-controllers/issues/403
The `ResourceNotFoundError` type was not used, so this could be simply deleted.
`PermissionDeniedOrNotFoundError` introduced confusion. E.g. `GetApp()` would return `NotFoundError` when no app was found, but some handlers would check for the `PermissionDeniedOrNotFoundError`, and omit the `NotFoundError` check. So we had a lot of erroneous 500 status responses to api calls which should have been 404s.
As described in the associated ADR, we believe that we should take the simple approach of returning `NotFoundError` when a resource is not found, and `ForbiddenError` when it is forbidden to the user. This way we communicate the result clearly to the handler layer without requiring it to introspect wrapped k8s errors. It is up to …
=> Remove ResourceNotFoundError and PermissionDeniedOrNotFoundError from repositories

.golangci.yml, api/tests/e2e/package_test.go, controllers/controllers/services/cfservicebinding_controller_test.go, controllers/controllers/services/cfserviceinstance_controller_test.go
#549
- cfservicebinding_controller_test and cfserviceinstance_controller_test
had variables not getting re-initialized between test runs, causing
flakiness.
no.
CI covers it.
@davewalter
=> Fix cross test contamination in controller units

api/tests/e2e/orgs_test.go, api/tests/e2e/roles_test.go, api/tests/e2e/spaces_test.go
No
Always reset vars used in tests. In particular, the object used in SetError does not get updated if the rest call does not fail, so you must ensure it is reset each time if you are going to check it on happy paths.
Nope
`make test-e2e`
=> Fix e2e/package test flake

api/apis/integration/app_test.go, api/apis/integration/apply_manifest_test.go, api/apis/integration/get_app_env_test.go, api/apis/package_handler.go, api/apis/process_handler.go, api/apis/process_handler_test.go, api/main.go, api/repositories/process_repository.go, api/repositories/process_repository_test.go, api/repositories/shared.go, api/tests/e2e/apps_test.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/processes_test.go, controllers/config/cf_roles/cf_admin.yaml, controllers/config/cf_roles/cf_space_developer.yaml, controllers/reference/cf-k8s-controllers.yaml, scripts/run-tests.sh
https://github.com/cloudfoundry/cf-k8s-controllers/issues/555
Enable authorization for the list process sidecars endpoint.
This introduces permissions to 'get' cfprocesses to space dev and admin.
Also included was a tidy up to the entire repositories/process_repository_test to remove unnecessary code and make
it simple to insert the new tests required for this story.
You may now also use `SEED` and `UNTIL_IT_FAILS` env vars to set the corresponding ginkgo options when running tests, saving you modifying the run-tests script.
No
See #555 
=> Enable authz on list process sidecars

api/apis/service_instance_handler.go, api/apis/service_instance_handler_test.go, api/payloads/service_instance.go, api/repositories/service_instance_repository.go, api/repositories/service_instance_repository_test.go, docs/api.md
#599
This PR adds the required query parameters to GET /v3/service_instances to support the `cf services` command.
No
See #599 
@julian-hj @gnovv
=> Add required params to /v3/service_instances

api/tests/e2e/apps_test.go, api/tests/e2e/builds_test.go, api/tests/e2e/droplets_test.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/helpers/resty.go, api/tests/e2e/matchers_test.go, api/tests/e2e/orgs_test.go, api/tests/e2e/packages_test.go, api/tests/e2e/processes_test.go, api/tests/e2e/roles_test.go, api/tests/e2e/spaces_test.go, api/tests/e2e/whoami_test.go
https://github.com/cloudfoundry/cf-k8s-controllers/issues/638
Introduce custom Gomega matchers to verify `resty.Response` status code  and body.
The custom matchers use a wrapper over `resty.Response` that implements the [`GomegaStringer`](https://github.com/onsi/gomega/blob/d01bc22577e88a1c7afa2448e81ee8e43a598d28/format/format.go#L61-L66)  interface and prints the `resty.Reponse` in a developers' friendly way. Thus we could make use of the Gomega's [`Message`](https://github.com/onsi/gomega/blob/d01bc22577e88a1c7afa2448e81ee8e43a598d28/format/format.go#L82) utility to display failure messages in a standard manner.
The body matcher can take either a value (then the standard `Equal` matcher is used to check the value), or a Gomega matcher.
Failure examples:
* Unexpected HTTP status code: …
=> Improve E2E tests failure messages

api/apis/integration/process_test.go, api/apis/process_handler.go, api/apis/process_handler_test.go
#554
This PR adds error handling for process permissions errors to the process handler in the API shim. This addresses the defect that @kieron-dev pointed out on #633, cleans up the error handling helper, and adds unit and integration tests.
No
see #554
I was soloing today, but I am hoping @kieron-dev or @gcapizzi will have a look.
=> Add error handling for process permissions errors

api/repositories/app_repository_test.go, api/repositories/process_repository_test.go, api/repositories/shared_test.go
Co-authored-by: Julian Hjortshoj <hjortshojj@vmware.com>
Resolves #647 
Updates api repo test helper functions to wrap `k8sClient.Create` call into initializing the CRs.
No
Run tests and confirm they pass
@julian-hj
=> Modified repo test helpers to include k8sClient.create

api/apis/build_handler.go, api/apis/build_handler_test.go, api/apis/integration/build_test.go
When creating a build for a package isn't authorised to see, the error should not be 404 but a 422. Fixes #543 for good.
=> Fix error in `POST /v3/builds`

go.mod, go.sum
No
Bumping a github.com/docker/distribution to v2.8.0
No
Tests are green
=> Bump github.com/docker/distribution to v2.8.0

controllers/controllers/services/integration/cfservicebinding_integration_test.go, controllers/controllers/services/integration/cfserviceinstance_integration_test.go, controllers/controllers/services/integration/suite_integration_test.go
#690 
I believe the error we were seeing with binding name not being set in the status after 2 seconds were simply due to the timeout being too short for a busy server. I addressed this by setting a generous 30s timeout using the `SetDefaultEventuallyTimeout` across all tests, rather than including the timeout parameter in each eventually call. Running tests with UNTIL_IT_FAILS set works until env test inevitably fails to grab a port after about 30 attempts, so it seems better.
The other flake was when the service instance was not found while reconciling the binding. This caused the 'binding secret does not exist' test to fail for the wrong reason. By including the entire status condition we want to see in the `Should` of the eventually, the test will pass when the binding is eventually …
=> Fix flakes in cfservicebinding integration test

api/apis/integration/integration_suite_test.go, api/apis/integration/role_test.go
https://github.com/cloudfoundry/cf-k8s-controllers/issues/500
Introduce integration tests for the `/v3/roles` endpoint
No
Green tests
@kieron-dev
=> Added integration tests for missing role tests

api/apis/app_handler.go, api/apis/app_handler_test.go, api/apis/integration/app_test.go, api/tests/e2e/apps_test.go
https://github.com/cloudfoundry/cf-k8s-controllers/issues/622
The authorization was pretty much already in place, just minor changes
in errors handling and backfilling missing tests
No
See story
=> Authorize stopping apps

api/repositories/pod_repository.go, api/repositories/pod_repository_test.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/processes_test.go, dependencies/kpack/cluster_store.yaml, dependencies/metrics-server-local-0.6.1.yaml, scripts/deploy-on-kind.sh
Co-authored-by: Ashwin Krishna <krishnaas@vmware.com>
Resolves #706 
Adds an e2e test for the GET process_stats endpoint when metrics server is present
Adds metrics-server to kind deployment script
no
Run tests.
@akrishna90
=> 706 update e2e process stats tests

api/config/base/rbac/role.yaml, api/reference/cf-k8s-api.yaml, api/repositories/service_instance_repository.go
https://github.com/cloudfoundry/cf-k8s-controllers/issues/617
The lack of these permissions was causing rolebinding creation to fail with errors like:
```
1.645736795215928e+09	INFO	Role Handler	create-role: not authorized	{"error": "Role forbidden: rolebindings.rbac.authorization.k8s.io \"cf-215e1b49bfe6ea9422f7fb635165b0d02a5013e5268f1d18b56b164ee2ac1b4b\" is forbidden: user \"system:serviceaccount:cf-k8s-api-system:cf-k8s-api-cf-admin-serviceaccount\" (groups=[\"system:serviceaccounts\" \"system:serviceaccounts:cf-k8s-api-system\" \"system:authenticated\"]) is attempting to grant RBAC permissions not currently held:\n{APIGroups:[\"services.cloudfoundry.org\"], Resources:[\"cfserviceinstances\"], Verbs:[\"get\" \"delete\"]}"}
```
No
You should be able to assign roles again like:
```
cf …
```
=> Add get/delete cfserviceinstance to cf-admin-clusterrole

api/apis/service_binding_handler.go, api/apis/service_binding_handler_test.go, api/payloads/service_binding.go, api/presenter/service_binding.go, api/presenter/shared.go, api/repositories/service_instance_repository.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/service_bindings_test.go, controllers/config/cf_roles/cf_space_manager.yaml, controllers/reference/cf-k8s-controllers.yaml
[#627]
This PR adds include=app support in service_credential_bindings
- /v3/service_credential_bindings can now accept a ?include=app
querystring
- when specified, the handler includes bound applications in the
response payload
- added e2e tests for listServiceBindings handler
- add list CFServiceBindings to space_manager RBAC so that space
managers have read access to service bindings
no
[#627]
@akrishna90
=> include=app support in service_credential_bindings

README.md, api/apis/space_manifest_handler.go, api/apis/space_manifest_handler_test.go
#161 
Add missing edge case handling and documentation
- throws a HTTP 404 instead of a HTTP 500 when Domain is not found
- add documentation for setting default domains
No
See #161
=> Add DomainNotFound error handling and missing documentation

api/tests/e2e/processes_test.go
No
Remove debug output, an obvious comment and commented code in the processes e2e test
No
No debug output from the processes e2e test
=> Get rid of debug output in the processes E2E

controllers/controllers/workloads/cfbuild_controller.go, controllers/controllers/workloads/cfbuild_controller_test.go, controllers/controllers/workloads/integration/cfbuild_controller_integration_test.go
https://github.com/cloudfoundry/cf-k8s-controllers/issues/692
Due to the asynchronous nature of hierarchical namespaces, the image
registry secret might not have been propagated by the time the CFBuild
controller creates the kpack image.
When this is the case (i.e. the image registry secret is not there yet),
the kpack build controller would just set an error on the kpack build
that the registry secret is not there and would no longer check for it.
Thus the build gets stuck in its inital state and a docker image is
never produced.
This change ensures that the secrets referenced by the package (that
include the registry secret) are available prior creating the kpack
image. If they are not, the reconciler returns an error so that the
reconciliation event is requeued for a retry later on. …
=> Ensure secrets referenced by CFPackage exist prior creating the Kpack image

api/tests/e2e/e2e_suite_test.go, api/tests/e2e/processes_test.go
No
* Tests no longer assume that processes are immediately created after
app droplet has been set
* Tests no longer assume that processes status is immediately RUNNING
No
Green e2e
=> Fix flaky processes e2e tests

api/apis/integration/integration_suite_test.go, api/main.go, api/repositories/k8s_client.go, api/repositories/repositories_suite_test.go, api/repositories/service_binding_repository_test.go, api/tests/integration/user_client_factory_test.go
https://github.com/cloudfoundry/cf-k8s-controllers/issues/572
Use a shared REST mapper in user client creation which utilises the mapper cache
No
green tests
=> Use a shared rest mapper to client

api/main.go, api/repositories/pod_repository.go
No.
Uses the same `k8sClientConfig` as the `privilegedK8sClient` for `CreateMetricsFetcher`.
No.
Run tests as normal.
@gnovv @clintyoshimura @tcdowney
=> Use NewForConfig in CreateMetricsFetcher

api/config/base/apiconfig/cf_k8s_api_config.yaml, api/config/base/ingress.yaml, api/config/base/service.yaml, api/config/config.go, api/config/overlays/kind-auth-enabled/apiconfig/cf_k8s_api_config.yaml, api/config/overlays/kind-local-registry/apiconfig/cf_k8s_api_config.yaml, api/config/overlays/kind-local-registry/kustomization.yaml, api/config/overlays/kind/apiconfig/cf_k8s_api_config.yaml, api/config/overlays/kind/kustomization.yaml, api/main.go, api/reference/cf-k8s-api.yaml, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/routes_test.go, api/tests/e2e/whoami_test.go, scripts/deploy-on-kind.sh, scripts/run-tests.sh
Co-authored-by: Dave Walter <walterda@vmware.com>
Resolves #387 
Add replaces serverURL in config.yaml and adds the ability to specify externalPort for api shim outputs.
No.
See issue.
@davewalter
=> Add external domain and port api configuration

go.mod, go.sum
We have a [new security notification on GitHub](https://github.com/cloudfoundry/cf-k8s-controllers/security/dependabot/3).
This PR bumps containerd to [1.5.10](https://github.com/containerd/containerd/releases/tag/v1.5.10) to address a CVE.
Hopefully not!
=> Bump github.com/containerd/containerd to 1.5.10

api/apis/fake/cfservice_binding_repository.go, api/apis/integration/service_binding_test.go, api/apis/service_binding_handler.go, api/apis/service_binding_handler_test.go, api/main.go, api/repositories/app_repository_test.go, api/repositories/service_binding_repository.go, api/repositories/service_binding_repository_test.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/service_bindings_test.go, controllers/config/cf_roles/cf_admin.yaml, controllers/config/cf_roles/cf_space_developer.yaml, controllers/config/cf_roles/cf_space_manager.yaml, controllers/reference/cf-k8s-controllers.yaml, docs/api.md
This is a draft PR--we still need to update the API docs to add the totally missing service_credential_bindings endpoint
[#718]
Adds DELETE handling for service bindings
no
#718 
=> Added DELETE /v3/service_credential_bindings/:guid

README.md, dependencies/cf-setup.yaml, scripts/install-dependencies.sh, scripts/run-tests.sh
[#607](https://github.com/cloudfoundry/cf-k8s-controllers/issues/607)
See #607 
Not to the api, but potentially to the end to end tests and to scripts that rely on the user's name.
cc @julian-hj to confirm that the proposed changes maintain the spirit of the chore issue
paired w/ @matt-royal
=> Rename default admin user to `cf-admin`

scripts/create-new-user.sh, scripts/deploy-on-kind.sh, scripts/generate-eirini-certs-secret.sh
No
We recently introduced more `openssl` commands into our scripts, but they only work on Linux, or if you have installed the `openssl@3` brew recipe on OSX. This PR introduces a check to see which version of `openssl` is available and adds alternative commands that are compatible with the default OSX version.
No
Make sure that the scripts work with both versions of `openssl` on OSX, and still work on Linux.
=> Make scripts work with the default OSX openssl

.github/ISSUE_TEMPLATE/chore.yml
Change template textarea id to `action-to-take`. There is a bug in GitHub's implementation of their templates, which will fill in the textarea with `new` if the id is `action`.
No.
Not much to accept - it's an issue template change.
@davewalter
=> Change gh chore template id

api/repositories/org_repository.go, api/repositories/org_repository_test.go, api/tests/e2e/orgs_test.go, controllers/config/cf_roles/cf_admin.yaml, controllers/controllers/workloads/integration/cfprocess_controller_integration_test.go, controllers/reference/cf-k8s-controllers.yaml
#702 
To avoid races setting this during deletion, it makes more sense to set this property during creation of orgs.
We also make sure the property is set on the root CF namespace
No
Delete an org with spaces lots of times and don't see an error about not being able to delete a namespace with child namespaces.
@gcapizzi
=> Set cascading deletion on orgs during creation

api/tests/e2e/e2e_suite_test.go, api/tests/e2e/service_bindings_test.go, tests/smoke/smoke_test.go
no
- We had delays built into some tests to wait for HNC role propagation
- These delays are theoretically no longer necessary because the API shim waits for permissions to appear before sending the HTTP response
We've run this PR through CI a couple of times with no failures, so we think the change set doesn't introduce new flakiness.
no
e2e tests should pass
@akrishna90
=> [DRAFT] Remove sleeps from e2e and smoke tests

Makefile, api/config/base/rbac/role.yaml, api/reference/cf-k8s-api.yaml, api/repositories/service_binding_repository.go
No.
The cf-admin is missing GET and DELETE for CFServiceBindings.
No.
Run tests as normal. Verify that cf-admin has updated RBAC.
@acosta11 @tcdowney
=> Update cf-admin rbac for servicebindings

tests/smoke/run-smoke-tests-kind.sh, tests/smoke/smoke_test.go
No. Consider this as a follow up to #751 
This PR updates the smoke tests to use HTTPS for apps endpoints. It also fixes the `run-smoke-test-kind.sh` to use the new `cf-admin` user.
No
deploy and run smoke tests
=> Update smoke tests to use https for kind

api/apis/service_binding_handler.go, api/apis/service_binding_handler_test.go, api/tests/e2e/service_bindings_test.go, scripts/deploy-on-kind.sh, tests/smoke/run-smoke-tests-kind.sh, tests/smoke/smoke_test.go
#627
Fix a bug where the `included` block of the list service bindings call would return apps even if no service bindings matched the service instance guid filter. Also includes some diffs from running `make fmt`.
No
Follow A/C for #627 and query for service bindings with a service instance guid filter of nonexistent instances. Expect no info returned in the `included` block of the response.
paired w/ @julian-hj
=> Only include app info for returned bindings

api/apis/app_handler_test.go, api/tests/e2e/apps_test.go
**Note:** There is a slight discrepancy between the product behavior and the stated A/C in #734 
The story expects an error like `"detail": "Process not found"`
The product is currently returning `"detail": "App not found. Ensure it exists and you have access to it."`
We believe that the product behavior is more correct, and doesn't leak any information that the user shouldn't have access to.
We also noticed that the app routes endpoint returns the `"App not found"` error message when the app cannot be found, so this behavior is more consistent.
Having said that, please feel free to reject the story if there is some nuance we missed.
#734
- implementation was already correct, but tests were missing
- this commit adds handler unit and e2e tests.
No.
#734 (see note above)
@acosta11
=> Backfill tests for /v3/apps/:guid/processes/:type

api/apis/app_handler.go, api/apis/build_handler.go, api/apis/buildpack_handler.go, api/apis/domain_handler.go, api/apis/droplet_handler.go, api/apis/job_handler.go, api/apis/log_cache_handler.go, api/apis/org_handler.go, api/apis/package_handler.go, api/apis/process_handler.go, api/apis/resource_matches_handler.go, api/apis/role_handler.go, api/apis/root_handler.go, api/apis/root_v3_handler.go, api/apis/route_handler.go, api/apis/service_binding_handler.go, api/apis/service_instance_handler.go, api/apis/service_route_binding_handler.go, api/apis/space_handler.go, api/apis/space_manifest_handler.go, api/apis/whoami_handler.go, api/tests/e2e/e2e_suite_test.go
No.
An endpoint is defined by a path and a method, we used endpoint constants for paths and duplicated them for operations using different methods on the same path (e.g. `GET` and `DELETE` on the same resource).
This removes the duplication and fixes the constant names.
No.
=> Endpoints are not paths

api/repositories/process_repository.go, api/repositories/process_repository_test.go, api/tests/e2e/e2e_suite_test.go, controllers/config/cf_roles/cf_admin.yaml, controllers/config/cf_roles/cf_space_developer.yaml, controllers/reference/cf-k8s-controllers.yaml
#734
This PR updates the `GetProcessByAppTypeAndSpace` function in the process repository to use a user client instead of the privileged client.
No
See #734
@acosta11
=> GetProcessByAppTypeAndSpace now uses a user client

api/tests/e2e/spaces_test.go, controllers/apis/networking/v1alpha1/integration/cfroute_webhook_integration_test.go, controllers/webhooks/cf_validation_errors.go, controllers/webhooks/networking/cfroute_validation.go, controllers/webhooks/networking/cfroute_validation_test.go, go.mod, go.sum
#664 
Hostname validation on routes
- validation on the api side was already in place.
- used `govalidator - IsDNSName()`  to validate hostnames on controllers via webhooks
No.
Follow acceptance on #664 
@Birdrock @clintyoshimura @acosta11
=> Routes on shared domains must have a hostname specified

api/actions/scale_process.go, api/actions/scale_process_test.go, api/tests/e2e/processes_test.go
[#625]
- this is primarily a testing change, since the scale and get methods
for the process repository already use the user client.
- the exception is in the handler code where we were missing a 403->404
translation.
no
[#625]
soloing at EOD... @gcapizzi @kieron-dev PTAL if you get a chance
=> RBAC logic for scale process endpoint

api/repositories/role_repository.go, api/repositories/role_repository_test.go
#819 
The CF CLI expects a specific error detail when adding a user to a role they are already a member of and will not ignore the error otherwise. This commit restores the expected error detail format so that the CLI will ignore the error.
[#819]
no, but it does introduce a **fixing** change
#819 
@clintyoshimura @danail-branekov @kieron-dev @georgethebeatle PTAL
=> Fix CLI errors during space creation

api/tests/e2e/spaces_test.go
no
We see a frequent errors in the space list tests that suggest either uninitialized variables in beforeEach or cross-contamination of the environment in parallel tests or both.
This PR attempts to clean those up by making the "list all spaces" test more resilient to extra spaces and by initializing a lot of local variables that could be leaking results from one test to the next in a single thread.
no
run e2e in the CI a bunch of times. There shouldn't be flakes in the space list tests anymore.
=> Reduce flakes in space list e2e tests

api/repositories/org_repository.go, api/tests/e2e/spaces_test.go
#820 
Fixes an issue where the v3 cf client expects a different error message to indicate that a create space command failed because the space already exists. Because the error message didn't contain the expected substring, the cli no longer ignored the error and the command failed.
no
See bug acceptance criteria
@julian-hj
=> Update create space exists error to match the cli

scripts/common.sh, scripts/deploy-on-kind.sh, scripts/install-dependencies.sh
This uses the `retry` utility function to retry the installation of the default `vcap.me` domain when `deploy-on-kind.sh` is invoked with `-d`.
Given `retry` was defined in `install-dependencies.sh`, I extracted it to a `common.sh` file and `source`d it in both scripts.
=> Retry domain installation in `deploy-on-kind.sh`

api/apis/route_handler.go, api/apis/route_handler_test.go, api/tests/e2e/routes_test.go, controllers/apis/networking/v1alpha1/integration/cfroute_webhook_integration_test.go, controllers/apis/networking/v1alpha1/integration/webhook_suite_integration_test.go, controllers/main.go, controllers/webhooks/cf_validation_errors.go, controllers/webhooks/networking/cfroute_validation.go, controllers/webhooks/networking/cfroute_validation_test.go, go.mod, go.sum
#754 
Validates FQDN on routes and also improves existing Hostname validation on routes
- added IsFQDN() for validating `host + "." + domain` value.
- IsHost() checks for validity of hostnames on routes
- removed the `HostNameIsInvalidError` as it is not being used by api repositories.
No.
Follow acceptance steps on #754
=> Add FQDN validation on routes to api and webhook

Makefile, controllers/config/default/manager_auth_proxy_patch.yaml, controllers/config/manager/manager.yaml, controllers/config/overlays/kind-controller-debug/kustomization.yaml, controllers/config/overlays/kind-controller-debug/manager_debug_container.yaml, controllers/config/overlays/kind-controller-debug/manager_debug_nodeport.yaml, controllers/remote-debug/Dockerfile, scripts/deploy-on-kind.sh
- the new option is -D or --debug
- when selected, this will rebuild the docker container with Delve and
deploy it with a port open on 40000
- this change also adds a NodePort for the debug channel, and exposes it
through Kind on localhost:30051
No, this was a dev-day project last Friday
This change adds a remote-debug option to the script that enables developers to debug controllers in-situ
There are a few parts involved:
- a new Dockerfile that builds the controller image on top of Ubuntu instead of distroless, and includes the Delve (`dlv`) executable.
- a Kustomize patch to change the options and command for the controller-manager deployment so that it runs Delve instead of running the controller manager directly.
- a NodePort service that maps the debug port from Delve
- a new port …
=> Add a controller debug option to deploy-on-kind script

controllers/controllers/workloads/imageprocessfetcher/image_process_fetcher.go
No.
Use `k8s.io/utils/net` `ParsePort` to  correctly parse and convert port numbers in `image_process_fetcher.go`
No.
Run tests as normal.
@tcdowney @gnovv @davewalter
=> Fix incorrect conversion of an integer

.github/workflows/codeql-analysis.yml
No, but discussed on the Mar 22, 2022 CF on K8s WG call that we'll try this out.
* We've decided to experiment with running Github's new CodeQL Github action. If it's noisy or unhelpful we can always remove this in the future.
* Docs: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning
No
On new PRs we can see code scans run.
@Birdrock
=> Add Github CodeQL static code analysis action

Makefile
No.
Updates for Go 1.18 compatibility.
No if using a version of Go that supports `go install`.
Delete binaries in `controllers/bin` then run `make install-controller-gen` and `make install-kustomize`.
@davewalter
=> Use `go install` for tooling instead of `go get`

api/repositories/route_repository.go, api/repositories/route_repository_test.go, api/tests/e2e/routes_test.go
[#736]
- route creation returns 422 unprocessable entity if the user doesn't
have rights to see the space
- it returns 403 Forbidden if the user has rights to view the space but
not create routes.
No.
#736 
Caveat: the A/C on the issue appears to be incorrect and calls for a 404 instead of a 422 in the case where the user lacks view permissions on the space.
=> Add RBAC to create route endpoint

README.md, controllers/config/rbac/cfservicebinding_reconciler_role.yaml, controllers/config/rbac/kustomization.yaml, controllers/reference/cf-k8s-controllers.yaml, scripts/install-dependencies.sh
closes #746 
Volume mount serviceBinding credentials onto workloads
- Add ClusterRole required by the ServiceBinding Controller to fetch the referenced CFServiceBinding object
- Add installation of ServiceBinding controller to `deploy-on-kind` script.
- Update README with manual installation instructions
no
see issue
@gnovv
=> Volume mount serviceBinding credentials onto workloads

api/repositories/route_repository.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/routes_test.go, controllers/webhooks/cf_validation_errors.go, controllers/webhooks/networking/cfroute_validation.go, controllers/webhooks/networking/cfroute_validation_test.go
#837 
In the route validating webhhook, check that all apps in the
destinations list are in the route's namespace.
Where an app is not found in the namespace, translate that to an API
unprocessable entity error
No
See #837
=> Check for route destinations outside the space

controllers/apis/workloads/v1alpha1/cfapp_types.go, controllers/config/crd/bases/workloads.cloudfoundry.org_cfapps.yaml, controllers/reference/cf-k8s-controllers.yaml, controllers/webhooks/workloads/cfapp_validation.go, controllers/webhooks/workloads/integration/cfapp_validation_integration_test.go
closes #723
- Adds Case-Insensitive CFApp spec.Name Validation
- Updates CFApp spec.Name regex to allow upper-case characters
Co-authored-by: Ashwin Krishna <krishnaas@vmware.com>
No.
see issue
currently there is a bug that prevents you from creating app names with upper-case letters initially.
You must validate by creating a lower-case named app, then trying to push the upper-case version afterwards.
We created a [bug issue](https://github.com/cloudfoundry/cf-k8s-controllers/issues/853) to track this.
@akrishna90 
@acosta11
=> Adds Case-Insensitive CFApp spec.Name Validation

api/apis/shared.go, api/repositories/route_repository.go, controllers/config/samples/cfroute.yaml, controllers/webhooks/cf_validation_errors.go, controllers/webhooks/networking/cfroute_validation.go, controllers/webhooks/networking/cfroute_validation_test.go, go.mod, scripts/deploy-on-kind.sh, scripts/install-dependencies.sh
#755 
Validates routes according to Cloud Controller rules.
It should not break anything currently existing. Previously valid routes may fail validation on update; this would require updating to a valid route.
* Run tests as normal.
* `cf create-route ... --path <some path>`
* `kubectl apply -f <some CFRoute>`
@tcdowney @acosta11 @davewalter
=> Validate CFRoute path

dependencies/hnc-manager-v0.9.0.yaml, scripts/install-dependencies.sh
No
We've noticed the hnc controller CPU being throttled at 100m. This increases the limit to 500m to avoid throttling. It has the effect of speeding up e2es running locally on kind from 20 minutes to 13 minutes and its CPU peaks at around 300m.
No
e2es run a bit quicker, and if you observe the CPU usage on the hnc pods, it shouldn't be near the limit.
=> Bump the allocated cpu for the HNC deployment

api/tests/e2e/service_instances_test.go
No
Fix service instance delete e2e test to use eventually to reduce the number of flakes
No
The e2e service instance delete test passes consistently
@matt-royal
=> Fix flaky service instance delete e2e test

api/actions/apply_manifest.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/spaces_test.go
No, but related to the changes introduced in #741  
Fix RBAC issue for apply manifest endpoint
- while invoking the `ListRoutesForApp()` function from `apply_manifest_action`, we were incorrectly passing `appGUID` as `spaceGUID` and vice versa. this PR fixes this issue
- `privilegedClient` was used in the repo method until the changes to address issue #741 was merged. We think `privilegedClient` dealt with non-existent spaces differently, causing the bug to fly under the radar. 
No
`cf push` should now succeed
@tcdowney @Birdrock @gnovv
=> Fix RBAC issue for apply manifest endpoint

api/tests/e2e/apps_test.go, api/tests/e2e/service_bindings_test.go
No
Some app and service binding tests checking list results need to account for apps and service bindings created by other tests. So instead of checking for an absolute length of the list results, check that expected elements are contained, and unexpected elements are not contained. That is sufficient in an e2e test.
No
e2e tests pass
=> Fix e2e list flakes for app and service binding

.github/workflows/codeql-analysis.yml
Now that all checks take ~12m on gh actions it has become the bottleneck
with runtime of ~20m. Maybe runnign it on main only is a good compromise
that will improve our dev turnaround
=> No longer run codeql on every PR

api/actions/apply_manifest_test.go, api/repositories/app_repository_test.go, api/repositories/process_repository_test.go, api/repositories/route_repository_test.go, api/tests/e2e/spaces_test.go
No, although #886 is related.
This adds unit tests for all positive cases in `ApplyManifest`. I assume these were missing as we wanted to rely on the integration tests, but #886 shows that it's easy to miss things as simple as swapping the order of two arguments.
No.
=> Backfill missing unit tests for ApplyManifest

api/repositories/app_repository.go, api/repositories/app_repository_test.go, api/tests/e2e/spaces_test.go
#741. This resolves an issue with the original PR
Correct the error message when a user applies a manifest to a space they can't access
No
See issue
@gcapizzi
=> Correct apply-manifest error when user can't access space

api/apis/route_handler.go, api/apis/route_handler_test.go, api/repositories/app_repository.go, api/tests/e2e/routes_test.go, controllers/webhooks/networking/cfdomain_validation_test.go, controllers/webhooks/networking/cfroute_validation.go, controllers/webhooks/networking/cfroute_validation_test.go, scripts/install-dependencies.sh
closes #853
- Modifies FQDN regex to allow domains w/ upper-case letters
- Removes extra api shim FQDN check to instead elevate webhook error
- Modifies route FQDN e2e test to use k8s client and create an invalid domain for just one edge case
see bug.
@acosta11 
@Birdrock
=> Fix Route FQDN Validating Webhook

api/tests/e2e/spaces_test.go
=> Remove hard-coded `vcap.me` in e2e test

dependencies/hnc/base/default-v1.0.0.yaml, dependencies/hnc/base/kustomization.yaml, dependencies/hnc/cf/deployment.yaml, dependencies/hnc/cf/kustomization.yaml, go.mod, go.sum, scripts/install-dependencies.sh
#908 and also does the dependabot PR to bump HNC to v1.0.0 in full.
Bump HNC to v1.0.0 production release!!!
When taking the new `default.yaml` for v1.0.0 from the hnc release, I realised it could be easy to lose the manual modifications we had made to the previous `hnc-manager-v0.9.0.yaml` file. So I've put the changes
in a patch file to apply with kustomize to make this more secure.
The bash lines to wait for HNC to come up fully have also been removed as v1.0.0 has a proper /readyz implementation.
Fixes: https://github.com/cloudfoundry/cf-k8s-controllers/issues/908
No
e2es green
=> Bump HNC to v1.0.0

scripts/assets/cf-k8s-api-kbld.yml, scripts/assets/cf-k8s-controllers-kbld.yml
No
This aligns the config with the concourse e2e configuration, which no longer uses docker to build the images within a docker-in-docker container image.
No
The e2e deploy step on concourse should succeed.
=> Update kbld config to use kubectlBuildkit

scripts/run-tests.sh
No
The new up-front user cert and service account creation scripting for e2es is causing a problem when the service account token isn't ready when we try to fetch it. This adds a retry loop so we will eventually get the token.
No
E2es should be greener
=> retry getting service account tokens

api/repositories/role_repository.go, api/repositories/role_repository_test.go
#905
This makes sure that `cf_user` bindings are always annotated with `propagate.hnc.x-k8s.io/none=true`, as we never want them to propagate.
No.
* Create `org1` with `space1` inside it.
* Assign `OrgManager` to user `foo` in `org1`
* See that the `root-namespace-rolebinding` for user `foo` only exists in the `cf` namespace, but *not* in the `org1` or `space1` namespaces.
=> Make sure `cf_user` bindings are never propagated

api/repositories/org_repository.go, dependencies/hnc/cf/deployment.yaml
Supposedly #303.
We have reverted the HNC qps setting to 50 as 200 seems to make GKE
cluster API unresponsive, causing nodes to be recreated.
We have also made the timeout in the org repo longer. It uses the same
timeout as used for waiting for the subnamespaceanchor to be ready.
Since the average time for propagation to complete is around 8 seconds
during heavy load on GKE during e2e tests, we have decided not to use
exponential backoff. This was missing a check at around 6 seconds then
having to wait until 12 seconds to succeed. Simply checking every 500ms
seems to provide better results.
No
e2es more stable
=> Tweak waiting for HNC propagation

scripts/common.sh, scripts/create-new-user.sh, scripts/run-tests.sh
No
Move common cert creation into common.sh and call from run-tests and create-new-user scripts.
No
e2es are more stable and don't fail with cert decoding errors
=> Make cert/token creation thread safe

scripts/account-creation.sh, scripts/common.sh, scripts/run-tests.sh
No
Extract creation of user certs/keys and service accounts/tokens from the run-tests script. Place it in a separate file that can be sourced from run-tests and in a concourse task
No
e2es green
=> Extract user/service account creation from run-tests script

api/tests/e2e/domains_test.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/routes_test.go, scripts/deploy-on-kind.sh, scripts/run-tests.sh
No
This simplifies the deployment process to help running tests on concourse.
Creating the default domain is the responsibility of the deployment rather than running tests, so move the creation there.
Since the GUID can be determined via the API, stop passing this in as an env var to the tests.
No
e2es green
=> Move default domain creation to deploy script

.github/ISSUE_TEMPLATE/explore.yaml
No
We talked as a team about how we've been using the "days to checkin" discussion during IPM just to discuss complexity and not to actually determine a timebox. Updating this template to make it more clear that this is optional and can be included if we decide an explicit timebox is helpful.
No
Create a new explore issue and make sure it looks good.
@davewalter @Birdrock
=> Update exploration issue template

api/tests/integration/integration_suite_test.go
There is no apparent reason to setup envtest in for every test in
`BeforeEach`. This change does that in `BeforeSuite` (i.e. once for the
suite) which halves suite execution time.
No
Green tests
=> Setup envtest per suite in api integration tests

api/tests/integration/integration_suite_test.go
There is one test in token_reviewer_test that restarts the envtest
server with custom arguments. If the envtest server is made global
it mens that the next test that happens to run would have an apiserver
with unexpected config and will fail
https://github.com/cloudfoundry/cf-k8s-controllers/blob/b5a45fd4b5914ff634964b3a53ab02c3fb13b6b7/api/tests/integration/token_reviewer_test.go#L47
=> Revert "Setup envtest per suite in api integration tests"

controllers/apis/networking/v1alpha1/integration/cfroute_webhook_integration_test.go, controllers/apis/networking/v1alpha1/integration/webhook_suite_integration_test.go, controllers/apis/networking/v1alpha1/webhook_suite_test.go, controllers/apis/workloads/v1alpha1/integration/cfapp_webhook_integration_test.go, controllers/apis/workloads/v1alpha1/integration/cfbuild_webhook_integration_test.go, controllers/apis/workloads/v1alpha1/integration/cfpackage_webhook_integration_test.go, controllers/apis/workloads/v1alpha1/integration/cfprocess_webhook_integration_test.go, controllers/apis/workloads/v1alpha1/integration/webhook_suite_integration_test.go, controllers/apis/workloads/v1alpha1/webhook_suite_test.go, controllers/controllers/networking/integration/suite_integration_test.go, controllers/controllers/networking/suite_test.go, controllers/controllers/services/integration/cfservicebinding_integration_test.go, controllers/controllers/services/integration/suite_integration_test.go, controllers/controllers/services/suite_test.go, controllers/controllers/workloads/integration/cfapp_controller_integration_test.go, controllers/controllers/workloads/integration/cfbuild_controller_integration_test.go, controllers/controllers/workloads/integration/cfpackage_controller_integration_test.go, controllers/controllers/workloads/integration/cfprocess_controller_integration_test.go, controllers/controllers/workloads/integration/suite_integration_test.go, controllers/controllers/workloads/suite_test.go, controllers/coordination/coordination_suite_test.go, controllers/coordination/integration/integration_suite_test.go, controllers/webhooks/networking/networking_suite_test.go, controllers/webhooks/services/suite_test.go, controllers/webhooks/webhooks_suite_test.go, controllers/webhooks/workloads/integration/suite_integration_test.go, controllers/webhooks/workloads/suite_test.go
No
Set the default eventually timeouts in all controllers tests
We hope that this will mitigate some flakes that seem to be
happening due to failed Updates resulting in exponential backoffs in the
reconciliation loop. This also saves setting timeouts explicitly in the code.
No
Green tests
=> Bump default eventually timeout for controller tests

api/repositories/org_repository.go, api/repositories/org_repository_test.go, api/repositories/repositories_suite_test.go
No, but related to #928
- We ran into an issues with creating cf-spaces where the creation would fail with cf-org not found error.
- Having a check to see if the user is able to list apps after creation of orgs and spaces would not work the way we expect if the user is a k8s "cluster-admin". The cluster-admins have permissions to list any object.
- Added a better check to make sure that the role binding exists for the current user in the newly created namespace before returning success on create orgs and spaces
No
- `make test-e2e` should pass
- smoke tests should pass consistently
@gnovv @clintyoshimura
=> Fix flakey behaviour with creating cfspace

api/apis/integration/app_test.go, api/apis/integration/apply_manifest_test.go, api/apis/integration/integration_suite_test.go, api/apis/integration/route_test.go, api/repositories/domain_repository_test.go, api/repositories/org_repository_test.go, api/repositories/package_repository_test.go, api/repositories/process_repository_test.go, api/repositories/repositories_suite_test.go, api/repositories/route_repository_test.go, api/tests/e2e/service_instances_test.go, api/tests/integration/token_reviewer_test.go
Some Eventually's that make sense have been left in place. This is
usually the case for resources that are not directly created by the
client (e.g. process, droplet, etc). When the API has async contract by
returning a 202 with a Location header, the same applies. In all other
cases we assume that resources should be directly available to the
client.
The goal is to expose any potential flakes due to the async nature of
k8s, evaluate how critical they are and decide how to best handle them,
rather than the current approach of hiding this information.
=> Remove Eventually statements from api related tests

scripts/account-creation.sh, scripts/common.sh
No
After recent changes to the scripts, they no longer run successfully on Mac computers due to different flags for `base64`. This PR accomplishes the same output in a way that works on both Mac and Linux.
No
Run the `./scripts/deploy-on-kind.sh` script locally and see that it succeeds
=> Fix the scripts to work on Macs

scripts/samples/deploy-release.sh
No
A sample script to deploy a release tarball on kind
No
Run the script and see it deploy. Optionally you can run e2es via `SKIP_DEPLOY=true KUBECONFIG=~/.kube/config make test-e2e` after targeting the `korifi cluster`
=> Sample script to deploy a release on kind

README.md, api/config/config.go, api/main.go
#956 
This PR adds new fields to the API config file to allow users to configure a cluster auth proxy. It also updates the README with instructions.
No
See #956 
@julian-hj
=> Add auth proxy config to API

api/tests/e2e/service_bindings_test.go
No 🤠 
tries to fix an RBAC flake due to test sequencing granting permissions to ServiceBindings before the empty list test runs.
The goal of the test is more RBAC focused rather than testing the empty list case anyway. Now it just confirms that it doesn't see ServiceBindings that we know aren't permitted by the RBAC.
no.
confirm boxes green.
@acosta11
=> Fix e2e ServiceBinding List Flake

api/apierrors/errors.go, api/apierrors/errors_test.go, api/apis/app_handler.go, api/apis/app_handler_test.go, api/apis/droplet_handler_test.go
closes #965
- Adds new apierror specifically for wrapping Droplet NotFound and Forbidden errors
no
see issue.
=> Bug: Fix GET CFApp Droplet Not Found message for CLI

Makefile, api/config/base/deployment.yaml, api/config/base/rbac/role.yaml, api/config/base/rbac/role_binding.yaml, api/config/base/rbac/service_account.yaml, api/reference/korifi-api.yaml
#469 
The name `cf-admin` should be reserved for the CloudFoundry Admin user [role]. So let's not use that in the API service account name, the cluster role it uses and the cluster role binding. The name `system` should be clear after kustomize has added its `korifi-api-` prefix.
No
`make test-e2e`
=> Improve service account / role naming

api/apis/fake/cfroute_repository.go, api/apis/route_handler.go, api/apis/route_handler_test.go, api/repositories/route_repository.go, api/repositories/route_repository_test.go, api/tests/e2e/routes_test.go, docs/api.md
[#957]
- Implements DELETE /v3/routes/{guid}/destinations/{destination_guid}
- Extra credit: added a unit test to validate 404 behavior when an
unprivileged user tries to add a route.
- Other extra credit: correct wrong URLs in the docs for routes.
No
[#957]
@matt-royal PTAL
=> Add DELETE endpoint for route destinations

.github/workflows/test-build-push-main.yml, README.md
No
This was failing after the cf -> korifi rename.
No
Badges visible at top of readme, and clickable through to the correct code climate report.
=> Fix codeclimate links in readme

api/apis/authentication_middleware.go, api/apis/authentication_middleware_test.go, api/apis/log_cache_handler.go, api/apis/log_cache_handler_test.go
No 🤠 
Reverts the auth on the v1 info endpoint- we were seeing an issue with `cf push` getting an unauthorized response:
```
REQUEST: [2022-04-27T10:54:47-07:00]
GET /api/v1/info HTTP/1.1
Host: localhost
Authorization: 
User-Agent: cf/0.0.0-unknown-version (go1.17.2; amd64 linux)
RESPONSE: [2022-04-27T10:54:47-07:00]
HTTP/1.1 401 Unauthorized
Content-Type: application/json
Date: Wed, 27 Apr 2022 17:54:47 GMT
X-Envoy-Upstream-Service-Time: 0
Vary: Accept-Encoding
Server: envoy
```
No.
Run `cf push` observe that we no longer see 401 errors
@acosta11 @tcdowney
=> Revert auth on v1/info endpoint

scripts/common.sh, scripts/deploy-on-kind.sh, scripts/generate-eirini-certs-secret.sh
No.
- openssl creates an ascii representation of a key every time we
generate one, which results in a big glob of useless dots and plusses
in our script output.
- this change redirects that output to /dev/null
No.
- run ./scripts/deploy-on-kind.sh or run the e2e tests
- observe that the output is 15% less annoying
=> Suppress acsii art from openssl

.golangci.yml, api/apis/fake/cfspace_repository.go, api/apis/space_manifest_handler.go, api/apis/space_manifest_handler_test.go, api/repositories/route_repository.go, api/repositories/route_repository_test.go, api/repositories/space_repository.go, api/tests/e2e/orgs_test.go, controllers/config/webhook/manifests.yaml, controllers/main.go, controllers/reference/korifi-controllers.yaml, controllers/webhooks/workloads/cforg_validation.go, controllers/webhooks/workloads/cforg_validation_test.go, controllers/webhooks/workloads/cfspace_validation.go, controllers/webhooks/workloads/cfspace_validation_test.go, controllers/webhooks/workloads/integration/cforg_validation_integration_test.go, controllers/webhooks/workloads/integration/cfspace_validation_integration_test.go, controllers/webhooks/workloads/integration/helpers/subnamespace_anchors.go, controllers/webhooks/workloads/integration/suite_integration_test.go
#768
Adds validating webhook for `CFOrg` and `CFSpace` that uses leases mechanism for denying requests trying to create duplicate spaces.
No
See issue #768 
@julian-hj
=> Add validation webhook for CFOrg and CFSpace for enforcing naming constraints

api/config/base/certificate.yaml, api/config/base/deployment.yaml, api/config/base/ingress.yaml, api/config/base/kustomization.yaml, api/config/base/kustomizeconfig.yaml, api/config/base/service.yaml, api/main.go, api/reference/korifi-api.yaml, scripts/deploy-on-kind.sh
#850
This PR updates the Korifi API to listen on TLS with an internal certificate generated by cert-manager, and tells the Contour HTTPProxy to connect over TLS and validate the API certificate.
No
See #850
@clintyoshimura @tcdowney @matt-royal
=> Configure TLS connection to API

api/repositories/space_repository.go, api/repositories/space_repository_test.go
#1035 
We are only guessing which namespaces to list in by iterating through any namespace containing a rolebinding for the user. The rolebinding might not give cfspace listing permission. So we must not fail when we encounter a k8s forbidden error.
No
You must create an org whose namespace contains a role binding for the current user, but that role binding does not provide list cfspace permission. Then attempt to list spaces as that user. This changes the 403 error into omitting spaces from that org in the results.
Creating such a rolebinding via CF is tricky. Maybe resort to doing it manually with kubectl.
=> Ignore forbidden errors when listing spaces

scripts/run-tests.sh
No
ENVVAR tweaks to the run-tests.sh script:
- GINKGO_NODES previously only affected e2e tests. Now it will work on any.
- Add NO_RACE to disable the --race flag.
No
Setting the env vars above has the intended effect.
=> Allow ginkgo nodes and --race to be set by env vars for all tests

scripts/run-tests.sh
No
I accidentally committed 'echo' in front of ginkgo in `run-tests.sh`. This fixes it.
=> Fix accidentally left debug line

api/apierrors/errors.go, api/repositories/domain_repository.go, api/repositories/pod_repository.go, controllers/controllers/networking/cfroute_controller.go, controllers/controllers/services/cfserviceinstance_controller.go, controllers/controllers/workloads/cfapp_controller.go, controllers/controllers/workloads/cfprocess_controller.go
No.
- for loop uses a local copy when looping. This shouldn't be
dereferenced, as the for loop will overwrite it and leave an
unreliable pointer behind.
- also, add underscore receivers for error returns we don't care about
in order to make golint/gosec happy.
No.
@akrishna90
=> Fix unsafe references to local for loop variables

controllers/apis/services/v1alpha1/cfservicebinding_types.go, controllers/apis/services/v1alpha1/cfserviceinstance_types.go, controllers/apis/workloads/v1alpha1/cfapp_types.go, controllers/apis/workloads/v1alpha1/cforg_types.go, controllers/apis/workloads/v1alpha1/cfspace_types.go, controllers/config/crd/bases/services.cloudfoundry.org_cfservicebindings.yaml, controllers/config/crd/bases/services.cloudfoundry.org_cfserviceinstances.yaml, controllers/config/crd/bases/workloads.cloudfoundry.org_cfapps.yaml, controllers/config/crd/bases/workloads.cloudfoundry.org_cforgs.yaml, controllers/config/crd/bases/workloads.cloudfoundry.org_cfspaces.yaml, controllers/reference/korifi-controllers.yaml
`kubectl` will now print the display name and age of the following resources:
- CFOrg
- CFSpace
- CFApp
- CFServiceInstance
- CFServieBinding
Issue: https://github.com/cloudfoundry/korifi/issues/1069
Improve the UX of kubectl users by printing the display name of a resource when its available.
No
Create an org, space, push an app, create a user-provided service instance, and then bind the instance. This will create all the affected custom resources on the cluster. Then view them all with `kubectl`.
These were the specific CF commands I ran:
1. `cf create-org o && sleep 1 && cf create-space s -o o && sleep 1 && cf target -o o -s s`
2. `cf push node`
3. `cf cups my-upsi`
4. `cf bind-service node my-upsi --binding-name my-binding` (if you don't specify a binding-name then the display name …
=> Include spec.displayName as an additionalPrinterColumn

Makefile, README.md, api/config/overlays/kind-api-debug/api_debug_container.yaml, api/config/overlays/kind-api-debug/api_debug_nodeport.yaml, api/config/overlays/kind-api-debug/kustomization.yaml, api/remote-debug/Dockerfile, controllers/config/overlays/kind-controller-debug/manager_debug_container.yaml, controllers/remote-debug/Dockerfile, scripts/deploy-on-kind.sh
No.
Allow remote debugging of the api container
No.
Follow updated instructions in README
> Deploying to `kind` for remote debugging with a locally deployed container registry
@davewalter
=> API server remote debug support

api/actions/apply_manifest.go, api/actions/apply_manifest_test.go, api/apis/integration/apply_manifest_test.go, api/apis/space_manifest_handler_test.go, api/payloads/manifest.go, api/payloads/manifest_test.go
#406
This PR adds support for the memory field in an application manifest, which will create a "web" process if one does not already exist with the specific memory request.
No
See #406
@akrishna90
=> Add support for "app memory" manifest field

api/authorization/user_client_factory_test.go
No
The `user_client_factory_test.go` has just flaked 3 times at line 131. We introduced the retrying wrapper to fix this sort of problem in production code, so lets use it with more than 0 retries!
No
The above test stops flaking
=> We need to retry k8s calls after creating a rolebinding

api/tests/e2e/domains_test.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/helpers/fail_handler.go, api/tests/e2e/helpers/resty.go, api/tests/e2e/orgs_test.go, api/tests/e2e/processes_test.go, api/tests/e2e/roles_test.go, api/tests/e2e/routes_test.go, api/tests/e2e/spaces_test.go
https://github.com/cloudfoundry/korifi/issues/656
This is implemented by transparently sending a unique correlation ID by
every `It`
* Wrapper for the resty client that would inject the correlation ID for
every API request
* The fail handler filters out API log entries that do not contain the
correlation ID
* The fail handler does not filter controllers logs though (as there is
no correlation ID)
* The correlation ID is being reset in a `BeforeEach` in the suite so
that every `It` gets a new value and does not have to care to do that
No
* Make a e2e test deliberately fail by e.g. changing the HTTP status code it expects
* Look at the api logs printed by the fail handler - it should only contain entries that contain the correlation ID available in the failed resty request headers
=> Filter API logs by correlation ID on E2E failure

kpack-image-builder/Makefile
No
- the Kustomize command we were using in the makefile didn't target the
image we want to replace when we build the controller.
no?
run deploy-on-kind.sh
=> Fix kpack-builder Kustomization

api/tests/e2e/apps_test.go, api/tests/e2e/droplets_test.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/log_cache_test.go, api/tests/e2e/packages_test.go, api/tests/e2e/processes_test.go, api/tests/e2e/routes_test.go
No
Update end to end tests to use a configurable file for app bits instead of the hardcoded binary. By default, behavior remains the same.
No
Deploy korifi normally for development and run end to end tests. See that tests continue to pass and that the prebuilt node app is still being pushed by default.
Prepare a different app known to successfully build with the default builder in the assets dir like the previously used `assets/node.zip`, set the "APP_BITS_FILE" environment variable accordingly to that file, and see that the tests continue to pass while pushing that app.
paired w/ @Birdrock
=> Make e2e app bits configurable

.github/workflows/test-build-push-main.yml
No
The `deploy-on-kind` with `SKIP_DEPLOY=true` assumes that the image is
present and it is set into the `IMG_KIB` env var
No
E2E on main actions workflow should succeed
@gcapizzi
=> Use the kpack-image-builder image built on previous step

api/authorization/token_reviewer_test.go
#1095 
Since we have an env-test server per ginkgo process, we must restore it after modifying it so that subsequent tests run against an env-test with the expected configuration.
No
The token-reviewer test stops flaking.
=> Fix env-test server after modifying it for test

scripts/deploy-on-kind.sh
The kpack-image-builder deployment is currently breaking CI on `main`, so we're taking it out for now, until we're sure it's working.
=> Don't deploy KIB in deploy-on-kind.sh for now

controllers/apis/v1alpha1/cfprocess_types.go, controllers/config/crd/bases/korifi.cloudfoundry.org_cfprocesses.yaml, controllers/reference/korifi-controllers.yaml
#720 
Update the descriptions for the memory and disk quota fields in the CFProcessSpec object to reflect the MiB units
no
See issue
@gnovv
=> Update the description for CFProcessSpec

api/apis/org_handler.go, api/apis/org_handler_test.go, api/config/config.go, api/config/overlays/kind-local-registry/apiconfig/korifi_api_config.yaml, api/config/overlays/kind/apiconfig/korifi_api_config.yaml, api/main.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/orgs_test.go, scripts/account-creation.sh, scripts/common.sh, scripts/deploy-on-kind.sh
#1090 
- The intent is to display a warning at login when a user with a
long-lived certificate logs in.
- We do this by setting the X-Cf-Warnings header when we detect such a
certificate. The CLI will relay the header string value to STDOUT.
- However the CLI doesn't check for warnings on the /whoami enpoint, so
we settled on the /v3/orgs endpoint because that gets called by the
CLI on each login.
- In the future we might consider enhancing the CLI to check for
warnings on /whoami and then moving the check into the whoami handler.
- The default threshold for warnings is 7 days, but that value is
configurable on the API shim configuration as
`userCertificateExpirationWarningDuration`
- Note: we could not unit test this code because the authentication
middleware isn't wired into the unit …
=> Add check for long-lived client certificates

scripts/account-creation.sh, scripts/deploy-on-kind.sh
No related issue.
This PR changes our e2e test setup so that it explicitly creates the ServiceAccount token, rather than assuming that the k8s cluster will automatically make a token secret. The automatic secret creation was removed in k8s 1.24.
This PR also changes the kind image back to the default, since we no longer require k8s 1.23 or older.
No
Sadly, we won't really know if this PR works until it's merged and we confirm that the github actions against the commit on main pass.
=> Explicitly create service account token

api/config/base/deployment.yaml, api/reference/korifi-api.yaml, controllers/config/manager/manager.yaml, controllers/reference/korifi-controllers.yaml, kpack-image-builder/config/manager/manager.yaml
no
Lowering resource requests in an effort to get e2e tests working again in github actions.
We've seen that deployments are consistently failing trying to deploy the kpack-build-controller-manager, which is the last deployment in the installation. I'm speculating that the environment is just out of CPU, as it has a [quota of 2 cores](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) and both of our controller managers were asking for .5 cores. This change reduces the request to something a bit more modest that should still work.
- reduce the memory and CPU request sizes for the api shim, controller
and kpack-build controller deployments
- this brings the request sizes more in line with other pods such as …
=> lower resource requests for korifi deployments

api/repositories/droplet_repository.go, api/repositories/droplet_repository_test.go, api/repositories/process_repository.go, api/repositories/process_repository_test.go
The list of namespaces we list a resource in is just a list of namespaces containing a `RoleBinding` for the current user. This does not mean the user will be authorised for the list action we are attempting in the namespace. Therefore we should silently ignore forbidden errors during list.
=> Listing droplets and processes must tolerate 403 errors

controllers/controllers/workloads/cfspace_controller.go, controllers/controllers/workloads/cfspace_controller_test.go, controllers/controllers/workloads/integration/cfspace_controller_integration_test.go
No.
The `CFSpaceReconciler` tries to create a couple of service accounts if they don't already exist, but it did so by running `Get` before `Create`, which was prone to races. This changes it to always try to create and ignore the error in case it's an `AlreadyExists` one.
No.
=> Fix race condition on service account creation

api/handlers/app_handler.go, api/handlers/app_handler_test.go, api/handlers/integration/apply_manifest_test.go, api/handlers/job_handler.go, api/handlers/job_handler_test.go, api/handlers/org_handler.go, api/handlers/org_handler_test.go, api/handlers/route_handler.go, api/handlers/route_handler_test.go, api/handlers/space_handler.go, api/handlers/space_handler_test.go, api/handlers/space_manifest_handler.go, api/handlers/space_manifest_handler_test.go, api/presenter/job.go, tests/e2e/orgs_test.go, tests/e2e/routes_test.go, tests/e2e/spaces_test.go
Issue: https://github.com/cloudfoundry/korifi/issues/1116
This issue came from some real world usage where an operator was mirroring orgs/spaces from a CF for VMs environment and was using the `CFOrg` and `CFSpace` resources directly. They wanted to include the org/space names in the `metadata.name` instead of the GUID for operational convenience (they did not care to support org/space renaming).
From the commit message:
- We previously required that Job identifiers adhered
to a strict structure of `<operation>-<optional prefix>-<GUID>`.
- This change loosens this restriction so that Kubectl users are not required
to use a GUID and instead are able to use any valid Kubernetes resource.
- Changes the delimiter between job operation and resource
identifier to be "~". The "~" character is …
=> Job handler no longer requires Job IDs contain a GUID

INSTALL.md
This might help clarifying that the instructions are for released tarballs, not git checkouts.
=> Add link to releases page to INSTALL.md

INSTALL.md
Some files actually have `.yml` extensions, not `.yaml`.
=> Fix file extensions in INSTALL.md

controllers/api/v1alpha1/cfdomain_types.go, controllers/config/crd/bases/korifi.cloudfoundry.org_cfdomains.yaml, controllers/controllers/networking/integration/cfroute_controller_integration_test.go, tests/e2e/routes_test.go
resolves #1100 
Adds regex validation to CFDomain spec.Name
No.
Try to create a domain with `*` in it, and see that it fails.
```
$ k apply -f controllers/config/samples/cfdomain2.yaml 
The CFDomain "bad-domain" is invalid: spec.name: Invalid value: "*.bad.domain": spec.name in body should match '^[a-zA-Z]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z]([a-zA-Z0-9-]*[a-zA-Z0-9])?)*$'
$ k apply -f controllers/config/samples/cfdomain2.yaml 
The CFDomain "bad-domain" is invalid: spec.name: Invalid value: ".bad.domain": spec.name in body should match '^[a-zA-Z]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z]([a-zA-Z0-9-]*[a-zA-Z0-9])?)*$'
```
@acosta11
=> Add CFDomain spec.Name regex validation

INSTALL.md
The instructions will constantly change to track `main`, but people will still try to use them to install our latest release. We should warn them and point them to the correct version of this file, which I'm going to add to the release notes for every release.
=> Add version warning to INSTALL.md

api/handlers/root_handler_test.go, api/presenter/root.go, docs/api.md
Nope
- The CF CLI has a rolling window of minimum CF API versions that they support
- The current minimum API version supported for the 8.x CLI line is `1.109.0` which is getting close to `3.111.0`. I figured it's better to just go ahead and bump this.
- CLI's versioning policy is defined here: https://github.com/cloudfoundry/cli/wiki/Versioning-and-Support-Policy
- `3.117.0` is the latest v3 version in a capi-release and there do not appear to be any breaking changes in the API contracts that we support. I read through the [capi-release](https://github.com/cloudfoundry/capi-release/releases) release notes and skimmed the latest v3 API docs to validate this. I also went ahead and updated our doc links internally.
No
1. Target the API and confirm that the new version is reported (can also …
=> Bump to latest v3 API Version

scripts/check-everything.sh, tests/e2e/apps_test.go, tests/e2e/e2e_suite_test.go, tests/e2e/helpers/resty.go, tests/e2e/processes_test.go, tests/e2e/spaces_test.go
This decouples the tests from the code and makes sure we detect any breaking change in the future.
=> Remove references to production code in the e2es

controllers/api/v1alpha1/cftask_types.go, controllers/config/crd/bases/korifi.cloudfoundry.org_cftasks.yaml, controllers/controllers/workloads/cftask_controller_test.go
We should use camel-casing in CRDs for consistency.
=> `sequence_id` -> `sequenceId`

tests/e2e/apps_test.go, tests/e2e/builds_test.go, tests/e2e/droplets_test.go, tests/e2e/e2e_suite_test.go, tests/e2e/log_cache_test.go, tests/e2e/orgs_test.go, tests/e2e/packages_test.go, tests/e2e/processes_test.go, tests/e2e/roles_test.go, tests/e2e/routes_test.go, tests/e2e/service_bindings_test.go, tests/e2e/service_instances_test.go, tests/e2e/spaces_test.go, tests/e2e/tasks_test.go
This removes the `kind` argument from `createRole`, `createOrgRole` and `createSpaceRole,` as we never used anything different from `rbacv1.UserKind`.
We will need to reintroduce something similar when we add support for service accounts, but maybe the best idea is to have separate helpers.
=> Remove unused kind argument from role helpers

api/handlers/task_handler.go, api/handlers/task_handler_test.go
Task creation should return:
* `404 Not Found` if the user can get apps in the space but the app doesn't exist, **or** if the user can't get apps in the space.
* `403 Forbidden` if the user can get apps in the space but can't create tasks in the space.
=> Fix HTTP errors for task creation

api/handlers/task_handler_test.go, api/presenter/task.go, api/repositories/task_repository.go, api/repositories/task_repository_test.go
#1196 
This adds the `created_at` and `updated_at` fields to task objects.
No.
=> Introduce `created_at` and `updated_at` timestamps in tasks

scripts/install-dependencies.sh
https://github.com/cloudfoundry/korifi/issues/1197
Bump Eirini to 0.4.0 to propagate the disk/memory constraints to the pod template
No
See story for acceptance
=> Bump eirini to 0.4.0

controllers/controllers/networking/cfroute_controller.go, controllers/controllers/networking/cfroute_controller_test.go, controllers/webhooks/networking/cfroute_validator.go, controllers/webhooks/networking/cfroute_validator_test.go
[#1225]
- The CFDomain object may go missing either because the user deleted it,
or because it got deleted first during uninstall.
- Our CFRoute controller should allow removal of routes in this
scenario.
- This commit fixes two different failure cases that occur when the
CFDomain no longer exists.
no
[#1225]
=> CFRoute finalizer tolerates missing CFDomain

go.mod, go.sum, tests/smoke/run-smoke-tests-kind.sh, tests/smoke/smoke_suite_test.go, tests/smoke/smoke_test.go
Loosely #1014
Main change is to rework the `cf login` so it will select the correct number for the given user.
Also bump cf-test-helpers to a recent version where is go.mod enabled and containing the 'with-stdin' runner.
No
Run the run-smoke-tests-kind.sh script and see it work.
@gcapizzi
=> Refactor the smoke test suite

api/repositories/task_repository.go, api/repositories/task_repository_test.go
No
* task initialised timeout timer is created before running the select
loop which means it is going to be created just once rather than on
every loop
* introduce a kill channel for the controller-like loop in the
repositories test
No
Run repositories test while monitoring memory usage, the test process should not use anything abnormal
@kieron-dev
=> Fix a timer memory leak in task repository

tests/e2e/processes_test.go
This test has flaked historically
=> Bump timeout to accommodate app push

controllers/controllers/workloads/integration/cfprocess_controller_integration_test.go, controllers/controllers/workloads/integration/suite_integration_test.go
No
Failed CI build: https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/92
The test flakes because it expects an LRP for a process with certain
properties. Due to setting the VCAP_SERVICES env var asynchronously, the
LRP might not have its env set according to the expectations initially.
Therefore, this change puts all the LRP checks into `Eventually`
No
N/A
=> Fix flaky cfprocess controller integration test

kpack-image-builder/controllers/suite_test.go
No
Bump Eventually timeout/polling interval
We suspect that the default timeout of 1 second causes flakes
No
N/A
=> Bump Eventually timeout/polling interval

controllers/controllers/workloads/cfapp_controller.go, controllers/controllers/workloads/cfapp_controller_test.go, controllers/controllers/workloads/integration/cfapp_controller_integration_test.go
#1266 
This adds a `Staged` condition to `CFApp` which will be set to true only if the app has a valid droplet reference. The condition will be unset back to false if the droplet referenced by the app disappears.
This will make it very easy for the task creation endpoint to identify apps that are not staged yet and return proper errors.
No.
=> Introduce the `Staged` condition for `CFApp`

api/Dockerfile, api/handlers/task_handler.go, api/handlers/task_handler_test.go, api/repositories/app_repository.go, api/repositories/app_repository_test.go, controllers/controllers/workloads/cfapp_controller.go, controllers/controllers/workloads/cfapp_controller_test.go
#1266 
This changes the task creation endpoint so that it returns a `422 Unprocessable Entity` if the target app is not staged. The implementation leverages the `Staged` status condition introduced in #1269.
Not really. The error message has changed from a generic 500 to the correct one.
@kieron-dev
=> Reject tasks on unstaged apps in the API shim

api/config/base/deployment.yaml, api/config/base/namespace.yaml, controllers/config/default/manager_auth_proxy_patch.yaml, controllers/config/manager/manager.yaml, kpack-image-builder/config/default/project_namespace/manager_auth_proxy_patch.yaml, kpack-image-builder/config/default/project_namespace/manager_config_patch.yaml, kpack-image-builder/config/manager/manager.yaml
https://github.com/cloudfoundry/korifi/issues/1221
Enable `restricted` pod security on Korifi "core" namespaces and pods
As this is a change in the deployment ymls - which we do not test - this PR has no tests
No. Although it technically enables the restricted pod security policy, Korifi's implementation does not violate it so no further changes are needed
See the story for acceptance
=> Configure Korifi with `restricted` pod-security

controllers/api/v1alpha1/shared_types.go, controllers/controllers/workloads/cforg_controller.go, controllers/controllers/workloads/cfspace_controller.go, controllers/controllers/workloads/integration/cforg_controller_integration_test.go, controllers/controllers/workloads/integration/cfspace_controller_integration_test.go, controllers/controllers/workloads/shared.go
https://github.com/cloudfoundry/korifi/issues/1204
Reconcile role binding deletions for CFOrg and CFSpace
- added a new label `propogated-from` on role-bindings for all propagated role-bindings
- reconcile when role bindings are deleted and check if the propagated role-bindings still exists in the parent namespace, if it doesn't go ahead and delete.
No
See issue
@Birdrock
=> Reconcile role binding deletions for CFOrg and CFSpace

api/actions/manifest.go, api/actions/manifest_test.go, api/payloads/manifest.go, api/payloads/manifest_test.go, controllers/controllers/workloads/cfapp_controller.go, controllers/controllers/workloads/cfapp_controller_test.go, controllers/controllers/workloads/integration/cfapp_controller_integration_test.go
#1207 
Processes that have a route mapped to them should default to having the PORT health check type
no
See issue
@akrishna90
=> Processes that have a route mapped to them default to having PORT health check type

INSTALL.md, api/main.go, api/repositories/fake/image_pusher.go, api/repositories/image_repository.go, api/repositories/image_repository_test.go, api/repositories/registry/image_pusher.go, api/repositories/registry/image_pusher_test.go, docs/using-container-registry-signed-by-custom-ca.md, kpack-image-builder/controllers/buildworkload_controller.go, kpack-image-builder/controllers/fake/image_process_fetcher.go, kpack-image-builder/controllers/imageprocessfetcher/image_process_fetcher.go, kpack-image-builder/controllers/suite_test.go, kpack-image-builder/main.go
#1192 
Allow platform operator to configure Korifi components to trust a self-signed/internal CA when interacting with the container registry
no
See Issue
@akrishna90 @julian-hj
=> Allow using a container registry signed by a custom CA

INSTALL.md, controllers/config/base/controllersconfig/korifi_controllers_config.yaml, controllers/config/config.go, controllers/config/overlays/kind-local-registry/controllersconfig/korifi_controllers_config.yaml, controllers/config/overlays/pr-e2e/controllersconfig/korifi_controllers_config.yaml, controllers/controllers/networking/cfroute_controller_test.go, controllers/controllers/networking/integration/suite_integration_test.go, controllers/controllers/workloads/integration/suite_integration_test.go
No
This PR renames the KorifiControllerNamespace config parameter as it is only used for the workloads TLS secret namespace.
The configuration parameter name change will be a breaking change for existing deployments.
Deploy Korifi following the docs and push an app.
=> Rename KorifiControllerNamespace config param

statefulset-runner/Makefile, statefulset-runner/config/manager/kustomization.yaml, statefulset-runner/config/manager/manager.yaml
no
The statefulset-runner's build configs were incorrectly pointing to controller:latest. This is to correct it to point to the statefulset-runner image.
no
All tests pass
@julian-hj
=> Fix the image tags for the statefulset-runner

statefulset-runner/Makefile, statefulset-runner/config/manager/manager.yaml
no
Remove the command argument in the config for statefulset-runner because /manager does not exist
no
Tests pass
@julian-hj
=> Fix the statefulset-runner configs to remove non existent /manager command

api/handlers/task_handler_test.go, api/presenter/task.go, api/repositories/task_repository.go, api/repositories/task_repository_test.go, tests/e2e/e2e_suite_test.go, tests/e2e/tasks_test.go
https://github.com/cloudfoundry/korifi/issues/1032
Expose task state into the API shim
No
See story
@kieron-dev
=> Expose task state in API get and create task responses

.github/ISSUE_TEMPLATE/flake.yml
It will make it a bit easier to log a flake chore, making sure we do not miss to label it with the `flake` label
=> Introduce a template for flakes

api/handlers/org_handler.go, tests/e2e/e2e_suite_test.go
#1291 
Add more logging to debug e2e async org creation flakes
* Add missed logging on org creation invalid input
* Report the failure message in the e2e suite
No
n/a
=> Add more logging to debug e2e async org creation flakes

statefulset-runner/Makefile, statefulset-runner/config/default/kustomization.yaml, statefulset-runner/config/manager/kustomization.yaml, statefulset-runner/config/manager/manager.yaml
No.
This PR renames the image tag `cloudfoundry/statefulset-runner` as `cloudfoundry/korifi-statefulset-runner`.
The korifi prefix clarifies that this is a korifi image, and is consistent with all of our other korifi docker images.
It also adds the korifi prefix to namespace and resource names.
No. We don't yet deploy this image in any of our tests or scripts.
- in `statefulset-runner` invoke `make docker-build`
- observe the new image tag
- run `load docker-image cloudfoundry/korifi-statefulset-runner:latest`
- run `make deploy`
- observe that the deployment uses the new image and deploys successfully with korifi prefixed names and namespaces.
@davewalter @acosta11
=> Fix statefulset-runner image and resource names

dependencies/kpack/cluster_store.yaml
latest go buildpack (as of today 1.6.0) requires buildpack api 0.8. The
buildpack api coming with the kpack version we deploy (5.2) provides
buildpack api up to 0.7
We cannot bump kpack before PR https://github.com/pivotal/kpack/pull/977
is merged.
Co-authored-by: Georgi Sabev <georgethebeatle@gmail.com>
No
Pin go buildpack to `1.5.0`
latest go buildpack (as of today 1.6.0) requires buildpack api 0.8. The
buildpack api coming with the kpack version we deploy (5.2) provides
buildpack api up to 0.7
We cannot bump kpack before PR https://github.com/pivotal/kpack/pull/977
is merged.
No
Kpack works on the Korifi deployment
=> Pin the `go` packeto buildpack to 1.5.0

INSTALL.md, api/repositories/repositories_suite_test.go, dependencies/kpack-release-0.6.0.yaml, dependencies/kpack/cluster_store.yaml, kpack-image-builder/controllers/suite_test.go, scripts/install-dependencies.sh
No
Unpin go buildpack and bump kpack to 0.6.0
We only bump kpack in `dependencies` but not in `go.mod` (because of
https://github.com/pivotal/kpack/pull/977)
No
Pushing `cf-acceptance-tests/assets/golang` works
=> Unpin go buildpack and bump kpack to 0.6.0

controllers/config/rbac/role.yaml, controllers/controllers/workloads/cforg_controller.go, controllers/controllers/workloads/cfspace_controller.go, controllers/controllers/workloads/integration/cforg_controller_integration_test.go, controllers/controllers/workloads/integration/cfspace_controller_integration_test.go, controllers/controllers/workloads/integration/suite_integration_test.go, controllers/controllers/workloads/shared.go
https://github.com/cloudfoundry/korifi/issues/1318
CFOrg/Space controllers do not propagate roles anymore
The only reason for orgs and spaces to propagate roles was the roles
needed by the `eirini-controller` in the workloads namespaces. As of
eirini-controller 0.5.0, that role has been promoted to `ClusterRole`,
i.e. there is no need to propagate it to workload namespaces anymore.
Still, CFOrg/Space controllers keep propagating role bindings (even
though to cluster roles) as role bindings are not cluster-wide resources
No
N/A
=> Do not propagate roles between orgs and spaces

api/handlers/app_handler.go, api/handlers/app_handler_test.go, api/handlers/fake/cfapp_repository.go, api/presenter/app.go, api/repositories/app_repository.go, api/repositories/app_repository_test.go, controllers/controllers/workloads/env/builder.go, tests/e2e/apps_test.go
#1270
App developer can view VCAP_SERVICES env var via `v3/apps/:guid/env` endpoint
- `VCAP_SERVICES` env variable is now part of `system_env_json`
- added missing e2e test for `v3/apps/:guid/env` endpoint
No
See issue #1270
@davewalter
=> App developer can view `VCAP_SERVICES` env var

dependencies/kpack/cluster_store.yaml
No
We had pinned the version for `nodejs` buildpack to `0.13` a while ago and hadn't reverted back.
In this PR, we initially tried to unpin the version
- unpinning the version was causing builds to fail with error
`chmod /workspace: operation not permitted`
- On looking further we found an [issue is opened](https://github.com/paketo-buildpacks/nodejs/issues/602) on paketo-buildpacks/nodejs repo to address the same.
- we decided to pin to the latest compatible v0.17.1 version 
- We should unpin the nodejs version once the issue has been addressed
No
Tests should pass.
@davewalter
=> Pin version of nodejs buildpack to v0.17.1

api/handlers/job_handler.go, api/handlers/service_binding_handler.go, controllers/controllers/workloads/cfprocess_controller.go
No.
- the logger requires Sprintf when formatting error strings and panics if we log with an odd number of trailing arguments.
- we *think* we found all of the offending log lines and fixed them here.
- see [this example](https://go.dev/play/p/yzVGHCN3_D-) to replicate the panic we were getting in the API logs.
No.
CI should pass e2e tests (The API shim was panicing)
Also look for gpanic in the API shim logs
@acosta11
=> Fix panics when logging with format strings

tests/e2e/e2e_suite_test.go
https://github.com/cloudfoundry/korifi/issues/1291
Improve error logging when create{Org,Space}Raw fails by including the body from the http response
No
=> Include body in create space error

api/apierrors/errors.go, api/handlers/fake/cftask_repository.go, api/handlers/task_handler.go, api/handlers/task_handler_test.go, api/presenter/task.go, api/repositories/app_repository.go, api/repositories/task_repository.go, api/repositories/task_repository_test.go, controllers/webhooks/cf_validation_errors.go, controllers/webhooks/workloads/cftask_validator.go, controllers/webhooks/workloads/integration/cftask_validator_test.go, tests/e2e/tasks_test.go
https://github.com/cloudfoundry/korifi/issues/1041
Introduce API endpoints to cancel tasks
```
POST /v3/tasks/{taskGUID}/actions/cancel
PUT /v3/tasks/{taskGUID}/cancel
```
Also, add a `cancel` href to task responses
No
See story
@kieron-dev
=> Introduce API endpoints to cancel tasks

statefulset-runner/Makefile, statefulset-runner/PROJECT, statefulset-runner/api/v1/pod_webhook.go, statefulset-runner/api/v1/pod_webhook_test.go, statefulset-runner/api/v1/webhook_suite_test.go, statefulset-runner/config/certmanager/certificate.yaml, statefulset-runner/config/certmanager/kustomization.yaml, statefulset-runner/config/certmanager/kustomizeconfig.yaml, statefulset-runner/config/default/kustomization.yaml, statefulset-runner/config/default/manager_webhook_patch.yaml, statefulset-runner/config/default/webhookcainjection_patch.yaml, statefulset-runner/config/webhook/generated/envtest-webhook-config.yaml, statefulset-runner/config/webhook/kustomization.yaml, statefulset-runner/config/webhook/kustomizeconfig.yaml, statefulset-runner/config/webhook/manifests.yaml, statefulset-runner/config/webhook/patches/object_selector_patch.yaml, statefulset-runner/config/webhook/service.yaml, statefulset-runner/controllers/runworkload_controller.go, statefulset-runner/main.go
#1234 
Adds a mutating webhook to add CF_INSTANCE_INDEX env var to pods created by statefulsets that have a `"korifi.cloudfoundry.org/add-stsr-index": "true"` label
No.
* Run tests.
* Deploy statefulset-runner and apply a statefulset with `"korifi.cloudfoundry.org/add-stsr-index": "true"` in pod spec label
@akrishna90 @matt-royal @tcdowney
=> Add pod mutating webhook to apply indexes

api/handlers/task_handler_test.go, api/presenter/task.go, api/repositories/task_repository.go, api/repositories/task_repository_test.go, controllers/controllers/workloads/cftask_controller.go, controllers/controllers/workloads/cftask_controller_test.go, go.mod, go.sum, scripts/install-dependencies.sh, tests/e2e/tasks_test.go
#1048
We bumped eirini-controller to 0.7.0 to get exit code failure messages included in the failed status condition.
This is used to populate the failure message in the TaskRecord and is passed back to the user in the get task response.
Cancelled tasks get the cancelled failure reason 'hard-coded'.
No
See #1048
@kieron-dev
<!-
- Include any links to related PRs, issues, stories, slack discussions, etc... that will help establish context.
- Is there anything else of note that the reviewers should know about this change?
- This project follows the Cloud Foundry [Code of Conduct](https://www.cloudfoundry.org/code-of-conduct/)
-->
=> Show the failure reason for failed/cancelled tasks

INSTALL.md, api/repositories/pod_repository.go, api/repositories/pod_repository_test.go, controllers/config/rbac/role.yaml, controllers/config/samples/cfprocess.yaml, controllers/controllers/workloads/cforg_controller.go, controllers/controllers/workloads/cfprocess_controller.go, controllers/controllers/workloads/cfprocess_controller_test.go, controllers/controllers/workloads/integration/cforg_controller_integration_test.go, controllers/controllers/workloads/integration/cfprocess_controller_integration_test.go, controllers/controllers/workloads/integration/cfspace_controller_integration_test.go, controllers/controllers/workloads/integration/suite_integration_test.go, controllers/controllers/workloads/testutils/shared_test_utils.go, docs/architecture.md, scripts/deploy-on-kind.sh, statefulset-runner/Makefile, statefulset-runner/controllers/runworkload_controller.go, statefulset-runner/controllers/runworkload_controller_test.go
#1145
Running processes is now managed via RunWorkload resources
Yes, workloads managed using Eirini `LRPs` are no longer compatible. Please redeploy your workloads to use `RunWorkload` resources
See issue #1145 
@davewalter
=> CFProcess generates RunWorkloads instead of LRPs

kpack-image-builder/config/default/project_namespace/manager_auth_proxy_patch.yaml, statefulset-runner/config/default/manager_auth_proxy_patch.yaml
No
This PR bumps the version of `kube-rbac-proxy` used by the `statefulset-runner` to v0.12.0. It also copies the `securityContext` block from `kpack-image-builder`.
No
@Birdrock
=> Bump version of kube-rbac-proxy used by statefulset-runner

api/apierrors/errors.go, api/repositories/app_repository.go, api/repositories/org_repository.go, api/repositories/route_repository.go, api/repositories/service_binding_repository.go, api/repositories/service_instance_repository.go, api/repositories/space_repository.go, api/repositories/task_repository.go, controllers/webhooks/cf_validation_errors_test.go, tests/e2e/orgs_test.go, tests/e2e/routes_test.go, tests/e2e/spaces_test.go
https://github.com/cloudfoundry/korifi/issues/1335
https://github.com/cloudfoundry/korifi/issues/1339
Webhook validation errors are a special case of K8S errors. Those
validation errors are usually mapped to `UnprocessableEntityError` with
quite few exceptions. Therefore,
* implement the default mapping in `apierrors.FromK8sError`
* only check for validation errors if mapping to another apierror type
Also, use `validationError.GetMessage` for the apierror details (as it
does not contain the machine-friendly error type which is irrelevant to
the human user)
No
N/A
=> Common handling of webhook validation errors

controllers/config/cf_roles/cf_space_manager.yaml
This should have been part of #1022, #1037 and #1038.
This allows users who are space managers to get and list tasks in their spaces.
No.
=> SpaceManager should be able to get and list tasks

controllers/webhooks/workloads/integration/cfspace_validation_integration_test.go, controllers/webhooks/workloads/integration/cftask_validator_test.go, controllers/webhooks/workloads/integration/suite_integration_test.go
#1303 
See issue
No
We can't get the test to flake, so we may not be able to accept this directly. We will know that we failed if we eventually see it flake again.
=> Attempt to de-flake CFSpace Validator integration tests

controllers/api/v1alpha1/cftask_types.go, controllers/config/crd/bases/korifi.cloudfoundry.org_cftasks.yaml
Problem introduced in #1040 (PR #1327).
This removes the `required` constraint on the `canceled` field of `CFTask`, as a task should not be considered canceled by default and it shouldn't be necessary to specify `canceled: false` to create a `CFTask`.
=> `CFTask.canceled` should not be a required field

controllers/api/v1alpha1/cftask_types.go, controllers/config/crd/bases/korifi.cloudfoundry.org_cftasks.yaml, controllers/webhooks/workloads/integration/cftask_validator_test.go
No
Make task status fields optional.
It was just the kubebuilder default to make them required, this was
never intended
no
N/A
@kieron-dev
=> Make task status fields optional

api/repositories/task_repository.go, api/repositories/task_repository_test.go
Bug from #1048 (PR #1347).
This fixes the `TaskRepository` so that canceled tasks have a failure message saying `"task was canceled"`.
=> Fix the failure message for canceled tasks

controllers/config/base/controllersconfig/korifi_controllers_config.yaml, controllers/config/config.go, controllers/config/config_suite_test.go, controllers/config/config_test.go, controllers/config/overlays/kind-local-registry/controllersconfig/korifi_controllers_config.yaml, controllers/config/overlays/pr-e2e/controllersconfig/korifi_controllers_config.yaml, controllers/controllers/workloads/cftask_controller.go, controllers/controllers/workloads/cftask_controller_test.go, controllers/controllers/workloads/integration/cftask_controller_integration_test.go, controllers/controllers/workloads/integration/suite_integration_test.go, controllers/main.go, tests/e2e/tasks_test.go
#1049
Tasks are deleted after their retention period
* Introduce a controller config property `taskTTL` that has format that
is parsable by time.ParseDuration, e.g. `12h30m6s`. In contrast to
`time.ParseDuration`, `taskTTL` also accepts days, so `12d6h` means 12
days and 6 hours
* The default `taskTTL` is 30 days (`30d`)
* On local kind and `pr-e2e` clusters `taskTTL` is set to `5s` in the
corresponding overlay so that e2e test that verifies that the task is
eventually deleted does not have to wait for 30 days
No
See story
@kieron-dev
=> Tasks are deleted after their retention period

statefulset-runner/config/manager/manager.yaml
This is related to #1221.
This does the same we did in #1221 on the new `statefulset-runner` `Namespace` and `Deployment`.
=> Enforce the `restricted` pod security standard for `statefulset-runner`

api/handlers/authentication_middleware.go, api/handlers/oauth_token_handler.go, api/handlers/oauth_token_handler_test.go, api/handlers/root_handler_test.go, api/main.go, api/presenter/root.go, go.mod, go.sum
[#1294]
- The CF CLI requires a token endpoint during log streaming
- This endpoint provides a token with a valid expiration, which allows
the CLI to proceed. The token is not used for actual authentication so
it only needs to be in a parsable format.
- Eventually the CLI will be updated to skip this call but for now we
need it.
no
[#1294]
@akrishna90
=> Add /oauth/token dummy endpoint

scripts/run-tests.sh
[#1388]
- Wait for the Ready condition on all clusterbuilders before starting
e2e tests.
- This will keep us from erroring out listing buildpacks in the case
where we start tests before the ClusterBuilder is done reconciling.
No.
[#1388]
@matt-royal
=> Wait for the ClusterBuilder before running e2e

api/handlers/log_cache_handler_test.go, api/presenter/log.go, api/repositories/build_repository.go, tests/e2e/log_cache_test.go
#1298
Sets "source_type" tag on LogEnvelopes to "STG" for build logs, enabling the CLI to output staging logs to console.
No.
Follow acceptance steps on issues
- DEV build for CF CLI is not required as the dummy `oauth/token` endpoint exists.
=> Set `source_type` tag on LogEnvelopes to `STG` for build logs.

api/handlers/integration/apply_manifest_test.go, api/handlers/integration/get_app_env_test.go, api/handlers/integration/route_test.go, api/main.go, api/repositories/app_repository.go, api/repositories/app_repository_test.go, api/repositories/conditions/await.go, api/repositories/conditions/await_test.go, api/repositories/conditions/conditions_suite_test.go, api/repositories/shared.go, api/repositories/task_repository.go, api/repositories/task_repository_test.go, controllers/api/v1alpha1/cfapp_types.go, controllers/api/v1alpha1/cftask_types.go, controllers/config/cf_roles/cf_admin.yaml, controllers/config/cf_roles/cf_space_developer.yaml
https://github.com/cloudfoundry/korifi/issues/1385
Await the `Staged` app condition on set app droplet
By doing that we ensure that the app controller has accepted the request
to set the app droplet and it is aware that the app is staged. Thus
subsequent creation of objects that depend on the app being staged (such
as tasks) would not fail.
Awaiting for a status condition of a task requires adding the `watch`
permission on apps for the `cf_admin` and `space-developer` roles
No
n/a
=> Await `Staged` condition on setting the app droplet

.github/dependabot.yml, api/remote-debug/Dockerfile, controllers/remote-debug/Dockerfile, kpack-image-builder/Dockerfile, statefulset-runner/Dockerfile
No
This PR bumps the version of Golang used to build component images to 1.18.4. It also configures dependabot to automatically bump the version in future.
No
=> Bump Golang to 1.18.4 in Dockerfiles

controllers/controllers/workloads/cftask_controller.go, controllers/controllers/workloads/cftask_controller_test.go, controllers/controllers/workloads/integration/cftask_controller_integration_test.go, controllers/controllers/workloads/integration/fixtures/vendir.lock.yml, controllers/controllers/workloads/integration/fixtures/vendir.yml, controllers/controllers/workloads/integration/fixtures/vendor/eirini-controller/deployment/helm/templates/core/task-crd.yml, go.mod, go.sum, scripts/install-dependencies.sh
#1203
Use the memory request/limit from the app's web process to set the task CPU request using the same formula as used by the process controller to convert memory to cpu millicores.
No
See #1203
@gcapizzi
=> Set Task CPU the same as the web process

controllers/controllers/networking/cfroute_controller.go, controllers/controllers/services/cfserviceinstance_controller.go, controllers/controllers/workloads/cfapp_controller.go, controllers/controllers/workloads/cforg_controller.go, controllers/controllers/workloads/cfspace_controller.go, controllers/controllers/workloads/shared.go, controllers/coordination/integration/name_registry_test.go, controllers/coordination/name_registry.go, controllers/coordination/name_registry_test.go, controllers/webhooks/networking/cfdomain_validator.go, controllers/webhooks/networking/cfdomain_validator_test.go, controllers/webhooks/networking/cfroute_validator.go, controllers/webhooks/networking/cfroute_validator_test.go, controllers/webhooks/services/cfservicebinding_validator.go, controllers/webhooks/services/cfservicebinding_validator_test.go, controllers/webhooks/services/cfserviceinstance_validator.go, controllers/webhooks/services/cfserviceinstance_validator_test.go, controllers/webhooks/workloads/cfapp_validator.go, controllers/webhooks/workloads/cfapp_validator_test.go, controllers/webhooks/workloads/cforg_validator.go, controllers/webhooks/workloads/cforg_validator_test.go, controllers/webhooks/workloads/cfspace_validator.go, controllers/webhooks/workloads/cfspace_validator_test.go, controllers/webhooks/workloads/cftask_validator.go, controllers/webhooks/workloads/cftask_validator_test.go
#1420 
This PR cleans up the finalizing checks in the controllers and adds checks to all validating webhooks to allow the update if the resource is currently being deleted (non-zero deletion timestamp) as the change is likely the removal of the finalizer, which shouldn't be blocked.
No
See #1420 
@Birdrock
=> Cleanup finalizing checks

scripts/deploy-on-kind.sh
No
This parallelises the build/deploy/await ready of the korifi components. The
only difference is that logs are not shown immediately, otherwise they would
get mixed up and become unintelligible.
=> Deploy korifi components to kind in parallel

api/repositories/task_repository.go, api/repositories/task_repository_test.go, tests/e2e/tasks_test.go
#1430
We must use the CNB lifecycle launcher to run task commands, else the environment will not be set up correctly. Also the complete command should be passed to the launcher without any string splitting.
No
Attempt to run a complex task that uses the buildpack environment, and it should succeed.
For example, deploy postfacto and attempt:
```
cf run-task postfacto -c 'ADMIN_EMAIL=user@example.com ADMIN_PASSWORD=pass bundle exec rake admin:create_user'
```
@kieron-dev
=> Use the cnb lifecycle launcher for running tasks

scripts/run-tests.sh
No
A recent `set -u` exposed some variables that needed defaulting to empty
No
Open a test in vim and press <space>ts
@kieron-dev
=> Default empty vars so that run-tests can be run from vim

dependencies/kpack/cluster_store.yaml
#1329 
Unpin nodejs and pin ruby buildpack to 0.11
- with ruby, the builds succeed but the pods fail to start with the latest version.
- we are extracting the start-command from the built image and setting it on the cf-process. This seems to work fine with ruby:0.11 but is broken on the latest version.
- removing the command from the cfprocess spec fixes the issue
- we decided to pin the version to 0.11 until we figure out how we want to fix this. See #1439 
No
All tests should pass
@Birdrock
=> Unpin nodejs and pin ruby buildpack to 0.11

scripts/deploy-on-kind.sh
No
This PR re-adds the `clean_up_img_refs` call when the script exits to revert changes made to the `kustomization.yaml` files when local images are built.
No
Run `./scripts/deploy-on-kind -l -d kind` and confirm that your Git repo is clean afterward.
=> Fix deploy-on-kind script to reset image refs

.envrc, controllers/api/v1alpha1/buildworkload_types.go, controllers/config/base/controllersconfig/korifi_controllers_config.yaml, controllers/config/config.go, controllers/config/config_test.go, controllers/config/crd/bases/korifi.cloudfoundry.org_buildworkloads.yaml, controllers/config/overlays/kind-local-registry/controllersconfig/korifi_controllers_config.yaml, controllers/config/samples/build_workload.yaml, controllers/controllers/workloads/cfbuild_controller.go, controllers/controllers/workloads/cfbuild_controller_test.go, kpack-image-builder/controllers/buildworkload_controller.go, kpack-image-builder/controllers/buildworkload_controller_test.go, kpack-image-builder/controllers/suite_test.go
#1427 
Implement the reconcileName in BuildWorkloads so builders will only produce images if the reconciler name matches
no
See issue
@davewalter
=> Implement the spec reconcileName in BuildWorkload

controllers/controllers/networking/cfroute_controller.go, controllers/controllers/networking/integration/cfroute_controller_integration_test.go
#1250
It turns out that Contour is disallowing websockets by default. This
breaks apps like postfacto. This commit allows all apps to use
websockets.
No
Deploy an app that uses websockets (e.g postfacto) and see it wokring. With postfacto working means that different browsers see live updates on the retro board.
@kieron-dev
=> Allow korifi apps to use websockets

controllers/config/config_test.go
No
The test being removed is able to pass loclally as well as in gh
actions, but fails consistently in our Concourse, because our test are
running as `root` in the ci image.
There seems to be no easy way of fixing this so we remove it to unblock
ci.
Running our tests as non-root is certainly a possibility, but we are not
convinced that it is worth the cost.
No
N/A
=> Remove test consistently failing on concourse

controllers/config/crd/kustomization.yaml
No
This PR disables the CRD conversion webhooks. We don't need these until we have a new version of a CRD.
No
=> Disable the CRD conversion webhooks

api/repositories/pod_repository.go, api/repositories/pod_repository_test.go
No
This PR solves a bug when running `cf scale -i` to a scale an App down. Before this change, the following sequence would consistently lead to an error:
1. `cf scale -i 4`
2. Wait for all instances to come up (by polling `cf app`)
3. `cf scale -i 1`
The user would see output like this:
```
$ cf scale node -i 1
Scaling app node in org o / space s as cf-admin...
Error unmarshalling the following into a cloud controller error: upstream connect error or disconnect/reset before headers. reset reason: connection termination
FAILED
```
No
Follow the steps in the "What is this change about?" section above. On this branch, there should be no error when scaling down the App.
=> Fix bug reading stats for recently-scaled-down process

controllers/controllers/workloads/cftask_controller.go, controllers/controllers/workloads/cftask_controller_test.go, controllers/controllers/workloads/integration/cftask_controller_integration_test.go
https://github.com/cloudfoundry/korifi/issues/1464
The task reconciler now returns an error when the app does not have the
`staged` status condition. The `staged=true` condition indicates that
the app's status has its droplet and `VCAP_SERVICES` secret set.
The task controller also explicitly checks for the droplet reference
being not empty to make sure that the task can transition into
`initialized` state.
Also, reorder objects creation on integartion tests to mitigate
https://github.com/cloudfoundry/korifi/issues/954
No
The flake is fixed
@kieron-dev
=> Require `staged` condition on app on task reconcile

api/handlers/org_handler.go, tests/e2e/orgs_test.go
Not specifically, but these two are related:
* https://github.com/cloudfoundry/korifi/issues/1090
* https://github.com/cloudfoundry/korifi/issues/1236
- Users have reported confusion regarding what certificate this message
was referring to. This clarifies that it is the client cert used for
authentication and not any of the ingress certs.
- Also directs the user to the Platform Operator who is more likely to
be the one who can solve the problem for them.
No
Follow the A/C on https://github.com/cloudfoundry/korifi/issues/1090 to set up the scenarios that trigger this warning. By default just authenticate with a client certificate that has an expiration of over a week.
@emalm
=> Clarify "long cert expiry" warning message

tests/smoke/smoke_test.go
#1394 
Increase the timeout for smoke tests to 5 minutes to reduce flakes. After analysis over several days worth of runs, it was determined that the errors that occur are due to timeouts and the apps become available after a longer wait period. After characterization, it was determined that in 97% of test runs, the apps are available in under 3 minutes. There were a few outliers where they took up to 4 minutes that seem to coincide with system load so 5 minutes seems like a safe value.
No
Smoke tests pass
=> Increase timeout for smoke tests to reduce flakes

tests/e2e/apps_test.go
No
Thie e2e app env test has been flaking like this recently:
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-e2es-periodic/builds/953
Looks like the two valuse under the  "user-provided" key can be returned
in any order. This commit makes the assertion order independent
No
Green tests
@eirini
=> Make assertion order independent

api/config/config.go, api/repositories/registry/image_builder.go, controllers/config/config.go
`ioutil.ReadDir` docs say use `os.ReadDir` instead. And similarly with `ioutil.TempFile` -> `os.CreateTemp`.
This fixes linter errors, e.g. https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-main/builds/220
No
There should be no material difference, but the golangci-lint task will pass.
=> Use the newer os functions rather than ioutil

controllers/controllers/workloads/cfapp_controller.go, controllers/controllers/workloads/integration/cfapp_controller_integration_test.go, go.mod
Issue: https://github.com/cloudfoundry/korifi/issues/1498
Sets an ownerReference on this Secret to the CFApp that it belongs to so that it gets cleaned up when the app is deleted.
No
1. `cf push` an app
2. Verify that it has a Secret containing `VCAP_SERVICES`: `kubectl -n $(cf space s --guid) get secrets`
There will be one with a `-vcap-services` suffix corresponding for the app
3. `cf delete APP_NAME -f`
4. Verify that the Secret is deleted
=> Delete 'VCAP_SERVICES' Secret when App is deleted

api/authorization/testhelpers/auth_provider.go, api/handlers/integration/apply_manifest_test.go, api/handlers/integration/integration_suite_test.go, api/repositories/repositories_suite_test.go, kpack-image-builder/config/config.go
No
Remove usages of the `ioutil` package, those were causing linter errors
No
`make lint` succeeds
@kieron-dev
=> Remove usages of the deprecated `ioutil` package

INSTALL.md
This updates [`INSTALL.md`](https://github.com/cloudfoundry/korifi/blob/improve-install-md/INSTALL.md) to:
- use `dependencies/cf-setup.yaml` for creating the root namespace and binding the admin user in it;
- add the installation of `metrics-server` as an optional dependency.
=> Improve `INSTALL.md`

job-task-runner/config/default/manager_auth_proxy_patch.yaml
No
This PR updates the job-task-runner config to use the same image reference for kube-rbac-proxy as the other components.
No
@matt-royal
=> Update kube-rbac-proxy image ref in job-task-runner

job-task-runner/config/default/manager_auth_proxy_patch.yaml, job-task-runner/config/manager/manager.yaml
No
This PR updates job-task-runner security context to add the pod-security labels to the namespace and set `seccompProfile` and `runAsNonRoot`.
No
Everything deploys successfully.
@matt-royal
=> Update job-task-runner security context

job-task-runner/config/manager/manager.yaml
No
This PR removes the hard-coded `job-task-runner` command from the deployment in favour of the image's entrypoint. It also adds more security context values.
No
Everything deploys and tests pass.
@matt-royal
=> Remove hard-coded job-task-runner command

job-task-runner/controllers/integration/taskworkload_controller_test.go, job-task-runner/controllers/taskworkload_controller.go
#1491
Set `Parallelism` and `Completions` on the Job resource both to 1
No
See a task runs once and once only
=> Set job parallelism and completions

controllers/api/v1alpha1/cfserviceinstance_types.go, controllers/config/crd/bases/korifi.cloudfoundry.org_cfserviceinstances.yaml, controllers/controllers/services/cfserviceinstance_controller.go, controllers/controllers/services/cfserviceinstance_controller_test.go, controllers/controllers/services/integration/cfserviceinstance_integration_test.go, controllers/controllers/services/integration/suite_integration_test.go
https://github.com/cloudfoundry/korifi/issues/714
* Use `Patch` in service instance controller
* Remove the redundant `CfServiceInstance.Status.Binding` field - it has
been only referenced in tests
* Improve the controller integration test
* Simplify the controller implementation
No
No conflict errors caused by updating service instance status by the controller
=> Use `Patch` in service instance controller

job-task-runner/controllers/integration/taskworkload_controller_test.go, job-task-runner/controllers/taskworkload_controller.go
This means that whatever the value of the same property on the service account
used to run the jobs, the service account token will not be mounted in the job
containers.
No
See #1492
@kieron-dev
=> Set the `AutomountServiceAccountToken` property to false on job pods

job-task-runner/Dockerfile
No
This means the docker build can use the go cache for building. No reason not to.
No
n/a
=> Remove the -a flag from go build in dockerfile

job-task-runner/controllers/integration/taskworkload_controller_test.go, job-task-runner/controllers/taskworkload_controller.go
#1463
Set the image pull secrets from the workload task onto the job's pod
No
See #1463 in the κορυφή github
=> Set the task workloads image pull secrets on the job's pod

controllers/api/v1alpha1/appworkload_types.go, controllers/config/base/controllersconfig/korifi_controllers_config.yaml, controllers/config/config.go, controllers/config/config_test.go, controllers/config/crd/bases/korifi.cloudfoundry.org_appworkloads.yaml, controllers/config/overlays/kind-local-registry/controllersconfig/korifi_controllers_config.yaml, controllers/controllers/workloads/cfprocess_controller.go, controllers/controllers/workloads/cfprocess_controller_test.go, controllers/controllers/workloads/integration/suite_integration_test.go, controllers/main.go, kpack-image-builder/controllers/buildworkload_controller_test.go, statefulset-runner/controllers/appworkload_controller.go, statefulset-runner/controllers/appworkload_controller_test.go, statefulset-runner/controllers/integration/appworkload_controller_test.go, statefulset-runner/controllers/suite_test.go
#1428
Operators can switch to other AppWorkload Reconciler
- added a required `ReconcilerName` field to `AppWorkloads.Spec` and regenerated manifests.
- sets `statefulset-runner` as default value for `AppReconciler` in controllers config yaml.
No
see issue #1428
=> Operators can switch to other AppWorkload Reconciler

api/authorization/namespace_permissions.go, api/authorization/namespace_permissions_test.go, api/handlers/integration/integration_suite_test.go, api/main.go, api/repositories/repositories_suite_test.go, go.mod
No
When looking at usages of rootNamespace throughout korifi, we noticed the NamePermissions helper received it but didn't use it.
This PR removes that property and fixes usages.
No
All tests green
=> Remove unused rootNamespace property from NamespacePermissions

controllers/controllers/workloads/cfapp_controller.go, controllers/controllers/workloads/cfbuild_controller.go, controllers/controllers/workloads/cforg_controller.go, controllers/controllers/workloads/cfpackage_controller.go, controllers/controllers/workloads/cfprocess_controller.go, controllers/controllers/workloads/cfspace_controller.go, kpack-image-builder/controllers/buildreconcilerinfo_controller.go, kpack-image-builder/controllers/buildworkload_controller.go, statefulset-runner/controllers/appworkload_controller.go
No
These errors are expected from the Kubernetes API when a resource is deleted and should not be logged as an "Error" since the system is functioning as intended.
Currently when a resource is deleted you'll see logs like this which may make an operator believe there is a problem.
```
1.6606013489512e+09	ERROR	controllers.CFSpace	Error when trying to fetch CFSpace cf-org-c5ef9015-e8f1-4342-9262-11af0c06a1f9/cf-space-custom	{"error": "CFSpace.korifi.cloudfoundry.org \"cf-space-custom\" not found"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler …
```
=> Stop logging expected "not found" errors when reconciling a resource

kpack-image-builder/controllers/buildworkload_controller.go, kpack-image-builder/controllers/buildworkload_controller_test.go
related to #1427
- Previously, the check to ignore BuildWorkload objects intended for
other reconcilers was nested in an if block so that it would only
apply to new objects.
- This resulted in the kpack reconciler failing to ignore objects that
were partially reconciled by another reconciler.
- In an unrelated change, this commit also makes a bunch of test helper
methods private, since they were not used anywhere outside the
package.
No. 
There's a new envtest that tests the previously failing case. That's probably the easiest way to reproduce this. Otherwise you would have to manually make the BuildWorkload and update the status and make the corresponding Image with all the right fields.
cc @matt-royal @clintyoshimura
=> Fix kpack builder check for reconcilerName

scripts/install-dependencies.sh
Related to #1137
The instructions were changed to use the community version of servicebindings, however there was an issue preventing us from using it in our dev scripts. That issue has been fixed in the latest release and so dev scripts can now be updated.
no
All tests pass
@davewalter @Birdrock
=> Update dev scripts to use community version of servicebindings

scripts/install-dependencies.sh, tests/dependencies/contour/kbld-image-mapping-to-fix-envoy-v1.23-bug.json
No
See https://github.com/envoyproxy/envoy/issues/22261 for details.
For now, v1.22-latest appears to work. v1.23-latest should work soon.
We can remove this change once there's a new contour release that
includes a fixed envoy.
No
./scripts/deploy-on-kind.sh runs successfully on an M1 mac and you're able to push an app
=> Fix contour on m1 Macs

api/repositories/build_repository.go, api/repositories/build_repository_test.go, api/repositories/buildpack_repository_test.go, api/repositories/org_repository_test.go, controllers/controllers/workloads/cfprocess_controller_test.go, kpack-image-builder/controllers/buildworkload_controller_test.go, statefulset-runner/controllers/integration/appworkload_controller_test.go, tests/matchers/represents_resource_quantity.go
No
This PR changes how we fetch build logs, so that we use the `korifi.cloudfoundry.org/build-workload-name` label instead of `image.kpack.io/image`. Both labels have the same value. Without this change, an alternative builder implementation would need to set a kpack-specific label on their build pods to make logs available. As we want to support non-kpack builders, this requirement doesn't make sense.
No
Tests passing should be sufficient. There is no user-visible change
=> Use the build-workload-name label to find build logs

controllers/controllers/workloads/cfprocess_controller_test.go
PR #1553 sorta
PR introduced a duplicate declaration which this removes.
Nope
Run tests.
=> Removes duplicate declaration of k8s.io/apimachinery/pkg/api/resource.

INSTALL.md
Not specifically, but ran into this while validating https://github.com/cloudfoundry/korifi/issues/1137.
Adds a note and a few links to the Kubernetes docs around user management and authentication
No
Read the updated section on the `ADMIN_USERNAME` and see if it is clearer.
@Birdrock @clintyoshimura
=> Update installation docs re: user management

api/apierrors/errors.go, api/handlers/apis_suite_test.go, api/handlers/package_handler_test.go, api/repositories/image_repository.go, api/repositories/image_repository_test.go
[#1474]
- Instead of returning a generic 500 unknown error, application source
when source upload to the container registry fails, use 502 and
CF-BlobstoreUnavailable with a more helpful description.
No
[#1474]
@matt-royal (who *will* be my pair later today)
=> Improve error handling when source upload fails

controllers/config/crd/bases/korifi.cloudfoundry.org_buildreconcilerinfos.yaml, controllers/config/crd/bases/korifi.cloudfoundry.org_buildworkloads.yaml, controllers/config/crd/bases/korifi.cloudfoundry.org_cfapps.yaml, controllers/config/crd/bases/korifi.cloudfoundry.org_cfbuilds.yaml, controllers/config/crd/bases/korifi.cloudfoundry.org_cforgs.yaml, controllers/config/crd/bases/korifi.cloudfoundry.org_cfpackages.yaml, controllers/config/crd/bases/korifi.cloudfoundry.org_cfprocesses.yaml, controllers/config/crd/bases/korifi.cloudfoundry.org_cfroutes.yaml, controllers/config/crd/bases/korifi.cloudfoundry.org_cfservicebindings.yaml, controllers/config/crd/bases/korifi.cloudfoundry.org_cfserviceinstances.yaml, controllers/config/crd/bases/korifi.cloudfoundry.org_cfspaces.yaml, controllers/config/crd/bases/korifi.cloudfoundry.org_cftasks.yaml, controllers/config/crd/bases/korifi.cloudfoundry.org_taskworkloads.yaml
No
Looks like latest controller-gen generates manifests a bit differently
No
Green tests
@kieron-dev
=> Update manifests to controller-gen v0.9.2 format

INSTALL.md, controllers/api/v1alpha1/shared_types.go, controllers/config/rbac/role.yaml, controllers/controllers/workloads/cfspace_controller.go, controllers/controllers/workloads/cfspace_controller_test.go, controllers/controllers/workloads/integration/cfspace_controller_integration_test.go, controllers/controllers/workloads/integration/suite_integration_test.go, controllers/main.go, tests/dependencies/kpack/service_account.yaml
[#1510]
- previously we had hard-coded logic to create a `kpack-service-account`
in each space.
- this commit looks for service accounts in the root namespace with a
specific annotation, and copies them instead.
- the contoller manager role is extended to watch/patch/delete service accounts in order to keep spaces
in sync with any changes in the root namespace.
no
[#1510]
@matt-royal
=> CFSpace controller propagates service accounts

Makefile
No
Do not run the `test` target within `test-controllers-api`
No
Run `make test-controllers-api`, see no tests other than the api and controllers ones are run
=> Do not run all test as part of the `test-controllers-api` target

api/repositories/task_repository.go, api/repositories/task_repository_test.go
This changes the failure reason for cancelled tasks to use the same spelling as traditional CF. It might look silly, but it makes a [CAT](https://github.com/cloudfoundry/cf-acceptance-tests/blob/a2262f3ce3129ec4f7f7b7f24455d610b8f9a509/tasks/task.go#L227) fail! 😅
=> Tasks are "cancelled", not "canceled"

docs/api.md
"Organizations" was accidentally out of order. The order is alphabetical, with some exceptions as per the [official API docs](https://v3-apidocs.cloudfoundry.org/).
=> Fix the order of API doc sections

Makefile, job-task-runner/Makefile, kpack-image-builder/Makefile, statefulset-runner/Makefile
No
Fix kind load targets to specify cluster name
Otherwise `kind load docker-image` is trying to use a cluster named `kind`
which does not exist in the context of `make test-e2e`
No
`make test-e2e` succeeds when there is no kind cluster
=> Fix kind load targets to specify cluster name

api/config/base/apiconfig/korifi_api_config.yaml, api/config/config.go, api/config/overlays/kind-local-registry/apiconfig/korifi_api_config.yaml, api/config/overlays/kind/apiconfig/korifi_api_config.yaml, api/handlers/integration/integration_suite_test.go, api/main.go, api/repositories/buildpack_repository.go, api/repositories/buildpack_repository_test.go, api/repositories/namespace_retriever.go, api/repositories/repositories_suite_test.go
#1529 
User can see accurate list of buildpacks when multiple build reconcilers are installed
Yes - `korifi_api_config.yaml` must have a populated `buildReconciler` top level field.
Run all tests. See acceptance steps in #1529 
@matt-royal
=> Make BuildReconciler configurable

api/repositories/org_repository_test.go
No, but related to this test run:
https://ci.korifi.cf-app.com/builds/5246001
The previous test checked for absolute timestamps for `CreatedAt`/`UpdatedAt` which was flaky since they could vary by a second or two, This change updates the assertion to check that we have the correct orgs/guids and ignore the exact values of the timestamps. Truncated failing test below:
```
• [FAILED] [0.175 seconds]
OrgRepository ListOrgs [It] returns the 3 orgs
/tmp/build/e45b3164/root/api/repositories/org_repository_test.go:189
Expected
<[]repositories.OrgRecord | len:3, cap:4>: [
...
{
Name: "org3-10063931",
GUID: "92ae51cc-8dc1-42eb-9f7f-d9b778d1f1dd",
Suspended: false,
Labels: nil,
Annotations: nil,
CreatedAt: "2022-09-02T17:20:28Z",
UpdatedAt: "2022-09-02T17:20:29Z",
},
]
to contain elements …
```
=> Fix flaky org repo test

Makefile, scripts/deploy-on-kind.sh, scripts/install-dependencies.sh
No
Fixes a bug introduced in commit 42e44ce4, which caused `scripts/deploy-on-kind.sh` to fail consistently unless the name `e2e` was used.
Also increases the CPU limit on the kpack-controller so that ClusterBuilder becomes ready quickly instead of the 10+ minutes it's been taking on some machines
No
`make test-e2e` passes
`./scripts/deploy-on-kind.sh` succeeds with a name besides e2e
=> Fix the deploy-on-kind script

controllers/config/crd/kustomization.yaml
No
Turn off the kustomization path to insert cert-manager cainjection annotations in some CRDs.
These are used for CRD version conversion webhooks, but we don't use those.
No
All continues to work
=> Do not inject cert-mgr ca into CRDs

api/repositories/build_repository.go, api/repositories/build_repository_test.go, controllers/controllers/workloads/cfbuild_controller.go, kpack-image-builder/controllers/buildworkload_controller.go
No
Improve the reason and message fields on the BuildWorkload `Succeeded` condition. These are eventually shown to the user upon failure, and the old messages were not clear or helpful.
Only if clients were depending on the old `reason` values we were using, which is unlikely
`cf push` an app that you know will fail to stage and observe that the error message is now clearer.
=> Improve the reason and message on BuildWorkload conditions

controllers/api/v1alpha1/cfservicebinding_types.go, controllers/config/crd/bases/korifi.cloudfoundry.org_cfservicebindings.yaml, controllers/controllers/services/cfservicebinding_controller.go, controllers/controllers/services/cfservicebinding_controller_test.go, controllers/controllers/workloads/cfapp_controller.go, controllers/controllers/workloads/cfapp_controller_test.go, controllers/controllers/workloads/env/builder.go, tests/e2e/apps_test.go, tools/k8s/k8s_suite_test.go, tools/k8s/reconcile.go, tools/k8s/reconcile_test.go
https://github.com/cloudfoundry/korifi/issues/714
Reconcilers can get quite messy provided that they return on various conditions and should update the reconciled object to reflect the current state of the system. These are two separate concerns and it is a smell to address them both in a single type.
-   Introduce PatchingReconciler
-   wraps the concrete reconciler logic
-   it uses generics to abstract the concrete type of the runtime object
-   if found, delegates to the concrete reconciler. The delegate reconciler interfaces also uses generics so that implementors receive the correct type, e.g. `*korifiv1alpha1.CFApp`
-   regardless of the result from the delegate reconciler, the patching reconciler patches the object and its status. Therefore, delegate reconcilers do not have to do …
=> Unify object updates in reconcilers

api/repositories/pod_repository.go, api/repositories/pod_repository_test.go
No.
This makes `PodRepo.ListPodStats` always `continue` when its `metricsFetcher` errors.
Yes: the `/v3/processes/{guid}/stats` endpoint won't fail anymore when fetching metrics fails for any reason.
=> Never fail when fetching Pod metrics fails

api/repositories/image_repository.go, go.mod, kpack-image-builder/controllers/buildworkload_controller.go
No.
This replaces the `authn.Keychain` implementation coming from Kpack with the one coming from `go-containerregistry`. This reduces our coupling with Kpack: we're now only using their resource types.
No.
=> Use `authn.Keychain` from `go-containerregistry`

controllers/controllers/workloads/integration/cfbuild_controller_integration_test.go
CI build: https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/2605
`FindStatusCondition` can return nil, thus the panic. Use the
`IsStatusConditionFalse` utility instead
No
Green tests
=> Fix a panic in the build controller integration tests

scripts/deploy-on-kind.sh, scripts/samples/deploy-release.sh
No.
This removes the `ingress-ready` label from our kind nodes. The label probably came from copy-and-pasting [this example](https://kind.sigs.k8s.io/docs/user/ingress/) which uses it to filter nodes using Contour's `spec.nodeSelector`. We never do this, so we shouldn't need to label our nodes.
No. This passed `make test-e2e` on my machine.
=> Remove unused `ingress-ready` label on kind nodes

api/handlers/integration/process_test.go, api/repositories/process_repository.go, api/repositories/process_repository_test.go, api/repositories/shared_test.go, controllers/api/v1alpha1/cfprocess_types.go, controllers/api/v1alpha1/cfprocess_webhook.go, controllers/api/v1alpha1/integration/cfprocess_webhook_integration_test.go, controllers/api/v1alpha1/zz_generated.deepcopy.go, controllers/config/crd/bases/korifi.cloudfoundry.org_cfprocesses.yaml, controllers/controllers/workloads/cfprocess_controller.go, controllers/controllers/workloads/integration/cfprocess_controller_integration_test.go, controllers/controllers/workloads/testutils/shared_test_utils.go
#1672
As zero is a valid value for `CFProcess.Spec.DesiredInstances` (set to
zero when the user wants to scale down process instances to 0) we cannot
rely on the field zero value. That is why the field has its type changed
to `*int` so that the CFProcess webhook would only default the instances
value if the pointer value is not set.
No
See story
=> Allow scaling web processes down to 0

api/repositories/process_repository_test.go
This behavior was broken before commit c8f84a, but now works as expected. This test will prevent any reversion
This is related to #1672 , but it's not the exact same issue. The PR for that issue did resolve this problem, though.
This PR adds a test to ensure that the ProcessRepo is able to scale processes to 0 instances. Before #1673 this behavior was broken.
No
Push an app, then use `cf scale -i 0` to scale it to 0. Confirm that the app was actually scaled down.
=> Add test for scaling a process to 0

controllers/controllers/workloads/cfspace_controller.go
#1666
Set the serviceaccount propagation for spaces to only add a reference to the package registry secret if it existed on the serviceaccount
No
See issue
@Birdrock
=> Update serviceaccount propagation for spaces

api/actions/manifest/normalizer.go, api/actions/manifest/normalizer_test.go, api/handlers/shared.go, api/handlers/space_manifest_handler_test.go, api/payloads/manifest.go
#1584
Introducing a disk-quota field on the app level in manifest, that applies to the web process if present, unless overridden by the process itself.
Beware that the field is called `disk-quota` at the app level, but
`disk_quota` at the process level.
No.
See story
@kieron-dev
=> Developer can push apps using the top-level disk_quota field in the manifest

api/actions/manifest/normalizer.go, api/actions/manifest/normalizer_test.go, api/payloads/manifest.go
#1582
App-level `instances` is used as default to the web process `instances`
if not set. If both are set, web process instances take priority
No
See story
@kieron-dev
=> Support app-level `instances` in manifest

api/actions/manifest/normalizer.go, api/actions/manifest/normalizer_test.go, api/payloads/manifest.go, controllers/api/v1alpha1/cfprocess_webhook.go, controllers/api/v1alpha1/integration/cfprocess_webhook_integration_test.go, controllers/api/v1alpha1/integration/webhook_suite_integration_test.go, controllers/config/base/controllersconfig/korifi_controllers_config.yaml, controllers/config/config.go, controllers/config/config_test.go, controllers/main.go
#1589, #1590, #1593, #1598
- Support healthcheck manifest app-level properties
- Default processes `timeout` to 60 if not set
No
See stories
@kieron-dev
=> Support healthcheck manifest app-level properties

controllers/controllers/workloads/cfspace_controller.go, controllers/controllers/workloads/integration/cfspace_controller_integration_test.go, controllers/controllers/workloads/integration/suite_integration_test.go
#1666 
k8s creates certain secrets like tokens and dockercfgs and links them to serviceaccounts that are not propagated when a new space is created. These secrets are unavailable and will cause anything using the propagated serviceaccounts to fail. There was a previous change to only reference the package registry secret from the secrets field for propagated serviceaccounts since that is explicitly propagated on create space. This is to also filter the imagepullsecrets field.
No
See issue
@Birdrock
=> Update service account imagepullsecret propagation

controllers/config/crd/bases/korifi.cloudfoundry.org_appworkloads.yaml, controllers/config/samples/appworkload.yml, controllers/config/samples/build_workload.yaml
Co-authored-by: Andrew Costa <ancosta@vmware.com>
Related to #1621 and #1665.
The `reconcilerName` field was accidentally re-added to the `AppWorkload` CRD. This PR is the result of running `make manifests` to remove it again.
No
See #1621 
@acosta11
=> Remove reconcilerName from AppWorkload CRD

INSTALL.md, INSTALL_kind.md
#1552 
This further improves our install instructions. In particular, it:
* adds more details on how to configure Kpack, as the tutorial we used to refer to is not very good for the Korifi use case;
* rearranges information so that it's closer to where it's needed;
* bumps `cf` to `v8.5` so that we can get all our fixes + `cf auth`;
* simplifies the creation of the necessary TLS certificates by leveraging cert-manager.
No. These instructions worked successfully on my local Kind cluster.
Install Korifi using the new instructions:
* [`INSTALL.md`](https://github.com/cloudfoundry/korifi/blob/install-md-fixes/INSTALL.md)
* [`INSTALL_kind.md`](https://github.com/cloudfoundry/korifi/blob/install-md-fixes/INSTALL_kind.md)
=> More `INSTALL*.md` fixes

scripts/common.sh, scripts/deploy-on-kind.sh, scripts/samples/deploy-release.sh
No.
This uses `cert-manager` instead of the local `openssl` to create the TLS certs we need in our scripts.
Hopefully not 😬
=> Create TLS certs in our scripts with cert-manager

statefulset-runner/Dockerfile
No.
This removes the `-a` flag from the `go build` command in one of our `Dockerfile`s, so that packages that are already up-to-date in the cache don't get forcefully rebuilt. This should speed up builds.
No.
=> Don't force rebuilding up-to-date package in Dockerfiles

HACKING.md
#1526
- New section describing docker image tagging in hacking.md
- Add missing $IMG_XXX vars to hacking.md
=> Push latest tag on release

controllers/controllers/services/cfservicebinding_controller.go, controllers/controllers/workloads/cfapp_controller.go, tools/k8s/k8s_suite_test.go, tools/k8s/patch.go, tools/k8s/patch_test.go, tools/k8s/reconcile.go
#714
- Introduce generic k8s `Patch` utility
- Use the generic `Patch` in CFApp and CFServiceBinding controllers
No
N/A
=> Use `Patch` instead of `Update` in CFApp and CFServiceBinding controllers

api/handlers/space_manifest_handler_test.go, api/payloads/manifest.go, controllers/api/v1alpha1/appworkload_types.go, controllers/api/v1alpha1/zz_generated.deepcopy.go, controllers/config/crd/bases/korifi.cloudfoundry.org_appworkloads.yaml, controllers/controllers/workloads/cfprocess_controller.go, controllers/controllers/workloads/integration/cfprocess_controller_integration_test.go, controllers/controllers/workloads/integration/suite_integration_test.go, statefulset-runner/controllers/appworkload_controller.go, statefulset-runner/controllers/appworkload_controller_test.go, statefulset-runner/controllers/integration/appworkload_controller_test.go, statefulset-runner/controllers/suite_test.go
#1701
CF allows `timeout` seconds for an app to start, with a probe each 2 seconds. Once started, CF probes the app each 30 seconds, killing the container if a probe fails. The `health-check-invocation-timeout` determines how long to wait for a response for these probes.
To reproduce this functionality in korifi we need to create:
1. A startup probe with:
-   periodSeconds: 2
-   timeoutSeconds: `health-check-invocation-timeout`
-   failureThreshold: (`timeout` / 2) rounded to the next integer.
2. A liveness probe with:
-   periodSeconds: 30
-   timeoutSeconds: `health-check-invocation-timeout`
-   failureThreshold: 1
The readiness probe is not required as this does not correspond to CF functionality. It would stop k8s routing traffic to an app failing the readiness probe, but would not …
=> Create the correct healthcheck probes

INSTALL.md
No
The cert manager issuer in the controllers namespace is actually called `korifi-controllers-selfsigned-issuer`.
No
Follow the install.md instructions, including using cert manager to generate ingress certs, and it should work.
=> Fix typo in install.md

controllers/controllers/networking/cfroute_controller.go, controllers/controllers/networking/cfroute_controller_test.go, controllers/controllers/networking/suite_test.go, controllers/controllers/services/cfservicebinding_controller_test.go, controllers/controllers/services/cfserviceinstance_controller.go, controllers/controllers/services/cfserviceinstance_controller_test.go, controllers/controllers/services/suite_test.go, controllers/controllers/workloads/cfapp_controller_test.go, controllers/controllers/workloads/cfbuild_controller.go, controllers/controllers/workloads/cfbuild_controller_test.go, controllers/controllers/workloads/cforg_controller.go, controllers/controllers/workloads/cforg_controller_test.go, controllers/controllers/workloads/cfpackage_controller.go, controllers/controllers/workloads/cfpackage_controller_test.go, controllers/controllers/workloads/cfprocess_controller.go, controllers/controllers/workloads/cfprocess_controller_test.go, controllers/controllers/workloads/cfspace_controller.go, controllers/controllers/workloads/cfspace_controller_test.go, controllers/controllers/workloads/cftask_controller.go, controllers/controllers/workloads/cftask_controller_test.go, controllers/controllers/workloads/shared.go, controllers/controllers/workloads/suite_test.go
NOTE: DO NOT merge prior releasing 0.3
#714
Use `PatchingReconciler` in all "core" controllers so that those controllers do
not need to patch the object being reconciled anymore. If they need to patch a
dependent object (e.g. a referenced secret), they use the `k8s.Patch` utility
that implements the standard patching k8s idiom.
No
Not functional change, green tests
=> Use `PatchingReconciler` in "core" controllers
