cloudfoundry/korifi

Makefile
go.mod
go.sum
tools/tools.go

#1712
Since vendir is used as part of our CI, we should not be fixing its version in our go.mod
Instead, the Makefile has been updated to install and use the latest version of vendir. Our CI will then call the `make vendir-update-dependencies` command.
No

No need to fix vendir version in our project go.mod

---

tests/e2e/helpers/fail_handler.go

#1714
Print kpack logs and droplet build pod logs when the `Droplet not found` error occurs.
While being here, also print "non-core" korifi controllers logs as well on every e2e failure
No
Figure out what is causing the `Droplet not found` error

Print additional debug info on `Droplet not found` e2e failures

---

api/Dockerfile
api/remote-debug/Dockerfile
controllers/Dockerfile
controllers/remote-debug/Dockerfile
job-task-runner/Dockerfile
job-task-runner/remote-debug/Dockerfile
kpack-image-builder/Dockerfile
kpack-image-builder/remote-debug/Dockerfile
statefulset-runner/Dockerfile
statefulset-runner/remote-debug/Dockerfile

No
Bump golang to 1.19.2 in all Dockerfiles so that we do not have to bump all the dependabot PRs one by one
No
Passing tests
@kieron-dev

Bump golang to 1.19.2 in all Dockerfiles

---

controllers/controllers/networking/cfroute_controller.go
helm/api/templates/configmap.yaml
helm/api/templates/ingress-cert.yaml
helm/api/values.yaml
helm/controllers/templates/ingress-cert.yaml
helm/controllers/templates/post-install-app-domain.yaml
helm/controllers/templates/role.yaml
helm/controllers/values.yaml
helm/korifi/values.yaml
helm/kpack-image-builder/templates/post-install-builderinfo.yaml
helm/kpack-image-builder/templates/pre-delete-builderinfo.yaml
scripts/assets/values-template.yaml
scripts/deploy-on-kind.sh

#1704
- Create default cf domain in the controllers helm chart
- Add ingress certs to helm chart
- Optionally activated with the `global.generateIngressCertificates` value
No
deploy-on-kind and CI continue to work
@kieron-dev

Create default domain and ingress certs (optionally) with helm

---

helm/api/templates/configmap.yaml
helm/api/values.yaml
helm/controllers/templates/configmap.yaml
helm/controllers/templates/root-namespace.yaml
helm/controllers/values.yaml
helm/korifi/templates/admin-user.yaml
helm/korifi/values.yaml
helm/kpack-image-builder/templates/cluster-builder.yaml
helm/kpack-image-builder/templates/configmap.yaml
helm/kpack-image-builder/templates/service-account.yaml
helm/kpack-image-builder/values.yaml
scripts/assets/kind-config.yaml
scripts/assets/values-template.yaml
scripts/deploy-on-kind.sh
scripts/install-dependencies.sh

- Default optional values in api config map template
- Korifi configuration by helm chart
#1704
The heml chart now
* creates the cf root namepsace
* created the kpack service account and optionally configures the cluster builder
No
Korifi deploys and tests are green
@kieron-dev

Korifi configuration in the halm chart

---

Makefile
helm/api/templates/role.yaml
helm/controllers/templates/manifests.yaml
helm/kpack-image-builder/templates/manifests.yaml
helm/statefulset-runner/templates/manifests.yaml
kpack-image-builder/Makefile
scripts/assets/kind-config.yaml
scripts/run-tests.sh
statefulset-runner/Makefile

No
Replace `sed` with `yq` in Makefiles: `sed` behaves differently on macos and linux and fails on `make manifests`
Also, fix `make test-e2e` to correctly create the cluster and provide proper arguments to `deploy-on-kind`
No
`make test-e2e` succeeds
@kieron-dev

Replace `sed` with `yq` in Makefiles

---

helm/controllers/templates/pre-install-cfroot-namespace.yaml
helm/controllers/templates/root-namespace.yaml

#1704
Create the cfroot namespace via a pre-install helm hook. Thus the root
namespace remains after uninstalling the Korifi/controllers chart
No
Delete the korifi chart, see the cf root namespace remains
@kieron-dev

Create the cfroot namespace in a pre-install hook

---

helm/kpack-image-builder/templates/cluster-builder.yaml

No
Pin the paketo java buildpack to 7.5.0. With current latest (7.6.0) we are seeing build failures on CI
No
Green tests

Pin the java paketo buildpack to v7.5.0

---

helm/api/templates/rbac.yaml

No. This is related to the work to create a Helm chart.
Renaming the API's clusterrole without renaming the corresponding clusterrolebinding caused upgrades to fail due to the inability to update the roleRef of a clusterrolebinding.
No.
Install Korifi v0.3.0 and then upgrade to "main".
@julian-hj

Rename the API clusterrolebinding

---

helm/controllers/templates/post-install-app-domain.yaml
helm/controllers/templates/pre-install-cfroot-namespace.yaml
helm/kpack-image-builder/templates/post-install-builderinfo.yaml
helm/kpack-image-builder/templates/pre-delete-builderinfo.yaml

No
* Change delete policies to add before-hook-creation to hook-succeeded.
This means that if a hook fails, you can re-run and not automatically
get an error that the resource already exists
* Change the delete policy for the role and binding used in the
pre-install hook. When set to hook-succeeded, there is a chance the
role or binding will be deleted before the job that relies on them
starts. So use the default before-hook-creation instead.
No
This should fix deploy on acceptance :)

Make helm hooks more resilient

---

helm/controllers/templates/pre-install-cfroot-namespace.yaml
helm/kpack-image-builder/templates/pre-delete-builderinfo.yaml

No
We have seen this delete hook failing when the install hasn't completed
as far as creating the korifi-kpack-image-builder-system namespace. So
it is safer to use the helm release namespace, defaulting to `default`,
which stands a better chance of existing.
No

Helm pre-delete hook job namespace fix

---

helm/api/templates/deployment.yaml
helm/controllers/templates/deployment.yaml
helm/job-task-runner/templates/deployment.yaml
helm/kpack-image-builder/templates/deployment.yaml

No
Annotate deployment pods with a checksum of the deployment configmap. This way when you helm upgrade and a configmap has changed, the corresponding pods will be restarted.
No

Restart deployments when their config changes

---

INSTALL.md
INSTALL_kind.md
helm/README.values.md
helm/api/values.yaml
helm/kpack-image-builder/templates/cluster-builder.yaml
helm/kpack-image-builder/templates/configmap.yaml
helm/kpack-image-builder/values.yaml
scripts/assets/values-template.yaml

#1578
Instead of putting `exampleClusterBuilder.create: true`, we now just leave `clusterBuilderName` empty in order to make helm create the example cluster builder configuration.
No

Remove exampleClusterBuilder.create property

---

controllers/controllers/workloads/cfapp_controller.go
tests/e2e/apps_test.go

No
We observed that the ObservedDesiredState on the CFApp status was never updating. This commit fixes that. 
We also have added an e2e test to test the behaviour
No
All tests should pass
@davewalter

Fixes setting observed desired state on cfApps

---

statefulset-runner/controllers/appworkload_controller.go
statefulset-runner/controllers/appworkload_controller_test.go

No
Adds the validation to check the runnerName back onto statefulset reconciler
No
All tests should pass
@davewalter

Adds RunnerName validation back on statefulset-runner

---

controllers/main.go

#1180 
Configure the korifi-controllers logger according to the proposal in the linked issue
No
Deploy korifi as you normally would and check the logs with k9s or kubectl directly. See that the log format for controller-manager logs matches the proposal.
paired w/ @clinty
Note out comment on the issue that we don't think it's currently possible to have controller-runtime pass the configured logger through to the underlying client-go klog logging that generates the leadership election logs.

Implement logging proposal for korifi-controllers

---

kpack-image-builder/main.go

[#1183]
- use json logging with RFC3339 timestamps
- set the same logger to klog so that the low level controller runtime calls also log to the same format.
[#1183]
@matt-royal

Use a standard logging for kpack-image-builder

---

INSTALL.md
Makefile
helm/README.md
helm/api/templates/configmap.yaml
helm/api/values.yaml
helm/controllers/templates/configmap.yaml
helm/controllers/templates/ingress-cert.yaml
helm/controllers/values.yaml
helm/kpack-image-builder/templates/configmap.yaml
helm/kpack-image-builder/values.yaml
kpack-image-builder/Makefile
scripts/assets/values-template.yaml
scripts/deploy-on-kind.sh

#1806
-   Rename `api.packageRegistry` to `api.packageRepositoryPrefix`.
-   Rename `kpack-image-builder.dropletRegistry` to `kpack-image-builder.dropletRepositoryPrefix`.
-   Replace `controllers.workloadsTLSSecret.name` with just `controllers.workloadsTLSSecret`.
Rename helm/README.values.md to helm/README.md for make it appear nicely
in github
Rename your helm values appropriately!

Improve helm value names

---

api/handlers/cli_version_middleware.go
api/handlers/cli_version_middleware_test.go
api/main.go
go.mod
go.sum
tests/e2e/cli_version_test.go

https://github.com/cloudfoundry/korifi/issues/1771
Introduce an API middleware that returns an error if the user agen is CF
cli and its version is `< 8.5.0`
No
* `cf api` succeeds with CF cli `>= 8.5.0`
* `cf api` fails with CF CLI `< 8.5.0`

Validate CF cli version

---

api/actions/manifest/applier.go
api/actions/manifest/applier_test.go
api/actions/shared/fake/cfapp_repository.go
api/actions/shared/shared.go
api/payloads/manifest.go
api/repositories/app_repository.go
api/repositories/app_repository_test.go
api/repositories/shared_test.go
kpack-image-builder/main.go

#1632 
Plumb through buildpack info in app update requests to properly trigger errors on unsupported buildpacks the same way as on create.
No
See issue #1632 
paired w/ @davewalter @Birdrock and clinty(but not using @ as he is out of office)
Note that we followed the pattern from the create app implementation and were not sure if there was an appropriate end to end test to author. If y'all ideas for how that would look, we'd be happy to spend another cycle on it.

Implement CFApp spec buildpacks patching

---

helm/kpack-image-builder/templates/cluster-builder.yaml

#1764
Unpin `paketo-buildpacks/java`, their latest release (`v7.7.0`) fixes the [maven buildpack issue](https://github.com/paketo-buildpacks/maven/issues/194) that made us pin it
No
Green E2E tests

Unpin paketo-buildpacks/java

---

controllers/controllers/workloads/cfprocess_controller.go
controllers/controllers/workloads/integration/cfprocess_controller_integration_test.go
controllers/controllers/workloads/testutils/shared_test_utils.go

https://github.com/cloudfoundry/korifi/issues/1731
Delete `AppWorkload`s for `CFProcess`es that have been scaled down to 0 instances. This has the side effect that `Statefulset`s for that app workload are also deleted as they are owned by `AppWorkload`s
As `CFProcess.Spec.DesiredInstances` is a pointer (i.e. can be unset), this PR treats the unset instances pointer as zero instances, therefore when `DesiredInstances` is unset on the spec, the `AppWorkload` gets deleted.
No
See #1731

Delete AppWorkloads for processes scaled down to 0

---

api/actions/manifest/normalizer.go
api/actions/manifest/normalizer_test.go
api/payloads/manifest.go

https://github.com/cloudfoundry/korifi/issues/1633
Since kpack-image-builder currently rejects any content of `buildpacks`,
this now makes the behaviour consistent as it will now also reject any
(non-trivial) content of `buildpack`.
No
See ammended story acceptance
@kieron-dev

Normalize deprecated manifest `buildpack` into `buildpacks`

---

api/authorization/cert_inspector.go
api/authorization/cert_inspector_test.go
api/authorization/identity_provider.go
api/authorization/namespace_permissions.go
api/authorization/namespace_permissions_test.go
api/authorization/testhelpers/client_cert.go
api/authorization/token_reviewer.go
api/authorization/token_reviewer_test.go
api/handlers/whoami_handler_test.go
api/presenter/identity.go

https://github.com/cloudfoundry/korifi/issues/1710
`system:masters` is a K8S built-in group that gives its user super
powers. For those users we do not need to check rolebindings as they are
allowed to do anything.
No
* Login to Korifi using the K8S admin user (not the cf-admin one)
* Create an org
* See the org created can be listed
@kieron-dev

Do not check rolebindings for `system:masters` users

---

statefulset-runner/main.go

[#1760]
Update logging configuration for the controller manager and configure the klog logger to defer to the controller manager logger
No
See issue. We manually deployed before and after making changes to look at the startup logs with kubectl and k9s.
Paired w/ @akrishna90

Implement standard logging format proposal for statefulset-runner

---

job-task-runner/main.go

[#1761]
Configure controller manager logger to use desired timestamp format and configure klog to defer to the controller manager logger.
No
See issue. We checked the startup logs with kubectl and k9s to see the desired json format.
paired w/ @akrishna90

Implement standard logging proposal for job-task-runner

---

helm/kpack-image-builder/templates/pre-delete-builderinfo.yaml

No
Our pre-delete hook should not depend on installation being successful.
It should not failed if installation did not manage to apply the crds.
No
Green tests
@danailster @gcapizzi

Fix helm pre-delete hook

---

INSTALL.md

No
Fixing a broken link in the docs

fix: broken link to kind install guide

---

controllers/controllers/workloads/cfspace_controller.go
controllers/controllers/workloads/integration/cfspace_controller_integration_test.go

no
Fix service account image pull secret propagation when copying service accounts to spaces. Some distributions of k8s create a dockercfg auto generated secret and adds it to service accounts. Copying service accounts with these secrets present in the secret or image pull secret fields causes a not found error because those secrets will not be copied into the space namespace.
no
All unit, integration, and e2e tests pass.
@davewalter @matt-royal @julian-hj

Fix service account image pull secret propagation

---

.github/workflows/test-pr.yml
HACKING.md
Makefile
api/Makefile
controllers/Makefile
kpack-image-builder/Makefile
scripts/check-everything.sh
statefulset-runner/Makefile

https://github.com/cloudfoundry/korifi/issues/1778
-   Remove unused targets
-   Extract Makefiles for api and controllers
-   The top-level Makefile just delegates to inner make targets.
-   Remove `fmt` and `vet` targets from the nested Makefiles as the
top-level targets are recursive
No
Not a functional change, generally make targets should work

Cleanup unused Makefile targets

---

Makefile
api/Makefile
controllers/Makefile
helm/api/templates/role.yaml
helm/controllers/templates/crds/korifi.cloudfoundry.org_appworkloads.yaml
helm/controllers/templates/crds/korifi.cloudfoundry.org_builderinfos.yaml
helm/controllers/templates/crds/korifi.cloudfoundry.org_buildworkloads.yaml
helm/controllers/templates/crds/korifi.cloudfoundry.org_cfapps.yaml
helm/controllers/templates/crds/korifi.cloudfoundry.org_cfbuilds.yaml
helm/controllers/templates/crds/korifi.cloudfoundry.org_cfdomains.yaml
helm/controllers/templates/crds/korifi.cloudfoundry.org_cforgs.yaml
helm/controllers/templates/crds/korifi.cloudfoundry.org_cfpackages.yaml
helm/controllers/templates/crds/korifi.cloudfoundry.org_cfprocesses.yaml
helm/controllers/templates/crds/korifi.cloudfoundry.org_cfroutes.yaml
helm/controllers/templates/crds/korifi.cloudfoundry.org_cfservicebindings.yaml
helm/controllers/templates/crds/korifi.cloudfoundry.org_cfserviceinstances.yaml
helm/controllers/templates/crds/korifi.cloudfoundry.org_cfspaces.yaml
helm/controllers/templates/crds/korifi.cloudfoundry.org_cftasks.yaml
helm/controllers/templates/crds/korifi.cloudfoundry.org_taskworkloads.yaml
helm/controllers/templates/manifests.yaml
helm/kpack-image-builder/templates/manifests.yaml
helm/statefulset-runner/templates/manifests.yaml
job-task-runner/Makefile
kpack-image-builder/Makefile
statefulset-runner/Makefile

#1849
Instead of making users install `gsed` on a mac in order to be able to use our makefiles, install `yq` locally instead.
We install away from `$HOME/go/bin`, which might be in the path, so that this `yq` does not clash with the other `yq` that might be installed and used in non-Korifi scripts.
`yq` also happens to be a lot more robust for modifying YAML that `sed`.
No.
`make manifests` and `make generate` work on Linux and Mac.
@kieron-dev

Use local yq to have consistent makefile across platforms

---

go.mod
go.sum
kpack-image-builder/controllers/imageprocessfetcher/image_process_fetcher.go

No
Its latest release (`0.15.0`) carries dependency to
`github.com/Sirupsen/logrus` (note the uppercase `S`) that causes
`case-insensitive import collision` error. As we are using
`buildpack/lifecycle` by only referring their types to unmarshal image
config, we now just define owr own types and use them instead.
No
No functional change, everything should work as before

Remove dependency to `buildpack/lifecycle`

---

api/main.go
api/repositories/service_binding_repository.go
api/repositories/service_binding_repository_test.go
controllers/api/v1alpha1/cfservicebinding_types.go
controllers/controllers/services/cfservicebinding_controller.go
controllers/controllers/services/cfservicebinding_controller_test.go
controllers/controllers/services/integration/cfservicebinding_integration_test.go
controllers/controllers/services/integration/suite_integration_test.go
controllers/controllers/workloads/cfapp_controller.go
controllers/controllers/workloads/cfapp_controller_test.go
controllers/controllers/workloads/fake/vcapservices_secret_builder.go
controllers/controllers/workloads/integration/cfapp_controller_integration_test.go
controllers/controllers/workloads/integration/suite_integration_test.go
controllers/main.go
tests/e2e/apps_test.go

https://github.com/cloudfoundry/korifi/issues/1716
The finalizer purpose was to ensure that a service binding is deleted
when an app is being deleted. This has now been replaced with an owner
reference from the app to the binding so that K8S takes care of that for
us. It is the reponsibility of the service binding creator to set the
owner ref, therefore this code was moved to the repository.
The binding finalizer also had the reponsibility to update the app
VCAP_SERVICES secret. Now this is taken care of by the app controller
that now listens to service binding events and rebuilds the secret
accordingly.
While being here, use the awaiter utility to wait for the binding ready
condition in the repository.
Service bindings created by kubectl users that have not their owner references
set are …

Get rid of the service binding finalizer

---

api/repositories/process_repository.go
controllers/api/v1alpha1/cfprocess_types.go
controllers/controllers/workloads/cfapp_controller.go
controllers/controllers/workloads/cfprocess_controller.go
controllers/controllers/workloads/cfprocess_controller_test.go
controllers/controllers/workloads/integration/cfapp_controller_integration_test.go
controllers/controllers/workloads/integration/cfprocess_controller_integration_test.go
controllers/controllers/workloads/testutils/shared_test_utils.go
helm/controllers/templates/crds/korifi.cloudfoundry.org_cfprocesses.yaml

[#1869]
- Prior to this change, when an app was re-pushed with source that caused the `command` to change for a CFProcess, we'd ignore the change.
- For example pushing a node app, and then pushing java code to the same app name would leave the `node` start command, which would then fail.
- This commit adds a separate `dropletCommand` field to store the command from the built image. If no `command` is explicitly set on the process, the `dropletCommand` is used.
- For apps that explictly set a `command` for the process (for example in a manifest) the `command` overrides the droplet command.
No
[#1869]
@tcdowney PTAL. I'm especially open to different suggestions for the field name `dropletCommand`

Handle changing process commands across builds

---

scripts/run-tests.sh

No
--slow-spec-threshold is deprecated, so take the recommendation and use --poll-progress-after. This prints a stack trace if a test takes a long time, so we can see what it's up to.
No
No ginkgo deprecation warnings when running tests
@kieron-dev

Change ginkgo slow-spec-threshold to poll-progress-after

---

api/handlers/process_handler_test.go
api/payloads/process.go
api/repositories/process_repository.go
api/repositories/process_repository_test.go
tests/e2e/e2e_suite_test.go
tests/e2e/processes_test.go

[#1444]
- Add new optional `metadata` field to /v3/processes/<GUID> PATCH requests.
- plumb metadata down to the repository layer and set labels and annotations on the underlying CFProcess object.
no
[#1444]
I was soloing on this. Anyone feel free to take a look.

support process metadata patching

---

controllers/controllers/networking/cfroute_controller.go
controllers/controllers/workloads/cfapp_controller.go
controllers/controllers/workloads/cforg_controller.go
controllers/controllers/workloads/cfspace_controller.go
controllers/controllers/workloads/shared.go
tools/k8s/finalizer.go
tools/k8s/finalizer_test.go

#1930
Commit immediately after setting finalizer in controllers
There is a potential race when deleting a resource with a finalizer
when the finalizer is not immediately persisted. E.g. for a CFSpace:
1. Create the CFSpace
2. Wait for namespace to appear
3. Delete the CFSpace.
However, the reconciler could well be in the code between creating that
namespace and propagating service accounts / secrets, and nothing has
yet been saved.
When the big 'patch' call finally occurs, the CFSpace has already been
deleted, since it didn't actually have a saved finalizer on it.
All resources created by the reconciliation are now orphaned and will
not be cleaned up.
(We also tidied up logs in the touched files)
No
We stop seeing flakes saying 'Eventually deletes the namespace'
@kieron-dev

Fix finalizer persistence race

---

README.helm.md
helm/kpack-image-builder/templates/cluster-builder.yaml
helm/kpack-image-builder/values.schema.json
helm/kpack-image-builder/values.yaml
scripts/assets/values-template.yaml

No
The full-cnb stack is expensive for image creation. Allow changing this to base-cnb in the helm chart.
Default to the existing values.
No
`make test e2e` still works, as does all CI
@kieron-dev

Allow switching cluster stack build and run images

---

tests/vendir.lock.yml
tests/vendir.yml
tests/vendor/kpack/release-0.8.0.yaml

No
kpack v0.8.1 introduced a bug where it often stops reconciling the
clusterbuilder because it cannot find the clusterstore. So we need to go
back to v0.8.0 for now.
No
CI should stop failing after timing out waiting for the ClusterBuilder to be ready

Ignore kpack-v0.8.1 when bumping test dependencies

---

helm/kpack-image-builder/templates/pre-delete-builderinfo.yaml

No
In the pre-delete helm hook to delete the builder info, we check the builder info CRD exists. This adds permission to get CRDs so that the check doesn't always fail.
No
See the builder info is deleted when you `helm delete` korifi

Pre-delete helm hook service account permission fix

---

README.helm.md
helm/api/templates/configmap.yaml
helm/api/values.schema.json
helm/api/values.yaml
helm/controllers/templates/configmap.yaml
helm/controllers/values.schema.json
helm/controllers/values.yaml
helm/korifi/values.yaml
helm/kpack-image-builder/templates/service-account.yaml
helm/kpack-image-builder/values.schema.json
helm/kpack-image-builder/values.yaml

#1923
The global value is used as package, droplet and kpack-build repository
secrets, so it makes sense to call it containerRegistrySecret.
Yes - helm chart value is renamed
Install korifi helm chart using the new name for the global registry secret and check you can push an app.

Rename helm packageRegistrySecret to containerRegistrySecret

---

INSTALL.kind.md
INSTALL.md
README.helm.md
api/config/config.go
api/handlers/package_handler.go
api/handlers/package_handler_test.go
api/main.go
helm/api/templates/configmap.yaml
helm/api/values.schema.json
helm/api/values.yaml
helm/kpack-image-builder/templates/configmap.yaml
helm/kpack-image-builder/values.schema.json
helm/kpack-image-builder/values.yaml
kpack-image-builder/config/config.go
kpack-image-builder/controllers/buildworkload_controller.go
kpack-image-builder/controllers/suite_test.go
scripts/assets/values-template.yaml
scripts/deploy-on-kind.sh

#1914
Do not append a suffix, as this means we cannot support registries which disallow dynamic repository creation on push (e.g. ECR).
Rename some config values to make this clear to operators:
- Helm value in kpack-image-builder:
- `dropletRepositoryPrefix` --> `dropletRepository`
- kpack-image-builder config map property
- `kpackImageTag` --> `dropletRepository`
Finally, update docs.
Yes. Korifi packagers and users should note the two renames above.
1. Deploy korifi successfully using the new helm value in the kpack-image-builder chart.
2. Successfully push an app.

Use configured dropletRepository as given

---

scripts/install-dependencies.sh

#1922
EKS does not support signing user certs, so we cannot run this script with an EKS cluster targeted
No
`deploy-on-kind.sh` works, as does CI
@davewalter

Avoid create-new-user.sh for AWS

---

controllers/controllers/workloads/cforg_controller.go
controllers/controllers/workloads/cfspace_controller.go
controllers/controllers/workloads/shared.go

No
When Korifi is deployed with custom runner & builder implementations, deleting the namespace causes resources to be deleted in an adhoc fashion causing a few resources to hang forever in their finalizer blocks. Deleting CFApps before NSes makes sure the resources required in finalizer blocks live around long enough for the whole operation to succeed.
No
All tests pass
@akrishna90

Fix race condition when deleting CFSpaces

---

controllers/controllers/networking/cfroute_controller.go
controllers/controllers/networking/cfroute_controller_test.go
tests/e2e/routes_test.go

Issue: https://github.com/cloudfoundry/korifi/issues/1986
Fixes a bug where a route could not be deleted since the controller did not have permission to update the Status of an HTTPProxy resource. This updates the implementation to use the PatchResource function instead which doesn't attempt to update the Status and backfills some tests.
No
You should no longer be able to reproduce the issue in https://github.com/cloudfoundry/korifi/issues/1986.
```
cf create-route apps-127-0-0-1.nip.io --hostname foo
cf routes # and see the route
cf delete-route apps-127-0-0-1.nip.io --hostname foo
cf routes # and see the route WAS deleted
```
@kieron-dev

Fix CFRoute deletion finalizer bug

---

helm/api/templates/configmap.yaml
helm/api/templates/deployment.yaml
helm/api/templates/rbac.yaml
helm/api/values.schema.json
helm/api/values.yaml
helm/controllers/templates/configmap.yaml
helm/controllers/values.schema.json
helm/controllers/values.yaml
helm/korifi/values.yaml
helm/kpack-image-builder/templates/cluster-builder.yaml
helm/kpack-image-builder/templates/configmap.yaml
helm/kpack-image-builder/templates/deployment.yaml
helm/kpack-image-builder/templates/post-install-builderinfo.yaml
helm/kpack-image-builder/templates/rbac.yaml
helm/kpack-image-builder/templates/service-account.yaml
helm/kpack-image-builder/values.schema.json
helm/kpack-image-builder/values.yaml

#1922
It is simpler to take the ARN of role granting ECR access and k8s
service account role mapping, than to require external service account
creeation by the user.
Helm values have changed
You can push an app on EKS with ECR container registry configured
@davewalter

Take EKS ECR Role ARN rather than service account name

---

controllers/controllers/workloads/cfbuild_controller.go
controllers/controllers/workloads/cfbuild_controller_test.go
controllers/controllers/workloads/cfpackage_controller.go
controllers/controllers/workloads/cfpackage_controller_test.go
controllers/controllers/workloads/cfspace_controller.go
helm/controllers/templates/role.yaml

no
Expands on the previously added fix for a race condition when Korifi is deployed with custom runner & builder implementations. The previous fix deleted any associated CFApps before deleting the namespace in the CFSpace finalizer since that caused resources to hang forever in their finalizer blocks. Making the owner references in the CFApp ownership chain set BlockOwnerDeletion to true ensures the child resources are fully removed before the CFApp is removed and therefore deletion of the namespace will not be blocked.
no
All tests pass
@akrishna90 @acosta11

Expand on race condition fix when deleting CFSpace

---

controllers/controllers/workloads/cfapp_controller.go
controllers/controllers/workloads/cfapp_controller_test.go
controllers/controllers/workloads/cfprocess_controller.go
controllers/controllers/workloads/cfprocess_controller_test.go
helm/controllers/templates/role.yaml

no
Make the owner references in the CFApp AppWorkload ownership chain set BlockOwnerDeletion to true to ensure that the child resources are fully removed before removing the CFApp
No
All tests pass
@julian-hj @Birdrock

Ensure child resources are deleted for CFApps

---

INSTALL.md

Related to #2011
We forgot to escape the <> in the INSTALL.md doc.
No, just docs.
View the docs.
@acosta11

Fix the rendering of the registry config table in the INSTALL.md doc

---

api/main.go
controllers/main.go
kpack-image-builder/main.go
statefulset-runner/main.go
tools/logr_writer.go

#2025
- the HTTP server used by controller manager runtime for webhooks uses the golang `log` package for logging.
- we can't control the creation of that HTTP server, so this change uses `log.SetOutput` to direct low level log lines to a LogrWriter with our zapr logger.
- this change also moves the LogrWriter to the tools package and makes it public since we are using it across executables.
No
#2025

Fix logging on webhook TLS errors

---

INSTALL.EKS.md
INSTALL.md
README.helm.md
api/config/config.go
api/config/config_test.go
api/main.go
api/repositories/image_repository.go
api/repositories/package_repository.go
api/repositories/package_repository_test.go
helm/api/templates/configmap.yaml
helm/api/values.yaml
helm/korifi/values.schema.json
helm/korifi/values.yaml
helm/kpack-image-builder/templates/configmap.yaml
helm/kpack-image-builder/values.yaml
kpack-image-builder/config/config.go
kpack-image-builder/controllers/buildworkload_controller.go
kpack-image-builder/controllers/suite_test.go
kpack-image-builder/main.go
scripts/assets/values-template.yaml
scripts/deploy-on-kind.sh
tools/registry/meta.go
tools/registry/meta_test.go

No.
- Consolidate registry config values so that users only have to specify `global.containerRepositoryPrefix`.
- Remove some leftover debug logs.
- Improve the error message when `global.containerRegistrySecret` is missing.
- Fix the docs.
Yes: the container repository prefix values have been consolidated into the single `global.containerRepositoryPrefix`.
@davewalter

Pre-release fixes for v0.5

---

api/handlers/app.go
api/handlers/app_test.go
controllers/api/v1alpha1/cfapp_webhook.go
controllers/api/v1alpha1/cfapp_webhook_test.go
controllers/main.go
statefulset-runner/main.go

https://github.com/cloudfoundry/korifi/issues/1912
The app revision used to be set/incremented un the cf app webhook
according to nontrivial logic that was trying to guess whether the app
is being stopped which was error prone and unpredictable because there
are no guaranteed how many times the hook will execute
This WIP is an attempt to move the logic from the webhook to the app
handler, or to be more exact, to eliminate it, since the app handler
knows with certainty if the app is being stopped or started. The handler
will bump the app  rev when the app stop endpoint is triggered. This
makes the app rev predictable by the user, since it no longer happens in
the reconciliation loop.
No
See story

Stabilize app revision

---

INSTALL.md
README.helm.md
helm/api/templates/ingress.yaml
helm/api/values.schema.json
helm/api/values.yaml

Issue: https://github.com/cloudfoundry/korifi/issues/1843
- This is a first step towards support of non-Contour routing for Korifi.
- The ability to have self-signed certificates issued by cert manager is
left intact, as certs are useful regardless of the networking
techology being used, and it can be switched off using the global
`generateIngressCertificates` flag
No
See issue
@eirini

Operator can avoid exposing the Korifi API via Contour

---

README.helm.md
controllers/config/config.go
controllers/config/config_test.go
controllers/controllers/workloads/cforg_controller.go
controllers/controllers/workloads/cfspace_controller.go
controllers/controllers/workloads/cfspace_controller_test.go
controllers/controllers/workloads/labels/compiler.go
controllers/controllers/workloads/labels/compiler_suite_test.go
controllers/controllers/workloads/labels/compiler_test.go
controllers/controllers/workloads/shared.go
controllers/controllers/workloads/suite_test.go
controllers/main.go
helm/controllers/templates/configmap.yaml
helm/controllers/values.schema.json
helm/controllers/values.yaml

https://github.com/cloudfoundry/korifi/issues/1844
-   This lets the operator set custom labels on korifi space namespaces
-   For instance disabling istio sidecar injection or changing the
pod-security-admission levels
No
See issue
@kieron-dev

Introduce the controllers.namespaceLabels value

---

INSTALL.EKS.md
INSTALL.md

#2045
There is an obscure dependency between post-install templates and the `--wait` flag. Post-install templates only wait for the main installation to be _ready_ if the `--wait` flag is specified in install or upgrade command.
Our scripts all use `--wait`, but our docs did not reflect that.
No
See issue

Add `--wait` to helm install in docs

---

controllers/api/v1alpha1/cforg_types.go
controllers/api/v1alpha1/cforg_types_test.go
controllers/api/v1alpha1/cfspace_types.go
controllers/api/v1alpha1/cfspace_types_test.go
controllers/api/v1alpha1/webhook_suite_test.go
helm/korifi/controllers/crds/korifi.cloudfoundry.org_cforgs.yaml
helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfspaces.yaml

#1717
Use the same regexp for validating Org and Space display names as is used in CAPI
No
E.g. create an org called "My Org". The space in the name is now accepted

Change CFOrg and CFSpace display name validation to match CAPI

---

README.helm.md
controllers/config/config.go
controllers/main.go
helm/korifi/controllers/configmap.yaml
helm/korifi/values.schema.json
helm/korifi/values.yaml

#1841
New helm value `contourRouter.include` controls inclusion of the
CFRouteReconciler in controllers.
When false, no services or contour HTTPProxies will be created for apps,
allowing a different reconciler to create the appropriate routing based
on the CFRoute resource.
No - unless you turn the component off. In which case, you will need to provide an alternative CFRoute reconciler.
See story

Introduce flag to exclude contour routing for apps

---

controllers/controllers/networking/cfdomain_controller.go
controllers/controllers/networking/cfdomain_controller_test.go
controllers/controllers/networking/cfroute_controller.go
controllers/controllers/networking/suite_test.go
controllers/controllers/shared/index.go
controllers/main.go
helm/korifi/controllers/role.yaml
tests/e2e/domains_test.go

https://github.com/cloudfoundry/korifi/issues/880
Deleting all routes associated with a domain when we delete the domain
No
See issue

Delete domain routes when finalizing CFDomain

---

controllers/controllers/networking/cfdomain_controller.go
controllers/controllers/networking/cfroute_controller.go
controllers/controllers/workloads/cfapp_controller.go
controllers/controllers/workloads/cfspace_controller.go

No.
While deploying Korifi from HEAD of main, Clint and I noticed errors in the korifi-controllers logs indicating a failure to add finalizers to certain resources because they were being deleted. This PR updates the reconcilers for resources that require a finalizer to check if the resource is being deleted before attempting to add a finalizer.
No.

Don't attempt to add finalizers to deleted resources

---

README.helm.md
controllers/main.go
helm/korifi/values.schema.json

#1844
This applies the `namespaceLabels` to org namespaces in addition to space namespaces. In the future we might consider having separate configurations for orgs and spaces, but in the meantime this should do.
No.

Apply `namespaceLabels` to org namespaces too

---

api/authorization/namespace_permissions.go
api/authorization/namespace_permissions_test.go
api/repositories/org_repository_test.go
api/repositories/repositories_suite_test.go
api/repositories/space_repository_test.go
controllers/api/v1alpha1/cforg_types.go
controllers/api/v1alpha1/cfspace_types.go
controllers/controllers/workloads/cforg_controller.go
controllers/controllers/workloads/cforg_controller_test.go
controllers/controllers/workloads/cfspace_controller.go
controllers/controllers/workloads/cfspace_controller_test.go
controllers/controllers/workloads/shared.go
controllers/webhooks/workloads/cforg_validator.go
controllers/webhooks/workloads/cforg_validator_test.go
controllers/webhooks/workloads/cfspace_validator.go
controllers/webhooks/workloads/cfspace_validator_test.go

#1717
This changes the way we manage org and space display names, according to [this comment](https://github.com/cloudfoundry/korifi/issues/1717#issuecomment-1386291322):
- we deprecated the `cloudfoundry.org/(org|space)-name` labels, now setting them as `XXX-deprecated-XXX`;
- we introduced the `cloudfoundry.org/(org|space)-name` annotations, which will accomodate any value that is valid for traditional CF;
- we introduced the `cloudfoundry.org/(org|space)-guid` labels, which will be useful to trace back namespaces to their org/name;
- validate org/space names to make sure that they're valid label values.
We also backfilled tests for org/space namespace metadata updating.
Yes: anything relying on the `cloudfoundry.org/(org|space)-name` label value won't be able to do that anymore. …

Support CF-compatible display names for orgs and spaces

---

api/repositories/buildpack_repository.go
api/repositories/buildpack_repository_test.go
api/repositories/package_repository_test.go

No
Ordering has moved from repositories to handlers, when explicit order_by params are used.
We remove the test remaining in repositories that was checking ordering no longer done there, and clean up some unused code.
No
Green CI

Remove dangling code after order-by move PR

---

INSTALL.EKS.md
INSTALL.md

No.
This:
- improves wording and formatting;
- uses links instead of plain URLs;
- adds the missing DNS section to the EKS install docs;
- improves instructions related to container registries to make them clearer and more useful;
- fixes a broken trust relationship in the EKS install docs.
No.
@kieron-dev

Fix and improve docs

---

api/handlers/user.go
api/handlers/user_test.go
api/main.go
api/presenter/user.go

https://github.com/cloudfoundry/korifi/issues/1239
Implement `list users` as a stub - this (temporary) solution is needed to make
`cf unset-org|space-role` work.
When usernames are passed as a filter, this returns a list of resources
with username and guid containing those values.
No
N/A
@kieron-dev @gcapizzi

Implement list users as a stub

---

api/config/config.go
api/handlers/fake/cfrole_repository.go
api/handlers/role.go
api/handlers/role_test.go
api/handlers/user_test.go
api/main.go
api/payloads/role.go
api/presenter/role.go
api/presenter/user.go
api/repositories/repositories_suite_test.go
api/repositories/role_repository.go
api/repositories/role_repository_test.go
helm/korifi/api/configmap.yaml
helm/korifi/controllers/cf_roles/cf_admin.yaml
helm/korifi/controllers/cf_roles/cf_org_user.yaml
helm/korifi/controllers/cf_roles/cf_space_developer.yaml
tests/e2e/e2e_suite_test.go
tests/e2e/matchers_test.go
tests/e2e/roles_test.go
tests/smoke/smoke_test.go

https://github.com/cloudfoundry/korifi/issues/1239
Implement listing roles (`GET /v3/roles`)
Invoked when unsetting org/space roles via the cf cli
No
1. `cf set-org-role bob org1 OrgManager`
2. `cf curl "/v3/roles"` -> see `bob` has the OrgManager role assigned in org `org1 `
3. `cf set-space-role bob org1 space1 SpaceDeveloper`
4. `cf curl "/v3/roles"` -> see `bob` has the SpaceDeveloper role assigned in space `space1 `
@kieron-dev

Implement list roles

---

api/handlers/fake/cfrole_repository.go
api/handlers/job.go
api/handlers/job_test.go
api/handlers/role.go
api/handlers/role_test.go
api/main.go
api/presenter/job.go
api/repositories/repositories_suite_test.go
api/repositories/role_repository.go
api/repositories/role_repository_test.go
helm/korifi/controllers/cf_roles/cf_admin.yaml
helm/korifi/controllers/cf_roles/cf_org_manager.yaml
helm/korifi/controllers/cf_roles/cf_space_manager.yaml
tests/e2e/e2e_suite_test.go
tests/e2e/roles_test.go

https://github.com/cloudfoundry/korifi/issues/1239
Implement DELETE /v3/role/{guid}
Also fix listing functionality to read the role guid that gets returned
to the user from the CFRole metadata, as the CFRole name contains the
sha256 sum of the role name and the user name, so that optimistic
locking will prevent us from creating duplicate entries
No
See story
@eirini

Implement DELETE /v3/roles/guid

---

api/actions/manifest.go
api/actions/manifest/normalizer.go
api/actions/manifest/normalizer_test.go
api/actions/manifest_test.go
api/handlers/app.go
api/handlers/app_test.go
api/handlers/fake/cfprocess_repository.go
api/handlers/process.go
api/handlers/shared.go
api/handlers/space_manifest_test.go
api/payloads/manifest.go
tests/e2e/apps_test.go
tests/e2e/e2e_suite_test.go
tests/e2e/spaces_test.go

#1661
Allow the list of apps in a space manifest to have more than 1 entry.
Also fix the behaviour of creating a web process during manifest application or app creation to match cf on VMs. I.e. the web process is created at the same time as the app.
Note that the web app is created earlier now, rather than when starting the app.
See story
@gcapizzi

Allow multiple apps in manifests

---

statefulset-runner/controllers/appworkload_to_stset.go
statefulset-runner/controllers/appworkload_to_stset_test.go

#2132
This stops apps being randomly restarted when the statefulset-runner appworkload reconciler runs.
No
See #2132

Make the pod affinity term stable

---

INSTALL.md

No related Issue.
The GitHub container registry is a good place to try out korifi because private images are available for free.
So, I added a description of the GitHub container registry to the installation instructions.
No breaking change.
NA
NA
NA

Added support for GitHub Container Registry

---

INSTALL.md

No related Issue.
The link to the instructions for installing kpack was broken and has been corrected.
No breaking change.
NA
NA
NA

Fix link to instructions for installing kpack

---

controllers/api/v1alpha1/builderinfo_types.go
helm/korifi/controllers/crds/korifi.cloudfoundry.org_builderinfos.yaml
kpack-image-builder/controllers/builderinfo_controller.go
kpack-image-builder/controllers/builderinfo_controller_test.go

No
The builder info ready status condition should be true iff the cluster builder ready status condition is true
No

Reflect the cluster builder ready status in the builder info status

---

kpack-image-builder/controllers/buildworkload_controller.go
kpack-image-builder/controllers/buildworkload_controller_test.go

#1798
This allows `cf push` to fail quickly when the `ClusterBuilder` is not ready. We believe this condition will only occur right after installing Korifi or if the `ClusterBuilder` is misconfigured, so it is fair to fail builds on it instead of trying to be eventually consistent.
Yes. When using the default `kpack-image-builder`, `BuildWorkload`s (and thus `CFBuild`s) will now fail immediately if the configured `ClusterBuilder` is not ready, instead of waiting for it to get back to ready.
- Deploy Korifi;
- make the `ClusterBuilder` invalid;
- try to `cf push`.
@gcapizzi

`BuildWorkload`s fail if the Kpack `ClusterBuilder` is not ready

---

api/actions/manifest/normalizer.go
api/handlers/service_instance_test.go

Fix linters
`rand.Seed()` is deprecated in go 1.20
@kieron-dev

Fix linter warnings

---

.github/workflows/test-pr.yml

No
We need to manually bump go-version in our github actions config.
We noticed this when the linter in concourse complained about rand.Seed() deprecated in go-1.20, but this wasn't picked up in the PR CI in github actions.
No

Bump go version in github action tests

---

.github/workflows/test-pr.yml

#2154
That means we don't have to manually bump the go version in .github/workflows/test-pr.yml each time the minor version changes
No

Use 'stable' for the go-version in github actions

---

scripts/install-dependencies.sh

From `man bash`: Enclosing characters in double quotes preserves the literal value of all characters within the quotes, with the exception of $, `, \
In bash, this should not work. We would like to be able to point a wide range of users to the `deploy-on-kind.sh` script which calls this script. We would like to ensure the widest range of users do not run into issue with this.
No
The script uses a wildcard inside double quotes. In bash, this should not work. We would like to be able to point a wide range of users to the `deploy-on-kind.sh` script which calls this script. We would like to ensure the widest range of users do not run into issue with this.
No
Run it in vanilla bash with no special settings.
N/A

Remove double quotes surrounding a wildcard

---

api/handlers/app.go
api/handlers/app_test.go
api/repositories/app_repository_test.go
controllers/api/v1alpha1/cfapp_types.go
controllers/api/v1alpha1/cfapp_webhook.go
controllers/controllers/services/cfservicebinding_controller_test.go
controllers/controllers/workloads/cfapp_controller.go
controllers/controllers/workloads/cfapp_controller_test.go
controllers/controllers/workloads/env/builder_test.go
controllers/main.go
controllers/webhooks/workloads/apprev_webhook.go
controllers/webhooks/workloads/apprev_webhook_test.go
controllers/webhooks/workloads/suite_integration_test.go
helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfapps.yaml
helm/korifi/controllers/manifests.yaml
tests/e2e/apps_test.go

https://github.com/cloudfoundry/korifi/issues/2040
- Bump app-rev on app stop via a mutating webhook
- Deprecate `CFApp.Status.ObservedDesiredState`
`CFApp.Status.ObservedDesiredState` is no longer used and is deprecated
No functional change, stable e2e tests
@kieron-dev

Bump `app-rev` in a mutating webhook

---

Makefile

No
Git doesn't store timestamps, so the vendir'ed code will also have current timestamps on files, which means the zip timestamps will always differ from the previous. Hence the korifi-bot will try to PR a dora.zip change every time it runs.
We leave the current dora.zip for now, and this will be addressed by a work on #1146 which should generate app zips on the fly.
No
@gcapizzi

Don't zip dora in when bumping vendir deps

---

tools/k8s/finalizer.go

No.
Previously we always logged a finalizer addition, even when the finalizer wasn't actually added because it was already there.
This fixes it to only log when the finalizer gets actually added.
No.
@gcapizzi

Fix the way we log finalizer addition

---

README.helm.md
controllers/config/config.go
controllers/config/config_test.go
controllers/controllers/workloads/env/vcap_app_builder.go
controllers/controllers/workloads/env/vcap_app_builder_test.go
controllers/controllers/workloads/suite_test.go
controllers/main.go
helm/korifi/controllers/configmap.yaml
helm/korifi/values.schema.json
helm/korifi/values.yaml
tests/e2e/apps_test.go

Issue: #2140
This is done to support `cf_api` which isn't something the controllers layer should know about.
Also populate that `cf_api` value by default in the controllers configmap in the helm templates
No
Push an app. See cf_api in its VCAP_APPLICATION env var (in the running app, and via the app env endpoint)
Put other values in the controllers config (probably via helm controllers.extraVCAPApplicationValues) and see them in the VCAP_APPLICATION env.
See that you cannot override the default VCAP_APPLICATION values.
@gcapizzi

Allow configurable extra vals in VCAP_APPLICATION env var

---

helm/korifi/api/configmap.yaml

#1925 
This PR fixes the API log level configuration. It was accidentally inside the check for an auth proxy value.
No
Deploy without configuring an auth proxy and see that the logLevel setting is present in the API ConfigMap.
@akrishna90

Fix the API log level config

---

scripts/install-dependencies.sh

No
Commit 7edfdb743c3ca74e7c8b14591d30539a3cea3173 broke EKS-E2E cluster creation as `install-dependencies.sh` would now fail with `INSECURE_TLS_METRICS_SERVER: unbound variable`.
This change maintains bash-3.x compatability and introduces a default empty value for the variable.
No
EKS-E2E cluster creation in CI works again

Default INSECURE_TLS_METRICS_SERVER to empty

---

kpack-image-builder/Makefile

No
The `manifests:` line was missing
No
Modify a kubebuilder role permission in kpack-image-builder, run `make manifests` and see the role yaml gets updated
@gcapizzi

Fix `make manifests` in kpack-image-builder

---

tests/e2e/apps_test.go
tests/e2e/matchers_test.go

#1146 
This is a small enhancement to @kieron-dev's tests that `VCAP_SERVICES` and `VCAP_APPLICATION` are set in the app container. This also tests that they are valid JSON objects
No

Test that VCAP_SERVICES and VCAP_APPLICATION are valid JSON

---

controllers/api/v1alpha1/cfprocess_types.go

No.
Remove nolint directives that were used to override a staticcheck regression
No. (Update to fixed version of golangci-lint v1.51.2
Run `make lint`
@davewalter @gcapizzi

Remove nolint:unused directives

---

tests/e2e/routes_test.go

#2216 
When we restored the ability for users to provide their own app for the majority of the e2e tests, we ran into a problem where the expected output does not always match the output from the default procfile app. This PR introduces a new `APP_BITS_OUTPUT` env var to allow users to specify the expected output for the test that cares about it.
No.
Run the e2e tests against an environment without a procfile buildpack and see that they pass if `APP_BITS_PATH` is set to another app and `APP_BITS_OUTPUT` is set to the expected output.
@acosta11 @Birdrock

Make procfile app output configurable

---

api/errors/errors.go
api/repositories/app_repository_test.go
api/repositories/org_repository.go
api/repositories/org_repository_test.go
api/repositories/space_repository.go
api/repositories/space_repository_test.go
controllers/controllers/workloads/cforg_controller.go
controllers/controllers/workloads/cforg_controller_test.go
controllers/controllers/workloads/cfspace_controller.go
controllers/controllers/workloads/cfspace_controller_test.go
controllers/controllers/workloads/shared.go
go.mod
go.sum

#2167
Improve error messaging on the create CFOrg/CFSpace api calls. Set proper error messages on the CFOrg/CFSpace object ready conditions.
no
See issue
@Birdrock @acosta11 @davewalter

Improve error messaging on the create CFOrg/CFSpace api calls

---

api/repositories/app_repository_test.go
helm/korifi/controllers/cfservicebindings-role.yaml
tests/e2e/apps_test.go
tests/e2e/assets/golang/go.mod
tests/e2e/assets/golang/main.go
tests/e2e/e2e_suite_test.go
tests/e2e/service_bindings_test.go
tests/e2e/service_instances_test.go

[#2175]
- Fixes a regression bug where compliant servicebindings controllers where not able to read cfservicebindings. This resulted in servicebindings controller failure to volume mount any `secrets` associated with `CFServiceBindings`.
- Adds a e2e case to validate that servicebindings are volume mounted.
- Reworded an `Fetch an app env` e2e case to match others.
- Formatted imports.
No.
See issue [#2175]

Allow compliant servicebindings controller to fetch cfservicebindings

---

api/errors/errors.go
api/repositories/buildpack_repository.go
api/repositories/buildpack_repository_test.go
api/repositories/org_repository.go
api/repositories/space_repository.go
kpack-image-builder/controllers/builderinfo_controller.go
kpack-image-builder/controllers/builderinfo_controller_test.go

#2174 
This PR improves the error responses from the `/v3/buildpacks` endpoint used by the "cf buildpacks" command.
- Wrap the error returned when the BuilderInfo resource cannot be retrieved in a ResourceNotFound apierror.
- Check the status of the BuilderInfo resource, and return the message if it isn't ready.
- Include the ClusterBuilder ready condition message in the BuilderInfo condition message if it is not ready.
No
See #2174 
@clintyoshimura @tcdowney

Improve "cf buildpacks" error responses

---

tools/tools.go

No
As of [Ginkgo v2.8.2](https://github.com/onsi/ginkgo/releases/tag/v2.8.2), "Ginkgo now includes a tools.go file in the root directory of the ginkgo package. This should allow modules that simply go get github.com/onsi/ginkgo/v2 to also pull in the CLI dependencies. This obviates the need for consumers of Ginkgo to have their own tools.go file and makes it simpler to ensure that the version of the ginkgo CLI being used matches the version of the library. You can simply run go run github.com/onsi/ginkgo/v2/ginkgo to run the version of the cli associated with your package go.mod."
No

Remove Ginkgo from tools/tools.go

---

api/repositories/app_repository.go
api/repositories/app_repository_test.go
api/repositories/task_repository_test.go
controllers/controllers/workloads/cfapp_controller.go
controllers/controllers/workloads/cfapp_controller_test.go
controllers/controllers/workloads/cfbuild_controller.go
controllers/controllers/workloads/cfbuild_controller_test.go
controllers/controllers/workloads/cftask_controller.go
controllers/controllers/workloads/cftask_controller_test.go
job-task-runner/controllers/status.go
job-task-runner/controllers/status_test.go
kpack-image-builder/controllers/buildworkload_controller.go

[#2166]
Improved `reason` on korifi resources
- Removed `Running` status condition from `cfApp`. The actual place to verify that the App processes are running is to look at the CFProcess objects or the pods that they scheduled.
- Renamed `Staged` status condition on `cfApp` to `Ready`. `Ready` actually indicates that a valid droplet is assigned to the App. That droplet might have just been staged, or it might be an old droplet that was reassigned to the App. It would be more accurate to say that the App is Ready instead. An app would start as Ready false and then become Ready true when a valid droplet ref is assigned.
- Updated `cfbuild` resource to have `BuildRunning` & `BuildNotRunnning` as reasons for `Staging` condition. `BuildFailed` & `BuildSucceeded` for `Succeeded` status …

Improve `reason` on korifi resources

---

README.helm.md
helm/korifi/api/configmap.yaml
helm/korifi/controllers/configmap.yaml
helm/korifi/values.schema.json
helm/korifi/values.yaml
scripts/assets/values-template.yaml

No
LogLevel was introduced into the helm configmaps without exposing it correctly in the values.yaml and values schema. This PR makes those changes, restricts the valid values to 'info' and 'debug', and updates the docs.
No

Integrate logLevel with helm configuration

---

tests/crds/README.md
tests/crds/crds_suite_test.go
tests/crds/crds_test.go

#1566
This PR adds a new test suite that uses the kubernetes API to drive korifi (via kubectl). For now it only tests org creation.
No
Run the new tests locally against a kind cluster and verify that they pass
@clintyoshimura @tcdowney

Add the crds test suite to test CRD-based workflows

---

.github/ISSUE_TEMPLATE/chore.yml

The chore label already makes it clear enough that this is a chore. Clicking on the label filters by it. Looks like the name prefix is redundant.

Remove the "[Chore]:" prefix of chore titles

---

Makefile
tools/config_change_watcher_test.go

No
We noticed the tools test was not included in CI, so we have added this.
This causes CI to fail since the config_change_watcher test has a problem. We have commented this out and this should be fixed.
No
@gcapizzi
@cloudfoundry/wg-cf-on-k8s-korifi-approvers

Run tests in the tools package

---

controllers/controllers/workloads/cftask_controller.go
controllers/controllers/workloads/cftask_controller_test.go
controllers/controllers/workloads/package.go
controllers/controllers/workloads/suite_test.go

No
This PR adds test coverage for happy-path CFTask event recording.
No
Run a task and see the `TaskWorkloadCreated` event on the CFTask once the resource has been reconciled.
@acosta11

Add tests for CFTask reconciliation events

---

controllers/controllers/services/cfservicebinding_controller.go
controllers/controllers/services/cfservicebinding_controller_test.go
tests/e2e/apps_test.go
tests/e2e/assets/golang/main.go
tests/e2e/e2e_suite_test.go
tests/e2e/service_bindings_test.go

Issue: https://github.com/cloudfoundry/korifi/issues/2285
Some service binding libraries (such as the Oauth2 connector in Spring Cloud Bindings) use a Service Binding's name as a configuration value. This does not always place nicely with the Service Instance GUID that Korifi currently sets for the Service Binding's name.
This change allows users to override the `.spec.name` property of a Service Binding during binding creation using the `cf bind-service --binding-name` parameter. If `--binding-name` is omitted then the ServiceBinding continues to use the Service Instance GUID as its name.
No, it should only impact new service bindings.
1. Push the golang test app (`tests/e2e/assets/golang`): `cf push test-app`
2. Create an UPSI: `cf cups my-upsi -p '{"secret": "credential"}'`
3. Bind the …

Set ServiceBinding .spec.name to the CFServiceBinding's displayName

---

api/authorization/token_reviewer.go
api/authorization/token_reviewer_test.go
tests/e2e/e2e_suite_test.go

#2280 
The `/whoami` endpoint returns the full ID from Service Account tokens.
No.
1. Create a Service Account (and Secret for k8s v1.24+)
2. Extract kubeconfig for SA.
3. Run `cf target` and verify that it is of the form `system:serviceaccount:<namespace>:<name>` (e.g. `system:serviceaccount:cf:my-serviceaccount`)
@akrishna90

whoami endpoint returns full serviceaccount IDs

---

api/handlers/shared.go
api/handlers/space_manifest_test.go
api/payloads/manifest.go
api/payloads/manifest_test.go
go.mod
go.sum

#2123 
See issue
No
Deploy korifi normally, hand-craft malformed app manifest file, and cf push with the manifest flag to trigger the error. Otherwise, see modified tests for specific field level errors to trigger.
@davewalter 
.
Note that we included a small change to the error message serialization from the related explore issue. Array fields no longer have a `.` before them, instead only having enclosing brackets `[]`.

Improve app manifest api validation

---

Makefile
api/main.go
api/repositories/package_repository.go
api/repositories/package_repository_test.go
api/repositories/repositories_suite_test.go
api/repositories/shared_test.go
controllers/api/v1alpha1/cfpackage_types.go
controllers/controllers/workloads/cfpackage_controller.go
controllers/controllers/workloads/cfpackage_controller_test.go
helm/korifi/controllers/cf_roles/cf_admin.yaml
helm/korifi/controllers/cf_roles/cf_space_developer.yaml
scripts/run-tests.sh

This is a prelude to #2232
This add status conditions to CFPackages.
Set initialized condition to true when:
- resource has finalizer set, and
- resource has app owner ref set.
Set ready condition to true when:
- resource has source package image set
Wait for the initialized condition in the CFPackage repo when creating a CFPackage.
Wait for the ready condition in the CFPackage repo when updating a CFPackage source image.
This will be used in the story above, where we need to expire old packages in controllers on the edge where the source image is first set.
This also improves the flake we've seen where CFPackage is not deleted in the e2e test which checks deleting an app deletes its related objects (due to a race where the package was not reconciled to set the app ownership before the …

Use status conditions on CFPackage

---

api/handlers/role_test.go
api/payloads/role.go
api/payloads/role_test.go
api/repositories/role_repository.go
helm/korifi/controllers/cf_roles/cf_org_manager.yaml

[#2279]
Allow setting roles for service accounts
- usernames of the form `system:serviceaccount:<namespace>:<name>` will be considered as service account type
- updated POST `/v3/roles` endpoint to create `Rolebindings` with subject as `Kind:ServiceAcccount` if username matches the above pattern
- updated GET `/v3/role`s endpoint to return user as `system:serviceaccount:<namespace>:<name>` if users are service accounts.
No
See issue #2279 
@Birdrock

Allow setting roles for service accounts

---

kpack-image-builder/controllers/buildworkload_controller.go

No
We are seeing flakes in google artifact registry where sometimes droplet
pushes fail due to 'config blob not found'.
This _might_ be due to us pushing and deleting the identical image very
heavily in the e2e tests.
This experimental change enables setting the current time as the build
creation date on the image, which will lead to slightly different images
each build. At the moment it seems to be stopping the flake.
No
e2e greener
@kieron-dev

Set current creation date on kpack build images

---

api/errors/errors.go
api/handlers/errors.go
api/main.go
api/routing/handler_test.go
api/routing/router.go
api/routing/router_test.go
tests/e2e/errors_test.go

#2292
This adds support for custom 404 and 405 handlers to our `routing` package. It then uses it to return well-formed CF errors.
The format of 404 and 405 errors will now be compatible with CF.
@kieron-dev

Return valid CF 404 errors

---

tools/image/client_test.go
tools/image/image_suite_test.go

No
Best effort to delete all images created during testing on real registries.
Note that repositories _are_ leaked, but being empty, we assume that is not a problem.
No
@kieron-dev

Cleanup all images after image/client tests on real registries

---

tests/crds/crds_test.go

No, @kieron-dev reported flakiness in crd tests. See
https://ci.korifi.cf-app.com//teams/main/pipelines/main/jobs/run-e2es-periodic/builds/7233
https://ci.korifi.cf-app.com//teams/main/pipelines/main/jobs/run-e2es-periodic/builds/7228
https://ci.korifi.cf-app.com//teams/main/pipelines/main/jobs/run-e2es-periodic/builds/7236
https://ci.korifi.cf-app.com//teams/main/pipelines/main/jobs/run-e2es-main/builds/661
...
Fixes flakey CRD tests
- observed that flakiness was due to the tests bailing out early without waiting `20s` for timeout.
- switched to using `wait()` on the `gexec.session` instead of a nested `Eventually` block.
- verified that when `RoleBindings` are not found we at least try for 20s before giving up.
No
Observe that we wait at least the timeout (20) seconds before bailing …

Fix flakey crd tests

---

api/handlers/build_test.go
api/presenter/build.go
api/presenter/build_test.go

#2255
Remove JSON from the handlers build test. Use selective MatchJSONPath instead, and move full JSON testing to the presenters package
No
Handlers tests remain green
@gcapizzi

Improve handlers build test

---

api/handlers/app.go
api/handlers/app_test.go
api/main.go
tests/e2e/apps_test.go

Fixes https://github.com/cloudfoundry/korifi/issues/2333
Add GET apps/packages handler
No
GIVEN I have pushed an app
WHEN I perform the following request
```
curl "https://api.example.org/v3/apps/[guid]/packages"
```
THEN I get a 200 OK response with a list of packages

Add GET apps/packages handler

---

api/authorization/namespace_permissions.go
api/authorization/namespace_permissions_test.go

No
Add missing namespace check when comparing service accounts with rolebinding subjects.
This is used to filter org listing, and for optimization when listing resources generally.
No
Fewer e2e flakes
@gcapizzi

Check service account NS when looking at rolebinding subjects

---

api/handlers/buildpack_test.go
api/presenter/buildpack_test.go

Issue: #2255
Simply handlers tests by moving json comparisons to the presenter package. Here we update the buildpack handler test.
No
@gcapizzi

Move buildpack handler test json to presenter test

---

api/handlers/buildpack_test.go
api/handlers/domain_test.go
api/presenter/buildpack_test.go
api/presenter/domain.go
api/presenter/domain_test.go

#2255
Move literal JSON testing from handlers to presenter package. In this case, do it for the domain handler test.
No
@gcapizzi

Remove literal JSON from handlers/domain test

---

api/handlers/buildpack_test.go
api/handlers/domain_test.go
api/handlers/droplet_test.go
api/handlers/handlers_suite_test.go
api/presenter/buildpack_test.go
api/presenter/domain.go
api/presenter/domain_test.go
api/presenter/droplet_test.go

#2255
Move literal JSON to the presenter package from the handlers test. This time for droplet handler
No
@gcapizzi

Move literal JSON to presenter package for handlers/droplet test

---

controllers/controllers/workloads/cftask_controller_test.go

No
The CFTask might be modified by the controller between the creation and update. So let's use patch instead of update to avoid update failing
No
@gcapizzi

Patch instead of Update in case obj modified in background

---

api/handlers/log_cache_test.go
api/presenter/log_test.go

#2255
Move full JSON testing from handlers to presenter package. This PR address the log-cache test.
No
@gcapizzi

Remove JSON from log-cache handlers test to presenter package

---

api/handlers/job.go
api/handlers/job_test.go
api/presenter/job.go
api/presenter/job_test.go

Issue: #2255
Move full JSON matching from handlers tests to presenters tests. This PR addresses job_test.
No
@gcapizzi

Move json from handlers/job_test to presenters

---

controllers/controllers/workloads/cfprocess_controller.go
controllers/controllers/workloads/cfprocess_controller_test.go
statefulset-runner/controllers/appworkload_to_stset.go
statefulset-runner/controllers/appworkload_to_stset_test.go

Follow up to issue with pod affinity ordering as env vars are also a list sensitive to ordering changes.
#2133 
Make AppWorkload and CFProcess reconciliation idempotent up to ordering of the env var lists.
No
Trigger re-reconciliation of the AppWorkload  with some frequency (by restarting the controller for instance) and see that the resource is not actually being updated. Check:
* the generation number remains consistent on the AppWorkload and its Statefulset
* the underlying Pods are not being deleted and recreated
paired w/ @tcdowney 
Note that we would also like to refactor the CFProcessController testing to more consistently detect ordering issues. And in general, we would like to have some sort of idempotency testing in place for the most important controllers. This will be a follow …

Sort env var lists

---

controllers/controllers/workloads/cforg_controller.go
controllers/controllers/workloads/cfspace_controller.go
controllers/controllers/workloads/cfspace_controller_test.go

No
When finalizing an org or space, the associated namespace is deleted,
and the finalizer is removed from the list. If the subsequent patch of
the metadata fails, we have a situation where the finalization will be
retried, but the namespace has already been deleted.
This commit ignores the now acceptable NotFound error so that
finalization can complete successfully.
No
Our clusters in CI are less frequently borked
@gcapizzi

Avoid hanging org/space finalizers

---

api/repositories/role_repository.go
api/repositories/role_repository_test.go
statefulset-runner/controllers/appworkload_to_stset_test.go

#2385
Include the service account namespace in the RoleBinding name so there is not conflicts between service accounts with the same name, but in different namespaces
no
See issue
@matt-royal

Include service account namespace in RoleBinding name

---

api/handlers/service_binding_test.go
api/presenter/service_binding.go
api/presenter/service_binding_test.go

#2255
This moves testing of the JSON output from the service binding handler tests to the service binding presenter tests.
No.
@gcapizzi

Remove literal JSON from the Service Binding handler tests

---

api/handlers/space_manifest_test.go
api/payloads/manifest_test.go

#2255
- Use standard request manipulation in a single JustBeforeEach
- Move payload tests to the payload package
No
@gcapizzi

Tidy up handlers space-manifest tests

---

api/handlers/service_route_binding_test.go

#2255
This replaces the usage of `MatchJSON` with JSON literals with `MatchJSONPath` in the Service Route Binding handler test.
No.
@gcapizzi

Remove JSON literals from the Service Route Binding handler test

---

api/handlers/task_test.go
api/presenter/task.go
api/presenter/task_test.go
api/repositories/task_repository.go
api/repositories/task_repository_test.go

#2255
- Replace CreationTimestamp with CreatedAt & UpdatedAt in TaskRecord
- Move full JSON matching from handlers/task_test to presenter package
No
@gcapizzi

Remove full JSON matching from handlers/task_test

---

api/handlers/user_test.go
api/presenter/user_test.go

#2255
Move full JSON testing from handlers to presenter package for the user handler.
No
@gcapizzi

Move full JSON matching from handlers to presenter tests for user

---

api/handlers/whoami_test.go
api/presenter/identity_test.go

#2255
Move full JSON matching from handlers tests to presenters package
No
@gcapizzi

Remove full JSON matching from whoami handlers test to presenter package

---

helm/korifi/templates/cert-mgr-issuer.yaml

No
We noticed that the Cert Manager self-signed issuer in the Helm templates was being created in the default namespace. While this worked (perhaps because Cert Manager falls back to the issuer in the default namespace if it cannot find one in the same namespace as the certificate request), it seems better to put the issuer in the same namespace as the rest of Korifi to indicate that Korifi is the one using it. We also want to avoid polluting the default namespace.
No

Put the selfsigned-issuer in the release NS

---

controllers/controllers/workloads/env/vcap_services_builder.go
controllers/controllers/workloads/env/vcap_services_builder_test.go

#2417
- when spec.serviceLabel is set on the ServiceInstance, we want to set "label" on the service itself in addition to placing it under a key with the same name.
No
#2417
@acosta11

Add custom label field to VCAP_SERVICES

---

kpack-image-builder/controllers/buildworkload_controller.go
kpack-image-builder/controllers/buildworkload_controller_test.go
kpack-image-builder/controllers/suite_test.go

#2440
A single kpack.Image is now used for an app. It is named using the app GUID.
Each `cf push` now creates a new kpack.Build on the kpack.Image. The buildworkload status is updated from the corresponding kpack.Build using the ImageGeneration label on the build which must match the image generation now stored in the buildworkload labels.
We have changed the reconciliation of buildworkloads to always update the kpack.Image, whether it exists or not, since we need to reuse existing images.
No. Although we are changing the relationship between buildworkloads and kpack images / builds.
Existing BuildWorkloads will have a 1:1 relationship with a kpack.Image. The kpack.Image will have 1 kpack.Build generated from the initial `cf push`. It may have subsequent builds generated in the background …

Use a single kpack.Image per CFApp for optimal build caching

---

helm/korifi/kpack-image-builder/role.yaml
kpack-image-builder/controllers/buildworkload_controller.go
kpack-image-builder/controllers/buildworkload_controller_test.go

#2455
Introduce a finalizer onto the kpack image builder BuildWorkload controller to delete kpack.Build resources when a BuildWorkload is deleted. Match on image and image generation labels.
No
See story
@gcapizzi

Delete corresponding kpack.Builds when buildworkloads are deleted

---

api/repositories/app_repository.go
api/repositories/domain_repository.go
api/repositories/droplet_repository.go
api/repositories/org_repository.go
api/repositories/package_repository.go
api/repositories/process_repository.go
api/repositories/route_repository.go
api/repositories/service_binding_repository.go
api/repositories/service_instance_repository.go
api/repositories/service_instance_repository_test.go
api/repositories/shared.go
api/repositories/space_repository.go
api/repositories/task_repository.go

#2422
- Use standard filtering for ListDomains
- Apply common filtering logic to ListDroplets
- Apply common filtering logic to ListOrgs
- Apply common filtering logic to ListPackages
- Use common filter logic in ListProcesses
- Use common filter logic for ListRoutes
- Use common filter logic for ListServiceBindings
- Use common filtering logic for ListServiceInstances
- Use common filter logic for ListSpaces
- Use common filter logic for ListTasks
- Deduplicate set include checking
No
@gcapizzi

Standard repository filtering

---

helm/korifi/controllers/configmap.yaml

No
Combine the Korifi controller ConfigMap configuration files. They are currently still separated as they were before all the controllers were unified. There doesn't seem to be a reason to keep them separate anymore.
No
All tests pass
@Birdrock @julian-hj

Combine the Korifi controller ConfigMap configuration files

---

kpack-image-builder/controllers/buildworkload_controller.go
kpack-image-builder/controllers/buildworkload_controller_test.go
kpack-image-builder/controllers/suite_test.go

Issue: https://github.com/cloudfoundry/korifi/issues/2441
Co-authored-by: Danail Branekov <danailster@gmail.com>
#2441
If two quick updates to kpack.Image for an app mean the kpack controller
misses the first change, detect this and mark the skipped build workload
as failed.
Also, set ginkgo's `Eventually` and `Consistently` timeouts to 10
seconds as skipped buildworkload tests occasionally flake with timeouts
when the system is under load (e.g. when `check-everything` is being
run)
No
1. Push an app
2. When push succeeds, simultaneously try to push different sources for the same app (tmux can be [configured](https://stackoverflow.com/questions/16325449/how-to-send-a-command-to-all-panes-in-tmux) to send keys to multiple panes)
3. One of the two pushes should fail with
```
Staging app and …
```

Mark skipped buildworkloads as failed

---

.gitignore
README.helm.md
controllers/config/config.go
controllers/main.go
helm/korifi/controllers/configmap.yaml
helm/korifi/values.schema.json
helm/korifi/values.yaml
kpack-image-builder/controllers/builderinfo_controller_test.go
kpack-image-builder/controllers/buildworkload_controller.go
kpack-image-builder/controllers/buildworkload_controller_test.go
kpack-image-builder/controllers/kpack_build_controller_test.go
kpack-image-builder/controllers/suite_test.go

Indirectly #1784
- Address flakes
- Give cluster builder a chance to be ready before failing a build
When the cluster builder is not ready, we examine the LastTransitionTime on the status condition. If it is more recent than the last N seconds (configurable by the new property `builderReadinessTimeout`, we retry the reconciliation. We fail as before otherwise.
New controllers config property builderReadinessTimeout.
Make the cluster builder unready and see how cf pushes fail
@kieron-dev

Configurable grace period for builder readiness

---

tests/e2e/apps_test.go
tests/e2e/droplets_test.go
tests/e2e/e2e_suite_test.go
tests/e2e/packages_test.go
tests/e2e/processes_test.go
tests/e2e/routes_test.go
tests/e2e/tasks_test.go

#2355 
Rename variables used to configure apps used in e2e tests
No, this is a test interface change that does not get used by default.
Get an app that pushes successfully and set the newly named env var to point at that app directory. Run E2E tests and see that pass.
@matt-royal

Use appropriate name for default app in e2e

---

kpack-image-builder/controllers/buildworkload_controller.go
kpack-image-builder/controllers/buildworkload_controller_test.go
tests/e2e/e2e_suite_test.go
tests/helpers/eventually_should_hold.go

- Set build worload droplet to latest kpack build image
#2469
Set build worload droplet to latest kpack build image. This way cf restage will
update the droplet of existing apps. This can be useful when kpack triggered a
rebuild as a result of chaged stack or buildpack versions
No
See story

Use latest kpack build image on restage

---

scripts/install-dependencies.sh

No
Removing code that said it can be removed after contour deploys envoy > 1.23. The kbld fix now fails, and contour deploys envoy 1.25 so the fix can be removed.
No
CI works.

Remove install contour apple silicon hack from install deps script

---

api/repositories/image_repository.go
api/repositories/image_repository_test.go
helm/korifi/values.schema.json

#2466
There are certain [rules](https://github.com/distribution/distribution/blob/main/docs/spec/api.md#overview) that apply to the naming of oci images. This commit is a best effort to detect invalid image refs and warn the user as early as possible
- The korifi helm chart does a basic pattern check so rule out invalid
fromat for `global.containerRepositoryPrefix` as well as `kpackImageBuilder.builderRepository`.
- The pattern check is insufficient, because it cannot detect whether
the final length of the image name after potentially stripping the
host is too long. It is simply too hard to tell if the
containerRepositoryPrefix starts with a host name, in which case it
should not be counted in the check
- [This code](https://github.com/cloudfoundry/korifi/blob/6d138abcee5564cdc17b670d6118e …

Do not accept invalid repo names and prefixes

---

helm/korifi/kpack-image-builder/role.yaml
kpack-image-builder/controllers/buildworkload_controller.go
kpack-image-builder/controllers/buildworkload_controller_test.go
tests/e2e/apps_test.go
tests/e2e/e2e_suite_test.go

Story: #2474
Bug: #1784
Allow use of app's buildpack or buildpacks field in the manifest, and `cf push -b BUILDPACK_NAME ...`
This uses a kpack.builder with the same stack and store as the default cluster builder, but with a limited order list matching the requested buildpacks. A builder is created if one doesn't already exist in the namespace (CF space). Deterministic naming is used to guarantee uniqueness for the particular buildpack ordering. Builders are owned by buildworkloads, so will be garbage collected when all referencing buildpacks are deleted.
Note there is a kpack issue, where changing a builder on an image does not trigger a new build. This code watches for that condition and fails the buildworkload with a message, relayed to the user, that modifying the source and …

Allow selection of buildpacks from those contained in the default store

---

helm/korifi/values.schema.json

Related to #2486 
This PR updates the pattern for the `builderRepository` value in the Helm chart to allow an empty value since it is optional.
No
Users are able to deploy without a value for `builderRepository`.
@julian-hj

Fix the builderRepository pattern

---

tests/e2e/assets/golang/go.mod

No
Reduce the golang version required by the golang test asset to 1.19. This version is still supported and not all installs have a kpack that's new enough to include golang 1.20.
No
PR checks pass

Reduce the golang version to 1.19 to support older kpack installs

---

tests/e2e/README.md
tests/e2e/apps_test.go
tests/e2e/processes_test.go

No
- Provide a way to change the buildpack used with the default app
- Also add a README.md for the e2e tests
- Also loosen assertion for /v3/app/:guid/processes endpoint to test for inclusion of the web process instead of ONLY the web process existing.
No
Tests still pass
@davewalter

Provide a way to change the buildpack used with the default app

---

kpack-image-builder/controllers/buildworkload_controller.go
kpack-image-builder/controllers/buildworkload_controller_test.go

#2474
Kpack would not trigger a build if the builder in the kpack image changes and latest build had failed (e.g. push with buildpack A that fails and then try to push with buildpack B) - see https://github.com/pivotal/kpack/issues/1198
In order to work around this kpack limitation we annotate the latest build with `image.kpack.io/additionalBuildNeeded` annotation that forces kpack into creating a new build thus picking up the builder specified in the kpack image.
No
1. `cf push dorifi -p ~/workspace/korifi/tests/e2e/assets/golang -b paketo-buildpacks/java` -> See it failing
2. `cf push dorifi -p ~/workspace/korifi/tests/e2e/assets/golang -b paketo-buildpacks/go` -> see it starts a new build and eventually succeed
@kieron-dev

Trigger a kpack build if requested buildpack changes

---

go.mod
go.sum

There is a dependabot alert https://github.com/cloudfoundry/korifi/security/dependabot/14
Update docker/distribution to v2.8.2 to resolve CVEs
No.
Run tests as normal
@davewalter

Update github.com/docker/distribution to v2.8.2

---

kpack-image-builder/controllers/buildworkload_controller.go
kpack-image-builder/controllers/buildworkload_controller_test.go

#2474
The builder pushes its image to the same registry as droplets, so use the same service account for the registry credentials as for droplets.
No
Set up a kpack cluster builder using a different registry for its build image and with a different service account for credentials from the droplet registry.
See that `cf push my-app -b MY_BUILDPACK` works.
@gcapizzi

Use correct service account when creating custom kpack builders

---

api/Dockerfile
api/main.go
api/remote-debug/Dockerfile
controllers/Dockerfile
controllers/main.go
controllers/remote-debug/Dockerfile
scripts/assets/korifi-debug-kbld.yml
scripts/assets/korifi-kbld.yml
version/version.go

#2537
This introduces the `version` package and sets the value of its
`Version` top-level variable using `-ldflags` and `Dockerfile` args.
No
Deploy Korifi, look at the api and controllers logs - they should mention the version
@gcapizzi

Introduce the version package

---

scripts/assets/korifi-debug-kbld.yml
scripts/assets/korifi-kbld.yml
scripts/deploy-on-kind.sh

rather than hardcoding it
Co-authored-by: Kieron Browne <kbrowne@vmware.com>
#2537
Compute Korifi version by looking at git tags instead of hardcoding it to `9999`. Thus we would get a realistic version in the local development scenario
No
Deploy korifi, look at logs, see a reasaonable version there
@kieron-dev

Compute Korifi version based on git tags

---

controllers/controllers/workloads/cforg_controller.go
controllers/controllers/workloads/cfspace_controller.go

No
Requeue performs a rate limited retry, probably exponential, so we may wait for too long before detecting org/space deletion has resulted in the namespace deletion. RequeueAfter is not rate limited.
No
CI should stop taking so long to delete the cf namespace.
@kieron-dev

Use RequeueAfter when waiting for namespace deletion

---

controllers/api/v1alpha1/cfapp_webhook_test.go
controllers/api/v1alpha1/webhook_suite_test.go
controllers/main.go
controllers/webhooks/version/suite_integration_test.go
controllers/webhooks/version/version_webhook.go
controllers/webhooks/version/version_webhook_test.go
helm/korifi/controllers/manifests.yaml
tests/e2e/service_instances_test.go
version/version.go

https://github.com/cloudfoundry/korifi/issues/2537
Implemented as a generic webhook that adds an annotation with the Korifi
version at the time of the object creation.
No
Create a Korifi object (such as CFApp), see it is annotated with the Korifi version
@gcapizzi

Annotate all Korifi objects with creation version

---

controllers/controllers/networking/cfdomain_controller.go
controllers/controllers/workloads/cfapp_controller.go
controllers/controllers/workloads/cfpackage_controller.go

No
It turns out that controller runtime appplies an exponential backoff
strategy for both error and requeue reconciliation results: https://github.com/kubernetes-sigs/controller-runtime/blob/30eae58f1b984c1b8139dd9b9f68dd2d530ed429/pkg/internal/controller/controller.go#L315-L335
This commit uses RequeueAfter on every korifi object finalization to
avoid potentially slowing down object deletion exponentially
No
Green tests

Optimize korifi resource finalization

---

controllers/controllers/networking/cfroute_controller.go
controllers/controllers/networking/cfroute_controller_test.go
controllers/controllers/services/cfservicebinding_controller.go
controllers/controllers/workloads/cfapp_controller.go
controllers/controllers/workloads/cfbuild_controller.go
controllers/controllers/workloads/cfbuild_controller_test.go
controllers/controllers/workloads/cftask_controller.go
kpack-image-builder/controllers/buildworkload_controller.go
scripts/deploy-on-kind.sh
statefulset-runner/controllers/appworkload_to_stset.go
statefulset-runner/controllers/pdb.go

No.
This PR updates the controllers to use `SetControllerReference` to set the owner reference for created resources, instead of `SetOwnerReference`. This has the benefit of setting the `BlockOwnerDeletion` flag in the owner reference to true.
No.

Use SetControllerReference where possible

---

api/repositories/deployment_repository.go
api/repositories/deployment_repository_test.go
controllers/webhooks/version/version_webhook.go
controllers/webhooks/version/version_webhook_test.go
go.mod
helm/korifi/controllers/cf_roles/cf_admin.yaml
helm/korifi/controllers/cf_roles/cf_space_developer.yaml
helm/korifi/controllers/manifests.yaml
version/version.go
version/version_suite_test.go
version/version_test.go

- Disallow rolling upgrades for appworkloads <= v0.7.1
- Use webhook to reset the version annotation if removed
#2537
Check the korifi creation version annotation on the appworkload and reject deployment creation if version <= 0.7.1.
Also extend the version annotation hook so that it restores the previous version if an update removes it.
No
Push an app on korifi v0.7.1.
Upgrade to latest korifi.
`cf restart --strategy=rolling` and see it fail.
`cf restart`
`cf restart --strategy=rolling` and see it pass.
@gcapizzi

Disallow rolling strategy for appworkloads <= v0.7.1

---

scripts/assets/kind-config.yaml

No
- Ephemeral Containers have been promoted to GA as of Kubernetes 1.27 and this feature gate has been removed See: https://github.com/kubernetes/kubernetes/pull/111402
- Having it set prevents Kind clusters from starting successfully with versions >= 1.27
~Korifi devs using `deploy-on-kind.sh` to deploy to older Kind cluster versions may no longer have ephemeral debug containers enabled.~ Actually they likely will. It has defaulted to `true` since K8s 1.23. (Search for "EphemeralContainers" here: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/)
This does not impact users running Korifi.
Run `deploy-on-kind.sh` and have it create a Kind cluster with K8s >= 1.27.
@davewalter

Remove EphemeralContainers feature gate from Kind config

---

.github/workflows/test-pr.yml
controllers/controllers/workloads/cfspace_controller.go

No.
This PR protects the CFSpace controller against unusual reconciliation issues:
- Deleting the root "cf" namespace could cause problems if the CFSpace controller propagates the deletion of service accounts before the CFApps have been deleted.
- Update the finalize function to remove the finalizer if the CFSpace namespace is not found.
No.
1. Deploy Korifi.
2. Push an app.
3. Delete the root "cf" namespace.
4. Confirm that the namespace is successfully deleted.

Protect against unusual CFSpace reconciliation issues

---

controllers/controllers/workloads/cfapp_controller_test.go
controllers/controllers/workloads/cfbuild_controller_test.go

No
Create the cfapp in `JustBeforeEach` so that nested `BeforeEach`es can
configure the app before it has been created. Thus we avoid the
CFApp controller noticing the app and populate `lastStopAppRev` with
`CFAppRevisionKey`
No
N/A

Fix flake: when status.lastStopAppRev is not empty [It] doesn't set it

---

api/errors/errors.go
api/errors/errors_test.go
api/handlers/app_test.go
api/handlers/buildpack_test.go
api/handlers/handlers_suite_test.go
api/handlers/log_cache_test.go
api/handlers/org_test.go
api/handlers/package_test.go
api/handlers/process_test.go
api/handlers/role_test.go
api/handlers/route_test.go
api/handlers/service_binding_test.go
api/handlers/service_instance.go
api/handlers/service_instance_test.go
api/handlers/space_manifest_test.go
api/handlers/task_test.go
api/payloads/app.go
api/payloads/buildpack.go
api/payloads/domain.go
api/payloads/package.go
api/payloads/process.go
api/payloads/role.go
api/payloads/route.go
api/payloads/service_binding.go
api/payloads/service_instance.go
api/payloads/task.go

#2301, #2306, #2308
- Relax expectErrorResponse to accept regexes
- Allow `per_page` and `page` query params to all list endpoints
No.
@gcapizzi

Allow page parameter in list endpoints

---

api/handlers/app_test.go
api/handlers/domain_test.go
api/payloads/domain.go
api/payloads/domain_test.go
api/payloads/lifecycle.go
api/payloads/log.go
api/payloads/metadata.go
api/payloads/metadata_test.go
api/payloads/payloads_suite_test.go
api/payloads/relationship.go
api/payloads/relationship_test.go
api/payloads/shared.go

#1996
Validate domain payloads with `jellydator/validation`
also:
- move validation tests to the playloads package
- test metadata and relationships independently in order to reduce
duplication
No
Green tests

Validate domain payloads with jellydator

---

api/handlers/droplet.go
api/handlers/droplet_test.go
api/payloads/build.go
api/payloads/build_test.go
api/payloads/droplet.go
api/payloads/droplet_test.go
api/payloads/metadata.go

#1996
- Use jellydator to validate build create payloads
- Use jellydator to validate droplet payloads
No
Everything works as before

Use jellydator for build and droplet payloads

---

controllers/api/v1alpha1/shared_types.go
controllers/config/config.go
controllers/config/config_test.go
controllers/controllers/shared/index.go
controllers/controllers/workloads/cfapp_controller.go
controllers/controllers/workloads/cforg_controller_test.go
controllers/controllers/workloads/cfspace_controller.go
controllers/controllers/workloads/cfspace_controller_test.go
controllers/controllers/workloads/shared.go
controllers/controllers/workloads/suite_test.go
controllers/main.go
helm/korifi/controllers/role.yaml
helm/korifi/job-task-runner/runner-rbac.yaml
helm/korifi/kpack-image-builder/service-account.yaml
helm/korifi/statefulset-runner/runner-rbac.yaml

No
This PR makes a number of changes to avoid problems uninstalling a korifi deployment:
- Don't propagate helm or kapp labels and annotations to secrets, role bindings or service accounts that are propagated by korifi. This avoids situations where kapp would attempt to tear down the propagated resources directly instead of letting the deletion of the root namespace trigger the process in a predictable order. We haven't seen similar problems for helm, but it seemed appropriate to also remove its labels/annotations, as the resources in question aren't managed by helm either.
- Add the `cloudfoundry.org/propagate-deletion` annotation for service accounts and role bindings. When this is present and set to `"false"`, then deleting the resource in the root namespace or an org namespace won't …

Avoid issues uninstalling korifi or deleting the root ns

---

controllers/coordination/name_registry.go
controllers/coordination/name_registry_test.go

#2587
This addresses a flake where a resource is created and quickly renamed in our integration tests. We suspect the 2 etcd instances are not yet sync'ed when we attempt to modified the lease created with the original resource name. We get a NotFound error. By allowing a limited number of retries with an exponential backoff, we should deal with this condition.
No
Expect not to see the error seen in the issue.

Retry acquiring lease lock when NotFound encountered

---

controllers/coordination/name_registry.go
controllers/coordination/name_registry_test.go
controllers/webhooks/duplicate_validator.go
controllers/webhooks/networking/cfroute_validator.go
controllers/webhooks/services/cfservicebinding_validator.go
controllers/webhooks/services/cfserviceinstance_validator.go
controllers/webhooks/workloads/cfapp_validator.go
controllers/webhooks/workloads/cforg_validator.go
controllers/webhooks/workloads/cfspace_validator.go
helm/korifi/controllers/manifests.yaml

No
Our name duplication validating webhooks are side-effecting: i.e. they create and modify leases. If a user runs a request in dry-run mode, the actual update on the resource will not be performed, and our lease updates should also not take place. So we now check the dry-run mode in the name-registry.
This PR also reverts the change to retr take the lease lock, as that does not fix our flake problem.
No
@gcapizzi

Don't modify leases when in dry-run mode

---

api/handlers/handlers_suite_test.go
api/payloads/payloads_suite_test.go
api/repositories/role_repository_test.go
api/repositories/task_repository_test.go
controllers/controllers/workloads/cfbuild_controller_test.go
controllers/controllers/workloads/cfprocess_controller_test.go
kpack-image-builder/controllers/buildworkload_controller_test.go
tests/e2e/e2e_suite_test.go
tests/helpers/cache_syncing_client.go

No.
This PR updates test helpers to call GinkgoHelper() as a better way to help Ginkgo compute failure locations. See [the docs](https://onsi.github.io/ginkgo/#mental-model-how-ginkgo-handles-failure) for details.
No, just test changes.
Deploy and run the tests.

Use GinkgoHelper in tests

---

api/payloads/manifest.go
api/payloads/manifest_test.go

The validator was always raising the following error when random-route was specified:
`"default-route and random-route may not be used together"`
This change makes it so that it only errors when both default-route and random-route are set to true.
Related Slack discussion: https://cloudfoundry.slack.com/archives/C0297673ASK/p1687556306576749
No
Fixes a bug where any manifest containing `random-route: true` would cause an error. Minimal example:
```yaml
--- 
applications: 
- name: dora
random-route: true
```
```
15:57 $ cf push node
Pushing app node to org o / space s as cf-admin...
Applying manifest file /Users/tdowney/go/src/github.com/cloudfoundry/cf-acceptance-tests/assets/node/manifest.yml...
Updating with these attributes...
applications:
- name: node
random-route: true …
```

Fix manifest validation for `random-route`

---

controllers/controllers/workloads/cforg_controller_test.go
controllers/controllers/workloads/cfspace_controller_test.go

#1935
- tests to ensure that the loggin is wired up correctly were looking for a log message indicating that a finalizer finished finalizing, which wasn't happening in the context of the test.
- Since we only care that we are getting log messages from the helper, this commit changes the test to look for a string indicating the source of the log message, rather than a specifc message that only happens when the finalizer succeeds.
No
- run tests
@davewalter @acosta11

Make controller logging tests more robust

---

tools/k8s/reconcile_test.go

Nope
The tools/k8s unit tests had a couple of failures. The gomega error matcher can't match on wrapped errors unless the type of the expected object matches the wrapped error type. This commit fixes it.
No
`ginkgo tools/k8s`

Fix failing unit tests

---

README.helm.md
api/repositories/task_repository_test.go
controllers/config/config.go
controllers/config/config_test.go
helm/korifi/controllers/configmap.yaml
helm/korifi/values.schema.json
helm/korifi/values.yaml
kpack-image-builder/controllers/buildworkload_controller.go
kpack-image-builder/controllers/buildworkload_controller_test.go
kpack-image-builder/controllers/suite_test.go
scripts/assets/values-template.yaml

#2634
- This value is used to set the size of the persistent disk we allocate for image caching when building images with kpack.
- it defaults to 2GiB which is similar to the 2GB default size that kpack allocates.
- The new setting allows customers building large applications to take advantage of caching.
Note: It's a little odd that the staging parameters are in the `api` section of the configuration, but if we want to eventually plumb these through the CFBuild object so that different builds can have different sized caches, then it *kind of* makes sense. I decided that it would be better to put the caching value next to the other staging resources than it would be to put  some of the configuration in the api section and other things in the `controllers` section. Ultimately, we might …

Add `buildCacheMB` helm chart value

---

api/handlers/build.go
api/handlers/deployment.go
api/handlers/service_binding.go
api/repositories/pod_repository.go
controllers/controllers/workloads/cfspace_controller.go
statefulset-runner/api/v1/pod_webhook.go

#1929
This PR eliminates the use of Sprintf in log messages. It moves injected values to named values instead.
No.
Deploy and run tests. Check the logs and confirm that the intended data is still being recorded.

Eliminate use of Sprintf in log messages

---

api/handlers/job.go
api/handlers/job_test.go
api/main.go
api/presenter/job.go
api/presenter/job_test.go
api/repositories/org_repository.go

#2605 
Return status of org deletion based on underlying CFOrg resource
No
See issue.
paired w/ @davewalter

Implement org deletion job endpoint

---

controllers/controllers/workloads/cforg_controller_test.go
controllers/controllers/workloads/cfspace_controller_test.go

No
The test that awaits for the namespace finalized log has often timed
out on CI. Increase the timeout to 30 seconds (from the default 10)
No
No flakes

Fix org/space deletion flakes

---

kpack-image-builder/controllers/buildworkload_controller.go
kpack-image-builder/controllers/buildworkload_controller_test.go

#2645
Custom kpack builders (the ones that are created on the fly for build
workloads with buildpacks specified) are shared by build workloads
that have the same set of buildpacks. Therefore, setting
ControllerReference from the build workload to the builder is incorrect
as the ControllerReference can only be set once.
This PR sets simple owner references to custom kpack builds instead.
No
See bug description

Build workloads do not own custom kpack builders via ControllerReference

---

helm/korifi/kpack-image-builder/role.yaml
kpack-image-builder/controllers/buildworkload_controller.go
kpack-image-builder/controllers/buildworkload_controller_test.go
kpack-image-builder/controllers/suite_test.go

#2634
We set build cache size on kpack `Images`, but if we already have an `Image`, and we try to change the buildCacheMB setting, redeploy Korifi, and then repush an app, the operation will fail if the storage class doesn't support resize, because kpack will try to modify the persistent disk. This change checks the storage class and deletes the `Image` if resizing isn't supported.
No
#2634
@davewalter

handle non-resizable storage classes for build cache

---

.golangci.yml
Makefile
api/actions/manifest/normalizer.go
api/actions/manifest/normalizer_test.go
api/authorization/testhelpers/client_cert.go
api/config/config.go
api/config/config_test.go
api/errors/errors.go
api/handlers/deployment.go
scripts/helmdoc/main.go
tests/helpers/cache_syncing_client.go
tests/helpers/cert_auth_header.go
tests/helpers/eventually_should_hold.go
tests/matchers/wraps_error.go

#1599
Include `gosec` and `staticcheck` as part of `make lint`.
Adding them here means it will be run as part of `scripts/check-everything.sh`, github actions on a PR, and `run-tests-main` on concourse.
No
See unsafe code get rejected in PR testing

Introduce gosec and staticcheck as part of the linting suite

---

tests/e2e/e2e_suite_test.go

No
Our mitigation against the GKE/GAR UNKNOWN_BLOB error is to pre-push the apps we push in the e2e tests. However, we ended up with different droplets when using `cf push` to those created in the e2e code.
The difference turned out to be omitting file permissions when we zipped the source in e2es. So this PR sets the file mode while zipping.
No
See UNKNOWN_BLOB flakes reduce / stop
@gcapizzi

Include filemode when zipping source in e2es

---

README.helm.md
api/config/config.go
api/config/config_test.go
api/handlers/build_test.go
api/payloads/app.go
api/payloads/build.go
controllers/api/v1alpha1/cfbuild_types.go
controllers/config/config.go
controllers/config/config_test.go
helm/korifi/api/configmap.yaml
helm/korifi/controllers/configmap.yaml
helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfbuilds.yaml
helm/korifi/values.schema.json
kpack-image-builder/controllers/buildworkload_controller.go
kpack-image-builder/controllers/buildworkload_controller_test.go
kpack-image-builder/controllers/suite_test.go

#2651 
Allows Operators to limit ephemeral disk used during staging
- these limits are set on the kpack image/build.
- `api.stagingRequirements.diskMB` from helm value is now considered as limits set by the platform operator.
- updates the description of `StagingDiskMB` in the CFBuild CRD to say its a "request" instead of "limit".
No
See #2651

Operator can limit ephemeral disk used during staging

---

controllers/config/config.go
controllers/config/config_test.go
helm/korifi/controllers/configmap.yaml
kpack-image-builder/controllers/buildworkload_controller.go
kpack-image-builder/controllers/buildworkload_controller_test.go
kpack-image-builder/controllers/suite_test.go

#2654
Allow operator to configure the staging resources limits. Passes through the MemoryMB configuration to the underlying kpack build pod in the kpack-image-builder controller.
No. Only breaking changes are internal to the controller configmap, which we do not expect operators to manually edit or provide themselves.
See issue.
paired w/ @davewalter

Operator can configure limit of staging MemoryMB

---

api/handlers/job.go
api/handlers/job_test.go
api/main.go
api/repositories/app_repository.go
api/repositories/app_repository_test.go
tests/e2e/apps_test.go
tests/e2e/orgs_test.go
tests/e2e/spaces_test.go

https://github.com/cloudfoundry/korifi/issues/2606
- Get rid of `handlers.DefaultDeletionRepositories`
- Wait for deletion jobs to complete in e2e tests
- Implement job for app deletions
No
See story
@gcapizzi

App deletion job

---

controllers/config/config.go
controllers/config/config_test.go
helm/korifi/controllers/configmap.yaml
helm/korifi/values.schema.json
helm/korifi/values.yaml
kpack-image-builder/controllers/buildworkload_controller.go
kpack-image-builder/controllers/buildworkload_controller_test.go
kpack-image-builder/controllers/suite_test.go

#2682 
Revert the changes that set resource limits on the kpack build pods, instead opting to configure requests.
No, only the internal controller configmap interface is updated.
See issue.
paired w/ @davewalter 
Added a note to the refactor issue dev notes about the difficulty we had reasoning about the exercising the different configuration options in the controller test suite.

Do not configure staging resources by default

---

api/repositories/org_repository.go
api/repositories/org_repository_test.go

#2605
The GetDeletedAt method now delegates to GetOrg. This is important since
orgs are special from rbac point of view since in order to know if we
have permission in an org we have to have role bindings to some role in
that org. This is why GetOrg is implemented via List-ing orgs and
filtering by guid. Not following that pattern results in any user seeing
any orgs.
No
See https://github.com/cloudfoundry/korifi/issues/2605#issuecomment-1636472656
@gcapizzi

Fix GetDeletedAt for orgs

---

helm/korifi/controllers/crds/korifi.cloudfoundry.org_appworkloads.yaml
helm/korifi/controllers/crds/korifi.cloudfoundry.org_builderinfos.yaml
helm/korifi/controllers/crds/korifi.cloudfoundry.org_buildworkloads.yaml
helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfapps.yaml
helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfbuilds.yaml
helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfdomains.yaml
helm/korifi/controllers/crds/korifi.cloudfoundry.org_cforgs.yaml
helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfpackages.yaml
helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfprocesses.yaml
helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfroutes.yaml
helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfservicebindings.yaml
helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfserviceinstances.yaml
helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfspaces.yaml
helm/korifi/controllers/crds/korifi.cloudfoundry.org_cftasks.yaml
helm/korifi/controllers/crds/korifi.cloudfoundry.org_runnerinfos.yaml
helm/korifi/controllers/crds/korifi.cloudfoundry.org_taskworkloads.yaml

No
Bump kubebuilder version annotation in crds
this is what one gets when running `make generate`
No
N/A

Bump kubebuilder version annotation in crds

---

api/repositories/org_repository.go
api/repositories/org_repository_test.go

[#2605]
Before this change, the job endpoint would say that an org was deleted as soon as the CFOrg finalizer removed their role binding from the Org namespace. We now fetch the CFOrg directly to determine if it's done deleting. If it isn't deleting, then we will use GetOrg to determine if the user has access to the org
No
Follow AC for the issue
@davewalter @gcapizzi @georgethebeatle

Actually wait for the CFOrg to be deleted in job endpoint

---

tests/e2e/e2e_suite_test.go

No
Allow the user to change the Eventually timeout in e2e tests via env var
No
No change to behavior. For environments where Eventually statements frequently time out, setting the env var to a higher value should resolve the problem
@davewalter

Make the e2e eventually timeout configurable via env var

---

controllers/webhooks/networking/cfroute_validator.go
controllers/webhooks/networking/cfroute_validator_test.go

#2705
This PR updates the route validator to only validate that a domain exists on creation. We only need to validate the domain on route creation as we do not allow users to change the domain reference on an existing route. Validating the existence of the domain on update can block app deletion if the domain has already been deleted.
No.
See the A/C in the issue.
@matt-royal

Fix app deletion when updating route destinations

---

scripts/deploy-on-kind.sh

No
When using deploy-on-kind we default to using the local registry. In
case we want a custom registry we should export the following vars:
DOCKER_SERVER
DOCKER_USERNAME
DOCKER_PASSWORD
REPOSOTORY_PREFIX
KPACK_BUILDER_REPOSITORY
In the INSTALL.kind.md we advise that people use dockerhub as the
registry, but setting DOCKER_SERVER to index.docker.io would result in a
wrong image-registry-credentials secret as the .dockerconfigjson wants
https://index.docker.io/v1/ as the host name. On the other hand
REPOSOTORY_PREFIX should be `index.dpcker.io/username/ and
KPACK_BUILDER_REPOSITORY should be
`index.docker.io/username/kpack-builder`, i.e. they do not have the
https scheme and the /v1 path suffix. The docker hub config json is very
picky about the server name and we need special treatment for …

Fix deploy-on-kind with docker hub as registry

---

api/payloads/service_binding.go
api/payloads/service_binding_test.go
api/repositories/service_binding_repository.go
api/repositories/service_binding_repository_test.go
tests/e2e/e2e_suite_test.go
tests/e2e/service_bindings_test.go

#2318
Filter service bindings via label selectors when listing
No
see story
@gcapizzi

Filter service bindings via label selectors when listing

---

README.helm.md
helm/korifi/controllers/post-install-app-domain.yaml
helm/korifi/kpack-image-builder/post-install-builderinfo.yaml
helm/korifi/kpack-image-builder/pre-delete-builderinfo.yaml
helm/korifi/statefulset-runner/post-install-runnerinfo.yaml
helm/korifi/values.schema.json
helm/korifi/values.yaml

Currently, Korifi cannot be installed via helm chart in air-gapped environments, as a hard-coded dockerhub  image is used for the helm jobs

make the image for the jobs configurable

---

tests/e2e/helpers/fail_handler.go

No
Fix line number reporting on an e2e test failure
Our fail handler wrapper was not skipping enough stack frames
No
N/A

Fix line number reporting on an e2e test failure

---

api/handlers/service_instance_test.go
api/payloads/service_instance.go
api/payloads/service_instance_test.go
api/repositories/service_instance_repository.go
api/repositories/service_instance_repository_test.go
tests/e2e/service_instances_test.go

#2692
This PR makes it possible to filter a list of service instances by their guids
No
- Create a couple of services
- `cf curl /v3/service_instances?guids=<service-instance-guid1>,<service-instance-guid2>`
- see the result only contains the two service instances with the guids above
@kieron-dev

Support listing service instances by guid

---

Makefile
README.helm.md
README.md
helm/korifi/kpack-image-builder/cluster-builder.yaml
helm/korifi/values.schema.json
helm/korifi/values.yaml
scripts/assets/values-template.yaml

- Ubuntu Bionic Beaver 18.04 left general support in April 2023 and mainline CF has switched to cflinuxfs4 which is based on Jammy Jellyfish 22.04 LTS
- See https://www.cloudfoundry.org/blog/jammy-jellyfish-cloud-foundry/ for more details on that.
No
This change updates our Helm template to install a stack based off of Ubuntu Jammy Jellyfish since Bionic is now at its end-of-life.
Since this is a change to the base image that apps build and run with there may be subtle difference. However, this should be very similar to the differences that apps might encounter when moving from `cflinuxfs3` to `cflinuxfs4` and there are dedicated Slack channels on CF Slack related to this (e.g. [#bosh-jammy](https://app.slack.com/client/T02FL4A1X/C02M2R39Y8Z)).
I don't expect there to be a major impact to …

Update default stack to Ubuntu Jammy Jellyfish

---

controllers/coordination/integration/integration_suite_test.go

No
Use uncached client in the name registry integration test
The name registry is an utility that is used in the context of
controllers which in case of outdated cache just retry reconciliation.
However, the integration test is not such a context, therefore using a
caching client does not make sense. Furthermore, doing so could cause
flakes due to a cache miss, for example https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-main/builds/950
No
N/A

Use uncached client in the name registry integration test

---

tests/e2e/e2e_suite_test.go
tests/helpers/fail_handler/handler.go
tests/smoke/smoke_suite_test.go

CurrentSpecReport().FailureMessage() seems to be empty in the context of
a fail handler.
Co-authored-by: Georgi Sabev <georgethebeatle@gmail.com>
No
Pass the correct failure message to the fail handler so that it can parse the droplet guid and print the build logs for debugging
No
When the e2ec suite fails with a droplet not found error, there should be a section quoting the parsed droplet guid and printing related logs

Pass failure message from fail handler to hooks

---

.github/workflows/test-pr.yml
Makefile

No
There is a CI build failure though: https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-e2es-pr/builds/1997
Fix `build-dorifi` to work with golang 1.21.0: `-C` flag is now required to be the first on the command line
No
Green CI

Fix `build-dorifi` to work with golang 1.21.0

---

INSTALL.EKS.md
INSTALL.kind.md
INSTALL.md
README.helm.md
api/Makefile
helm/korifi/api/configmap.yaml
helm/korifi/api/deployment.yaml
helm/korifi/api/ingress-cert.yaml
helm/korifi/api/rbac.yaml
helm/korifi/api/role.yaml
helm/korifi/api/service.yaml
helm/korifi/controllers/configmap.yaml
helm/korifi/controllers/deployment.yaml
helm/korifi/controllers/ingress-cert.yaml
helm/korifi/controllers/post-install-app-domain.yaml
helm/korifi/controllers/rbac.yaml
helm/korifi/controllers/service.yaml
helm/korifi/job-task-runner/runner-rbac.yaml
helm/korifi/kpack-image-builder/cluster-builder.yaml
helm/korifi/kpack-image-builder/post-install-builderinfo.yaml
helm/korifi/kpack-image-builder/pre-delete-builderinfo.yaml
helm/korifi/kpack-image-builder/service-account.yaml
helm/korifi/statefulset-runner/post-install-runnerinfo.yaml
helm/korifi/statefulset-runner/runner-rbac.yaml
helm/korifi/templates/_helpers.yaml
helm/korifi/templates/admin-user.yaml
helm/korifi/values.schema.json
helm/korifi/values.yaml
scripts/assets/values-template.yaml
scripts/deploy-on-kind.sh

#2650
Cleanup the Helm values to make them more understandable for operators. The api.builderName parameter does not seem to be used and the yaml that Helm generated was the same after it was removed. The api.lifecycle.stagingRequirements parameter was moved to global.stagingRequirements because both api and controllers use those parameters.
no
All tests pass
@acosta11 
- Include any links to related PRs, issues, stories, slack discussions, etc... that will help establish context.
- Is there anything else of note that the reviewers should know about this change?
- This project follows the Cloud Foundry [Code of Conduct](https://www.cloudfoundry.org/code-of-conduct/)
-->

Cleanup Helm values

---

tests/e2e/e2e_suite_test.go
tests/e2e/orgs_test.go
tests/helpers/cert_auth.go
tests/helpers/k8s.go

#2519
Check kubernetes server version from within the test
Thus we simplify e2e tests setup
No
E2E tests passing

Check kubernetes server version from within the test

---

tests/e2e/e2e_suite_test.go

No
When the `CSR_SIGNING_DISALLOWED` env var is set, tests that require
certificate authentication are skipped. Useful when running tests
against clusters where CSR signing is not allowed, such as EKS.
No
* Set the `CSR_SIGNING_DISALLOWED` env var
* Run e2e tests against e.g. EKS
* See tests succeed

Configure whether cert authentication is supported

---

scripts/create-new-user.sh
tests/e2e/orgs_test.go
tests/helpers/k8s.go

No
Remove cluster version check
- Kubernetes 1.22 is already end of life
- Also improve test description
No
N/A

Remove redundant cluster version check in e2e tests

---

helm/korifi/controllers/tls-cert-delegation.yaml

#2807 
Correcting template when using `api.expose`; not all contour resources get turned off causing the deployment to fail.
no
Install Korifi into a kubernetes cluster that does not have contour installed. See ticket for more.

Adding "if" test of `api.expose` around tls-cert-delegation.yaml.

---

tests/e2e/e2e_suite_test.go

No, but it is related to #2784.
This PR updates the E2E tests to check the value of the `CSR_SIGNING_DISALLOWED` env var. Concourse always creates the env var in the running container, so it will always be found, which will always cause the tests to be skipped.
No.
Confirm that running the E2E tests with the `CSR_SIGNING_DISALLOWED` env var set to anything except "true" does not skip the certificate authentication tests.

Check the value of CSR_SIGNING_DISALLOWED

---

controllers/controllers/networking/cfdomain_controller.go
controllers/controllers/networking/cfroute_controller.go
controllers/controllers/services/cfservicebinding_controller.go
controllers/controllers/services/cfserviceinstance_controller.go
controllers/controllers/shared/index.go
controllers/controllers/workloads/build/cf_build_controller.go
controllers/controllers/workloads/cfapp_controller.go
controllers/controllers/workloads/cforg_controller.go
controllers/controllers/workloads/cfpackage_controller.go
controllers/controllers/workloads/cfprocess_controller.go
controllers/controllers/workloads/cfspace_controller.go
controllers/controllers/workloads/cftask_controller.go
job-task-runner/controllers/taskworkload_controller.go
kpack-image-builder/controllers/builderinfo_controller.go
kpack-image-builder/controllers/buildworkload_controller.go
kpack-image-builder/controllers/kpack_build_controller.go
statefulset-runner/controllers/appworkload_controller.go
statefulset-runner/controllers/appworkload_controller_test.go
statefulset-runner/controllers/runnerinfo_controller.go
statefulset-runner/controllers/runnerinfo_controller_test.go
statefulset-runner/controllers/suite_test.go
tools/k8s/reconcile.go
tools/k8s/reconcile_test.go

No
Setup a logger in the patching reconciler and inject it into the context that is passed to concrete object reconcilers. This way object reconcilers can just use that logger and not bother setting it up themselves.
This PR is a response to @davewalter's [comment](https://github.com/cloudfoundry/korifi/pull/2829#issuecomment-1693866828). Dave, could you please review this one?
No
Controllers logs appear
@davewalter

Setup logger in context in the patching reconciler

---

api/handlers/app_test.go
api/payloads/app.go
api/payloads/app_test.go
api/repositories/app_repository.go
api/repositories/app_repository_test.go
api/repositories/shared_test.go
controllers/webhooks/workloads/cfapp_validator.go
controllers/webhooks/workloads/cfapp_validator_test.go

https://github.com/cloudfoundry/korifi/issues/2796
Return an error when updating app lifecycle type
Thus making the lifecycle type immutable for both cf api and kubectl
users
No
See story

Return an error when updating app lifecycle type

---

tests/e2e/spaces_test.go

https://github.com/cloudfoundry/korifi/issues/2862
The `space.apply_manifest` job endpoint is stubbed to always return
`HTTP 200`. As the app env vars secret might not have been created yet,
we put the app env vars expectations in `Eventually` to let the app
controller process the app and create the secret
No
Flake fixed

Put app env vars expectations in `Eventually`

---

api/repositories/package_repository.go
api/repositories/package_repository_test.go
controllers/api/v1alpha1/webhook_suite_test.go
controllers/controllers/workloads/build/cf_build_controller.go
controllers/controllers/workloads/build/cf_build_controller_test.go
controllers/controllers/workloads/suite_test.go
controllers/main.go
controllers/webhooks/finalizer/suite_integration_test.go
controllers/webhooks/version/suite_integration_test.go
controllers/webhooks/workloads/cfapp_validator.go
controllers/webhooks/workloads/cfapp_validator_test.go
controllers/webhooks/workloads/cfpackage_validator.go
controllers/webhooks/workloads/cfpackage_validator_test.go
controllers/webhooks/workloads/suite_integration_test.go
helm/korifi/controllers/manifests.yaml
tests/e2e/builds_test.go
tests/e2e/packages_test.go

#2797
Error when package type does not match app type
* Check that the package type matches the app type when creating the
package via the API
* Do not error on package type and app lifecycle type mismatch when
creating the CFPackage with kubectl. This is to ensure that kubectl
users can create CFPackages that reference apps that do not yet exist
* Do not allow changing the package type
* Fail the CFBuild if CFPackage type and CFApp lifecycle type mismatch.
This way kubectl users would in the end get the mismatch error.
No
See story

Package type validation

---

api/handlers/space_test.go
api/payloads/space.go
api/payloads/space_test.go

No
Support filtering spaces by guid. This is needed by the cf routes command
No
The cf routes command succeeds

Support filtering spaces by guid

---

scripts/run-tests.sh
tests/crds/crds_suite_test.go
tests/crds/crds_test.go
tests/helpers/k8s.go
tests/smoke/smoke_suite_test.go
tests/smoke/smoke_test.go

#2788
This PR cleans up the test env vars:
- Smoke tests now create an admin service account when required.
- Standardise on API_SERVER_ROOT for the API address.
- Standardise on APP_FQDN for the app domain.
- Always skip SSL validation.
- Always use https.
Only in tests.
All the tests pass.

Cleanup test env vars

---

controllers/controllers/workloads/build/cf_build_controller_test.go
controllers/controllers/workloads/build/suite_test.go

No
This flake has occurred a couple of times during the weekend. It was
most probably caused by the cfbuild controller seeing the build success
status too soon, causing it to not delegate to the delegate reconciler
even once. Changing the test to wait for the first invocation of the
delegate reconciler before patching the build status to successfuls
state would prevent this problem. Then it would be safe to assert that
the delegate call count remains stable.
Also  renamed the fakeStatusCondition to delegateInvokedCondition for
clarity
Link to failed build: https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/12261#L6500636d:59
No
Green tests

Fix a CI flake in cfBuild controller tests

---

api/handlers/service_binding.go
api/handlers/service_binding_test.go

#2179
Mask forbidden as not found error in service binding handler
No

Mask forbidden as not found error in service binding handler

---

tests/crds/crds_test.go

No
Org deletion is generally a bit slow and causes CRD tests to flake
frequently. Bumping timeout should address that
No
N/A

Bump delete org timeout in CRD tests

---

README.helm.md
helm/korifi/api/rbac.yaml
helm/korifi/controllers/rbac.yaml
helm/korifi/values.schema.json
helm/korifi/values.yaml

No
This value would allow the korifi api and controller images to be pulled from a
private registry. This can be useful in corporate environments if an internal
mirror registry is being used as well as in environments with no internet.
No
N/A

Introduce a systemImagePullSecrets helm value

---

docs/known-differences-with-cf-for-vms.md

https://github.com/cloudfoundry/korifi/issues/2913
As discussed in https://github.com/cloudfoundry/korifi/issues/2913 there is a difference in the Korifi behaviour during a rolling update compared to CF on VMs. That is why, I think that it makes sense to document this at the moment.
No
Docs change

Extend korifi diff CF docs with container lifecycle

---

tests/crds/crds_suite_test.go
tests/crds/crds_test.go
tests/e2e/e2e_suite_test.go
tests/helpers/cf.go
tests/helpers/eventually.go
tests/helpers/k8s.go
tests/smoke/smoke_suite_test.go
tests/smoke/smoke_test.go

No
Instead of specifying cutom timeouts in `Eventually`, configure the
default eventually timeout and polling interval consistently across
e2e suites.

Configure eventually timeouts in e2e tests

---

controllers/controllers/workloads/env/vcap_services_builder.go
kpack-image-builder/controllers/buildworkload_controller.go
kpack-image-builder/controllers/buildworkload_controller_test.go

No
This test awaits for the build workload reconciler to notice that the
builder is not ready:
* if the builder status is unknown, the build workload status is also
set to unknown
* if the builder is not ready, the workload redy status is set to false
In either case, test should assert that the build worklod consistently
does not become ready (i.e. its redy status is either nil, or false)
before making the builder ready.
No
The test does not flake

Allow ready status to equal false when builder not ready

---

kpack-image-builder/controllers/buildworkload_controller.go
kpack-image-builder/controllers/buildworkload_controller_test.go

https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/12802
Previously we used `builderReadyCondition.IsFalse()` to check whether
the builder is ready. However, `IsFalse` returns `false` when the
condition is `nil` which is not what we want - when the ready condition
is `nil` we should consider that the builder is not ready.
Instead, we now use `builderReadyCondition.IsTrue()` which only returns
`true` if the ready condition is set, and its status is `True`.
We also change the way we check for builder ready timeout - we base the
check on the build workload creation time instead of the builder ready
status condition transition time as the condition itself might be nil.
No
Passing kpack image builder

Use `builderReadyCondition.IsTrue()` to check readiness

---

INSTALL.kind.md
INSTALL.md
scripts/installer/Dockerfile
scripts/installer/install-korifi-kind.yaml

https://github.com/cloudfoundry/korifi/issues/2895
Introduce a k8s job definition that when run on a kind cluster would install Korifi dependencies and latest Korifi release. This also involves a Dockerfile for the job image.
No
Install Korifi on kind following INSTALL.kind.md

Korifi installer for kind clusters

---

api/authorization/testhelpers/auth_provider.go

No
We have observed the following flakes:
```
+-------+----------------------------------+-----------------------------------------------------
| Ended | Job                              | Url
+-------+----------------------------------+-----------------------------------------------------
| 2h    | main/run-tests-periodic          | https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/13087
| 134d  | main/run-tests-periodic          | https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/9873
| 275d  | main/run-tests-periodic          | https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/6213
| 287d  | main/run-tests-periodic          | …
```

Auth provider server accepts unhandler requests

---

controllers/api/v1alpha1/webhook_suite_test.go
controllers/controllers/networking/suite_test.go
controllers/controllers/workloads/build/suite_test.go
controllers/controllers/workloads/suite_test.go
controllers/main.go
controllers/webhooks/finalizer/suite_integration_test.go
controllers/webhooks/version/suite_integration_test.go
controllers/webhooks/workloads/suite_integration_test.go
tests/helpers/test_env.go

https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-e2es-eks-pr/builds/1312
Webhooks validate create/modify requests, therefore they have to work on
the actual object state and not a cached version.
The following flake demonstrates that seeing an outdated state may
result into create failure.
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-e2es-eks-pr/builds/1312
No

Use uncached client for webhooks

---

scripts/run-tests.sh

No
This is needed so that we can see the thread dump when we SIGQUIT long
running tests (some tests are currently timing out after 40+ minutes)

Set the ginkgo output-interceptor-mode to none

---

controllers/controllers/workloads/cfpackage_controller_test.go

No
The flaky test tries to check that the package cleaner has been called
for the app that the test package belongs to. However the package
cleaner is shared accorss the whole workloads suite, meaning that the
package controller can be triggered for other apps' packages. Perhaps
this is what was causing the flake:
- The test waits for a new call of the cleaner (eventually call count is
bumped)
- Then the test checks that the cleaner was called for the app owning
the test package, but the app is not the expected one because some
other test dealing with packages is running in parallel
Putting both checks under the same eventually clause will make the test
retry until both conditions are true. We have to also iterate over all
calls starting from the first recorded one up to …

Fix flake: https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/13588

---

tests/smoke/smoke_suite_test.go

No
Print api logs on smoke test failures

Print api logs on smoke test failures

---

controllers/controllers/workloads/cfpackage_controller_test.go

Fix: https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/13846
We need to check if any of the subsequent calls to Clean is cleaning the
app under test, not just the first one

Fix: https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/13846

---

tests/e2e/domains_test.go

https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-e2es-eks-periodic/builds/5518
Delete domain test waits for the deletion job
It is incorrect to perform checks on domain routes while the domain is
being deleted.
No

Delete domain test waits for the deletion job

---

tests/smoke/smoke_suite_test.go

https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-e2es-main/builds/1022
Using `Expect`s in the fail handler could lead into the fail handler
retriggering itself in case of the expectation failure. Instead of using
`Expect`s we just log the error and return from the handler
No
Smoke tests complete

Avoid `Expect` in the smoke test fail handler

---

tests/smoke/smoke_suite_test.go

#3061
Print cforg namespace in case of a smoke test failure.
Hopefully this would give us more information why org deletion times out
in smoke tests
No

Print cforg namespace in fail handler

---

scripts/installer/install-korifi-kind.yaml
scripts/installer/kbld.yaml
scripts/installer/run-locally.sh

#3053
- Introduce utility script to run installer locally
- Set `networker.gatewayClass=contour` in installer
No
Kind installer works

Set `networker.gatewayClass=contour` in installer

---

api/actions/process_stats.go
api/actions/process_stats_test.go
tests/assets/golang/main.go

https://github.com/cloudfoundry/korifi/issues/3082
Looking at the terminated state of a container is not reliable as this
state does not last very long. Once a workload container exits
(regardless of the exit code) consistently, k8s puts the container into
`Waiting` state with reason `CrashLoopBackOff` until the scheduler
starts it again. As this is an exponential backoff, this state tends to
last longer and longer if the app keeps crashing.
With the previous implementation of looking at the `Terminated` state we
could never see the instance as `crashed` in the `cf app` output when we
intentionally kept crashing it.
No
See story

Consider a container crashed when in CrashLoopBackOff

---

api/payloads/manifest.go
api/payloads/manifest_test.go

Co-authored-by: Danail Branekov <danailster@gmail.com>
#3050
Both manifest service formats are now supported:
```
services:
- my_service
- name: your_service
```
No
See story

Support manifest services without name

---

helm/korifi/templates/gateway.yaml

No.
We had a single reference to `korifi-gateway` not helm templated.
No.
- install with a namespace specified. 
- Observe that we have a broken reference to the non-existent `korifi-gateway` namespace.
@davewalter @Birdrock

Fix hardcoded namespace

---

INSTALL.md

No
DISCLAIMER: This is purely optional. Feel free to simply discard this PR if you want to stick to static provisioning of contour.
I was not able to get static provisioning of contour with a custom domain and certificates to work. The instructions are confusing and I am far from an expert. However, dynamic provisioning was quite simple and straightforward. 
No. Documentation only.
1. Follow the dynamic provisioning directions in the install guide. 
2. Verify load balancer DNS in the install guide.
NOTE: I did not change the static provisioning instructions as I was not able to get them to work.

add dynamic provisioning for contour

---

api/handlers/package_test.go
api/payloads/package.go
api/payloads/package_test.go
api/repositories/package_repository.go
api/repositories/package_repository_test.go

No
The latest version of the CF CLI (v8.7.8) introduced a change where the 'StagePackage' function now uses the "guids" query parameter when listing packages for an app. Korifi did not support this parameter, even though it claimed to support API v3.117.0.
This call is made by the CLI when an application is pushed with the `--no-start` option and then started with `cf start`.
No. It fixes a compatibility issue with CF CLI v8.7.8.
Install CF CLI v8.7.8 and attempt to `cf push` an application.
@acosta11

Add "guids" as a valid package list filter

---

api/repositories/app_repository.go
controllers/controllers/workloads/cfapp_controller.go
controllers/controllers/workloads/env/vcap_app_builder.go
controllers/controllers/workloads/env/vcap_app_builder_test.go
controllers/controllers/workloads/env/vcap_services_builder.go
controllers/controllers/workloads/env/vcap_services_builder_test.go
controllers/controllers/workloads/k8sns/reconciler.go
controllers/controllers/workloads/k8sns/reconciler_test.go

#3125
According to the [docs](https://github.com/kubernetes/api/blob/48ed98046a81320c5ec6681f614e31892035edef/core/v1/types.go#L6841):
```
stringData allows specifying non-binary secret data in string form.
It is provided as a write-only input field for convenience.
All keys and values are merged into the data field on write, overwriting any existing values.
```
This means that it is not always safe to use StringData, since existing
keys will never be removed
No

Prefer using Data over StringData in secrets

---

job-task-runner/controllers/integration/taskworkload_controller_test.go
job-task-runner/controllers/taskworkload_controller.go
statefulset-runner/controllers/appworkload_to_stset.go
statefulset-runner/controllers/appworkload_to_stset_test.go

N/A
Presently Korifi places a seccompProfile on the container, while this works for the container when you want to layer in a service mesh such as Istio you run into a few issues. During the Korifi installation, if you follow the install guide as described it has you place a `pod-security.kubernetes.io/enforce=restricted` on the root namespace, then this cascades to created organization and space namespaces. When this happens, for a space that desires to enable the Istio service mesh, the `istio-init` and `istio-validation` sidecar containers are started with the default seccompProfile which results in the entire pod being unable to be scheduled due to two containers wanting additional privileges. Istio has support for it's own custom, chained CNI which removes the need for the additional …

Add a seccompProfile to the pod

---

README.helm.md
controllers/config/config.go
controllers/main.go
helm/korifi/controllers/configmap.yaml
helm/korifi/values.schema.json
helm/korifi/values.yaml
job-task-runner/controllers/integration/suite_test.go
job-task-runner/controllers/integration/taskworkload_controller_test.go
job-task-runner/controllers/taskworkload_controller.go
job-task-runner/controllers/taskworkload_controller_test.go
statefulset-runner/controllers/appworkload_to_stset.go
statefulset-runner/controllers/appworkload_to_stset_test.go
statefulset-runner/controllers/integration/suite_test.go

No
PR https://github.com/cloudfoundry/korifi/pull/3156 changes the
definition of statefulset/job by setting the seccomp profile on the
statefulset/job template spec. This causes all workload pods to get
automatically restarted when upgrading from previous Korifi releases.
We introduce new `statefulsetRunnerTemporarySetPodSeccompProfile` and
`jobTaskRunnerTemporarySetPodSeccompProfile` helm values whose default
value would prevent altering existing statefulsets and jobs.
Those will be probably removed in future releases.
No, it fixes a breaking change
No restart of workload pods on Korifi upgrade
@shanman190

Configure whether to set workload pod seccompProfile

---

api/Dockerfile
api/repositories/app_repository_test.go
controllers/api/v1alpha1/cfservicebinding_types.go
controllers/api/v1alpha1/zz_generated.deepcopy.go
controllers/controllers/services/cfservicebinding_controller.go
controllers/controllers/services/cfservicebinding_controller_test.go
controllers/controllers/services/credentials/credentials.go
controllers/controllers/services/credentials/credentials_test.go
controllers/controllers/workloads/cfapp_controller_test.go
controllers/controllers/workloads/env/builder.go
controllers/controllers/workloads/env/vcap_services_builder.go
controllers/controllers/workloads/env/vcap_services_builder_test.go
docs/architecture-decisions/0016-user-provided-service-credentils.md
helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfservicebindings.yaml

#2900
Fix VCAP_SERVICES env var format: service binding credentials are objects, not string key value pairs
No

Credentials in VCAP_SERVICES are objects

---

tests/smoke/smoke_suite_test.go

#3061
Add debugging information to investigate flake
No

Print all org namespaces on org deletion timeout

---

api/routing/router_test.go
tests/smoke/smoke_suite_test.go
tests/smoke/smoke_test.go

#3061
Smoke tests have been failing frequently because org deletion times out.
Previous debug output showed that the timeout is caused by org namespace
being not deleted because of app pods do not disappear and remaining
pods are in phase `Pending` (e.g. see
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/deploy-korifi-acceptance/builds/802)
We have found a [k8s bug
report](https://github.com/kubernetes/kubernetes/issues/121435) that
pending pods cannot be deleted. We suspect that in those cases the
cluster is just being slow.
In order to workaround that bug, we simply ignore the org deletion exit
code as org deletion is not really in the focus of the smoke tests. Org
deletion is covered in details by e2e tests.
Also, delete the related debug logs as they are not needed …

Ignore org deletion exit code in AfterSuite

---

controllers/controllers/workloads/cfprocess_controller.go
controllers/controllers/workloads/cfprocess_controller_test.go

https://github.com/cloudfoundry/korifi/issues/3081
Adding MEMORY_LIMIT environment variable into cfprocess generation to ensure compatibility with classic CF behavior
no, should not.
kubectl get appworkload -n -o yaml
Check, that spec.env has a variable with Name: "MEMORY_LIMIT"

adding MEMORY_LIMIT environment variable to CFAppWorkload in cfprocess controller

---

api/handlers/app.go
api/handlers/app_test.go

https://github.com/cloudfoundry/korifi/issues/2357
I'm adding a new API endpoint that will reply the requested feature and show it as not enabled. This is for consistency with classical CF. See more details in https://github.com/cloudfoundry/korifi/issues/2357
Not as far as I can see. 
GIVEN I have pushed an app to korifi
WHEN I GET /v3/apps/:guid/features/:name
THEN I see the following response
```
HTTP/1.1 200 OK
Content-Type: application/json
{
"name": "feature-name",
"description": "fature description",
"enabled": false
}
```
@danail-branekov @georgethebeatle 
<!--
I stole most of this from our internal fork but changed the "PATCH" there into "GET" as requested in the Issue.

added fake getAppFeature in apps handler and related tests for issue-2357

---

tests/crds/crds_suite_test.go

No
Whenever the test setup is creating an org/space, it should wait for the
ready condition, rather than expecting a non empty status guid

Fix a flake in CRDs tests

---

controllers/controllers/networking/cfroute_controller.go
controllers/controllers/networking/cfroute_controller_test.go
controllers/webhooks/networking/cfroute_validator.go
controllers/webhooks/networking/cfroute_validator_test.go

https://github.com/cloudfoundry/korifi/issues/3210
We want to allow users to define CF Routes with uppercase letters and still have them Work. This is required for CATS compatibility.
not that I have seen or that it would be expected.
cf create-route apps-127-0-0-1.nip.io --hostname TEST123 
should work and create a valid HTTPRoute like: test123.apps-127-0-0-1.nip.io 
@danail-branekov @georgethebeatle

added fix to allow usage of uppercase letters

---

tests/crds/apps_test.go
tests/crds/crds_suite_test.go
tests/e2e/e2e_suite_test.go
tests/helpers/fail_handler/handler.go
tests/helpers/fail_handler/pods.go
tests/smoke/smoke_suite_test.go

No
- Print pod logs since the start of the test run. It is not sufficient
to print logs since the current spec start time, because this way we
are missing logs emitted during the test setup
- Print the logs of all builds in the space under test. There should
generally be one build per test space, so we do not expect this to go
out of hand.
- We are doing this in order to address the following flake:
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-e2es-eks/builds/677
The test is failing to get the latest kpack build with empty name. We
suspect that the name is empty because the build failed and kpack did
not update the Image resource. We hope that with this improvement we
will be able to see what is causing the build failure next time this
test flakes.
No

Improve fail handlers in e2e tests

---

tests/crds/crds_suite_test.go

https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-e2es-eks-periodic/builds/7693
We are deleting the test org in background. By deleting a copy of the
org we ensure that the shared `testOrg` variable is not modified once
deletion is done. Not doing that would mess up subsequent `It`s

Avoid data pollution on tear-down

---

controllers/controllers/workloads/cfprocess_controller_test.go
controllers/controllers/workloads/env/builder.go
controllers/controllers/workloads/env/builder_test.go

https://github.com/cloudfoundry/korifi/issues/3229
Adding environment variable `CF_INSTANCE_PORTS` to workloads
not, that i expect it
- deploy an app, that prints the environment variable CF_INSTANCE_PORTS
- check that the app actually has the environment variable
@danail-branekov @georgethebeatle 
I've seen strange errors when executing `go test -v`: 12:04:37.313765   45784 reflector.go:462] pkg/mod/k8s.io/client-go@v0.29.3/tools/cache/reflector.go:229: watch of *v1.Secret ended with: an error on the server ("unable to decode an event from the watch stream: context canceled") has prevented the request from succeeding - i hope that this is some local issue...

added environment variable CF_INSTANCE_PORTS

---

api/payloads/manifest.go
api/payloads/manifest_test.go

https://github.com/cloudfoundry/korifi/issues/3231
support small letters in memory definition, analog to original CF [spec](https://v3-apidocs.cloudfoundry.org/version/3.156.0/index.html#the-manifest-schema) 
not that i'm aware of.
push an app, with memory values like:
128m
128mb
128g
128gb
128t
128tb
@danail-branekov  @georgethebeatle

adapted regex to also allow small letter m, mb, t, tb, g and gb.

---

api/repositories/app_repository.go
api/repositories/app_repository_test.go
api/repositories/conditions/await_test.go
api/repositories/service_instance_repository.go
api/repositories/service_instance_repository_test.go
controllers/api/v1alpha1/shared_types.go
controllers/controllers/services/instances/controller.go
controllers/controllers/services/instances/controller_test.go
controllers/controllers/workloads/cfprocess_controller.go
controllers/controllers/workloads/k8sns/reconciler.go
statefulset-runner/controllers/appworkload_controller.go
tools/k8s/condition_builder.go
tools/k8s/condition_builder_test.go

No
- Replace the existing CredentialSecretAvailable condition with Ready in
controller and repository
- Remove one of the two constants for the Ready condition
- The awaiter test now works with Ready condition (unimportant, but this
way we can better understand what resources are not yet using the
Ready condtion
No
Green tests

Introduce Ready condition for cfServiceInstances

---

api/handlers/info_v3.go
api/handlers/info_v3_test.go
api/main.go
api/presenter/info.go
api/presenter/info_test.go
tests/e2e/info_v3_test.go

https://github.com/cloudfoundry/korifi/issues/2914
Add initial `v3/info` endpoint that presents the fields as implmented in
https://github.com/cloudfoundry/cloud_controller_ng/blob/main/app/controllers/v3/info_controller.rb
and
https://github.com/cloudfoundry/cloud_controller_ng/blob/main/app/presenters/v3/info_presenter.rb
with some static default values for the time being.
This change is the first step in getting a working `v3/info` endpoint implementation.
The next step would be to extend Korifi via configuration to provide some dynamic content (For example the `description` field and others) to be returned by the endpoint `v3/info`.
No, it adds a new endpoint not available before.
- Switch to the Git branch.
- Setup local dev environment, `./scripts/deploy-on-kind.sh korifi`
- cf api …

Add initial /v3/info endpoint

---

controllers/controllers/workloads/cftask_controller.go

https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-e2es-eks-periodic/builds/7836
Log why an app is not ready while reconciling tasks
Hopefully this would bring more insight to troubleshoot this flake:
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-e2es-eks-periodic/builds/7836

Log why an app is not ready while reconciling tasks

---

tests/helpers/service_account.go

https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-e2es-eks/builds/690
Instead of waiting for 10 seconds the serrvice account secret to get
populated, use the default one. Test suites set it to 4 minutes by
default.

Do not use explicit timeout when creating the service account

---

api/middleware/cli_version.go
api/middleware/cli_version_test.go

No.
Allow to use most recent CF CLI pre-release versions with Korifi.
No.
Run `./scripts/deploy-on-kind.sh korifi`, use a recent pre-release version of cf cli, try to use Korifi with the pre-release cf cli and it should work with this PR.

Allow pre-release cli versions

---

docs/api.md

https://github.com/cloudfoundry/korifi/issues/2914
Document newly available v3/info API endpoint.
No.

Update `api.md` to reflect v3/info addition

---

api/repositories/app_repository.go
api/repositories/app_repository_test.go
api/repositories/conditions/await.go
api/repositories/conditions/await_test.go
api/repositories/fakeawaiter/await.go
api/repositories/shared.go
tests/e2e/e2e_suite_test.go

No
This is an attempt to fix test flakes like this one:
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-e2es-eks-periodic/builds/8092#L66377a10:1977
In this test we are pusing an app and then immediately trygin to create
a task for the pushed app. The problem is that the app may take some
time to become properly STAGED and STARTED and the test is not waiting
for the app
Having said that it is not trivial to wait for the app to become
STARTED, because of the nature of the cf v3 api: According to the
[docs](https://v3-apidocs.cloudfoundry.org/version/3.159.0/index.html#the-app-object)
the `state` field in the app response is representing the app desired
state (not the actual state). Luckily there is an endpoint for getting
the current app droplet, namely
```
GET …
```

Wait for app to become staged after droplet is set

---

scripts/install-dependencies.sh

No
6eb3943b6395d8645a4716eefe7b184e059f419f introduced a bash issue when running `./scripts/deploy-on-kind.sh korifi` more than once (on macOS Sonoma). If you run the script more than once, `TEMP_FILES` variable might be empty. With the option `set -u` an empty `TEMP_FILES` will throw an unbound error.
```bash
bash-3.2$ set -u
bash-3.2$ arr=()
bash-3.2$ echo "${arr[@]}"
bash: arr[@]: unbound variable
bash-3.2$ echo "${arr[@]-}"
bash-3.2$ exit
```
No.
To reproduce the issue, run the command `./scripts/deploy-on-kind.sh korifi` more than once.
It should exit the script with the following error:
`.../github.com/cloudfoundry/korifi/scripts/install-dependencies.sh: line 108: TEMP_FILES[@]: unbound variable`
None

Fix unbound variable error in bash

---

api/handlers/app.go
api/handlers/app_test.go
api/main.go
tests/e2e/apps_test.go

#2340 
It adds the endpoint `GET /v3/apps/:guid/processes/:type/stats` and returns the stats that are already available in the [ProcessStats](https://github.com/cloudfoundry/korifi/blob/c5ee87da875c96a9da6e58c4e01d6c554821d2c4/api/presenter/process_stats.go#L53-L65).
No
cf push an app and try to access the stats endpoint.
It should deliver the same result as `cf curl /v3/processes/:guid/stats`
None

Add initial GET /v3/apps/:guid/processes/:type/stats endpoint

---

api/repositories/buildpack_repository_test.go
api/repositories/org_repository_test.go
api/repositories/package_repository_test.go
api/repositories/repositories_suite_test.go
api/repositories/space_repository_test.go
controllers/controllers/workloads/cf_buildpack_build_controller_test.go
controllers/controllers/workloads/cforg_controller.go
controllers/controllers/workloads/cforg_controller_test.go
controllers/controllers/workloads/cfpackage_controller.go
controllers/controllers/workloads/cfpackage_controller_test.go
controllers/controllers/workloads/cfprocess_controller.go
controllers/controllers/workloads/cfprocess_controller_test.go
controllers/controllers/workloads/cfspace_controller.go
controllers/controllers/workloads/cfspace_controller_test.go
controllers/controllers/workloads/cftask_controller_test.go
controllers/controllers/workloads/env/env_suite_test.go
controllers/controllers/workloads/k8sns/reconciler_test.go
controllers/controllers/workloads/testutils/shared_test_utils.go
statefulset-runner/controllers/appworkload_controller.go
statefulset-runner/controllers/appworkload_controller_test.go
statefulset-runner/controllers/appworkload_to_stset_test.go
statefulset-runner/controllers/integration/appworkload_controller_test.go
statefulset-runner/controllers/integration/runnerinfo_controller_test.go
statefulset-runner/controllers/integration/suite_test.go
statefulset-runner/controllers/runnerinfo_controller_test.go
statefulset-runner/controllers/suite_test.go

#3237
Korifi custom resources that have their `Ready` condition set by
controllers now utilise the ready condition builder pattern we recently
came up with. The afffected resources are:
* CFPackage
* CFOrg
* CFSpace
* CFProcess
* AppWorkload
While being here,
* take the opportunity to slightly improve their tests
* use the `korifiv1alpha1.StatusConditionReady` constant wherever it
makes sense
No
No functional change

Use the ready condition builder in relevant controllers

---

README.helm.md
helm/korifi/api/deployment.yaml
helm/korifi/controllers/deployment.yaml
helm/korifi/values.schema.json
helm/korifi/values.yaml

No
Adding the `nodeSelector` and `tolerations`options to the Korifi helm chart schema.
This will allow the users to determine the assignment of the `korifi-api` and `korifi-controllers` pods on specific nodes.
Also, used together with `taints` and `tolerations`, certain nodes can be designated for Korifi `api` and `controllers` pods only.
No.
1. You need to have a Kubernetes cluster with at least 2 nodes.
2. Label one of the nodes with some label of your choice, e.g. `role=korifi-controlplane`;
3. Taint the same node with some taint of your choice, e.g. `role=korifi-controlplane:NoSchedule`;
4. Checkout this branch and install Korifi from it by adding the following settings to the helm install korifi command:
```
--set=nodeSelector.role=korifi-controlplane \
--set tolerations[0].key=role …
```

Add node selector and tolerations options into Korifi helm chart schema

---

README.helm.md
api/config/config.go
api/config/config_test.go
controllers/config/config.go
controllers/config/config_test.go
helm/korifi/api/configmap.yaml
helm/korifi/controllers/configmap.yaml
helm/korifi/values.schema.json
helm/korifi/values.yaml
scripts/deploy-on-kind.sh
scripts/installer/install-korifi-kind.yaml

#3262
The upcoming managed services support would be initially disabled by
setting the helm value to `false` (the default)
Operators should deliberately enable the flag should they want to give
the feature a try.
This change simply introduces the flag in the helm chart, there is no
implementation that uses it yet. The `deploy-on-kind` script sets it to
`true` as it is meant to be run for development purposes.
The kind installer sets it to `true` as well - whoever is installing
Korifi on kind probably just wants to play with it, therefore enabling
the experimental support does make sense.
No
See story

Introduce `experimental.managedServices.include` helm value

---

helm/korifi/kpack-image-builder/cluster-builder.yaml

No
Latest java buildpack (15.1.0) brings `ca-certificates` buildpack 3.8.2
which reports that the jammy stack is not supported. Thus the cluster
builder never becomes ready
see https://github.com/paketo-buildpacks/ca-certificates/issues/235
No
Cluster builder becomes ready

Temporarily pin java buildpack to 15.0.0 and ruby buildpack to 0.46.1

---

docs/architecture-decisions/0017-rolling-restarts.md

No
Introduce an ADR about rolling restarts. This is needed because of the confusing nature of app restarts in Korifi and its implications throughout the code base
No
N/A

Write an ADR about rolling restart

---

.github/dependabot.yml

No
Group all dependabot gomod bumps into one PR. This will significantly reducde the effort of merging dependabot dependencies

Group all gomod dependency bumps into one PR

---

api/handlers/service_broker.go
api/handlers/service_broker_test.go
api/main.go
api/middleware/disable_managed_services.go
api/middleware/disable_managed_services_test.go

No
Reject managed services requests when support is disabled via a middleware

Reject managed services requests when support is disabled

---

api/repositories/domain_repository.go

No
Returning a forbidden error upon any failure when getting the CFDomain
from the repository is simply wrong, especially in situations where
handlers are masking forbidden errors as not found.
Potentially this should give use more information to ivestigate the
flake below should it occur again
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-e2es-periodic/builds/16159
No

Do not return forbidden error on get domain failure

---

api/repositories/service_broker_repository.go

No.
Minor refactor to improve readability of code and demonstrate iterator chaining with go-functional.
No.
No functional change.
N/A.
N/A.

Use iterator chaining

---

api/handlers/fake/cfservice_broker_repository.go
api/handlers/job.go
api/handlers/service_broker.go
api/handlers/service_broker_test.go
api/main.go
api/payloads/service_broker.go
api/presenter/job.go
api/repositories/service_broker_repository.go
api/repositories/service_broker_repository_test.go
helm/korifi/controllers/cf_roles/cf_admin.yaml
tests/e2e/e2e_suite_test.go
tests/e2e/service_brokers_test.go

#3268
Implement deleting service brokers
No
See story
Also, `cf delete-service-broker` should now work

Implement `DELETE /v3/service_brokers/guid`

---

api/actions/shared/fake/cfapp_repository.go
api/actions/shared/shared.go
api/repositories/app_repository.go
api/repositories/app_repository_test.go
api/repositories/repositories_suite_test.go
api/repositories/service_instance_repository.go

No
Just `Create` or `Patch` explicitly as repositories are pretty aware of
whether the object should be created or updated

Do not use `controllerutil.CreateOrPatch` in repositories

---

api/handlers/fake/cfservice_plan_repository.go
api/handlers/service_plan.go
api/handlers/service_plan_test.go
api/payloads/service_plan.go
api/payloads/service_plan_test.go
api/presenter/service_plan.go
api/presenter/service_plan_test.go
api/repositories/service_plan_repository.go
api/repositories/service_plan_repository_test.go
controllers/api/v1alpha1/cfservice_plan_types.go
controllers/controllers/services/brokers/controller.go
controllers/controllers/services/brokers/controller_test.go
helm/korifi/controllers/cf_roles/cf_admin.yaml
helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfserviceplans.yaml
tests/e2e/e2e_suite_test.go
tests/e2e/service_brokers_test.go
tests/e2e/service_offerings_test.go
tests/e2e/service_plans_test.go

#3275
Implement updating service plan visibility
- For now `public` is the only allowd value other than `admin`, which is
the default
- Bonus: Introduce the `visibility_type` field in the service plan
resource. This makes `cf service-access` display the plan visibility
correctly

Implement POST /v3/service_plans/{guid}/visibility

---

api/payloads/service_plan.go
api/payloads/service_plan_test.go
api/presenter/service_plan.go
api/presenter/service_plan_test.go
api/repositories/service_plan_repository.go
api/repositories/service_plan_repository_test.go
tools/collections.go
tools/collections_test.go

#3278
Filter service plans by `available`
A plan is `available` when its visbility is not `admin`.
See
https://github.com/cloudfoundry/cloud_controller_ng/blob/d543a6668838174d99fdf54945398055dab5bc79/app/models/services/service_plan.rb#L88-L103
for reference

Filter service plans by `available`

---

api/handlers/service_offering.go
api/handlers/service_plan.go
api/handlers/service_plan_test.go
api/main.go
api/payloads/service_plan.go
api/payloads/service_plan_test.go
api/repositories/service_offering_repository.go
api/repositories/service_offering_repository_test.go
model/included.go
model/included_test.go
model/model_suite_test.go

#3279
Include service offerings when listing plans

Include service offerings when listing plans

---

api/handlers/service_plan.go
api/handlers/service_plan_test.go
api/main.go
api/payloads/service_plan.go
api/payloads/service_plan_test.go

#3280
Include service broker fields when listing plans
->

Include service broker fields when listing plans

---

api/payloads/service_plan.go
api/payloads/service_plan_test.go
api/repositories/service_offering_repository.go
api/repositories/service_offering_repository_test.go
api/repositories/service_plan_repository.go
api/repositories/service_plan_repository_test.go
controllers/api/v1alpha1/shared_types.go
controllers/controllers/services/brokers/controller.go
controllers/controllers/services/brokers/controller_test.go
tests/e2e/e2e_suite_test.go
tests/e2e/service_brokers_test.go
tests/e2e/service_plans_test.go

#3420
* The broker controller sets the broker name under the
`korifiv1alpha1.RelServiceBrokerNameLabel` label when reconciling
broker catalog. This is safe as upon a broker rename the controller
would reconcile its catalog again and would ammend plans/offering
labels
* The plan repository filters plans by broker name whenever the broker
names filter is specified
* While being here:
- The constant `RelServiceBrokerLabel` has been renamed to
`RelServiceBrokerGUIDLabel` to make it explicit that this is the
broker guid
- The constant `RelServiceOfferingLabel has been renamed to
`RelServiceOfferingGUIDLabel` to make it explicit that this is the
offering guid
- The value of the `RelServiceBrokerGUIDLabel` and
`RelServiceOfferingGUIDLabel` constants has the `-guid` suffix added
in order to be …

Support broker name filter when listing service plans

---

controllers/main.go
job-task-runner/controllers/integration/suite_test.go
job-task-runner/controllers/status.go
job-task-runner/controllers/status_test.go
tools/k8s/reconcile.go

No
Slight improvement of controllers logger wiring. We can save some typing if we
make the patching reconciler create the logger named after the resource baing
reconciled

Patching Reconciler names logger after recounciled resource

---

controllers/controllers/workloads/spaces/controller.go
controllers/controllers/workloads/spaces/controller_test.go

issue #3439
#3439
Label `CFSpace` namespaces with org guid via the `cloudfoundry.org/org-guid` label

Label CFSpace namespace with `cloudfoundry.org/org-guid label`

---

api/payloads/service_instance.go
api/payloads/service_instance_test.go
tests/smoke/catalog_test.go
tests/smoke/services_test.go
tests/smoke/suite_test.go

#3291
Include service plan fields when listing service instances
No
See story

Include service plan fields when listing service instances

---

controllers/controllers/services/instances/managed/controller_test.go
controllers/controllers/services/osbapi/clientfactory_test.go
controllers/controllers/services/osbapi/suite_test.go

Flakes:
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/19051
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/19049
The client factory is an utility and its tests are not executed in the
context of the controllers retry loop. Therefore, in order to avoid
flakes from k8s eventual consistency, we use `EnsurePatch` in tests
instead of `k8sClient.Patch` to ensure that the factory sees the state
of the objects the test setup creates.

Use `EnsurePatch` in OSBAPI client factory tests

---

.envrc
Makefile
api/Makefile
controllers/Makefile
job-task-runner/Makefile
kpack-image-builder/Makefile
scripts/deploy-on-kind.sh
scripts/installer/run-locally.sh
scripts/run-tests.sh
statefulset-runner/Makefile
tools/Makefile

No
* Make use of file-based rules as make targets to ensure that binaries
are only installed if not already available
* Configure `GOBIN` env var to `./bin`. Thus `go install` installs
binaries in `./bin`
* Add `GOBIN` to path
* Use simple binary names as `GOBIN` is on the `PATH`

Use make targets to install binary dependencies

---

Makefile
api/Dockerfile
api/remote-debug/Dockerfile
controllers/Dockerfile
controllers/remote-debug/Dockerfile

no
hardcoded `GOARCH` prevents local testing with `kind` when using ARM64 machine
no

Support multi-arch builds for local development

---

controllers/controllers/services/bindings/controller.go
controllers/controllers/services/bindings/controller_test.go
controllers/controllers/services/bindings/suite_test.go
controllers/controllers/services/bindings/upsi/controller.go
controllers/controllers/services/instances/upsi/controller.go
controllers/main.go

Introdce a sub-controller for user provided services that
has the responsibility to create the binding credentials secret
This refactoring makes it possible to support managed services in the
future by adding a managed services credentials sub-controller that
knows how to retrieve credentials from a broker
No

Refactor binding controller

---

tools/k8s/condition_builder.go
tools/k8s/reconcile.go
tools/k8s/reconcile_test.go

No, but a log line in a flake:
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-e2es-periodic/builds/17452#L66b8eb5f:5768
Status conditions must have non-empty reason, otherwise the patch
operation is rejected by kubernetes.
When constructing the `NotReadyError`, a reconciler might set the cause
but not be able to determine the reason. Instead of trying to adhere to
always setting the reason in the controllers, the patching reconciler
now ensures that it is defaulted to `Unknown`.
While being here, move the `NotReadyError` type into the `reconcile.go`
file - it logically makes sense to be there

Patching reconciler ensures non-empty status reason

---

controllers/controllers/services/instances/managed/controller.go

Flakes
A couple of flakes on the CI showed that a managed service might be
deprovisioned with the broker twice:
```
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/19402
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/19396
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/19358
```
Analysis showed that when the controller [requeues the reconcile event
on
finalization](https://github.com/cloudfoundry/korifi/blob/2dfdb3848bc8690e3e5be14a535ae52c46152d46/controllers/controllers/services/instances/managed/controller.go#L265),
the very same object (same generation, same resource version) could be
reconciled twice thus request deprovision the instance from the broker
twice.
In order …

Do not requeue when finalizing managed service instance

---

kpack-image-builder/controllers/buildworkload_controller.go
kpack-image-builder/controllers/buildworkload_controller_test.go

no
If an error is thrown during the [generation of droplet status](https://github.com/cloudfoundry/korifi/blob/7b38428e46429002e303e8cbd428422ce2a859d3/kpack-image-builder/controllers/buildworkload_controller.go#L268-L282), the `BuildWorkload` object ends up in a deadlock situation, where each subsequent reconciliation loop exits early and no droplet info is written.
no

Write `Succeeded` condition only after adding droplet info into `BuildWorkload` status

---

helm/korifi/templates/gateway.yaml
helm/korifi/values.schema.json
helm/korifi/values.yaml
scripts/deploy-on-kind.sh
scripts/installer/install-korifi-kind.yaml

no
This change adds new values to the Helm chart for configuring `listeners[].port` and `spec.infrastructure` properties of the Gateway object. These properties simplify local setup as well as improve integration with various components around the Gateway and it's generated resources (like passing annotations from gateway down to the generated `Service` object, which might be used by Gardener's [`external-dns-management`](https://github.com/gardener/external-dns-management) component).
no

Allow Gateway `spec.listeners[].port` and `spec.infrastructure` configuration via Helm values

---

README.helm.md
controllers/controllers/services/instances/managed/controller.go
controllers/controllers/services/instances/managed/controller_test.go
helm/korifi/values.schema.json
scripts/helmdoc/main.go

No
When the provision request fails (i.e. the broker returns a not OK
status code), we fail the service instance (set its
`ProvisioningFailedCondition` status condition). Thus the service
instance controller will not request provisioning again.
No

Fails service instance when provisioning fails

---

scripts/helmdoc/main.go

Commit a426011560e4a3f1e04cd38c4c07d1e18c68690e moved global helm values to top-level.
No
There is some reference to a property named 'global' which does not exist anymore.
No.
Run `make generate` and the file `README.helm.md` should be unmodified.

helm md generator: Remove obsolete code

---

statefulset-runner/controllers/appworkload_controller.go
statefulset-runner/controllers/appworkload_to_stset.go
statefulset-runner/controllers/appworkload_to_stset_test.go

This PR replaces the anti-affinity setting (used in the statefulset-runner) with the newer [pod topology spread constraint](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/) to distribute workloads.

Replace anti-affinity with topology spread

---

docs/known-differences-with-cf-for-vms.md

Add section about stack handling to known-differences-with-cf-for-vms.md
Feel free to correct me about that but to my understanding the current restage/staging behaviour in korifi comes with the difference to CF on VMs below, just to get that written down somewhere as @beyhan pointed me to this doc.
It might make sense to rephrase that by someone with deeper technical knowledge in the Korifi implementation and fact check it.
No
Documentation
No
Crosscheck documentation
None

Add section about stack handling differences to known differences docs

---

README.helm.md
controllers/config/config.go
controllers/main.go
helm/korifi/controllers/configmap.yaml
helm/korifi/values.schema.json
helm/korifi/values.yaml
job-task-runner/controllers/integration/suite_test.go
job-task-runner/controllers/integration/taskworkload_controller_test.go
job-task-runner/controllers/taskworkload_controller.go
job-task-runner/controllers/taskworkload_controller_test.go
kpack-image-builder/controllers/buildworkload_controller_test.go
statefulset-runner/controllers/appworkload_to_stset.go
statefulset-runner/controllers/appworkload_to_stset_test.go
statefulset-runner/controllers/integration/suite_test.go

#3164
Remove the following helm values:
* `statefulsetRunnerTemporarySetPodSeccompProfile`
* `jobTaskRunnerTemporarySetPodSeccompProfile`
Those helm values were introduced to avoid workloads restart on Korifi
upgrade. With the upcoming release workloads would be restarted by an
unrelated change anyway, so it is a convenient moment to get rid of
those.
It causes workloads restart on Korifi upgrade

Remove temporary helm values

---

helm/korifi/api/configmap.yaml
helm/korifi/controllers/configmap.yaml
helm/korifi/values.yaml
scripts/deploy-on-kind.sh
scripts/installer/install-korifi-kind.yaml

No
Rename the flag that enables experimental service support to ```
experimental.managedServices.enabled ```
The PR is intentionally marked as draft because it would fail CI chacks anyway,
as the flag is called differently in the CI scripts
The flag is already called experimentalManagedServicesEnabled in the configmap
and in the code, so let's be consistent
Enabled sounds more appropriate than include, since it is a crosscutting
feature and not a component the you can include/exclude
Yes, CI should be updated accordingly
Wdyt @danail-branekov

Rename experimental services flag

---

helm/korifi/kpack-image-builder/cluster-builder.yaml

#3362
Unpin java and ruby buildpack versions

Revert "Temporarily pin buildpacks: java to 15.0.0, ruby to 0.46.1"

---

api/presenter/service_broker_test.go
api/presenter/service_offering_test.go
api/presenter/service_plan_test.go

No.
https://cloudfoundry.slack.com/archives/C0297673ASK/p1729171006582719
When running unit tests locally, some unit tests were failing on machines with local time != UTC.
Here's an extract (some lines left out):
```
Summarizing 3 Failures:
[FAIL] Service Offering [It] returns the expected JSON
.../api/presenter/service_offering_test.go:75
[FAIL] Service Broker [It] returns the expected JSON
.../api/presenter/service_broker_test.go:57
[FAIL] Service Plan ForServicePlan [It] returns the expected JSON
.../api/presenter/service_plan_test.go:100
expected
"created_at": "1970-01-01T01:00:01+01:00",
to match JSON of
"created_at": "1970-01-01T00:00:01Z",
first mismatched key: "created_at"
```
No.

tests: Fix time comparison by using UTC timezone

---

tests/helpers/test_env.go

CI flakes
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/19700
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/19695
We have been seeing test env failing to bind to a port quite
frequently, especially that now we are starting test env on every `It`
rather than once per suite.
This change retries starting test env - we hope that this should make
such failures disappear

Retry starting testenv

---

controllers/api/v1alpha1/cfservicebinding_types.go
controllers/controllers/services/bindings/controller.go
controllers/controllers/services/bindings/controller_test.go

Also, annotate the `CFServiceBinding` object with the `korifi.cloudfoundry.org/service-instance-type` annotation. This helps for determining the type of the instance it references without looking up the instance.
fixes #3294

Configure servicebinding.io bindings for managed services

---

api/repositories/app_repository_test.go
controllers/api/v1alpha1/cfserviceinstance_types.go
controllers/controllers/services/instances/managed/controller.go
controllers/controllers/services/instances/managed/controller_test.go
controllers/controllers/services/instances/managed/suite_test.go
controllers/controllers/workloads/env/vcap_services_builder.go
controllers/controllers/workloads/env/vcap_services_builder_test.go
helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfserviceinstances.yaml

Service bindings in `VCAP_SERVICES` are by default grouped within a key that matches their instance type (`user-provided` or `managed`)
fixes #3295

Use service instance type for VCAP_SERVICES

---

controllers/controllers/services/instances/managed/controller_test.go

No, but CI flakes:
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/19906
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/19908
Do not verify that provision requests are performed only <Up>once
In ditributed systems it is hard to guarantee that a resource state is
reconciled exactly once. Managed service instances controllers try to
achieve that by setting the `ProvisionRequested` status condition but
occasionally they might get reconcile a state where this status
condition is not set twice.
We have seen such situations in the following flakes:
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/19906
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/bui …

Do not assume instance provisioning is performed exactly once

---

api/payloads/manifest.go
api/payloads/manifest_test.go

#3546
disk_quota can be a floating point number under CF for VMs.
I've looked up cloudcontroller_ng and found
https://github.com/cloudfoundry/cloud_controller_ng/blob/9a1dcf1faf466aa286d4372623b6e75ad7d2ce1b/lib/cloud_controller/app_manifest/byte_converter.rb#L11
and tried to apply it to the current validation we have in Korifi.
I checked whether I could add some positive test cases (that 1.5G gets successfully accepted), but could not find any existing test cases so far and how it could be done with the current code setup.
Nevertheless, I've checked locally with kind to push an app with 1.5 GB disk_quota and 0.5G memory and it was successfully translated to the corresponding resources.
```diff
--- a/manifest.yml
+++ b/manifest.yml
@@ -1,6 +1,7 @@
---
applications:
- name: test-app
- …
```

Support floating point number values for disk_quota and memory

---

docs/api.md

No.
I've checked get GET apps endpoint and saw that we support all query parameters regarding `order_by`.
While I was there, I've also added the supported `query_by` query parameter for `List buildpacks`.
No.

Update `api.md` to reflect latest API improvements

---

controllers/controllers/services/bindings/controller.go
controllers/controllers/services/bindings/controller_test.go

The binding controller does not get any data from the CFApp, therefore watching CFApps does not make sense. The only reason we had the watch is to make the binding not ready when the app is gone. In an ideal world however this is not a valid state, as app finalization [deletes all bindings for the app](https://github.com/cloudfoundry/korifi/blob/df9925de6b12eeb51cc05d3dd70019250b8e0175/controllers/controllers/workloads/apps/controller.go#L364-L386)
fixes #3527

Remove watching of the CFApp resource

---

tests/e2e/e2e_suite_test.go
tests/e2e/service_bindings_test.go
tests/e2e/service_brokers_test.go
tests/e2e/service_instances_test.go
tests/e2e/service_offerings_test.go
tests/e2e/service_plans_test.go
tests/helpers/broker/deleter.go
tests/smoke/catalog_test.go
tests/smoke/services_test.go
tests/smoke/suite_test.go

No
Leaked service instances and bindings have caused some problems to CI
clusters, since they have finalizers and prevent the namespaces in which
they are created to go away. Resolving this problem requres manual
intervention. This commit makes the logic retry until no binding or
instances are left for each service plan of the related broker

Improve logic for cleaning up of service resources

---

controllers/controllers/services/instances/managed/controller.go
controllers/controllers/services/instances/managed/controller_test.go
controllers/controllers/services/osbapi/client.go
controllers/controllers/services/osbapi/client_test.go

No
Do not fail service instance on broker server error
Previously we were setting the ProvisioningFailedCondition to true if
the broker returned error on provision, no matter the error. The problem
with doing this is that the error can be recoverable, such as the
network flaking, but the instance is sent to a state from which it
cannot recover (When the ProvisioningFailedCondition is set the
reconciler gives up early in the reconciliation loop).
This change fixes the problem described above by defining a new
UnrecoverableError type in the osbapi client. The controller would then set the
ProvisioningFailedCondition only if the error it received is an
UnrecoverableError.
According to the OSBAPI spec unrecoverable perovision error codes are
400, 409 and 422.

Do not fail service instance on broker server error

---

helm/korifi/templates/components.yaml
helm/korifi/values.schema.json
helm/korifi/values.yaml

no
This change adds new value `crds.include` to the chart. When set to `crds.include: false`, no CRDs will be installed as part of the Helm installation. It's a common pattern to manage CRDs separately due to the [Helm limitations](https://helm.sh/docs/topics/charts/#limitations-on-crds)
no

Allow skipping CRDs installation

---

README.helm.md
api/config/config.go
api/config/config_test.go
api/handlers/root.go
api/handlers/root_test.go
api/main.go
api/payloads/role.go
api/payloads/role_test.go
api/presenter/root.go
api/presenter/root_test.go
helm/korifi/api/configmap.yaml
helm/korifi/values.schema.json
helm/korifi/values.yaml

#2243
* New experimental helm values to configure UAA
* The configured uaa url will be returned by the `/` endpoint
* When UAA support is enabled `cf_on_k8s` in the `/` endpoint is false
* This will make `cf login` talks to the configured UAA instead of
reading the kubeconfig
* Note that the cluster should be configured to trust the UAA via
[oidc](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server)

Experimental UAA support

---

api/repositories/service_instance_repository.go
api/repositories/service_instance_repository_test.go
controllers/api/v1alpha1/cfserviceinstance_types.go
controllers/controllers/services/instances/managed/controller.go
controllers/controllers/services/instances/managed/controller_test.go
controllers/controllers/services/instances/upsi/controller.go
controllers/controllers/services/instances/upsi/controller_test.go
controllers/webhooks/finalizer/webhook.go
controllers/webhooks/finalizer/webhook_test.go

Finalizaers are added to all instances no matter what the type is. In UPSI controller added removing the finalizer when deletion timesamp is not zero
#3562 
No

Remove checking instance type in webhook

---

scripts/create-new-user.sh

No
This change adds a check for the availability of the `openssl` command in the `createCert` function.
If `openssl` is not installed or not available in the system's PATH, the script will print an error message and exit with a non-zero status.
The [Korifi installation guide](https://tutorials.cloudfoundry.org/korifi/local-install/) does not list openssl as a prerequisite. 
While running the `deploy-on-kind.sh` script, I encountered an issue where the script silently failed during certificate creation. Instead of an informative error message, the output was misleading:
```bash
./deploy-on-kind.sh korifi
make: Entering directory '/home/user/repos/korifi'
make: 'bin/yq' is up to date.
make: Leaving directory '/home/user/repos/korifi'
None of $DOCKER_SERVER $DOCKER_USERNAME $DOCKER_PASSWORD …
```

Check if OpenSSL is availabile

---

controllers/controllers/services/instances/upsi/controller_test.go

No
Fix test for upsi instance last operation logic
No

Fix test for upsi last operation update type

---

controllers/api/v1alpha1/cfserviceinstance_types.go
controllers/controllers/services/instances/managed/controller.go
controllers/controllers/services/instances/managed/controller_test.go
controllers/controllers/services/osbapi/client.go
controllers/controllers/services/osbapi/client_test.go
tests/e2e/e2e_suite_test.go
tests/smoke/apps_test.go
tests/smoke/bind_service_test.go
tests/smoke/catalog_test.go
tests/smoke/services_test.go
tests/smoke/suite_test.go
tests/smoke/unbind_service_test.go

Added if staetement in OSBAPI CLient for unrecoverable errors and implemented polling to Deprovision last operation. Also, when deprovision fails the instance is not deleted, it sets the failed state to instance the last operation
#3586 
No

Implement polling for instances deprovisioning

---

controllers/api/v1alpha1/cfservicebinding_types.go
controllers/controllers/services/bindings/controller.go
controllers/controllers/services/bindings/controller_test.go
controllers/controllers/services/bindings/managed/controller.go
controllers/controllers/services/bindings/sbio/servicebinding.go
controllers/controllers/services/bindings/sbio/servicebinding_test.go
controllers/controllers/services/bindings/sbio/suite_test.go
controllers/controllers/services/bindings/upsi/controller.go
tools/collections.go
tools/collections_test.go

The logic for servicebinding.io creation is moved to the respective controllers and some consants are moved to the korifiv1alpha1 package
#3576 
No

Refactor binding controllers

---

Makefile
api/repositories/app_repository.go
api/repositories/app_repository_test.go

No
An app is staged when it has current droplet set
Checking for the ready condition on the app to determine whether the app
is staged does not make sense as during an app restart, the app becomes
unready (but remains staged as it references a valid droplet)
No

An app is staged when it has current droplet set

---

Makefile
api/repositories/app_repository.go
api/repositories/app_repository_test.go
go.mod
go.sum
tests/helpers/flock.go
tests/helpers/k8s.go
tests/smoke/list_test.go
tests/smoke/run_task_test.go
tests/smoke/suite_test.go

#3636
Smoke tests for listing resources
The tests verify that
* Authorised users can list resources
* Unauthorised users get empty resources list but no error

Smoke tests for listing resources

---

controllers/api/v1alpha1/cfservicebinding_types.go
controllers/controllers/services/bindings/controller.go
controllers/controllers/services/bindings/controller_test.go
controllers/controllers/services/bindings/managed/controller.go
controllers/controllers/services/instances/managed/controller.go
controllers/controllers/services/instances/managed/controller_test.go
controllers/controllers/services/osbapi/client.go
controllers/controllers/services/osbapi/client_test.go
controllers/controllers/services/osbapi/clientfactory.go
controllers/controllers/services/osbapi/fake/broker_client.go
controllers/controllers/services/osbapi/types.go
helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfservicebindings.yaml

- Added IsAsync flag to UnbindResponse in OSBAPI and the logic in the Unbind method
- Added returning Gone error
- Implementing the Unbind call in binding controller and also polling the last operation for the unbind response
- Refactor binding controller so that the calls for the Bind, Unbind and Provison and Deprovision in the services controller are identical
- Implement Setting owner reference with BlockOwnerDeletion=true and added 'foregroundDeletion' finalizer in binding controller
fixes #3296
#3296
No

Implement unbind from managed service instance

---

tests/smoke/bind_service_test.go
tests/smoke/list_test.go
tests/smoke/unbind_service_test.go

No
Before this change all tests that were binding to as service instances
were using the buildpack app. When we bind to an app that is ready and
running the app becomes unready for a while and restarts. If we try to
run a task against such an app the operation will fail, because the app
is unready. This change creates a cheap app record and binds/unbinds to
this app to prevent messing with the running app state

Create a uniques app whenenver we bind/unbind to a service instance

---

controllers/controllers/services/bindings/controller_test.go
controllers/controllers/services/bindings/managed/controller.go
controllers/controllers/services/instances/managed/controller.go
controllers/controllers/services/instances/managed/controller_test.go
controllers/controllers/services/osbapi/types.go
tests/assets/sample-broker-golang/main.go

No
Ensure credentials secret is created on async bind
* When the bind operation state is `succeeded`, requeue the reconcile
request. Thus we ensure that the controller would try to `bind` again,
and as the bind operation has already succeeded, it would get a
response containing the binding credentials
* When checking the state of the last operation in asynchronous
provision/bind, instance/binding controllers consider the operation to
have completed when its state is either `succeeded`, or `failed`.
Anything else is considered as if the operation is ongoing. Thus we
protect ourselves from brokers returning nonsense operation state
* The test for the instance controller is refactored so that the
synchronous provisioning is the "default" case and there is a
dedicated context for asynchronous …

Ensure binding credentials are stored on async bind

---

api/actions/manifest/applier.go
api/actions/manifest/applier_test.go
api/handlers/space_manifest_test.go
api/payloads/manifest.go
tests/assets/sample-broker-golang/main.go

#3549
Send manifest service parameters to the broker

Support manifest service parameters

---

Makefile

#3649
- **Revert "Temporarily pin cf cli version to 8.8.3"**
- **Enable `globstar` option when running bash commands**
No

Unpin CF cli

---

tests/e2e/service_bindings_test.go
tests/e2e/service_brokers_test.go
tests/e2e/service_instances_test.go
tests/e2e/service_offerings_test.go
tests/e2e/service_plans_test.go
tests/helpers/broker/deleter.go
tests/smoke/bind_service_test.go
tests/smoke/catalog_test.go
tests/smoke/services_test.go
tests/smoke/unbind_service_test.go

No
e2e and smoke tests do not leak test brokers

Ensure e2e and smoke tests delete their brokers

---

Makefile

Related pull:
https://github.com/cloudfoundry/korifi/pull/3702
Keeps Makefile working with version of bash bundled with MacOS
No
After building binaries, running `make clean-bin` should still remove all built files from bin directories.
@danail-branekov @georgethebeatle

Update Makefile to be compatible with bash 3.x

---

README.helm.md
scripts/assets/templates/kind-builder.yml
scripts/deploy-on-kind.sh
scripts/installer/install-korifi-kind.yaml

No
Use minimal cluster builder for local dev scenario
No

Use minimal cluster builder/stack/store for local dev scenario

---

controllers/controllers/services/instances/managed/controller.go
controllers/controllers/services/instances/managed/controller_test.go
controllers/controllers/services/osbapi/client.go
controllers/controllers/services/osbapi/client_test.go
controllers/controllers/services/osbapi/types.go
tests/helpers/broker/broker.go

#3716
- Send 'service_id' and 'plan_id' as querry params in the Deprovision
request
- Always send Content-Type: 'application'json' header

Improve OSBPI compatibility

---

.github/dependabot.yml

No
We are temporarily disabling dependabot PR grouping, until we resolve
the blocker aound bumping controller runtime to 0.20.0, which contains
breaking changes and will take some time to fix

Temporarily disable dependabot PR grouping

---

helm/korifi/controllers/pre-upgrade-set-space-guid.yaml

#3672
This hook labels Korifi existing resources (`cfapps`, `cfbuilds`,
`cfpackages`, `cfprocesses`, `cfroutes`, `cfservicebindings`,
`cfserviceinstances`, `cftasks`) with the
`korifi.cloudfoundry.org/space-guid` label. This label is needed to
adopt improvements in resource listing (see #3636)
The hook runs on pre-upgrade only, as it only make sense in an upgrade
scenario.

Pre-upgrade helm hook to label resources with space-guid

---

statefulset-runner/controllers/appworkload_controller.go
statefulset-runner/controllers/appworkload_controller_test.go

#3687
If we do not do this the appworkload controller keeps re-creating the
same statefulSet over and over again while it is being deleted by the
recursive foreground delete operation incurred by deletig the org (the
same happens on app deletion for similar reasons). This persistent
re-creation of the statefulset results in a significant slowdown of the
convergence of the delete operation
With this chage the reconciler stops creating statefulSets once it sees
that DeletionTimestamp is set, this speeding up the deletion convergence

Stop appworkload reconciliation when DeletionTimestamp is set

---

controllers/controllers/workloads/build/controller.go
controllers/controllers/workloads/build/controller_test.go
controllers/controllers/workloads/build/suite_test.go
controllers/controllers/workloads/processes/controller.go
controllers/controllers/workloads/processes/controller_test.go
controllers/controllers/workloads/processes/suite_test.go
controllers/controllers/workloads/tasks/controller.go
controllers/controllers/workloads/tasks/controller_test.go
controllers/controllers/workloads/tasks/suite_test.go
job-task-runner/controllers/taskworkload_controller.go
job-task-runner/controllers/taskworkload_controller_test.go
kpack-image-builder/controllers/builderinfo_controller.go
kpack-image-builder/controllers/builderinfo_controller_test.go
kpack-image-builder/controllers/suite_test.go
statefulset-runner/controllers/runnerinfo_controller.go
statefulset-runner/controllers/runnerinfo_controller_test.go

#3687
Skip reconciling objects being deleted when no finalization needed
Though not really related to the issue, not wasting time reconciling objects that are being deleted is generally a good idea.
PS: Please don't judge about `builderinfo_controller_test.go`, I have at least filed a [chore](https://github.com/cloudfoundry/korifi/issues/3743) about it

Skip reconciling objects being deleted when no finalization needed

---

.github/workflows/assign-closed-issues-to-rc-milestone.yml

No
By doing that we would keep the release-candidate milestone up to date
with things that are done.

Assign closed issues to the `release-candidate` milestone

---

kpack-image-builder/controllers/builderinfo_controller_test.go
kpack-image-builder/controllers/buildworkload_controller_test.go
kpack-image-builder/controllers/suite_test.go
tests/helpers/eventually.go

#3743
The builder info is created in `JustBeforeEach` so that the test could
conifugure its finalizers in `BeforeEach`. This is to address a flake in
the test when the builder info is being deleted, e.g
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/21592
While being here,
- refactor the suite to create the test root namespace and start the controller in `BeforeEach`. Thus test could not bother cleaning up.
- remove`Serial` from the builder info controller test
- Simplify the builder info controller test by removing contexts that do
not contribute changes to the default setup
- Remove test cases that verify that the builder info controller is
listening on cluster builder eventually deletion. The test verifies
that the info is reconciled on builder …

Refactor kpack-image-builder tests

---

controllers/controllers/services/bindings/controller.go
controllers/controllers/services/bindings/managed/controller.go
controllers/controllers/services/bindings/upsi/controller.go

#3273
Remove the `service instance` argument from `ReconcileResource`. It was
unused in the managed sub-controller, the upsi one can look the instance
up itself.
This helps for a cleaner interface
@uzabanov @georgethebeatle

Simplify binding sub-controllers interface

---

controllers/controllers/services/bindings/controller_test.go
controllers/controllers/services/bindings/managed/controller.go

GitHub [Issue](https://github.com/cloudfoundry/korifi/issues/3739)
When the type of the credential binding is 'key' creating a servicebinding.io secret is redundant. This PR's goal is changing the way the controller creates sbio secrets so it is only created when the type is 'app'
No
The servicebinding.io secret should not be created when the type of the credential binding is 'app'

Create serviceBinding.io secret with type app only

---

Makefile

No
golangci-lint 1.64.2 reports false positives with the ginkgolinter, see https://github.com/golangci/golangci-lint/issues/5398

Temporarily pin golangci-lint to 1.63.4

---

Makefile

#3794
The [issue](https://github.com/golangci/golangci-lint/issues/5398) with false positives from the ginkgolinter has been resolved, therefore we no longer need to pin golangci-lint

Unpin golangci-lint

---

controllers/controllers/networking/domains/suite_test.go
controllers/controllers/networking/routes/suite_test.go
controllers/controllers/services/bindings/controller_test.go
controllers/controllers/services/bindings/suite_test.go
controllers/controllers/services/brokers/suite_test.go
controllers/controllers/services/instances/managed/suite_test.go
controllers/controllers/services/instances/upsi/suite_test.go
controllers/controllers/workloads/env/env_suite_test.go
controllers/webhooks/finalizer/suite_test.go
controllers/webhooks/relationships/suite_test.go
controllers/webhooks/version/suite_test.go
controllers/webhooks/workloads/apps/suite_test.go
controllers/webhooks/workloads/orgs/suite_test.go
controllers/webhooks/workloads/packages/suite_test.go
controllers/webhooks/workloads/spaces/suite_test.go
controllers/webhooks/workloads/tasks/suite_test.go
job-task-runner/controllers/integration/suite_test.go
kpack-image-builder/controllers/suite_test.go
kpack-image-builder/controllers/webhooks/finalizer/suite_integration_test.go
statefulset-runner/controllers/integration/suite_test.go

No
Flake: https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/22068
According to failure logs, the service binding is being reconciled
multiple times before the binding gets into its ready state.
This means that if we stub the broker client to return a sync response
on invocation 3 only, it is quite probable that the fake's sync response
is not properly processed and subsequent reconciles still see that the
operation is ongoing.
Therefore, this change alters stubs the broker client to return a sync
response (i.e. override the default async one) when it returns a
succeeded operation
While being here, also fix the order of shutting down the the k8s client cache and manager

fix binding controller flake

---

controllers/controllers/services/osbapi/client.go
controllers/controllers/services/osbapi/client_test.go
controllers/controllers/services/osbapi/clientfactory.go
controllers/controllers/services/osbapi/fake/broker_client.go
controllers/controllers/services/osbapi/types.go
controllers/controllers/workloads/build/fake/delegate_reconciler.go
tests/assets/sample-broker-golang/main.go

[Issue](https://github.com/cloudfoundry/korifi/issues/3751)
This is 1 of 2 PRs related to the above issue. With this PR there is a new method introduced to the broker client which is responsible to retrieve the service binding. 
No

Added GetServiceBinding to the broker client

---

controllers/controllers/workloads/processes/controller.go
tools/k8s/patch.go
tools/k8s/patch_test.go

#1949
- Use a single app workload var instead of deep copying objects, which
is confusing
- Instead of using controllerutil.CreateOrPatch, implement a similar
behaviour ourselves
- By first trying to creaate the new appWorkload, we avoid a potential
race
- We know that we are going to need fine control over what fields are
being mutated on create vs update
- Also add a new TryPatchResource utility that can handle an error
returned by the modify func

Refactor cfprocess controller

---

controllers/controllers/workloads/build/controller_test.go

No
Attempt to fix flake
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/22813#L67d272c1:43:58
Use EnsurePatch to make sure that the build is patched effectively
before we try to assert that it is no longer reconciled

Attempt to fix flake

---

api/handlers/job.go
api/handlers/job_test.go
api/presenter/job.go
api/presenter/job_test.go
api/repositories/service_instance_repository.go
controllers/controllers/workloads/apps/controller.go
controllers/controllers/workloads/apps/controller_test.go

#3856
- Return POLLING jobs state for async instance/bindings operations. This way the `--wait` flag of the cf cli behaves correctly
- Ignore NotFound error on deleting service instances. This prevents `cf purge-service-instance` from failing if invoked while the service is already being deprovisioned.

Fix async service create/delete and and bind/unbind

---

controllers/controllers/services/instances/managed/controller.go
controllers/controllers/services/instances/managed/controller_test.go

#3857
The CF API spec mandates that when a service instance is deleted, all
related bindings are deleted as well. On the other hand, OSBAPI brokers
may not accept unbind requests for bindings that have their service
instance already being deprovisioned.
In order to address this, the managed instance controller would ensure
that there are no more bindings remaining prior deprovisioning the
instance with the broker.
The actual binding deletion is taken care of by the OwnerReference from
the binding to the instance.

Requeue instance finalization when bindings remaining

---

tests/smoke/services_test.go
tests/smoke/unbind_service_test.go

N/A
After the fix for issue #3856, plain `cf delete-service` returns
immediately and deletion takes place in the bacground. Our tests assume
that the execution is synchronous. To preserve this assumption, we add
the `--wait` flag to the delete instance/binding cli commands

Wait for service instance/binding deletion in smoke tests

---

tests/smoke/list_test.go
tests/smoke/suite_test.go

No
Debug info for flake
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-e2es-eks-periodic/builds/12882
- The build error logs says that cf curl /v3/packages returned invalid
JSON. The JSON output is now logged in case of test failure
- Improve fail hander. It now makes sure it is authorized as cf-admin
(in case the failing test swithed users)

Add debug info for flake

---

api/handlers/fake/cforg_repository.go
api/handlers/org.go
api/handlers/org_test.go
api/payloads/org.go
api/payloads/org_test.go
api/repositories/org_repository.go
api/repositories/org_repository_test.go

[Issue](https://github.com/cloudfoundry/korifi/issues/3852)
This change enables support for updating the organization name via the `PATCH /v3/organizations/:guid `API endpoint.
No

Updated org patch endpoint to support org name

---

api/presenter/app_test.go
api/presenter/droplet_test.go
api/presenter/shared.go

Currently if you push a cf app, without specifying the buildpack in the manifest, the lifecycle response will look like this: 
```
"lifecycle": {
"type": "buildpack",
"data": {}
},
``` 
In such a scenario, we want the response to look like this: 
```
"lifecycle": {
"type": "buildpack",
"data": {
"buildpacks": []
}
},
```
This PR fixes this. 
No

[Bug] Buildpacks does not appear correctly app  response

---

api/repositories/service_binding_repository_test.go
api/repositories/service_instance_repository.go
api/repositories/service_instance_repository_test.go
controllers/api/v1alpha1/cfservicebinding_types.go
controllers/api/v1alpha1/cfserviceinstance_types.go
controllers/controllers/services/bindings/controller.go
controllers/controllers/services/bindings/controller_test.go
controllers/controllers/services/bindings/managed/controller.go
controllers/controllers/services/instances/finalize.go
controllers/controllers/services/instances/managed/controller.go
controllers/controllers/services/instances/managed/controller_test.go
controllers/controllers/services/instances/upsi/controller.go
controllers/controllers/services/instances/upsi/controller_test.go
controllers/controllers/workloads/env/vcap_services_builder.go
controllers/controllers/workloads/env/vcap_services_builder_test.go
helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfserviceinstances.yaml

#3876
- Do not set owner ref from instance to binding. Delete bindings in finalizer
instead.
- Now that we handle binding cleanup in controllers finalizers instead of
relying on owner references, we need to adapt the purge logic as follows:
- Set noopDeprovisioning to true on the instance being purged
- Delete the instance
- The instance and biding controller will respect the noopDeprovisioning
flag and will not call out to the broker while finalizing instances and
bindings
- As the instance no longer owns the binding, we can simplify the app
controller's finalizer by making the app the owner of the binding

Make sure a service instance is not deleted until all its bindings are gone

---

api/handlers/app.go
api/handlers/app_test.go
tests/e2e/apps_test.go

#3621
The `web` process is created by the app controller anyway, therefore
creating the process from the API does not make sense

Do not create the `web` process in the app handler

---

api/repositories/service_binding_repository_test.go

Flake: https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/23545
Service binding's `UpdatedAt` is populated by the last modification
timestamp of managed fields. It could happen that it is a bit off
from the creation timestamp

Fix flake in service binding repository

---

api/repositories/conditions/await.go
api/repositories/conditions/await_test.go
api/repositories/fakeawaiter/await.go
controllers/controllers/workloads/apps/controller.go
controllers/controllers/workloads/apps/controller_test.go
controllers/controllers/workloads/processes/controller.go
controllers/controllers/workloads/processes/controller_test.go
controllers/controllers/workloads/tasks/controller_test.go
tools/k8s/conditions/builder.go
tools/k8s/conditions/builder_test.go
tools/k8s/conditions/checker.go
tools/k8s/conditions/checker_test.go
tools/k8s/conditions/suite_test.go
tools/k8s/reconcile.go

No, but the infamous bindings flake
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-e2es-eks-periodic/builds/13307
Applications, their processes and workloads represent a tree-like
logical structure. Each of the tree nodes have a `Ready` status
condition that is managed by the respective controllers.
When stopping/starting an app from the API, the API would await the
`CFApp` `Ready` condition. Therefore, it is important that whenever the
app becomes ready, it is guaranteed that its child nodes (processes and
workloads) are ready as well.
This change should address long ongoing flake of inconsistent service
bindings after app restart, for example https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-e2es-eks-periodic/builds/13307

Propagate the ready condition from workloads to apps

---

INSTALL.md
README.helm.md
controllers/Makefile
helm/korifi/api/deployment.yaml
helm/korifi/api/ingress-cert.yaml
helm/korifi/controllers/deployment.yaml
helm/korifi/controllers/ingress-cert.yaml
helm/korifi/controllers/manifests.yaml
helm/korifi/controllers/webhook-cert.yaml
helm/korifi/kpack-image-builder/deployment.yaml
helm/korifi/kpack-image-builder/manifests.yaml
helm/korifi/kpack-image-builder/webhook-cert.yaml
helm/korifi/statefulset-runner/deployment.yaml
helm/korifi/statefulset-runner/manifests.yaml
helm/korifi/statefulset-runner/webhook-cert.yaml
helm/korifi/templates/_helpers.yaml
helm/korifi/templates/cert-mgr-issuer.yaml
helm/korifi/templates/gateway.yaml
helm/korifi/values.schema.json
helm/korifi/values.yaml
kpack-image-builder/Makefile
kpack-image-builder/controllers/suite_test.go
kpack-image-builder/controllers/webhooks/finalizer/suite_integration_test.go
statefulset-runner/Makefile

#3931
Make the cert manager an optional dependency
* Add a `generateWebhookCertificates` helm value similar to the
existing `generateIngressCertificates`
* If neither `generateIngressCertificates` nor
`generateIngressCertificates` values are set - do not create a cert
manager issuer
* Generate ingress and webhook certificates only when the respective
helm value is set.
* As a result the cert manager is not used when both
`generateIngressCertificates` and `generateWebhookCertificates` are
set to false, making it an optional dependency
* Add `webhookCertSecret` helm value for each component that runs webhooks
* Add template for reading the caBundle value from a webhook cert secret
* Insert the caBundle into the generated webhook manifest (if
`generateWebhookCertificates` is set to `true`)
* …

Make the cert manager an optional dependency

---

api/handlers/service_plan.go
api/handlers/service_plan_test.go
tests/e2e/e2e_suite_test.go
tests/e2e/service_plans_test.go

#2363
Adding the `/v3/service_plans/<guid>` endpoint
No

Implementing GET service_plans/guid endpoint

---

helm/korifi/Chart.yaml
helm/korifi/migrations/post-upgrade-set-migrated-by.yaml
scripts/deploy-on-kind.sh
scripts/installer/run-locally.sh

#3949
* When building and deploying Korifi, the version on docker images and
chart's `version` is derived from the latest git tag. Thus, when the
helm chart is listed (`helm -n korifi list`), proper version is
displayed
* The character `v` is stripped from the git tag when computing the
version, as chart's `version` has to be a valid semver.
* The chart `appVersion` has been removed as it matches `version` anyway
* The migration job runs after upgrade and puts
`korifi.cloudfoundry.org/migrated-by` on apps and domains. The value
of the label is the chart version (see above). By "touching" those
resources, their update webhooks kick in and populate the new
filtering labels. There is no need to set them from within the
migration job.
* The migration job has lowest hook weight (`-9999`) to …

Configure helm version based on the github release

---

helm/korifi/migrations/post-upgrade-set-migrated-by.yaml

#3920
With https://github.com/cloudfoundry/korifi/pull/3984, Korifi is now
setting labels related to filtering via a webhook. For existing routes
however this webhook would not kick in unless the route is updated.

Set `migrated-by` label on `CFRoutes`

---

api/repositories/app_repository_test.go
api/repositories/build_repository.go
api/repositories/build_repository_test.go
api/repositories/droplet_repository.go
api/repositories/droplet_repository_test.go
api/repositories/repositories_suite_test.go
api/repositories/shared.go
controllers/api/v1alpha1/cfbuild_types.go
controllers/controllers/workloads/build/buildpack/controller.go
controllers/controllers/workloads/build/buildpack/controller_test.go
controllers/controllers/workloads/build/docker/controller.go
controllers/controllers/workloads/build/docker/controller_test.go
controllers/webhooks/label_indexer/webhook.go
controllers/webhooks/label_indexer/webhook_test.go
helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfbuilds.yaml
helm/korifi/migrations/post-upgrade-set-migrated-by.yaml

#3988
Use label selectors to filter CFBuilds
* Introduce a `CFBuild.Status.State` field to reflect the build state, populated by the build controller
* The build and droplet repositories just use the `CFBuild.Status.State` field when setting the record state; they no longer interet the CFBuild statuses
* The indexer webhook sets the `build-state` label on CFBuilds with the value from `CFBuild.Status.State`
* The migration job sets the `migrated-by` label on CFBuilds in order to force the indexer webhook on existing builds during upgrade
* The build repository uses label selector to filter builds when listing
The PR has been split into several commits to make it easier to review. Feel free to squash them when merging.

List builds via label selectors

---

api/authorization/namespace_permissions.go
api/authorization/namespace_permissions_test.go
api/repositories/klient.go
api/repositories/klient_test.go
api/repositories/org_repository.go
api/repositories/org_repository_test.go
api/repositories/repositories_suite_test.go
controllers/api/v1alpha1/cforg_types.go
controllers/api/v1alpha1/shared_types.go
controllers/controllers/services/instances/managed/controller.go
controllers/controllers/services/instances/managed/controller_test.go
controllers/controllers/workloads/orgs/controller.go
controllers/controllers/workloads/orgs/controller_test.go
controllers/controllers/workloads/spaces/controller.go
controllers/controllers/workloads/spaces/controller_test.go
controllers/webhooks/finalizer/webhook_test.go
controllers/webhooks/label_indexer/webhook.go
controllers/webhooks/label_indexer/webhook_test.go
controllers/webhooks/version/version_test.go
helm/korifi/controllers/manifests.yaml
helm/korifi/migrations/post-upgrade-set-migrated-by.yaml
tools/k8s/k8s_suite_test.go
tools/k8s/patch_test.go
tools/k8s/reconcile_test.go
tools/k8s/retrying_client_test.go
tools/k8s/selectors.go
tools/k8s/selectors_test.go

#3988
* Introduce `org-name`, `guid` and `ready` labels on CFOrgs
* Use label selectors when listing orgs in the repository instead of
filtering them on the client side

Filter orgs when listing via label selectors

---

controllers/webhooks/common_labels/webhook.go
controllers/webhooks/common_labels/webhook_test.go

No, but CI failure:
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/deploy-korifi-acceptance/builds/1141#L682aef86:1251
Set `created_at` label also on update
This ensures that old objects (that have existed prior introducing the
webhook) get the created_at label as well. Furthermore, this guarantees
that the user cannot modify the label via kubectl

Set `created_at` label also on update

---

api/actions/manifest/state_collector.go
api/actions/manifest/state_collector_test.go
api/handlers/app.go
api/handlers/app_test.go
api/repositories/process_repository.go
api/repositories/process_repository_test.go
controllers/api/v1alpha1/cfprocess_webhook.go
controllers/api/v1alpha1/cfprocess_webhook_test.go
controllers/webhooks/common_labels/suite_test.go
controllers/webhooks/common_labels/webhook.go
controllers/webhooks/common_labels/webhook_test.go
controllers/webhooks/label_indexer/webhook.go
controllers/webhooks/label_indexer/webhook_test.go
helm/korifi/controllers/manifests.yaml

#3988
Usee label selectors to filter cfprocesses on the server side when listing
Also:
- The process can be filtered by multiple space guids, so fix that
- Move the appGUIS and processType labels to the label indexer webhook
- Fix the common_labels webhook kubebuilder annotation and added tests
for each type of resource

Use label selectors to filter processes

---

helm/korifi/migrations/post-upgrade-set-migrated-by.yaml

CI failure: https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/deploy-korifi-acceptance/builds/1149
Touch CFProcesses during the migration webhook
This is needed to enforce `created_at` label by the common webhook

Touch CFProcesses during the migration webhook

---

controllers/webhooks/common_labels/webhook_test.go

CI flakes:
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/24985
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/24979
Allow 2 seconds tolerance for created_at label in tests

Allow 2 seconds tolerance for created_at label in tests

---

helm/korifi/migrations/post-upgrade-set-migrated-by.yaml

No
Security groups are new resources therefore they do not need migration

Do not migrate security groups

---

api/config/config.go
api/config/config_test.go
api/main.go
helm/korifi/api/configmap.yaml
helm/korifi/api/deployment.yaml
helm/korifi/api/ingress-cert.yaml
helm/korifi/templates/cert-mgr-issuer.yaml
helm/korifi/values.yaml

#4025
Do tls validation when talking to local log cache. Do not skip validation unless explicitly configured via helm value

Perform tls validation in log cache client unless explicitly disabled

---

INSTALL.md
README.helm.md
api/main.go
helm/korifi/api/deployment.yaml
helm/korifi/api/ingress-cert.yaml
helm/korifi/api/internal-cert.yaml
helm/korifi/controllers/webhook-cert.yaml
helm/korifi/kpack-image-builder/webhook-cert.yaml
helm/korifi/statefulset-runner/webhook-cert.yaml
helm/korifi/templates/_helpers.yaml
helm/korifi/templates/cert-mgr-issuer.yaml
helm/korifi/values.schema.json
helm/korifi/values.yaml

No, this is a fix to make acceptance deployment green again
Introduce dedicated internal api tls cert
- It does not make sense to have both the external and the internal SAN
in the same certificate
- On acceptance the external cert is issued by letsenctypt, which is a
limited resource, so it is not optimal to have this cert issued for the
internal dns name as well
- Instead have a dedicated certificate for the internal api dns that is
signed by the korifi internal ca
- The korifi api server is configured with both the internal and the
external certificates and it would serve the correct one depending on
the client request

Introduce dedicated internal api tls cert

---

api/main.go
helm/korifi/api/deployment.yaml
helm/korifi/api/internal-cert.yaml
helm/korifi/templates/cert-mgr-issuer.yaml

No
- No need to create a new issuer that uses a cert with isCA: true
- We can generate the korifi-tls-internal cert with isCA: true and use
it as a CA when doing the logcache intenal loopback.
- No need for a dedicated ca volume and mount - the internal-cert is
being used as a CA as well

Make the intenal server cert a valid CA

---

api/repositories/service_broker_repository.go
api/repositories/service_broker_repository_test.go
controllers/controllers/services/credentials/credentials_test.go
tools/secrets.go
tools/secrets_test.go

No
- Service credentials are stored as json objects under a "credentials"
key.
- A json object is modelled as map[string]any in golang, but korifi was
using any, which is a bit too broad.
- Additionally simplify tests

Improve credential secret serialization

---

api/handlers/app.go
api/handlers/app_test.go
api/handlers/build_test.go
api/handlers/buildpack_test.go
api/handlers/deployment_test.go
api/handlers/domain_test.go
api/handlers/droplet_test.go
api/handlers/org.go
api/handlers/org_test.go
api/handlers/package.go
api/handlers/package_test.go
api/payloads/app.go
api/payloads/app_test.go
api/payloads/droplet.go
api/payloads/droplet_test.go
api/payloads/org.go
api/payloads/org_test.go
api/payloads/package.go
api/payloads/package_test.go
api/payloads/service_offering.go
api/repositories/droplet_repository.go
api/repositories/droplet_repository_test.go
api/repositories/org_repository.go
api/repositories/org_repository_test.go
api/repositories/process_repository.go
api/repositories/process_repository_test.go

#3701
Most of this change deals with introducing dedicated payloads for
listing resources in the context of other resources. For example:
- there is a payload for listing droplets via /v3/droplets
- there is an alternative payload for listing the droplets in the
context of an app via /v3/apps/:guid/droplets
- these payloads are a bit different
- both should support ordering and paging

Ordering for droplets, orgs, packages

---

api/repositories/k8sklient/descriptors/errors/resolution.go
api/repositories/k8sklient/descriptors/errors/resolution_test.go
api/repositories/k8sklient/descriptors/errors/suite_test.go
api/repositories/k8sklient/descriptors/mapper.go
api/repositories/k8sklient/k8sklient_suite_test.go
api/repositories/k8sklient/lister.go
api/repositories/k8sklient/lister_test.go

No
In order for the error producer and the error consumer can work
together, we extract the error type and the error predicate in a
dedicated package and define a constructor for the error
The error producer must use the constructor (as the error type is
package visible), and the consumer must use the predefined predicate (as
it cannot create a pointer to the type).
This way we guarantee that no type mismatch will happen

Ensure list is retried when object resolution fails

---

scripts/deploy-on-kind.sh
scripts/installer/install-korifi-kind.yaml

On my machine, deploying the Helm release took more than the [default `5m`](https://helm.sh/docs/intro/using_helm/#helpful-options-for-installupgraderollback) to run the `post-install`-hook. 
Increasing the `--timeout` to `15m` made the kind deployment pass on my machine.

fix(deploy-on-kind): increase timeout for Helm deployment

---

README.md

#4164
codeclimate badges have been broker for a while. It seems that there is
no easy codeclimate replacement, we are removing them

Remove code climate badges from the README
