cloudfoundry/korifi

Makefile, api/v1alpha1/cfapp_webhook.go, api/v1alpha1/cfapp_webhook_integration_test.go, api/v1alpha1/cfapp_webhook_test.go, api/v1alpha1/webhook_suite_test.go, go.mod
#9 
- the cfApp label key will need to be updated later based on what is agreed on this [story](https://github.com/cloudfoundry/cf-k8s-controllers/issues/31)
=> Set the appGUID label on CFApp records

apis/workloads/v1alpha1/cfapp_webhook_test.go, controllers/workloads/cfapp_controller_test.go, controllers/workloads/suite_integration_test.go, webhooks/workloads/cfapp_validation_test.go
No
Code cleanup as discussed at team forum:
- standardize on g.Expect vs Expect
- general cleanup
No
N/A
=> Code cleanup

docs/architecture-decisions/0003-structuring-kubernetes-resource- labels.md, docs/architecture-decisions/0003-structuring-kubernetes-resource-labels.md
#31 
Adding an ADR to record the decision on syntax of CR labels.
No.
=> Structuring CR Labels

README.md
#23 
Fix to instructions for manual install.
No.
Follow README
=> README fix for kubectl apply instructions

.envrc, apis/workloads/v1alpha1/cfapp_webhook_integration_test.go, apis/workloads/v1alpha1/cfapp_webhook_test.go, apis/workloads/v1alpha1/cfbuild_webhook_integration_test.go, apis/workloads/v1alpha1/cfbuild_webhook_test.go, apis/workloads/v1alpha1/cfpackage_webhook_integration_test.go, apis/workloads/v1alpha1/cfpackage_webhook_test.go, apis/workloads/v1alpha1/cfprocess_webhook_integration_test.go, apis/workloads/v1alpha1/cfprocess_webhook_test.go, apis/workloads/v1alpha1/webhook_suite_test.go, controllers/networking/cfroute_controller_test.go, controllers/networking/suite_test.go, controllers/workloads/cfapp_controller_integration_test.go, controllers/workloads/cfapp_controller_test.go, controllers/workloads/cfbuild_controller_integration_test.go, controllers/workloads/cfbuild_controller_test.go, controllers/workloads/suite_integration_test.go, go.mod, go.sum, webhooks/workloads/cf_workloads_validation_errors_test.go, webhooks/workloads/cfapp_validation_integration_test.go, webhooks/workloads/cfapp_validation_test.go, webhooks/workloads/suite_integration_test.go
no.
changed all tests from spec to ginkgo
probably
`make test` should pass
@akrishna90 @davewalter
=> Switch Tests from spec to ginkgo

api/apis/app_handler_test.go, api/apis/fake/cfroute_repository.go, api/apis/route_handler.go, api/apis/route_handler_test.go, api/docs/api.md, api/payloads/destination.go, api/payloads/route.go, api/presenter/route.go, api/repositories/route_repository.go, api/repositories/route_repository_test.go
https://github.com/cloudfoundry/cf-k8s-api/issues/84
Adds a POST endpoint to add Destinations to Route.
No
Follow acceptance steps on the issue.
@matt-royal
=> Add a POST endpoint to add destinations to a route

api/apis/integration/integration_suite_test.go
No
Attempt to fix the integration build failures when tests are run in parallel
No
This is done if the PR tests pass consistently (do a few reruns)
@davewalter
=> Change the server port per test so parallel tests don't collide

.github/workflows/test-build-push-main.yml
Fix the main pipeline after merging Makefiles
=> Fix the main pipeline after merging Makefiles

controllers/config/samples/cfapp.yaml, controllers/controllers/workloads/cfprocess_controller.go, controllers/controllers/workloads/cfprocess_controller_test.go, controllers/controllers/workloads/integration/cfapp_controller_integration_test.go, controllers/controllers/workloads/integration/cfprocess_controller_integration_test.go, controllers/controllers/workloads/integration/suite_integration_test.go, controllers/controllers/workloads/testutils/shared_test_utils.go
Adds some test refactors and fixed a bug with the LRP Health Check when the CFProcess has no ports
=> fixed port bug on LRP

api/apis/package_handler.go, api/apis/package_handler_test.go
#162 
Add GET endpoint for retrieving Packages by GUID
No.
Run tests `make test-api-unit`
=> Add Package GET endpoint

api/apis/apis_suite_test.go, api/apis/domain_handler.go, api/apis/domain_handler_test.go, api/apis/fake/cfdomain_repository.go, api/apis/route_handler.go, api/apis/shared.go, api/docs/api.md, api/main.go, api/payloads/domain.go, api/presenter/domain.go, api/presenter/route.go, api/repositories/domain_repository.go, api/repositories/domain_repository_test.go, api/repositories/route_repository_test.go, go.mod, go.sum
#177 
Adds a List Domain Endpoint with filter by query parameters capability (filters supported - "names")
No.
Follow acceptance steps on  #177 
@Birdrock
=> Add list domain endpoint with filter support

api/apis/job_handler.go, api/apis/job_handler_test.go, api/presenter/job.go
#164 
Adds the job endpoint which always returns a static response with `state` set to `COMPLETE`
No.
Follow acceptance steps on #164 
@Birdrock
=> API Client can retrieve Jobs for space manifest application

Makefile
No.
Adding additional targets for KinD.
No.
Run make targets.
@davewalter
=> Add make targets for working with KinD

api/apis/app_handler.go, api/apis/app_handler_test.go, api/apis/fake/pod_repository.go, api/apis/integration/create_app_test.go, api/apis/process_handler.go, api/docs/api.md, api/main.go, api/repositories/pod_repository.go, api/repositories/pod_repository_test.go
#170 
- adds POST v3/apps/:guid/actions/restart endpoint
- implementation uses a polling mechanism to achieve restart synchronously
No
Follow acceptance on #170 
@gnovv
=> App developer can restart an app with downtime

api/config/base/rbac/role.yaml, api/reference/cf-k8s-api.yaml, api/repositories/app_repository.go
Give the API shim the ability to create/update secrets so that it is able to create/update app env vars.
@matt-royal @akrishna90 @Birdrock
=> Give the API shim the ability to create/update secrets

api/apis/integration/integration_suite_test.go, api/apis/org_handler.go, api/apis/route_handler.go, api/payloads/destination.go, api/repositories/app_repository.go, api/repositories/build_repository.go, api/repositories/package_repository.go, api/repositories/process_repository.go, api/repositories/shared_test.go, controllers/controllers/workloads/cfapp_controller.go, controllers/controllers/workloads/shared.go, controllers/controllers/workloads/testutils/shared_test_utils.go
No.
Use Version 4 UUID.
No.
Run tests as normal
@emalm
=> Generate Version 4 UUIDs

README.md, api/repositories/package_repository.go, api/repositories/pod_repository.go, api/repositories/pod_repository_test.go, scripts/install-dependencies.sh
#268 
Use the latest available image for eirini to pull in the changes for labels
No
Follow acceptance on #268 and #175
@gnovv
=> Bump eirini to use latest img and updated eirini labels to match the new format

.envrc
No.
Adding `.envrc` files for ease of development environment configuration.
No.
From root: `go test ./...`
From `api`: `go run main.go`
From `controllers`: `go run main.go`
@gnovv @acosta11 @davewalter
=> Add envrc files for root and project dirs

api/apis/process_handler_test.go, api/apis/space_manifest_handler_test.go, api/payloads/manifest.go, api/payloads/manifest_test.go
#155  
Add validation to prevent instance count -1
No
Same as #155
pair @davewalter
=> Add manifest apply instance count validation

api/apis/authentication_middleware.go, api/apis/authentication_middleware_test.go, api/apis/org_handler.go, api/apis/org_handler_test.go, api/apis/shared.go, api/apis/space_handler.go, api/apis/space_handler_test.go, api/main.go, api/repositories/authorization/cert_inspector.go, api/repositories/authorization/errors.go, api/repositories/authorization/identity_provider.go, api/repositories/authorization/identity_provider_test.go, api/repositories/authorization/token_reviewer.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/orgs_test.go, api/tests/e2e/roles_test.go, api/tests/e2e/spaces_test.go, api/tests/integration/cert_inspector_test.go, api/tests/integration/token_reviewer_test.go
This adds a middleware that will block any request coming from users with missing or invalid authentication credentials.
=> Add authentication middleware

controllers/controllers/workloads/integration/cfprocess_controller_integration_test.go, controllers/controllers/workloads/integration/suite_integration_test.go
=> Use PATCH to assign droplets to builds in tests

api/apis/package_handler.go, controllers/controllers/workloads/cfbuild_controller.go
#317 
Uses the path lib to join image paths.
No.
Run tests as normal.
=> Join paths with Go path lib

api/apis/droplet_handler.go, api/apis/fake/cfdroplet_repository.go, api/apis/fake/cfpackage_repository.go, api/apis/package_handler.go, api/apis/package_handler_test.go, api/docs/api.md, api/main.go, api/payloads/package.go, api/presenter/droplet.go, api/presenter/package.go, api/repositories/droplet_repository.go, api/repositories/droplet_repository_test.go, api/repositories/package_repository.go, api/repositories/package_repository_test.go
#315 
Adds `GET v3/packages` and GET `v3/packages/<guid>/droplets`
no
Follow README to start cluster and run local version of API. Try to push an app then start and stop with cf cli
@davewalter _
=> Implement GET /v3/package/<guid>/droplets

controllers/docs/architecture-decisions/0009-document-cf-restart-implementation.md
closes #260
Adds ADR for `cf restart` design
No
N/A
@akrishna90
=> Added ADR for cf restart

api/apis/app_handler.go, api/apis/build_handler.go, api/apis/package_handler.go, api/apis/service_route_binding_handler.go, api/presenter/app.go, api/presenter/domain.go, api/presenter/droplet.go, api/presenter/org.go, api/presenter/package.go, api/presenter/process.go, api/presenter/route.go, api/presenter/service_route_binding.go, api/presenter/shared.go, api/tests/e2e/apps_test.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/orgs_test.go, api/tests/e2e/spaces_test.go
Related to #324 
This PR refactors the API list presentation logic to use a generic ForList() helper function. It also updates the e2e tests accordingly.
No
* Run `make test`
* Deploy everything and use the API
=> Refactor API list presentation logic

api/apis/app_handler.go, api/apis/app_handler_test.go, api/apis/fake/cfapp_repository.go, api/docs/api.md, api/repositories/app_repository.go, api/repositories/app_repository_test.go, api/repositories/repositories_suite_test.go, controllers/config/cf_roles/cf_space_developer.yaml, controllers/reference/cf-k8s-controllers.yaml
#334
This PR implements the `DELETE /v3/apps/:guid` endpoint for the `cf delete` command.
No
See #334
@Birdrock
=> Implement DELETE /v3/apps/:guid

controllers/config/samples/cfroute.yaml, controllers/controllers/shared/index.go, controllers/controllers/workloads/cfapp_controller.go, controllers/controllers/workloads/cfapp_controller_test.go, controllers/controllers/workloads/fake/cfclient.go, controllers/controllers/workloads/integration/cfapp_controller_integration_test.go, controllers/controllers/workloads/integration/suite_integration_test.go, controllers/controllers/workloads/shared.go, controllers/controllers/workloads/testutils/shared_test_utils.go, controllers/main.go
#337 
Deleting a CFApp deletes matching Destinations for the app on CFRoute
No.
follow acceptance on #337 
@acosta11
=> Deleting CFApp removes CFRoute Destinations that match the app

controllers/controllers/networking/cfroute_controller.go
No
We were curious about changing the array while iterating on it. We tried it on playground and saw that it skips checking the `if` condition on the element that was moved. https://go.dev/play/p/v8JWwIrXLsP
To be safe, we created a new slice to hold the list of elements that need to be retained and replace the original list with this retained elements list 
No
Running `make test` should pass.
@julian-hj
=> Refactor loops for deleting httpproxies that match cfroute

README.md, controllers/controllers/shared/index.go, controllers/controllers/workloads/cfapp_controller.go, controllers/controllers/workloads/integration/suite_integration_test.go, dependencies/kpack-release-0.5.0.yaml, dependencies/kpack/cluster_store.yaml, go.mod, go.sum, scripts/install-dependencies.sh
#359
This PR bumps kpack to 0.5.0.
No
Deploy and confirm that everything works.
@Birdrock
=> Bump kpack to 0.5.0

scripts/deploy-on-kind.sh
- reduce the number of hacks we use for local registry deployment by 1
- reduce "sleep" time after patching kind containerd instance from 30s
to 10s.
No
Small tweaks to improve the deploy-on-kind.sh script when using a local container registry
No
```
./scripts/deploy-on-kind.sh xyz local
k apply -f controllers/config/samples/cfdomain.yaml
cf co o && cf target -o o && cf create-space s && cf target -s s
cd ../cf-acceptance-tests/assets/node
cf p node
curl node.vcap.me
```
=> Resolve TODO in deploy-on-kind.sh

api/docs/api.md
#381 
This PR updates the API doc to add org and space endpoints
No
Review the API doc and see the org and space endpoints that are currently implemented.
@gnovv
=> Update API doc to add org/space endpoints

api/apis/fake/space_repository.go, api/apis/job_handler.go, api/apis/job_handler_test.go, api/apis/space_handler.go, api/apis/space_handler_test.go, api/apis/space_manifest_handler.go, api/docs/api.md, api/presenter/job.go, api/repositories/fake/cfspace_repository.go, api/repositories/org_repository.go, api/repositories/org_repository_test.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/spaces_test.go
closes #379
- adds space GUID filtering to the ListSpaces repo function for use in GetSpace, but does not implement space GUID filtering in the list spaces endpoint
- converts ListSpaces to use a message
no
See issue
@davewalter
=> Add delete spaces endpoint

scripts/deploy-on-kind.sh
No
This PR helps to streamline the `deploy-on-kind.sh` script for developer workflows and make it more approachable with usage text. It also applies the default domain for kind automatically so that we don't have to do it manually each time we set up a cluster, and exposes port 30050 so that you can access the local docker registry if you're using that option.
New command line options:
- -l for local registry
- -c to skip everything except controller build and deployment
- -a to skip everything except api build and deployment
- -v for bash -x output
- -h usage text
No, the default usage remains the same.
- run the following
```
./scripts/deploy-on-kind.sh kind -l
cf api http://localhost --skip-ssl-validation
cf login #choose "kind-kind"
cf co o && cf target -o o && cf create-space s && cf …
```
=> add options to deploy-on-kind.sh

api/apis/apis_suite_test.go, api/apis/integration/apply_manifest_test.go, api/apis/job_handler_test.go, api/apis/org_handler_test.go, api/apis/shared.go, api/apis/space_handler.go, api/apis/space_handler_test.go, api/authorization/errors.go, api/main.go, api/repositories/org_repository.go, api/repositories/org_repository_test.go, api/repositories/repositories_suite_test.go
Co-authored-by: Andrew Costa <ancosta@vmware.com>
#389
Adds auth to space delete 
No
See issue
@acosta11
=> Added auth to space delete endpoint

api/tests/e2e/apps_test.go, api/tests/e2e/orgs_test.go, api/tests/e2e/spaces_test.go, scripts/deploy-on-kind.sh, scripts/install-dependencies.sh
No
These were erroneously present due to the user auth bug #437. Now that's
fixed, things work immediately and first time.
No
e2e tests are green
=> Remove `Eventually`s from e2e tests

.golangci.yml, api/apis/domain_handler.go, api/apis/process_handler.go, api/repositories/route_repository_test.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/orgs_test.go, api/tests/e2e/roles_test.go, api/tests/e2e/spaces_test.go, controllers/webhooks/workloads/integration/helpers/subnamespace_anchors.go, controllers/webhooks/workloads/integration/subnamespaceanchor_validation_test.go, controllers/webhooks/workloads/subnamespaceanchor_validation_test.go
Enabling the dupl linter for detecting duplicate code
No
Tests should be passing
@kieron-dev
=> Enable the dupl linter

api/main.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/orgs_test.go, api/tests/e2e/spaces_test.go
* Dynamically delete spaces when deleting an org
* Attempt to work around problem when ginkgo doesn't stop test when
expect fails in a before each go routine
* Allow more time for org and space creation
=> Async test fixes

api/actions/fetch_process_stats.go, api/actions/fetch_process_stats_test.go, api/apis/process_handler_test.go, api/presenter/process_stats.go
closes #475
Changes GET process/stats when desiredState is STOPPED to match cloud controller
no
see issue
@acosta11
=> Updated process stats for DOWN state

api/apis/app_handler.go, api/apis/app_handler_test.go, api/apis/fake/cfapp_repository.go, api/apis/integration/apply_manifest_test.go, api/apis/integration/create_app_test.go, api/apis/integration/get_app_env_test.go, api/apis/integration/integration_suite_test.go, api/main.go, api/presenter/app.go, api/repositories/app_repository.go, api/repositories/app_repository_test.go, api/repositories/repositories_suite_test.go, docs/api.md
#411 
Add the GET /v3/apps/:guid/env endpoint. Only the `environment_variables` value is implemented
No
Follow the AC in the issue
@akrishna90
=> Add GET /v3/apps/:guid/env endpoint

api/apis/org_handler.go, api/apis/org_handler_test.go, api/repositories/org_repository.go, api/repositories/org_repository_test.go, api/tests/e2e/orgs_test.go, api/tests/e2e/roles_test.go
=> Only CF admins can create orgs

api/tests/e2e/e2e_suite_test.go
https://github.com/cloudfoundry/cf-k8s-controllers/issues/538
The org repo waits for the subnamespaces anchor status to become OK,
unfortunately this only indicates that the underlying namespace has been
created. Objects propagation is carried out asynchronously, therefore
there is a tiny amount of time that rolebindings from the parent
namespace are not available into the child namespace. During this short
interval the org/space might be unusable even for admins as they are not
yet bound to their roles in that particular namespace.
HNS currently does not provide a mechanism to signal that propagation is
complete so it is very hard for us to implement a proper fix. Therefore
until we are sure that this is an actual problem, e2e tests would just
wait for the admin role binding to appear in …
=> E2E tests wait for admin role binding in orgs/spaces

api/apis/fake/org_repository.go, api/apis/org_handler.go, api/apis/org_handler_test.go, api/apis/space_handler.go, api/apis/space_handler_test.go, api/repositories/org_repository.go, api/repositories/org_repository_test.go, api/tests/e2e/spaces_test.go
#552
Fixes bug where one can pass a space guid as the org guid when creating a space, and end up with a sub-space.
No
See repro in #552
=> Check org accessible before creating space

api/apis/app_handler.go, api/apis/app_handler_test.go, api/apis/integration/app_test.go, api/tests/e2e/apps_test.go
#448 
Make sure get app routes fails with a 404 when user doesn't have permission to see the app.
No
See issue #448 
=> Correct authz responses for get app routes

controllers/controllers/workloads/cfprocess_controller.go, controllers/controllers/workloads/cfprocess_controller_test.go, controllers/controllers/workloads/integration/cfprocess_controller_integration_test.go, controllers/controllers/workloads/integration/suite_integration_test.go, controllers/controllers/workloads/shared.go, controllers/controllers/workloads/testutils/shared_test_utils.go
resolves #462
Implements `VCAP_SERVICES` env vars in process controller.
No
See issue.
@matt-royal
=> Add VCAP_SERVICES env vars to LRPs

api/apis/fake/cfservice_instance_repository.go, api/apis/service_instance_handler.go, api/apis/service_instance_handler_test.go, api/config/base/rbac/role.yaml, api/main.go, api/payloads/service_instance.go, api/presenter/service_instance.go, api/reference/cf-k8s-api.yaml, api/repositories/role_repository_test.go, api/repositories/service_instance_repository.go, api/repositories/service_instance_repository_test.go, api/repositories/shared.go, controllers/config/cf_roles/cf_admin.yaml, controllers/config/cf_roles/cf_space_developer.yaml, controllers/controllers/workloads/cfprocess_controller_test.go, controllers/reference/cf-k8s-controllers.yaml, docs/api.md
resolves #457
#457
- Updates RBAC
- Updates docs
No
See issue.
@akrishna90
=> Implements GET /v3/service_instances

api/apis/integration/apply_manifest_test.go, api/apis/job_handler.go, api/apis/job_handler_test.go, api/apis/space_manifest_handler.go, api/apis/space_manifest_handler_test.go, api/presenter/job.go
#491
Add missing Route delete job.
No.
* `cf delete-route ...` to check calls to job endpoint
@davewalter
=> Add route delete job

api/apis/integration/route_test.go
No.
Disable flakey test until authenticed route listing is implemented
No.
Run integration tests
@davewalter @akrishna90
=> Disable route integration test

controllers/apis/networking/v1alpha1/integration/webhook_suite_integration_test.go, controllers/apis/workloads/v1alpha1/integration/webhook_suite_integration_test.go, controllers/webhooks/workloads/integration/suite_integration_test.go
No
Add missing GinkgoRecover in tests
Also remove .g file
No
N/A
@kieron-dev
=> Add missing GinkgoRecover in tests

api/apis/build_handler.go, api/apis/build_handler_test.go, api/apis/droplet_handler.go, api/apis/integration/build_test.go, api/apis/shared.go, api/main.go, api/repositories/app_repository_test.go, api/repositories/build_repository.go, api/repositories/build_repository_test.go, api/repositories/buildpack_repository_test.go, api/repositories/droplet_repository_test.go, api/repositories/org_repository_test.go, api/repositories/repositories_suite_test.go, api/repositories/role_repository_test.go, api/repositories/route_repository_test.go, api/repositories/service_instance_repository_test.go, api/tests/e2e/builds_test.go
#542 
Adds authorization to the get build endpoint.
No
See #542 
@kieron-dev
=> Add authz to get build endpoint

api/main.go
No
* Create repo objects once and inject them in handlers instead of wire
repos on each handler construction
* Tidy-up the code
No
Green tests
=> Extract repo wiring

api/apis/apis_suite_test.go, api/apis/app_handler_test.go, api/apis/build_handler.go, api/apis/build_handler_test.go, api/apis/integration/build_test.go, api/apis/org_handler_test.go, api/apis/role_handler_test.go, api/apis/route_handler_test.go, api/apis/service_instance_handler_test.go, api/apis/space_handler_test.go, api/main.go, api/repositories/app_repository_test.go, api/repositories/build_repository.go, api/repositories/build_repository_test.go, api/repositories/domain_repository_test.go, api/repositories/errors.go, api/repositories/package_repository.go, api/repositories/package_repository_test.go, api/repositories/shared.go, api/tests/e2e/builds_test.go, controllers/config/cf_roles/cf_admin.yaml, controllers/config/cf_roles/cf_space_developer.yaml, controllers/config/cf_roles/cf_space_manager.yaml, controllers/controllers/networking/integration/cfroute_controller_integration_test.go, controllers/reference/cf-k8s-controllers.yaml
#543 
Use the user k8s client for get package and create build in the repository code.
You must be admin or space developer to create a build now.
See #543
=> Add authorization to create build

api/repositories/package_repository_test.go
No
Simplify package state test into standard Ginkgo constructs. This makes the test more readable, shorter and idomatic.
No
Green tests
=> Improve test for package state

controllers/controllers/shared/index.go, controllers/controllers/workloads/cfapp_controller.go, controllers/controllers/workloads/cfprocess_controller.go
Co-authored-by: Akira Wong <wakira@vmware.com>
Resolves #598
Changes label lookup for ServiceBinding to use an Indexed field instead
No
N/A
@matt-royal
=> 598 Changed process controller to use SerivceBinding indexer

controllers/controllers/workloads/cfbuild_controller.go, controllers/controllers/workloads/cfbuild_controller_test.go, controllers/controllers/workloads/integration/cfbuild_controller_integration_test.go
=> Add unit test for CFBuildController service bindings

api/apis/log_cache_handler.go, api/apis/process_handler.go, api/apis/resource_matches_handler.go, api/apis/root_v3_handler.go, api/apis/shared.go, api/payloads/manifest.go, controllers/controllers/workloads/cfprocess_controller.go
#653 
Handle a couple of unhandled errors in the production code
No
Tests are green
=> Handle unhandled errors

api/actions/apply_manifest.go, api/actions/apply_manifest_test.go, api/actions/fake/cfprocess_repository.go, api/actions/shared.go, api/apis/app_handler.go, api/apis/app_handler_test.go, api/apis/fake/cfprocess_repository.go, api/apis/process_handler.go, api/apis/process_handler_test.go, api/payloads/process.go, api/repositories/process_repository.go, api/repositories/process_repository_test.go, controllers/controllers/workloads/integration/cfbuild_controller_integration_test.go, docs/api.md
#535 
As a developer I want to set health check using CFSetHealthCheck
- Implemented the patch process endpoint
- Implemented the get app process by type endpoint
no
Follow acceptance steps from issue
@akrishna90
=> As a developer I want to set health check using CFSetHealthCheck

api/apis/org_handler.go, api/apis/org_handler_test.go, api/authorization/errors.go, api/repositories/org_repository.go, api/repositories/org_repository_test.go, api/repositories/route_repository.go, api/repositories/route_repository_test.go, controllers/config/cf_roles/cf_admin.yaml, controllers/controllers/workloads/integration/cfapp_controller_integration_test.go, controllers/reference/cf-k8s-controllers.yaml
#615 
Updates `cf-admin` permissions to delete orgs
- switched to using ForbiddenError in the repo layer
- Log the error in case of InvalidAuthErr
No
Follow acceptance on issue #615 
@davewalter
=> Update cf-admin permissions to delete orgs

api/apis/fake/cfservice_instance_repository.go, api/apis/integration/create_service_binding_test.go, api/apis/integration/integration_suite_test.go, api/apis/service_instance_handler.go, api/apis/service_instance_handler_test.go, api/apis/shared.go, api/main.go, api/repositories/errors.go, api/repositories/guid_to_namespace.go, api/repositories/guid_to_namespace_test.go, api/repositories/service_instance_repository.go, api/repositories/service_instance_repository_test.go, api/repositories/shared.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/packages_test.go, api/tests/e2e/roles_test.go, api/tests/e2e/service_instances_test.go, controllers/config/cf_roles/cf_admin.yaml, controllers/config/cf_roles/cf_space_developer.yaml, controllers/config/cf_roles/cf_space_manager.yaml, controllers/reference/cf-k8s-controllers.yaml
#617 
Implements delete for service instances.
No
See issue #617 
=> Add the DELETE /v3/service_instances endpoint

api/apis/integration/service_binding_test.go, api/apis/service_binding_handler_test.go, api/repositories/service_binding_repository_test.go
While reviewing PR #682 we came up with some ideas on how to further improve some tests. To prevent unnecessary slowdown we are raising this draft with these suggestions. If you  agree with these suggestions feel free to promote and merge this PR.
=> Test improvements for PR #682

api/apis/fake/org_repository.go, api/apis/org_handler.go, api/apis/org_handler_test.go, api/main.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/orgs_test.go, api/tests/e2e/routes_test.go, docs/api.md
#663 
App developer can list domains for an organization
no
#663 
@julian-hj @gnovv
=> Add list domains for organizations

controllers/apis/services/v1alpha1/shared_types.go, controllers/controllers/services/cfservicebinding_controller.go, controllers/controllers/services/cfservicebinding_controller_test.go, controllers/controllers/services/cfserviceinstance_controller.go, controllers/controllers/services/cfserviceinstance_controller_test.go, controllers/controllers/services/integration/cfservicebinding_integration_test.go, controllers/controllers/services/integration/cfserviceinstance_integration_test.go, controllers/controllers/services/integration/suite_integration_test.go, controllers/controllers/shared/index.go, controllers/main.go
#558 
See #558 - implement cleanup of servicebindings
No
See #558 - can use sample config resources and directly apply to cluster
paired w/ @clintyoshimura
=> Delete ServiceBindings when associated ServiceInstance or App is deleted

api/apis/service_binding_handler_test.go, api/payloads/service_binding.go, api/repositories/service_binding_repository.go, api/repositories/service_binding_repository_test.go
[#719](https://github.com/cloudfoundry/cf-k8s-controllers/issues/719)
See #719
No
See #719
paired w/ @matt-royal
=> Implement service binding filtering by app guid and type

controllers/controllers/workloads/cfprocess_controller.go, controllers/controllers/workloads/integration/cfprocess_controller_integration_test.go, scripts/deploy-on-kind.sh
#661 
See #661 
No
See the issue
=> Use correct port for health checks

api/repositories/org_repository.go, api/repositories/org_repository_test.go
No. There is a slack thread here though: https://cloudfoundry.slack.com/archives/C0297673ASK/p1646344103600849
- This is basically a workaround for the problem that HNC reports
readiness before it has completed role binding propagation. If HNC
fixes that (or we stop using it) this code would no longer be
necessary.
- After a new SubNamespaceAnchor is ready, we wait until we have rights in
the namespace before returning OK.
- For now, we test access by listing CFApps with exponential backoff. There might be a more appropriate resource type to use, or we may find a better resource type to test with later (e.g. CFSpace)
No
- With a newly deployed environment
- Run the following:
```
cf co o && cf target -o o && cf create-space s && cf target -s s
```
- This command should work without adding …
=> Add logic to wait for HNC role propagation

controllers/controllers/networking/cfroute_controller.go
#548 
Fix deletion of invalid CFRoute when there is an existing HTTPProxy for the FQDN in another namespace
No
Delete `Validation Webhooks` corresponding to `cf-k8s-controllers` and then follow acceptance steps on #548 
@tcdowney
=> Fix deleting invalid CFRoutes

api/repositories/pod_repository.go, api/repositories/pod_repository_test.go
The current implementation of the `extractIndex` helper will return `-1` when the `CF_INSTANCE_INDEX` is not set. This will then be used to index the `records` slice in `ListPodStats` and cause a panic.
This change replaces any usage of the value `-1` with explicit `error`s and adds tests for the following scenarios:
- the `Pod` does not have an `opi` container
- the `opi` container does not have `CF_INSTANCE_INDEX` set
- `CF_INSTANCE_INDEX` is not a valid integer
- `CF_INSTANCE_INDEX` is negative
=> Improve the handling of invalid `LRP` `Pod`s

scripts/deploy-on-kind.sh
no
This change uses a somewhat cleaner approach to creating secrets using `kubectl apply`
- adds a helper function to generate tls cert secrets, since we do it twice now
- uses kubectl/customize secretGenerator instead of sed/grep to inject the certificates
no
e2e tests should exercise this code.
re-running on top of an already deployed cluster would be another good test.
I did this solo, but any of @georgethebeatle @Birdrock @gnovv @davewalter PTAL
=> Clean up secrets generation in deploy-on-kind.sh

scripts/deploy-on-kind.sh
No.
This adds a `-d/--default-domain` flag to `scripts/deploy-on-kind.sh` which restores the installation of the `vcap.me` domain, which is quite useful for local development and acceptance.
No.
There are some improvements that we could do in our scripts if we could assume GNU/Linux - e.g. use [`getopt`](https://man7.org/linux/man-pages/man1/getopt.1.html) and get optional arguments. My initial idea was to have a generic `-d DOMAIN, --domain-name=DOMAIN` option, but it's quite tricky to do without using `getopt`. `getops` should be available on all machines but does not support long options.
=> Add option to create vcap.me in deploy-on-kind.sh

api/apis/package_handler.go, api/apis/package_handler_test.go, api/repositories/package_repository_test.go, api/repositories/shared_test.go, api/tests/e2e/packages_test.go
#624
This PR fixes the error response for the `GET /v3/package/:guid` endpoint. It also adds test coverage for this endpoint.
No
See #624
@acosta11
=> Fix error response for GET /v3/packages/:guid

api/actions/scale_app_process.go, api/actions/scale_app_process_test.go, api/apis/integration/app_test.go, api/apis/integration/apply_manifest_test.go, api/apis/integration/get_app_env_test.go, api/apis/integration/process_test.go, api/main.go, api/repositories/process_repository.go, api/repositories/process_repository_test.go, api/tests/e2e/apps_test.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/processes_test.go, controllers/config/cf_roles/cf_admin.yaml, controllers/config/cf_roles/cf_space_developer.yaml, controllers/config/cf_roles/cf_space_manager.yaml, controllers/reference/cf-k8s-controllers.yaml
resolves #623 
- Adds RBAC to Scale Process for App
- Updates e2e, repo, and action unit tests to account for RBAC
- Updates cf_admin and cf_space_developer to add list and patch processes to permissions
- Updates cf_space_manager to add list processes to permissions
No
See issue
@julian-hj
=> 623 Add RBAC to Scale App Process

api/apis/integration/role_test.go, api/config/base/apiconfig/role_mappings_config.yaml, api/main.go, api/reference/cf-k8s-api.yaml, api/repositories/role_repository.go, api/repositories/role_repository_test.go, api/tests/e2e/e2e_suite_test.go
#721 
When roles are created (rolebindings are created), users get an additional `cf_user` rolebinding
No.
Run all tests as normal.
@clintyoshimura @tcdowney @gcapizzi
=> Every user bound to cf_user role in the root ns

api/tests/e2e/e2e_suite_test.go, api/tests/e2e/routes_test.go
#642
Add e2e test for list destinations on route endpoint
no
see issue
=> Add e2e test for list destinations

api/actions/scale_app_process.go, api/actions/scale_app_process_test.go, api/apis/app_handler.go, api/apis/process_handler_test.go, api/payloads/process.go, api/repositories/process_repository.go, api/repositories/process_repository_test.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/processes_test.go
#733
This PR adds e2e tests for the `GET /v3/apps/:guid/processes` endpoint
No
See #733
@Birdrock
=> Add e2e tests for GET /v3/apps/:guid/processes

api/repositories/process_repository.go, api/repositories/process_repository_test.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/processes_test.go
#735 
Update patch process endpoint to use the `userClient`
- Added e2e tests for it.
- Fixed failing process repository tests
No
see issue
=> Add RBAC to Patch Process endpoint

api/actions/scale_process.go, api/actions/scale_process_test.go, api/apis/integration/integration_suite_test.go, api/repositories/process_repository_test.go, api/tests/e2e/domains_test.go, api/tests/e2e/spaces_test.go, controllers/config/rbac/role.yaml, controllers/controllers/services/cfservicebinding_controller.go, controllers/controllers/services/cfservicebinding_controller_test.go, controllers/controllers/services/integration/cfservicebinding_integration_test.go, controllers/controllers/services/integration/suite_integration_test.go, controllers/controllers/workloads/integration/suite_integration_test.go, controllers/main.go, controllers/reference/cf-k8s-controllers.yaml, controllers/webhooks/networking/cfdomain_validation_test.go, dependencies/servicebindings-1.0.0.yaml, go.mod, go.sum, scripts/install-dependencies.sh
[#506]
This change makes a k8s ServiceBinding when we create a CF ServiceBinding and the secret exists.
no
[#506]
=> Add functionality to create ServiceBinding

api/actions/scale_app_process_test.go, api/actions/scale_process.go, api/actions/scale_process_test.go, api/apis/integration/build_test.go, api/main.go, api/repositories/package_repository.go, api/repositories/package_repository_test.go, api/tests/e2e/packages_test.go, controllers/config/cf_roles/cf_admin.yaml, controllers/config/cf_roles/cf_space_developer.yaml, controllers/config/cf_roles/cf_space_manager.yaml, controllers/reference/cf-k8s-controllers.yaml
#732
Add RBAC to the List Packages endpoint
No
- Create a Package in a new space with the cf admin or cluster admin user on a cluster with the shim installed.
- Log in to the shim as a new user, create a package a new space, then curl `/v3/packages`
- See that only the package the new user created is returned in the list of resources
cc @gnovv
=> Add RBAC to List Packages endpoint

api/actions/scale_app_process.go, api/apis/app_handler.go, api/apis/job_handler.go, api/apis/job_handler_test.go, api/apis/org_handler.go, api/apis/route_handler_test.go, api/apis/space_handler.go, api/repositories/droplet_repository_test.go, api/repositories/org_repository.go, api/repositories/org_repository_test.go, api/repositories/process_repository.go, api/repositories/process_repository_test.go, api/repositories/route_repository.go, api/repositories/route_repository_test.go, api/tests/e2e/orgs_test.go, api/tests/e2e/processes_test.go, api/tests/e2e/routes_test.go, api/tests/e2e/spaces_test.go, controllers/Dockerfile, controllers/controllers/workloads/cfapp_controller.go, controllers/controllers/workloads/cfapp_controller_test.go, controllers/controllers/workloads/shared.go, go.mod, go.sum, scripts/deploy-on-kind.sh
#724 
Add prefixes to orgs, spaces, processes, and routes to allow operators to identify resources created by cf
No
See issue
@julian-hj
=> Add prefix to org, space, process, and route GUIDS

.github/ISSUE_TEMPLATE/epic.yml
This will make it slightly easier to create new epics. I wasn't able to test the file so not sure it will actually work 🤷
=> Add epic issue template

dependencies/hnc-manager-v0.9.0.yaml
This seems to speed up e2e tests by ~20%
=> Bump the HNC QPS throttle to 200

api/tests/e2e/spaces_test.go
closes #742
Adds RBAC for POST manifest diff
(This was already done by GET Space RBAC, so we just added an e2e test)
No
See issue.
**Note** currently the 403 not authorized case is not possible because the manifest diff is not actually processed beyond checking if the space exists
=> Add RBAC to POST manifest diff

README.md, api/repositories/repositories_suite_test.go, controllers/controllers/workloads/integration/suite_integration_test.go, dependencies/kpack-release-0.5.2.yaml, scripts/install-dependencies.sh
#866 
Bumps kpack to latest 0.5.2 version 
no
`make test` should succeed
=> Bump kpack version to 0.5.2

scripts/run-tests.sh
No
Speed up the run-tests script for e2e tests by creating user certificates and service accounts in parallel
No
`make test-e2e` passes
=> Parallelise cert and service account creation in run-tests.sh

api/tests/e2e/apps_test.go, api/tests/e2e/builds_test.go, api/tests/e2e/domains_test.go, api/tests/e2e/droplets_test.go, api/tests/e2e/e2e_suite_test.go, api/tests/e2e/orgs_test.go, api/tests/e2e/packages_test.go, api/tests/e2e/processes_test.go, api/tests/e2e/roles_test.go, api/tests/e2e/routes_test.go, api/tests/e2e/service_bindings_test.go, api/tests/e2e/service_instances_test.go, api/tests/e2e/spaces_test.go
#867 
Use a common org for all tests
No.
Tests are green
@kieron-dev
=> Setup a commont test org and use it in most tests

.github/workflows/test-pr.yml
No
Since we block merging on having passed a subset of tests, we must run them on every PR. This fixes changes to only text files being unmergeable.
No
After rebasing on this commit, #882 and #898 should be mergeable.
=> Trigger PR tests on any change

README.md
#444 
See issue
No
See issue
@akrishna90
=> Document creating root namespace & granting admin access

api/repositories/app_repository_test.go
Get rid of `Serial` in list app repository tests
* The app repo uses a restricted user client to list apps, therefore
it can only return apps in namespaces the user client is permissioned
to. Therefore it makes no sense to ensure that there are no apps in
other spaces (as the repo does not "see" them at all)
* While being here introduced misc improvements:
* Moved `cfapp2`, `cfApp3`, `space2`, `space3` down to contexts that
really need them (i.e. they are not created for every test)
* Extracted some invocations of the function under test in
`JustBeforeEach` to delete a bunch of code repetition
No
Green tests
=> Remove the `Serial` constraint from ListApp repo test

api/repositories/package_repository_test.go
The package repo uses a unprivileged client, i.e. it only sees
packages from allowed namespaced. Therefore it makes no sense to execute
list tests sequentially as the package repo does not "hear" the noise
for neightbour nodes anyway.
While being here:
* Removed all `AfterEach`es - test environment is thrown away so no
cleanup really needed
* Moved the code under test in `JustBeforeEach` so that the invocation
under test is not invoked explicitly in `It`s
* Reordered the `ListPackages` contexts to better reuse parent contexts'
resources
* Reduced the number of resources being created in nested context in
favour of using the resources created in the top-level `BeforeEach`
No
Green tests
=> Remove the `Serial` decorator in ListPackages test

api/repositories/service_binding_repository_test.go
The repository is using a unprivileged client so the repo cannot see
service bindings created in unauthorised namesaces. Therefore using the
`Serial` decorator when listing packages does not make sense.
While being here, the code under test has been moved to `JustBeforeEach`
to remove duplicate invocations in the `It`s
No
Green tests
=> Remove the `Serial` decorator from ListServiceBindings test

api/repositories/service_instance_repository_test.go
The service instance repo can only list service instances in spaces it
has permissions on (via using a unprivileged user). Therefore, using
`Serial` makes no sense as noise from neighbour Ginkgo nodes is
unnoticed.
While being here:
* Move code under test to `JustBeforeEach`
* Remove all `Eventually`s as repository code is synchronous. If we
assume that the CRUD k8s api is not synchronous, then we should be
putting `Eventually` around all k8s calls, which is apparently not
needed and is gross.
No
Green tests
=> Remove the `Serial` decorator from service instance repo tests

controllers/config/default/manager_auth_proxy_patch.yaml, controllers/reference/korifi-controllers.yaml
[#978]
This addresses CVE-2021-3121
We certainly hope not
@davewalter
=> Update kube-rbac-proxy to 0.12.0

api/apis/org_handler.go, api/apis/org_handler_test.go, api/config/base/rbac/role.yaml, api/reference/korifi-api.yaml, api/repositories/app_repository_test.go, api/repositories/build_repository_test.go, api/repositories/droplet_repository_test.go, api/repositories/image_repository_test.go, api/repositories/namespace_retriever_test.go, api/repositories/org_repository.go, api/repositories/org_repository_test.go, api/repositories/package_repository_test.go, api/repositories/process_repository_test.go, api/repositories/repositories_suite_test.go, api/repositories/role_repository_test.go, api/repositories/route_repository_test.go, api/repositories/service_binding_repository_test.go, api/repositories/service_instance_repository_test.go, api/tests/e2e/orgs_test.go, controllers/apis/workloads/v1alpha1/cforg_types.go, controllers/config/cf_roles/cf_admin.yaml, controllers/config/cf_roles/cf_org_manager.yaml, controllers/config/cf_roles/cf_org_user.yaml, controllers/config/cf_roles/cf_root_namespace_user.yaml, controllers/config/crd/bases/workloads.cloudfoundry.org_cforgs.yaml, controllers/reference/korifi-controllers.yaml
Closes #765
See issue
See issue
@gnovv 
We know that we broke at least one e2e test, due to the missing uniqueness validation on CFOrg.spec.name. We either need to pend this test or block this PR on the work to add that validation.
=> Switch OrgRepository to use CFOrg resources

api/authorization/user_client_factory_test.go, api/config/overlays/pr-e2e/apiconfig/korifi_api_config.yaml, api/config/overlays/pr-e2e/kustomization.yaml
#1015
Rename cf-k8s.cf -> korifi.cf-app.com
No
CI still works
=> Prepare to rename ci domain to korifi.cf-app.com

scripts/common.sh, scripts/deploy-on-kind.sh, scripts/samples/deploy-release.sh
No
Put the script function `create_tls_secret` in a shared location so that it can be used in samples/deploy-release.sh.
We also make the OpenSSL / LibreSSL difference more explicit here, and fail to run if the openssl command describes itself as anything else.
No
The `deploy-on-kind.sh` script continues to work on linux and macs.
=> Move create_tls_secret to common.sh

.github/workflows/test-build-push-main.yml
No. 
But related to changes introduced in #1002 
Fixes typo error caused by copy pasta.
No
Github actions on main should succeed
=> Fix artifact name to upload in github actions

controllers/controllers/networking/cfdomain_controller.go, controllers/controllers/networking/cfroute_controller.go, controllers/controllers/networking/cfroute_controller_test.go, controllers/controllers/networking/integration/suite_integration_test.go, controllers/controllers/services/cfservicebinding_controller.go, controllers/controllers/services/cfservicebinding_controller_test.go, controllers/controllers/services/cfserviceinstance_controller.go, controllers/controllers/services/cfserviceinstance_controller_test.go, controllers/controllers/services/integration/suite_integration_test.go, controllers/controllers/workloads/cfapp_controller.go, controllers/controllers/workloads/cfapp_controller_test.go, controllers/controllers/workloads/cfbuild_controller.go, controllers/controllers/workloads/cfbuild_controller_test.go, controllers/controllers/workloads/cforg_controller.go, controllers/controllers/workloads/cfpackage_controller.go, controllers/controllers/workloads/cfpackage_controller_test.go, controllers/controllers/workloads/cfprocess_controller.go, controllers/controllers/workloads/cfprocess_controller_test.go, controllers/controllers/workloads/integration/suite_integration_test.go, controllers/main.go, kpack-image-builder/config/manager/kustomization.yaml
closes #921 
Adds remaining constructors for CF Controllers
No
Tests pass, push app works
=> Add Remaining Controller Constructors

api/actions/read_app_logs.go, api/actions/read_app_logs_test.go, api/repositories/build_repository.go, api/repositories/pod_repository.go, kpack-image-builder/Makefile, scripts/deploy-on-kind.sh
#1078
This PR adds timestamps to the build log output and updates the log API endpoint to respect the `descending` query parameter.
No
See #1078
@julian-hj
=> Add timestamps to build logs

INSTALL.md
[#1097]
Add documentation for using DockerHub/GCR image registry configuration
no
See issue
@davewalter
=> Document using for DockerHub/GCR registry config

scripts/deploy-on-kind.sh
No
1. Use persistent storage. This _seems_ to stop the kpack errors when
builds fail due to a kpack image not being found in the local
registry
2. Move containerd config change to the cluster config so we don't have
to restart containerd on the control-plane or wait 10 seconds.
We hope that this would solve the problem of droplets not being found thus making e2e tests time out
No
Consistent green e2e tests run
@kieron-dev
=> Kind local registry improvements

api/actions/read_app_logs.go, api/actions/read_app_logs_test.go
#1094 
Added implementation of start_time to app logs
- truncate app logs before start_time
- clean up sleeps in unit tests
- enforce proper chronological ordering of build and run logs (instead
of assuming that they will be in the correct order.)
- enforce length limit (since we glue together build and run logs, each
of which might be as long as the limit.)
no.
#1094
=> Added implementation of start_time to app logs

api/handlers/task_handler_test.go, api/presenter/task.go
#1017
Remove unnecessary fields from task response
Nobody uses these so far and they were hardcoded. They are going to be
added as part of future stories.
Green tests
=> Remove unnecessary fields from task response

api/actions/manifest.go, api/actions/manifest_test.go, api/handlers/shared.go, api/handlers/space_manifest_handler_test.go, api/payloads/manifest.go, tests/e2e/e2e_suite_test.go, tests/e2e/spaces_test.go
#1206 
See Issue
no
See Issue
@akrishna90
=> App Developer can request a "random route" via their app manifest

api/handlers/task_handler_test.go, api/presenter/task.go, api/repositories/task_repository.go, api/repositories/task_repository_test.go, controllers/api/v1alpha1/cftask_types.go, controllers/config/config.go, controllers/config/crd/bases/korifi.cloudfoundry.org_cftasks.yaml, controllers/controllers/networking/integration/suite_integration_test.go, controllers/controllers/workloads/cfapp_controller.go, controllers/controllers/workloads/cfapp_controller_test.go, controllers/controllers/workloads/cftask_controller.go, controllers/controllers/workloads/cftask_controller_test.go, controllers/controllers/workloads/integration/cftask_controller_integration_test.go, controllers/controllers/workloads/integration/suite_integration_test.go, controllers/main.go
#1197 
Introduce default memory and disk values both in the rest response and in the CRD status
No
See #1197
@gcapizzi
=> Task default memory and disk

tests/e2e/helpers/fail_handler.go
https://github.com/cloudfoundry/korifi/issues/1254
Do not use `Expect` in the fail handler
`Expect` internally panics which might be a reason for going into an
endless loop invoking the handler
No
None
=> Do not use `Expect` in the fail handler

api/repositories/task_repository_test.go
No
Wait for the dummy controller go routine to complete in `AfterEach` so
that the killchannel is not overwritten by the next `It`
No
N/A
=> Fix data race in test

controllers/controllers/services/cfservicebinding_controller.go, controllers/controllers/services/cfservicebinding_controller_test.go
[#1238]
We had unnecessary else conditions creating extra nesting.
no
n/a
=> Clean up if/else logic

api/actions/manifest.go, controllers/controllers/workloads/shared.go
No
Fix unsafe references to local variables in for loop
no
Tests pass
@akrishna90
=> Fix unsafe refs to local variables in for loop

scripts/install-dependencies.sh
https://github.com/cloudfoundry/korifi/issues/1221
Bump eirini-controller to 0.5.0
No
N/A
@kieron-dev
=> Bump eirini-controller to 0.5.0

api/actions/manifest_test.go, controllers/webhooks/cf_validation_errors.go, controllers/webhooks/networking/cfdomain_validator.go, controllers/webhooks/networking/cfdomain_validator_test.go, controllers/webhooks/networking/cfroute_validator.go, controllers/webhooks/networking/cfroute_validator_test.go
#1086 
See issue
No
See issue
@Birdrock
=> Reject requests that updates immutable fields

api/handlers/org_handler.go, tests/e2e/orgs_test.go
Please critique this, I wanted to spend some time digging into the weeds a little and did it solo.
#1236 
Updating the messaging so that the user has a little more detail.
No
See #1090 
=> Adds additional details to the long cert warning.

api/handlers/whoami_handler.go, tests/e2e/whoami_test.go
No
Log errors in `whoami` when getting identity fails
No
N/A
@kieron-dev
=> Log errors in `whoami` when getting identity fails

scripts/install-dependencies.sh
No
Install local eirini-controller via setting the `EIRINI_VERSION` env var to `local`
No
N/A
@kieron-dev
=> Install local eirini-controller

.github/workflows/test-pr.yml, Makefile
No
Run statefulset-runner tests in the PR flow
No
N/A
@kieron-dev
=> Run statefulset-runner tests in the PR flow

controllers/api/v1alpha1/cftask_types.go, controllers/config/rbac/role.yaml, controllers/controllers/workloads/cfapp_controller.go, controllers/controllers/workloads/cftask_controller.go, controllers/controllers/workloads/cftask_controller_test.go, controllers/controllers/workloads/integration/cftask_controller_integration_test.go, controllers/controllers/workloads/integration/fixtures/vendir.lock.yml, controllers/controllers/workloads/integration/fixtures/vendor/eirini-controller/deployment/helm/templates/core/lrp-crd.yml, controllers/controllers/workloads/integration/fixtures/vendor/eirini-controller/deployment/helm/templates/core/task-crd.yml, go.mod, go.sum, scripts/install-dependencies.sh
https://github.com/cloudfoundry/korifi/issues/1031
Introduce status conditions on the task object:
* `Started` - when the eirini task starts
* `Succeeded` - when the task succeeds
* `Failed` - when the task fails
No
See story
@kieron-dev
=> Introduce task state conditions on the task object

api/handlers/fake/cftask_repository.go, api/handlers/task_handler.go, api/handlers/task_handler_test.go, api/main.go, api/presenter/task.go, api/repositories/task_repository.go, api/repositories/task_repository_test.go, tests/e2e/tasks_test.go
https://github.com/cloudfoundry/korifi/issues/1037
Introduce an endpoint in the API shim to list tasks
No
See story
@kieron-dev
=> Introduce `GET /v3/tasks` endpoint

tests/e2e/tasks_test.go
#1037
We must check list tasks includes our expected results, rather than that it equals just our expected results since other tests might be running in parallel
No
e2es pass
=> Remove potential race in e2e task test

tests/e2e/helpers/fail_handler.go
...so that we can run unfiltered in CI to get more info about flaky tests
=> Make filtering by correlationId configurable

api/handlers/fake/cftask_repository.go, api/handlers/task_handler.go, api/handlers/task_handler_test.go, api/repositories/task_repository.go, api/repositories/task_repository_test.go, tests/e2e/tasks_test.go
#1038 
Implement the `/v3/apps/:appGUID/tasks` endpoint
No
Se #1038
=> Implement listing tasks for an app

statefulset-runner/controllers/integration/runworkload_controller_test.go
#1306 
- We saw flakes in the runworkload controller integration tests when
updating the statefulset from test code.
- Switching to Patch instead of Update allows the test code to fiddle
with the status of the StatefulSet even when something else has
touched it from another thread.
No.
#1306 
=> Use Patch to fix integration test races

api/repositories/task_repository.go, tests/e2e/apps_test.go
This PR fixes an issue with implicit memory aliasing in a for loop.
No
=> Avoid implicit memory aliasing in a for loop

tests/e2e/apps_test.go, tests/e2e/routes_test.go
#519 
Adds missing E2E test for `GET /v3/jobs/{guid}` endpoint
No
E2E tests should pass
=> Adds missing E2E test for `GET /v3/jobs/{guid}` endpoint

api/authorization/retrying_k8s_client.go, api/authorization/retrying_k8s_client_test.go
No
The k8s retrying client does not retry on Korifi webhook validation errors
Webhook validation errors are received by the shim as forbidden errors that
have a status reason containing the json marshalled validation error and status
code `Forbidden`.
It makes no sense for the retrying client to retry the operation (e.g. `Patch`)
on such forbidden errors as the validating webhook would consistently return
the same error over and over again
No
Green tests
=> Do not retry on webhook validation errors

api/repositories/service_binding_repository.go, api/repositories/service_binding_repository_test.go, controllers/webhooks/workloads/integration/cfspace_validation_integration_test.go
No
Run `make fmt`, push the result
No
N/A
=> gofmupt the code

INSTALL.md, controllers/controllers/workloads/integration/cforg_controller_integration_test.go, controllers/controllers/workloads/integration/cfspace_controller_integration_test.go, controllers/controllers/workloads/shared.go, dependencies/cf-setup.yaml, scripts/install-dependencies.sh
#1286
Only role-bindings with annotation `cloudfoundry.org/propagate-cf-role` set to `true` will be propagated
No
See issues #1286
=> Use opt-in strategy for role-binding propagation

api/handlers/oauth_token_handler.go
No
Fix formatting
No
1. Run `make fmt`
2. See no diff
=> Fix formatting

api/repositories/task_repository_test.go
No
No need to create our own timer and channel as we can use a context with
timeout
No
Green tests
@kieron-dev
=> Use context.WithTimeout in client.Watch

kpack-image-builder/Makefile, scripts/run-tests.sh, statefulset-runner/Makefile
No
This PR updates the run-tests script to install and use the latest version of envtest.
No
Tests pass.
=> Update run-tests to use latest envtest

controllers/main.go
No.
Allow local controller runs. Provide method to disable controllers to run webhooks in cluster without controller manager.
No.
@acosta11 @davewalter
=> Support local controller runs

api/repositories/pod_repository.go, api/repositories/pod_repository_test.go
#1084 
This PR fixes the CPU reported in the `/v3/processes/<guid>/stats` endpoint.
No
See #1084 
@Birdrock
=> Fix CPU reported in process stats endpoint

controllers/controllers/workloads/cftask_controller.go, controllers/controllers/workloads/cftask_controller_test.go, controllers/controllers/workloads/integration/cftask_controller_integration_test.go, controllers/controllers/workloads/integration/suite_integration_test.go, controllers/main.go
#1386
When creating an eirini task, set its environment to match the associated CFApp
=> Set env from CFApp into the Eirini Task

dependencies/kpack/cluster_stack.yaml
No
Allows ruby native extentions to compile and probably more.
No
Green tests
@kieron-dev
=> Use the full cnb builder image

controllers/controllers/networking/cfroute_controller.go, controllers/controllers/services/cfservicebinding_controller.go, controllers/controllers/services/cfservicebinding_controller_test.go, controllers/controllers/services/cfserviceinstance_controller.go, controllers/controllers/services/integration/cfservicebinding_integration_test.go, controllers/controllers/workloads/env/builder.go, tests/e2e/apps_test.go
#1352
Reconcile VCAP services secret on cf service binding delete
No
See issue
@Birdrock @clintyoshimura
=> cf unbind-service cleans up credentials in VCAP_SERVICES

dependencies/kpack/cluster_store.yaml, kpack-image-builder/controllers/imageprocessfetcher/image_process_fetcher.go
#1439 
Fixes an issue with how command and args were processed. The issue lead to a situation where args would be dropped.
No.
Push a ruby rackup app (e.g.: CATS hello-world)
@akrishna90 @davewalter @matt-royal
=> Fix command string truncation in bash string cmds

docs/api.md
- Make the structure consistent
- Remove any information already present in the official docs
- Always link to the official docs
- Use the same order as the official docs
- Add missing endpoints
- Update outdated entries
This is hard to evaluate from the diff, but you can take a look at the [new version of the document](https://github.com/cloudfoundry/korifi/blob/api-docs-cleanup/docs/api.md).
=> Rewrite the API docs

tests/smoke/smoke_test.go
No
Do the equivalent of echo cf-admin | cf login in the smoke test code
No
Green tests
@kieron-dev
=> Simplify login code in smoke tests

INSTALL.md
No
Bump eirini version and change the helm install command to make it work
No
Install the release
@gcapizzi
=> Fix eirini version and install command

kpack-image-builder/controllers/buildworkload_controller_test.go
No
These might have caused flakes similar to this one:
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-main/builds/212
No
Green tests
@eirini
=> Bump eventually timeouts to avoid flakes

job-task-runner/controllers/integration/taskworkload_controller_test.go, job-task-runner/controllers/taskworkload_controller.go
https://github.com/cloudfoundry/korifi/issues/1400
Set limits to task workload pods
No
See story
@kieron-dev
=> Set limits to task workload pods

scripts/deploy-on-kind.sh
No
This PR adds a serial option to the `deploy-on-kind.sh` script. This allows the user to see the real-time output from the deploy of each component, which is useful for debugging.
No
Run the script with the `-s` flag and see each component install with real-time output.
@matt-royal
=> Add serial option to deploy-on-kind script

.github/dependabot.yml, api/Dockerfile, api/remote-debug/Dockerfile, controllers/Dockerfile, controllers/remote-debug/Dockerfile, job-task-runner/Dockerfile, kpack-image-builder/Dockerfile, statefulset-runner/Dockerfile
No
This PR adds the `job-task-runner` Dockerfile to the dependabot config.
Hopefully not.
Deploy everything.
=> Add job-task-runner to the dependabot config

api/apierrors/errors.go, api/handlers/app_handler.go, api/handlers/app_handler_test.go, api/handlers/fake/cfapp_repository.go, api/handlers/shared.go, api/payloads/app.go, api/payloads/shared.go, api/presenter/app.go, api/repositories/app_repository.go, api/repositories/app_repository_test.go, api/repositories/build_repository_test.go, api/repositories/buildpack_repository_test.go, api/repositories/domain_repository_test.go, api/repositories/image_repository_test.go, api/repositories/namespace_retriever_test.go, api/repositories/org_repository_test.go, api/repositories/package_repository_test.go, api/repositories/pod_repository_test.go, api/repositories/process_repository_test.go, api/repositories/shared.go, api/repositories/shared_test.go, controllers/webhooks/cf_validation_errors.go
#1359 
See issue
No
See issue
@acosta11
=> App Developer can view and set labels/annotations on Apps

controllers/controllers/workloads/integration/cfprocess_controller_integration_test.go, tests/matchers/represents_resource_quantity.go
No
Fixes a small typo in the name of a recently-added matcher
No
N/A
=> Remove incorrect 's' from RepresentResourceQuantity

api/handlers/app_handler_test.go, api/handlers/fake/org_repository.go, api/handlers/org_handler.go, api/handlers/org_handler_test.go, api/payloads/org.go, api/presenter/org.go, api/repositories/app_repository.go, api/repositories/build_repository_test.go, api/repositories/buildpack_repository_test.go, api/repositories/org_repository.go, api/repositories/org_repository_test.go, api/repositories/repositories_suite_test.go, controllers/controllers/workloads/cfprocess_controller_test.go, kpack-image-builder/controllers/buildworkload_controller_test.go, statefulset-runner/controllers/integration/appworkload_controller_test.go, tests/matchers/represents_resource_quantity.go
#1368
See issue
no
See issue
@matt-royal
=> Update labels/annotations on Orgs

api/handlers/app_handler.go, api/handlers/app_handler_test.go, api/handlers/auth_aware_handler.go, api/handlers/fake/space_repository.go, api/handlers/org_handler_test.go, api/handlers/space_handler.go, api/handlers/space_handler_test.go, api/payloads/app.go, api/payloads/org.go, api/payloads/space.go, api/presenter/app.go, api/presenter/org.go, api/presenter/service_instance.go, api/presenter/shared.go, api/presenter/space.go, api/repositories/app_repository.go, api/repositories/app_repository_test.go, api/repositories/org_repository.go, api/repositories/org_repository_test.go, api/repositories/shared.go, api/repositories/space_repository.go, api/repositories/space_repository_test.go, controllers/controllers/workloads/cfprocess_controller_test.go, scripts/install-dependencies.sh
=> Add PATCH /v3/spaces/:guid endpoint

api/handlers/integration/route_test.go, api/repositories/app_repository_test.go, controllers/controllers/services/integration/cfserviceinstance_integration_test.go, controllers/controllers/workloads/cfbuild_controller.go, controllers/controllers/workloads/cforg_controller.go, controllers/controllers/workloads/cfprocess_controller.go, controllers/controllers/workloads/cfspace_controller.go, controllers/controllers/workloads/integration/cfprocess_controller_integration_test.go, controllers/controllers/workloads/integration/cfspace_controller_integration_test.go, job-task-runner/controllers/taskworkload_controller_test.go, kpack-image-builder/controllers/buildreconcilerinfo_controller_test.go, kpack-image-builder/controllers/buildworkload_controller.go, statefulset-runner/controllers/appworkload_controller.go
No
Small refactor for readability
No
PR tests still pass
=> Use client.ObjectKeyFromObject where possible

tests/e2e/apps_test.go, tests/e2e/e2e_suite_test.go
Related to a suggestion in https://github.com/cloudfoundry/korifi/issues/1505. See the following comment:
https://github.com/cloudfoundry/korifi/issues/1505#issuecomment-1222218545
Adds a test to verify that some key child resources for an app (packages, builds, processes) are deleted when the parent app is deleted.
No, just enhances an e2e test.
Tests continue to pass.
@gcapizzi
=> Add e2e test to verify key CFApp-owned resources are deleted

controllers/controllers/workloads/cforg_controller.go, controllers/controllers/workloads/cfprocess_controller.go, controllers/controllers/workloads/cfspace_controller.go
No
This PR fixes loop accessor usage to avoid implicit memory aliasing in for loops.
No
Tests pass.
=> Fix loop accessor usage

controllers/controllers/workloads/cfprocess_controller.go, controllers/controllers/workloads/integration/cfprocess_controller_integration_test.go
#1201
See issue
No
See issue
@gcapizzi
=> Specify an ephemeral storage request for AppWorkloads

api/repositories/service_binding_repository_test.go
No
Wait for the controller simulation to exit on `AfterEach`. Not doing that might
cause flakes as the simulation routine carries on after the test has finished
No
Green tests
=> Wait for the controller simulation to exit in `AfterEach`

api/actions/manifest.go, api/actions/manifest_test.go, api/handlers/build_handler.go, api/handlers/build_handler_test.go, api/handlers/integration/build_test.go, api/main.go, api/payloads/build.go, api/payloads/manifest.go, api/repositories/app_repository_test.go, controllers/api/v1alpha1/buildworkload_types.go, controllers/api/v1alpha1/zz_generated.deepcopy.go, controllers/config/crd/bases/korifi.cloudfoundry.org_buildworkloads.yaml, controllers/controllers/workloads/cfbuild_controller.go, controllers/controllers/workloads/integration/cfbuild_controller_integration_test.go, job-task-runner/controllers/taskworkload_controller.go, kpack-image-builder/controllers/buildworkload_controller.go, kpack-image-builder/controllers/buildworkload_controller_test.go
=> Error when buildpack is specified during first push

controllers/controllers/workloads/cfapp_controller.go, controllers/controllers/workloads/integration/cfapp_controller_integration_test.go
Vaguely related to #1585.
Processes created during manifest application used to ignore the command coming from the droplet if any. This lead to processes without a command, which resulted in the container entrypoint taking over. This was accidentally working for the `web` process (as CNBs set it as the main image command) but not correct in general.
Yes. Processes created via the manifest will now get their command defaulted to the one coming from the droplet, while previouly there were just getting ignored.
=> Do not ignore droplet process command on start

api/actions/manifest_test.go, api/payloads/destination.go, api/payloads/manifest.go, api/payloads/manifest_test.go, controllers/api/v1alpha1/cfprocess_webhook.go, controllers/controllers/workloads/cftask_controller.go
#1585
Remove some  code duplication around default cfprocess valuse as they are taken care of by the webhook
No
Green tests
@kieron-dev
=> Remove duplicate defaulting

api/actions/manifest/normalizer_test.go
No
Combine the table tests for setting app-level values onto the web process, whether the process already exists or not
No
@kieron-dev
=> Refactor normalizer_test

controllers/api/v1alpha1/buildworkload_types.go, controllers/controllers/workloads/cfprocess_controller.go, controllers/controllers/workloads/integration/cfprocess_controller_integration_test.go
#1665 
This PR backfills missing tests for the liveness and readiness probes for all healthcheck types. It also refactors the implementation
No
Tests pass
=> Backfill probe tests

api/actions/manifest/applier_test.go, api/payloads/manifest.go, api/payloads/manifest_test.go, api/repositories/process_repository.go, api/repositories/process_repository_test.go, tests/e2e/apps_test.go, tests/e2e/e2e_suite_test.go, tests/e2e/processes_test.go, tests/e2e/spaces_test.go
#1696
* Make DesiredInstances in repo create message a pointer type
* Extend e2e manifest test to check instance count on web process
No
See #1696
@kieron-dev @gcapizzi
=> Ensure web process instances always correctly defaults

kpack-image-builder/controllers/buildworkload_controller_test.go
No
Use `'k8s.Patch` to update objects' status in tests. Using `Updated` causes flakes
No
All tests pass
@kieron-dev
=> Use `k8s.Patch` in kpack builder tests

Makefile, job-task-runner/Makefile, kpack-image-builder/Makefile, statefulset-runner/Makefile
#1704
Those targets are now explicit when invoking helm instead of invoking
each other. That makes them easier to reason about.
No
`make deploy-xxx` works
@kieron-dev
=> Fix deploy-xxx make targets

HACKING.md, INSTALL.md, INSTALL_kind.md, helm/README.values.md
https://github.com/cloudfoundry/korifi/issues/1704
Update installation docs with helm chart instructions
No
Deploy Korifi by following the INSTALL.md
@kieron-dev
=> Update installation docs with helm chart instructions

Makefile, helm/api/templates/role.yaml, helm/controllers/templates/manifests.yaml, helm/kpack-image-builder/templates/manifests.yaml, helm/statefulset-runner/templates/manifests.yaml, kpack-image-builder/Makefile, scripts/assets/kind-config.yaml, statefulset-runner/Makefile
No
Make `scripts/deploy-on-kind.sh` work on macOS again
No, it fixes a breaking change
Run `scripts/deploy-on-kind.sh` in both a linux and macOS environment and confirm that it results in a healthy korifi installation
=> Use gsed on macOS and sed on linux

scripts/assets/kind-config.yaml
No
Fix `deploy-on-kind` by fixing the kind cluster config yaml
No
`scripts/deploy-on-kind.sh` works
=> Fix kind cluster config yaml

helm/controllers/templates/pre-install-cfroot-namespace.yaml
No
We need patch permission in case the namespace already exists
No
=> Add patch permission to cf namespace creator

api/main.go
[#1179]
- use zapr logging with RFC3339 timstamp format
- fix the initial "serving" log message to use the logger from controller-runtime
- (all other logging appears to correctly use the controller runtime already)
[#1179]
@matt-royal
=> Use consistent logging format for korifi-api

scripts/deploy-on-kind.sh
No
* Make local registry the default
- the `-l` flag has been removed
* New flag for using a custom registry
- You need to supply 6 (six!) env vars to make this work:
* DOCKER_SERVER
* DOCKER_USERNAME
* DOCKER_PASSWORD
* PACKAGE_REGISTRY
* DROPLET_REGISTRY
* KPACK_BUILDER_REPOSITORY
* Remove the check that stops you using debug without a local registry
Yes - for devs running `deploy-on-kind.sh`
=> Enable deploy-on-kind custom registries

controllers/controllers/workloads/cfspace_controller.go, controllers/controllers/workloads/integration/cfspace_controller_integration_test.go
[#1802]
In kubernetes v1.23 and before, secrets were automatically created for service accounts' tokens. These secrets were automatically added to the service account resource. Our code was ignoring this behavior and rewrote the serviceaccount.secrets on every update. This led to a recreation of the service account's token secret any time the CFSpace reconciler ran.
No
[#1802]
@akrishna90
=> Don't clobber secrets on propagated service accounts

helm/api/templates/_helpers.yaml, helm/api/templates/configmap.yaml, helm/api/templates/deployment.yaml, helm/api/values.schema.json, helm/api/values.yaml, helm/controllers/templates/_helpers.yaml, helm/controllers/templates/deployment.yaml, helm/controllers/values.schema.json, helm/job-task-runner/templates/_helpers.yaml, helm/job-task-runner/templates/deployment.yaml, helm/job-task-runner/values.schema.json, helm/korifi/templates/_helpers.yaml, helm/korifi/templates/admin-user.yaml, helm/korifi/values.schema.json, helm/kpack-image-builder/templates/_helpers.yaml, helm/kpack-image-builder/templates/deployment.yaml, helm/kpack-image-builder/values.schema.json, helm/kpack-image-builder/values.yaml, helm/statefulset-runner/templates/_helpers.yaml, helm/statefulset-runner/templates/deployment.yaml, helm/statefulset-runner/values.schema.json
#1807
Use json schemas to describe required values in the korifi helm values files
No
Installing korifi should continue to work
=> Helm value required validation

controllers/controllers/workloads/cfspace_controller.go, controllers/controllers/workloads/integration/cfspace_controller_integration_test.go
[#1811]
Before this change, the Secrets and ImagePullSecrets were set on creation and never updated
No
See [#1811]
@julian-hj
=> Update secrets on propagated service accounts on all updates

api/main.go
[#1786]
- previously, the API didn't notice when certificates or keys were rotated. As a result, every 60 days when cert manager rotated the internal api certificate, TLS requests via contour would start to fail until the API deployment was restarted.
- this commit uses the the cert watcher from the controller runtime to keep tabs on the certs in the filesystem, so that we notice new certs as soon as they happen.
No.
[#1786]
@matt-royal
=> Listen for changes to api internal cert

HACKING.md
No
- update prerequisite list (e.g. add helm, remove kustomize)
- update deploy-on-kind syntax
- update test instructions to include `make test-e2e`
- lots of format tweaks
No
Check if the hacking guide seems more correct than before? 🤷🏻‍♂️
I think it's just @akrishna90 and @acosta11 in the US office this week...PTAL
=> Tidy up HACKING.md

controllers/api/v1alpha1/cfroute_types.go, controllers/api/v1alpha1/cftask_types.go, helm/controllers/templates/crds/korifi.cloudfoundry.org_cfroutes.yaml, helm/controllers/templates/crds/korifi.cloudfoundry.org_cftasks.yaml
[#1751]
- CFRoute and CFTask field descriptions had minor inaccuracies or missing detail.
No.
[#1751]
@akrishna90 @acosta11 PTAL
=> Improve spec field descriptions on CRDs

Makefile
#1778
Extract component list in common vars
This makes it easy to add/remove components
No
N/A
=> Extract component list in common vars

api/main.go
[#1179]
We found some additional cases where low level loggers from klog and the http server's log.Logger (the golang standard library logger) were getting into the log stream unformatted. This PR redirects those log streams.
- set klog.Log to use the zapr logger
- create an io.Writer shim to collect error messages from the http server ErrorLogger and redirect them to our zapr logger's Error() method.
No
some details are in the comments of [#1179]
=> Format logs from low level loggers

controllers/api/v1alpha1/cftask_types.go, helm/controllers/templates/crds/korifi.cloudfoundry.org_cftasks.yaml
#1751 
Update CRD descriptions
No.
Check cases noted in issue.
=> Updated CRD descriptions

controllers/controllers/networking/integration/cfroute_controller_integration_test.go
No
* Add a test to verify the controller finalizer (updates contour proxy
includes when a duplicate route is deleted)
* Use `Eventually(func(g Gomega){}).Should(Succeed())` wherever makes
sense to improve test readability
* Remove `eventually` from `It` descriptions (as evenuality is an
implementation detail)
No
N/A
@kieron-dev
=> Improve the CFRoute controller integration test

api/repositories/app_repository_test.go, api/repositories/task_repository_test.go, controllers/controllers/workloads/cfspace_controller_test.go
no
Rename instances of the word "dummy" in codebase
no
All tests pass
@julian-hj
=> Rename the word dummy in codebase

tests/e2e/e2e_suite_test.go
No
We have been creating test apps with the default 1GB memory. This can
overload CI and we see lots of pending app pods because there isn't
enough memory to start them all at once.
By creating apps via apply manifest, we can set a smaller memory limit.
This also has a nice side effect of being closer to the CF CLI way of
creating an app.
No
E2Es continue to run OK in CI. Hopefully faster and more reliably.
=> Limit test app's memory to 128MB

.github/workflows/add-to-icebox.yml
This uses [`actions/add-to-project`](https://github.com/actions/add-to-project) to automatically add any new issue to the icebox in our backlog project.
=> Add workflow to add any new issue to the icebox

api/handlers/build_handler.go, api/handlers/build_handler_test.go, api/payloads/build_test.go, api/payloads/domain_test.go, api/payloads/package_test.go, api/payloads/payloads_suite_test.go
#1996
Move payload tests from handlers to payloads package
No
All tests green
@davewalter
=> Move build payload tests from handlers to payloads

INSTALL.EKS.md, INSTALL.md
#1924
Document the process of installing Korifi on EKS using ECR as the container registry.
Hopefully not, it's just docs.
Follow the instructions.
@davewalter
=> Document installation on EKS with ECR

api/handlers/apis_suite_test.go, api/handlers/app_handler.go, api/handlers/build_handler.go, api/handlers/buildpack_handler.go, api/handlers/domain_handler.go, api/handlers/droplet_handler.go, api/handlers/integration/integration_suite_test.go, api/handlers/job_handler.go, api/handlers/log_cache_handler.go, api/handlers/oauth_token_handler.go, api/handlers/org_handler.go, api/handlers/package_handler.go, api/handlers/process_handler.go, api/handlers/resource_matches_handler.go, api/handlers/role_handler.go, api/handlers/root_handler.go, api/handlers/root_v3_handler.go, api/handlers/route_handler.go, api/handlers/service_binding_handler.go, api/handlers/service_instance_handler.go, api/handlers/service_route_binding_handler.go, api/handlers/space_handler.go, api/handlers/space_manifest_handler.go, api/handlers/task_handler.go, api/handlers/whoami_handler.go, api/main.go, go.mod, go.sum
#2010
This replaces `gorilla/mux` with the router from `chi`.
No.
@davewalter
=> Replace `gorilla/mux` with `chi`

HACKING.md, INSTALL.EKS.md, INSTALL.kind.md, INSTALL.md, scripts/assets/kind-config.yaml, scripts/deploy-on-kind.sh
https://github.com/cloudfoundry/korifi/issues/1904
Fix docs
=> Fix docs to reflect merged helm chart

api/Dockerfile, api/remote-debug/Dockerfile, controllers/Dockerfile, controllers/remote-debug/Dockerfile
No
Bump golang in Dockerfiles
no
No functional change
=> Bump golang in Dockerfiles

api/actions/manifest/applier.go, api/actions/manifest/applier_test.go, api/handlers/route.go, api/handlers/route_test.go, api/repositories/route_repository.go, api/repositories/route_repository_test.go, helm/korifi/controllers/cf_roles/cf_admin.yaml, helm/korifi/controllers/cf_roles/cf_space_developer.yaml
https://github.com/cloudfoundry/korifi/issues/1659
=> Push remove destination logic down to repo layer

helm/korifi/.gitignore
no
This was useful when we had subcharts, and now stops you noticing that
the old charts subdir should be removed.
no
=> Remove helm gitignore

controllers/controllers/networking/cfdomain_controller.go
No
Fix implicit memory aliasing in a for loop.
No
Everything works.
=> Fix implicit memory aliasing in a for loop

INSTALL.md
#1843
This moves the custom ingress section to the installation paragraph and formats/rephrases it slightly.
No.
=> Improve the docs about custom ingress

controllers/controllers/workloads/cforg_controller.go
No
This is a follow-on to #2079 
No
See #2079 
=> Don't attempt to add finalizers to deleted orgs

HACKING.md
No.
Various edits on `HACKING.md` to improve spelling and formatting.
No.
=> Improve HACKING.md

controllers/controllers/networking/cfdomain_controller_test.go
https://github.com/cloudfoundry/korifi/issues/2109
This fixes a flake where the domain routes are not deleted upon deleting
the domain. The reason is that the domain may get deleted before the
controllers k8s client manager notices the CFRoutes that reference the
domain.
By awaiting the valid CFRoute status we ensure that controllers
have reconciled the routes at leas once (i.e. are aware of their
existence)
No
N/A
=> Await for valid CFRoute status prior domain deletion

helm/korifi/controllers/crds/korifi.cloudfoundry.org_appworkloads.yaml, helm/korifi/controllers/crds/korifi.cloudfoundry.org_taskworkloads.yaml
No
Regenerate crds (via running `make manifests`) after bumping k8s libs
No
Run `make manifests`, see no diff
=> Regenerate crds after k8s libs have been bumped

api/repositories/route_repository.go
No
Use `Patch` to remove destinations from route. Using `Update` causes occasional flakes
No
N/A
@gcapizzi
=> Use `Patch` to remove route destinations

job-task-runner/controllers/taskworkload_controller.go, job-task-runner/controllers/taskworkload_controller_test.go
#2094
When reconciling task workloads, a job should only be created if it hasn't already been created. Checking the job doesn't exist is not sufficient, since jobs are removed after TTL expires.
This change makes the reconciler check the initialized status condition. A job will only be created if one doesn't exist and the initialized condition is not true.
No
Set TaskTTL to something big, e.g. 1d.
Set JobTTL to something small, e.g. 5s.
Push an app.
Run a task.
See the job gets created, runs and is deleted around 5s after completion.
See the job is never recreated.
=> Don't create job if workload already initialized

api/handlers/service_instance_test.go
Replace rand with crypto/rand
@eirini
=> Fix linter warnings

api/Dockerfile, api/remote-debug/Dockerfile, controllers/Dockerfile
No
This saves 3 iterations of CI with the separate dependabot PRs
=> Bump remaining dockerfile go versions to 1.20.0

api/repositories/build_repository_test.go, controllers/api/v1alpha1/cfprocess_types.go
No
- Remove unused constants
- Mark unused false positives as nolint
No
`make lint` succeeds
@kieron-dev
=> Fix linter issues

.golangci.yml, api/errors/errors_test.go, api/repositories/app_repository_test.go, api/repositories/route_repository_test.go, api/repositories/service_binding_repository_test.go, controllers/controllers/workloads/cforg_controller_test.go, statefulset-runner/controllers/appworkload_to_stset_test.go, tests/e2e/processes_test.go, tests/e2e/service_bindings_test.go
No
Enable Ginkgo golangci-lint linter and address reported issues
No
N/A
@kieron-dev
=> Enable ginkgolinter

controllers/controllers/workloads/env/builder.go, controllers/controllers/workloads/env/builder_test.go, controllers/controllers/workloads/env/env_suite_test.go
No
Make env builder test an integration test
No
green tests
=> Make env builder test an integration test

api/handlers/domain.go, api/handlers/fake/cfservice_binding_repository.go, api/handlers/service_binding.go, api/handlers/service_binding_test.go, api/payloads/service_binding.go, api/presenter/service_binding.go, api/repositories/metadata_test.go, api/repositories/service_binding_repository.go, api/repositories/service_binding_repository_test.go, helm/korifi/controllers/cf_roles/cf_admin.yaml, helm/korifi/controllers/cf_roles/cf_space_developer.yaml, tests/e2e/service_bindings_test.go
https://github.com/cloudfoundry/korifi/issues/1448
- Implement `PATCH /v3/service_credential_bindings/guid`
- Implement `GET /v3/service_credential_bindings/guid`
No
See story
=> Set metadata on Service Binding

api/Dockerfile, api/remote-debug/Dockerfile, controllers/Dockerfile, controllers/remote-debug/Dockerfile
No
Bump golang to 1.20.1 in builders in all Dockerfiles
No
N/A
=> Bump golang to 1.20.1 in builders in all Dockerfiles

controllers/controllers/workloads/env/builder_test.go
No.
This introduces helpers that make sure a creation/patch/deletion is visible to the client before returning. The helpers seem to have eliminated the flakyness we were observing before.
No.
=> Fix flakes in the `env.Builder` integration test

controllers/api/v1alpha1/cfapp_types.go, controllers/controllers/workloads/env/builder_test.go, controllers/controllers/workloads/env/env_suite_test.go, controllers/controllers/workloads/env/vcap_app_builder_test.go, controllers/controllers/workloads/env/vcap_services_builder_test.go, helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfapps.yaml
#2140
- Remove missed raciness from env builder tests after merge
- Make new status field on cfapp optional
No
Deploy korifi-v0.6.0
Push an app on it
Deploy korifi on the branch main
Re-push the app - it should succeed
@gcapizzi
=> Fix up VCAP_APPLICATION problems

tests/e2e/apps_test.go
No
We need an eventually to wait for the re-pushed app to be available and serving the new content
No
=> Fix re-push app flake

api/handlers/fake/cftask_repository.go, api/handlers/task.go, api/handlers/task_test.go, api/payloads/task.go, api/payloads/task_test.go, api/presenter/task.go, api/repositories/task_repository.go, api/repositories/task_repository_test.go
#1943
See issue
No
See issue
@julian-hj
=> App Developer can view and set labels/annotations on Tasks

.github/pull_request_template.md
No
Move the "Things to remember" section of the PR template into a comment so that it isn't visible in the final PR
No
None
@julian-hj
=> Move the "Things to remember" header into a comment

tests/e2e/e2e_suite_test.go
No
This PR restore the user's ability to override the app bits when running the e2e tests in case they do not have a procfile buildpack available. Users now specify the path to the desired app via the `APP_BITS_PATH` env var.
Not really. The override for the e2e tests changed, which could cause unexpected failures.
Run the e2e tests against an environment without a procfile buildpack and see that they pass if `APP_BITS_PATH` is set to another app.
@akrishna90
=> Restore ability to override E2E app bits

Makefile, api/handlers/task_test.go, api/payloads/task_test.go, api/repositories/task_repository_test.go, tests/e2e/e2e_suite_test.go
No
`make fmt` used to generate diffs. Also, exclude `tests/e2e/assests/vendored` from `make fmt`
No
`make fmt` generates no diff
=> Fix formatting in code

api/actions/manifest/applier_test.go, api/actions/manifest/normalizer.go, api/actions/manifest/normalizer_test.go, api/payloads/app.go, api/payloads/manifest.go, api/payloads/shared.go, api/repositories/app_repository.go, api/repositories/app_repository_test.go, tests/e2e/e2e_suite_test.go, tests/e2e/spaces_test.go
=> App Developer can set labels/annotations on Apps via the app manifest

api/handlers/build.go, api/handlers/build_test.go, api/handlers/droplet.go, api/handlers/droplet_test.go, api/handlers/fake/cfdroplet_repository.go, api/handlers/shared.go, api/main.go, api/payloads/build.go, api/payloads/build_test.go, api/payloads/droplet.go, api/payloads/droplet_test.go, api/payloads/shared.go, api/presenter/droplet.go, api/repositories/droplet_repository.go, api/repositories/droplet_repository_test.go, docs/api.md, helm/korifi/controllers/cf_roles/cf_admin.yaml, helm/korifi/controllers/cf_roles/cf_space_developer.yaml, tests/e2e/builds_test.go, tests/e2e/droplets_test.go
#1953
Allow users to set labels/annotations on droplets. Disallow users to set labels/annotations on builds.
no
See issue
@akrishna90 @acosta11
=> Allow users to set labels/annotations on droplets

scripts/account-creation.sh, tests/crds/crds_suite_test.go, tests/crds/crds_test.go, tests/crds/run-crds-tests-kind.sh, tests/smoke/run-smoke-tests-kind.sh
#1568 
See issue
The CRD tests now require 2 environment variables to run, so existing CI tasks and PR checks will likely fail until they are updated
- Run scripts/deploy-on-kind.sh kind
- Run tests/crds/run-crds-tests-kind.sh and confirm it passes
@tcdowney @clintyoshimura
=> Test space creation and assigning user roles in CRD tests

helm/korifi/controllers/crds/korifi.cloudfoundry.org_appworkloads.yaml, helm/korifi/controllers/crds/korifi.cloudfoundry.org_taskworkloads.yaml, tests/crds/crds_suite_test.go
No.
Run `make manifests` and `make fmt`.
No.
@kieron-dev
=> Run `make manifests` and `make fmt`

api/repositories/role_repository.go, api/repositories/role_repository_test.go
#2279 
Fix an issue with validating org requirements with service account role bindings.
No.
Run tests or follow acceptance steps on #2279
@matt-royal @acosta11
=> Fix ServiceAccount name for validate org

tests/crds/crds_test.go
#2267
Add delete functionality (orgs, spaces, & role bindings) to crds test
no
crds test passes
@akrishna90
=> Add delete functionality to crds test

api/handlers/org_test.go, api/presenter/org_test.go
#2255
This starts testing JSON in the presenter tests and simplifies the handler tests.
No.
@gcapizzi
=> Move JSON testing from org handler tests to the presenter package

api/handlers/process_test.go, api/presenter/process.go, api/presenter/process_stats_test.go
#2255
Remove full JSON checking from handlers/process_test.go. This is done in the presenter package now.
No
@gcapizzi
=> Remove full JSON checking in handlers process test

api/handlers/resource_matches_test.go, api/handlers/role.go, api/handlers/role_test.go, api/payloads/role_test.go, api/presenter/role.go, api/presenter/role_test.go
#2255
* Move the full matching of the JSON to the presenter package;
* inject and mock the RequestJSONValidator into the handler to simplify validation tests.
No.
@gcapizzi
=> Improve the role handler tests

docs/using-kubernetes-api-to-create-cf-resources.md, tests/crds/crds_test.go
No
Update the documentation about declaratively creating orgs, spaces and roles
No
Follow the docs and confirm that they're clear and correct.
=> Improve declarative org, space and role documentation

api/handlers/service_instance_test.go, api/presenter/service_instance_test.go
#2255
This moves JSON testing from the service instance handler test to the corresponding presenter test.
No.
@gcapizzi
=> Don't test JSON in the service instance handler test

api/handlers/app_test.go, api/handlers/space_test.go, api/presenter/space.go, api/presenter/space_test.go, api/repositories/space_repository.go, api/repositories/space_repository_test.go
#2255
- Use a string for spaceRecord CreatedAt/UpdatedAt
- Move JSON testing to the space presenter test
No.
@gcapizzi
=> Test JSON in presenter tests

.github/dependabot.yml, .github/workflows/add-issues-to-projects.yml
No
- Remove removed components from dependabot config
- Fix if conditions in add-to-icebox/roadmap GA workflow
@gcapizzi
=> github actions fixes

scripts/deploy-on-kind.sh
No
Remove some redundant complexity from deploy-on-kind.sh
No
Deploy with and withour custom docker registry and be able to push an app
=> Cleanup kind script

kpack-image-builder/controllers/buildworkload_controller.go, kpack-image-builder/controllers/buildworkload_controller_test.go
#2455
If you push the same source code enough times for garbage collection to kick in, it would previously delete the kpack.Build which is also referenced by the current droplet. This would trigger deletion of the droplet OCI image, and then the app would fail.
This fixes that by only deleting kpack.Builds when other buildworkloads don't reference them.
No
Push the same source more than 6 times and see the app continues to work
@kieron-dev
=> Only garbage collect kpack.Builds not referenced by other BuildWorkloads

scripts/deploy-on-kind.sh
No
Most notably:
- Removed the `-r` flag as discussed on standup. We should either use
flags or user env vars to configure a custom docker regisry to push
to. Given that it would be hard to properly handle complex command
line args we prever the env way. We make sure that either all five env
vars that describe a custom registry are passed together or none of
them are passed. This is to avoid insonsistent deployments.
- All registry related env vars are defaulted in one place making it
easier to comprehend what is going on.
- Global vars are all upper case now
- Passing cmd line args has been moved to a function and a main function
has been introduced that calls everything in the right order.
No
Deploy on kind works with and without the custom registry env vars passed
@eirini
=> Cleanup deploy-on-kind script

scripts/account-creation.sh, tests/e2e/apps_test.go, tests/e2e/buildpacks_test.go, tests/e2e/cf_user_test.go, tests/e2e/e2e_suite_test.go, tests/e2e/orgs_test.go, tests/e2e/packages_test.go, tests/e2e/processes_test.go, tests/e2e/routes_test.go, tests/e2e/spaces_test.go
#2377
See issue.
No.
Run E2E tests with the make target. See that the scripts appropriately configure the cluster and the test suite passes.
paired w/ @davewalter
=> E2E tests for role assignment to ServiceAccounts

helm/korifi/api/role.yaml, helm/korifi/controllers/crds/korifi.cloudfoundry.org_appworkloads.yaml, helm/korifi/controllers/crds/korifi.cloudfoundry.org_builderinfos.yaml, helm/korifi/controllers/crds/korifi.cloudfoundry.org_buildworkloads.yaml, helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfapps.yaml, helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfbuilds.yaml, helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfdomains.yaml, helm/korifi/controllers/crds/korifi.cloudfoundry.org_cforgs.yaml, helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfpackages.yaml, helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfprocesses.yaml, helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfroutes.yaml, helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfservicebindings.yaml, helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfserviceinstances.yaml, helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfspaces.yaml, helm/korifi/controllers/crds/korifi.cloudfoundry.org_cftasks.yaml, helm/korifi/controllers/crds/korifi.cloudfoundry.org_taskworkloads.yaml, helm/korifi/controllers/manifests.yaml, helm/korifi/controllers/role.yaml, helm/korifi/job-task-runner/role.yaml, helm/korifi/kpack-image-builder/role.yaml, helm/korifi/statefulset-runner/manifests.yaml, helm/korifi/statefulset-runner/role.yaml
No
Regenerate YAMLs after controller-gen update
No
@kieron-dev
=> Latest controller-gen version means updated yamls

tests/e2e/helpers/fail_handler.go
No
Fix geting the build logs on "droplet not found" failure
No
N/A
@kieron-dev
=> Fix geting the build logs on "droplet not found" failure

tests/e2e/e2e_suite_test.go, tests/e2e/helpers/fail_handler.go
No
- Print events for build pod when droplet not found
- Pre-push the test apps only on GKE
No
Green tests
@kieron-dev
=> Various e2e test improvements

tests/e2e/helpers/fail_handler.go
No
Print Volume Attachments whenever the `Droplet not found` e2e flake takes place
Additional context: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1302#issuecomment-1178020423
No
N/A
=> Print VolumeAttachments on `Droplet not found` flake

controllers/controllers/networking/cfdomain_controller.go, controllers/controllers/networking/cfroute_controller.go, controllers/controllers/networking/cfroute_controller_test.go, tests/e2e/apps_test.go
No
Attempts to fix flake: https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-main/builds/816
No
Green tests
@eirini
=> Do not rely on route status during finalization

controllers/controllers/workloads/cftask_controller_test.go
No
Avoid comparing k8s objects with BeEquivalentTo, as their k8s managed
metadata is subject to change
No
Greent tests
=> Fix flaky test

api/repositories/conditions/await_test.go
Co-authored-by: Georgi Sabev <georgethebeatle@gmail.com>
No
Attempt to fix flake: https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/9277#L64661285:8
No
Green tests
=> Bump timeout in awaiter test to fix flake

api/middleware/http_logging.go
No
Log the URL and method in the HTTP response log entry so that we are sure what is the request a response is for (in case of scrambled logs)
No
N/A
=> Log URL and method in the response HTTP logging

controllers/controllers/networking/cfdomain_controller.go, controllers/controllers/networking/cfroute_controller.go, controllers/controllers/workloads/cfapp_controller.go, controllers/controllers/workloads/cforg_controller.go, controllers/controllers/workloads/cfpackage_controller.go, controllers/controllers/workloads/cfspace_controller.go, controllers/webhooks/version/version_webhook.go, kpack-image-builder/controllers/buildworkload_controller.go, kpack-image-builder/controllers/kpack_build_controller.go
No.
This PR updates controller logging to use the debug log level for informational logging and the info log level for reconciliation error logging.
No.
Deploy, push an app, and observe the controller logs.
=> Fix log levels

controllers/controllers/services/cfserviceinstance_controller.go, controllers/controllers/workloads/cfbuild_controller.go, controllers/controllers/workloads/cfprocess_controller.go, helm/korifi/controllers/role.yaml, helm/korifi/statefulset-runner/role.yaml, statefulset-runner/controllers/appworkload_controller.go
no
Add finalizer update permissions for cfserviceinstances/appworkloads/buildworkloads/statefulsets for OpenShift compatibility
no
All tests pass and e2e tests pass on OpenShift
@acosta11
=> Add finalizer update permissions

api/actions/process_stats_test.go
No
Make usage time verification less strict
No
N/A
=> Fix process stats test

api/Dockerfile, controllers/Dockerfile, controllers/remote-debug/Dockerfile
No
Several dependabot bumps:
- Bump golang from 1.20.4 to 1.20.5 in /controllers
- Bump golang from 1.20.4 to 1.20.5 in /controllers/remote-debug
- Bump golang from 1.20.4 to 1.20.5 in /api
No
N/A
=> dependabot bumps

.golangci.yml, controllers/controllers/workloads/cfspace_controller.go, controllers/controllers/workloads/shared.go, statefulset-runner/controllers/integration/runnerinfo_controller_test.go, statefulset-runner/controllers/runnerinfo_controller_test.go
No
Enable back the ginkgolinter
- The issue with ginkgolinter has been resolved
- Fix a linter warning
- Fix formatting
No
N/A
=> enable ginkgo linter

tests/smoke/smoke_test.go
No
This PR expands the smoke tests to validate the creation and binding of a service instance, and running a task.
No.
Deploy and run the tests.
=> Expand the smoke tests to validate the creation and binding of a service instance, and running a task

controllers/controllers/networking/cfdomain_controller.go, controllers/controllers/networking/cfdomain_controller_test.go, controllers/controllers/networking/cfroute_controller.go, controllers/controllers/networking/cfroute_controller_test.go, controllers/controllers/networking/suite_test.go, controllers/controllers/services/cfservicebinding_controller.go, controllers/controllers/services/cfservicebinding_controller_test.go, controllers/controllers/services/cfserviceinstance_controller.go, controllers/controllers/services/cfserviceinstance_controller_test.go, controllers/controllers/services/suite_test.go, controllers/controllers/shared/index.go, controllers/controllers/workloads/cfapp_controller.go, controllers/controllers/workloads/cfapp_controller_test.go, controllers/controllers/workloads/cfbuild_controller.go, controllers/controllers/workloads/cfbuild_controller_test.go, controllers/controllers/workloads/cforg_controller.go, controllers/controllers/workloads/cforg_controller_test.go, controllers/controllers/workloads/cfpackage_controller.go, controllers/controllers/workloads/cfpackage_controller_test.go, controllers/controllers/workloads/cfprocess_controller.go, controllers/controllers/workloads/cfprocess_controller_test.go, controllers/controllers/workloads/cfspace_controller.go, controllers/controllers/workloads/cfspace_controller_test.go, controllers/controllers/workloads/cftask_controller.go, controllers/controllers/workloads/cftask_controller_test.go, controllers/controllers/workloads/shared.go, controllers/controllers/workloads/suite_test.go
#1935 
This PR updates the org and space controllers to pass the logger to helper functions via the context.
No
@kieron-dev
=> All controllers pass logger in the ctx

api/handlers/deployment.go, api/handlers/deployment_test.go
#2542 
Standardize the RunnerInfo lookup error return against current patterns.
No.
Run tests as normal.
@matt-royal
=> Change Runner info lookup error

api/handlers/app_test.go, api/handlers/build_test.go, api/handlers/deployment_test.go, api/handlers/domain_test.go, api/handlers/droplet_test.go, api/handlers/handlers_suite_test.go, api/handlers/org_test.go, api/handlers/package_test.go, api/handlers/process_test.go, api/handlers/role_test.go, api/handlers/route_test.go, api/handlers/service_binding_test.go, api/handlers/service_instance.go, api/handlers/service_instance_test.go, api/handlers/task_test.go, api/handlers/validator.go, api/handlers/validator_test.go, api/payloads/lifecycle_test.go, api/payloads/process_test.go, api/payloads/service_instance.go, api/payloads/service_instance_test.go
#1996
- Payloads can ignore keys via ignore regexps
- Use the request validator to decode request in handlers
No
N/A
=> Use validator in handlers to decode requests in handlers

tests/e2e/e2e_suite_test.go
#2595
Do not push test apps from e2e suite setup, concourse CI is taking care of it prior running e2es
No
e2e tests succeed
=> Do not push test apps from e2e suite setup

.codeclimate.yml
#2614
Exclude fakes and generated files, and tweak some thresholds:
| Check                       | Failures | Threshold | Action            | New count |
| --------------------------- | -------- | --------- | ----------------- | --------- |
| duplication:identical-code  | 2        | 100       | Force back to 100 | 2         |
| duplication:similar-code    | 70      | 100       | Increase to 400   | 4         |
| structure:argument_count    | 23       | 4         | Increase to 5     | 6         |
| structure:file_lines        | 1       | 250       | Increase to 500   | 1         |
| structure:method_count      | 1        | 20        | Increase to 30    | 1         |
| structure:method_lines      | 8       | 25        | Increase to 50    | 8         |
| structure:return_statements | 56 …
=> Add codeclimate configuration file

api/actions/manifest/applier_test.go, api/handlers/app.go, api/handlers/app_test.go, api/handlers/fake/cfapp_repository.go, api/payloads/app.go, api/payloads/app_test.go, api/payloads/lifecycle.go, api/payloads/lifecycle_test.go, api/payloads/manifest.go, api/repositories/app_repository.go, api/repositories/app_repository_test.go, api/repositories/shared_test.go, controllers/coordination/integration/integration_suite_test.go, controllers/coordination/integration/name_registry_test.go, controllers/coordination/name_registry.go, controllers/coordination/name_registry_test.go, controllers/webhooks/duplicate_validator.go, controllers/webhooks/workloads/suite_integration_test.go, helm/korifi/controllers/role.yaml, kpack-image-builder/controllers/buildworkload_controller_test.go, tests/e2e/apps_test.go, tests/e2e/e2e_suite_test.go, tests/helpers/controllers_user.go
https://github.com/cloudfoundry/korifi/issues/2327
Support for updating app name, buildpacks and stack
No
See story
@kieron-dev
=> Support for updating app name, buildpacks and stack

api/handlers/job.go, api/handlers/job_test.go, api/main.go, api/repositories/role_repository.go, api/repositories/role_repository_test.go, tests/e2e/roles_test.go
#2609
Implement the role deletion job properly so that it waits for the role to get deleted
No
See story
@kieron-dev
=> Report deletion status in role deletion jobs

api/handlers/app.go, api/handlers/app_test.go, api/presenter/app.go, tests/e2e/apps_test.go
#2326
Introduce a dummy ssh enabled endpoint
No
See story
@kieron-dev
=> Implement a dummy app ssh enabled handler

.github/workflows/test-pr.yml, README.helm.md, scripts/check-everything.sh, tools/Makefile
#2653
This PR adds the tools tests to the PR workflows, as well as the check-everything developer script.
No
Check that CI runs the tools tests on PRs.
@acosta11
=> Run tools tests on PRs

kpack-image-builder/controllers/buildworkload_controller_test.go
No
Fix flaky test
No
Greent tests
@gcapizzi
=> Initialize vars to avoid test order issues

INSTALL.kind.md
=> Fix `INSTALL.kind.md`

INSTALL.kind.md
=> Improve INSTALL.kind.md

api/handlers/org.go, api/handlers/org_test.go, tests/e2e/orgs_test.go
#2304
Implement getting an org by org guid
No
See story
@gcapizzi
=> Implement `GET /v3/organizations/org-guid`

api/handlers/space.go, api/handlers/space_test.go, tests/e2e/spaces_test.go
#2303
Implement getting a space by space guid
No
See story
=> Implement `/v3/spaces/[guid]`

.github/workflows/test-pr.yml, tests/helpers/users.go
No
Run staticcheck on PRs
No
staticcheck is run on PRs
=> Run staticcheck in github actions PR flow

api/Dockerfile, api/remote-debug/Dockerfile, controllers/Dockerfile, controllers/remote-debug/Dockerfile
No
Pin golang to 1.20.7 in Dockerfiles
We suspect that 1.21.0 causes issues leading to tests getting stuck
No
All tests passing
=> Pin golang to 1.20.7 in Dockerfiles

api/repositories/buildpack_repository.go
No
Fix a linter error
No
`make lint` succeeds
=> Fix a linter error on memory aliasing

api/payloads/package.go, api/payloads/package_test.go, api/presenter/package.go, api/presenter/package_test.go, api/repositories/package_repository.go, api/repositories/package_repository_test.go, controllers/api/v1alpha1/cfpackage_types.go, helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfpackages.yaml, tests/e2e/e2e_suite_test.go, tests/e2e/packages_test.go
#2791
Support creation of docker packages
No
See story
=> Support creation of docker packages

api/actions/manifest/normalizer.go, api/actions/manifest/normalizer_test.go, api/payloads/manifest.go, api/payloads/manifest_test.go, tests/e2e/e2e_suite_test.go, tests/e2e/spaces_test.go, tests/smoke/smoke_suite_test.go, tests/smoke/smoke_test.go
#2831
Add support for applying docker app manifests
No
See story
=> Support for applying docker app manifests

api/payloads/package.go, api/payloads/package_test.go, api/repositories/dockercfg/dockercfg_suite_test.go, api/repositories/dockercfg/json.go, api/repositories/dockercfg/json_test.go, api/repositories/package_repository.go, api/repositories/package_repository_test.go
#2792
Support private docker images when creating packages
No
See story
=> Support private docker images when creating packages

controllers/controllers/networking/cfroute_controller.go
No
Use `DeepCopy` to copy route destinations
No
=> Use `DeepCopy` to copy route destinations

controllers/controllers/workloads/cfprocess_controller_test.go
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/11806
It could happen that both cfroutes are created in the same second and
there is no stable way to pick the "older" route, which caused this test
to flake.
No
=> Fix CI flake

api/handlers/package.go, api/handlers/package_test.go
https://github.com/cloudfoundry/korifi/issues/2821
Error when uploading package bits to non-bits packages
No
See story
=> Error when uploading package bits to non-bits packages

controllers/controllers/workloads/k8sns/ns_finalizer_test.go
to avoid offending anyone.
No
This change replaces the term "dummy" with "example" to avoid using terms people could find offensive or triggering.
No
Normal tests should cover it. The change only affects a single test file.
=> replace dummy with example

controllers/controllers/workloads/cfspace_controller_test.go
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/12110
Create the service account in `JustBeforeEach` with all the metadata
needed by tests rather than creating it in `BeforeEach` and patch it in
`JustBeforeEach`. This eliminates the potential race condition where the
CFSpace controller has not noticed the service account patch yet.
No
The test does not flake
=> Fix service account propagation flake

controllers/controllers/workloads/cfprocess_controller.go, controllers/controllers/workloads/cfprocess_controller_test.go
https://github.com/cloudfoundry/korifi/issues/2883
Reconcile CFProcesses without route destinations:
* Do not create startup/liveness probes
* Do not set `VCAP_APP_HOST` and `PORT` env vars
No
See story
=> Reconcile CFProcesses without route destinations:

controllers/webhooks/workloads/cfpackage_validator_test.go
No
avoid using the term dummy as someone might find it offensive or triggering
No
Normal test runs should suffice
=> replace dummy with a different string

docs/api.md, docs/docker-apps.md
#2887
Overview of the docker apps support
No
N/A
=> Overview of docker apps support

controllers/controllers/workloads/cftask_controller_test.go
https://github.com/cloudfoundry/korifi/issues/2873
Instead of messing up with the CFTask status that is supposed to be a
repsponsibility of the CFTask controller itself, set the status on the
task workload. We then expect the CFTask controller to notice the workload
change and self-rechedule itself to delete the CFTask in a while.
No
The test does not flake
=> Fix expired CFTask deletion test flake

docs/api.md
No
Update `api.md` to reflect latest API improvements
No
N/A
=> Update `api.md` to reflect latest API improvements

tests/helpers/service_account.go
https://github.com/cloudfoundry/korifi/issues/2923
Bump service account token creation timeout
No
=> Bump service account token creation timeout

Makefile
No
Fixes: https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/bump-tests-vendor/builds/315
Vendir impot path has changed
No
Green tests
=> Fix vendir installation

tests/e2e/apps_test.go
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-e2es-eks-periodic/builds/5005
Thus we ensure that the restart request succeeds
No
=> Check the HTTP status code when restarting the app

controllers/controllers/workloads/env/vcap_app_builder.go, controllers/controllers/workloads/env/vcap_app_builder_test.go, tests/e2e/matchers_test.go
That change add application routes as property "uris" of the env variable VCAP_APPLICATION. 
No
- Deploy a CF application: cf push my-application
- check environment: cf env my-application 
- check property "uris" of env variable VCAP_APPLICATION 
- The list shall be _not null_ and contain application routes. If no routes are configured, it shall be an empty list []
@danail-branekov @georgethebeatle
=> add application uris feature + tests

api/authorization/token_reviewer.go
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-e2es-periodic/builds/12131
Log token reviwe error on invalid tokoen error
No
=> Log token review failure error when it occurs

docs/known-differences-with-cf-for-vms.md
I found that there are some missing features on Korifi side for apps and added those.
=> Extend known differences for Apps

INSTALL.md
The param name in the instructions does not match the name in the helm chart. Instructions -> networking.gatewayClassName. Helm chart -> networking.gatewayClass
No. Documentation update only.
Compare to helm chart: https://github.com/cloudfoundry/korifi/blob/39d33e00434f6f76f7bf39de3bd36df16a4882aa/helm/korifi/values.yaml#L125
=> Correct helm chart variable name

controllers/controllers/workloads/cfpackage_controller_test.go
Co-authored-by: Danail Branekov <danailster@gmail.com>
No
Fixes flake: https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/15736#L65f14fb5:113
No
N/A
=> Fix test flake

tests/smoke/smoke_suite_test.go
#3061
Print more debug logging
No
=> Print leaked namespaces and their pods in smoke tests

controllers/controllers/workloads/cf_docker_build_controller.go, controllers/controllers/workloads/cf_docker_build_controller_test.go
No
Fail docker build when the referenced docker image cannot be fetched. This reports the error to the user immediately.
No
=> Fail docker CFBuild if the package image cannot be fetched

controllers/controllers/workloads/cf_docker_build_controller_test.go
No
Fix a flake in docker image build reconciler
=> Fix a flake in docker image build reconciler

.golangci.yml, controllers/controllers/workloads/cf_buildpack_build_controller.go, controllers/controllers/workloads/cfprocess_controller.go, controllers/controllers/workloads/cfprocess_controller_test.go, controllers/controllers/workloads/cftask_controller.go, controllers/controllers/workloads/env/builder.go, controllers/controllers/workloads/env/builder_test.go, controllers/controllers/workloads/ports/ports.go, controllers/controllers/workloads/ports/ports_suite_test.go, controllers/controllers/workloads/ports/ports_test.go, controllers/controllers/workloads/suite_test.go, controllers/main.go
#3168
Builk process-specific environment in a dedicated env builded
=> refactor env builder

controllers/controllers/services/bindings/controller_test.go
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/16314
Ensure that the test setup simulates the "legacy" UPSI credentials
secret situation
=> Fix a flake in binding controller tests

controllers/cleanup/build_cleaner.go
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-e2es-eks-periodic/builds/7975
Log additional information on build cleanup
We believe that the flake above might be caused by app build disappearing which causes the app not to start. As e2e tests are not cleaning up builds themselves, the smoking gun is the build cleaner
=> Log deletable builds

INSTALL.kind.md, scripts/installer/install-korifi-kind.yaml
No
Adopt dynamic contour provisioning in kind installer
No
Run the kind installer, see it works
=> Update Kind installer with contour dynamic provisioning

README.md
=> Removing the word experimental from README.md

tests/crds/crds_suite_test.go
No
fixes: https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-e2es-periodic/builds/16037
=> More unique org/space names

api/handlers/fake/cfservice_broker_repository.go, api/handlers/service_broker.go, api/handlers/service_broker_test.go, api/presenter/service_broker.go, api/presenter/service_broker_test.go, api/presenter/service_offering.go, api/repositories/service_broker_repository.go, api/repositories/service_broker_repository_test.go, helm/korifi/controllers/cf_roles/cf_admin.yaml, helm/korifi/controllers/cf_roles/cf_root_namespace_user.yaml, tests/e2e/service_brokers_test.go
fixes #3266
Implement `GET /v3/service_brokers`
=> Implement `GET /v3/service_brokers`

api/Dockerfile, api/actions/manifest.go, api/actions/manifest/applier.go, api/actions/manifest/applier_test.go, api/actions/manifest/state_collector.go, api/actions/manifest/state_collector_test.go, api/actions/manifest_test.go, api/actions/shared/fake/cfapp_repository.go, api/actions/shared/fake/cfdomain_repository.go, api/actions/shared/shared.go, api/handlers/app.go, api/handlers/app_test.go, api/handlers/domain.go, api/handlers/fake/cfdomain_repository.go, api/handlers/fake/cfprocess_repository.go, api/handlers/org.go, api/handlers/org_test.go, api/handlers/process.go, api/handlers/process_test.go, api/payloads/app.go, api/payloads/app_test.go, api/repositories/app_repository.go, api/repositories/app_repository_test.go, api/repositories/domain_repository.go, api/repositories/domain_repository_test.go, api/repositories/process_repository.go, api/repositories/process_repository_test.go, api/tools/singleton/singleton.go, api/tools/singleton/singleton_suite_test.go, api/tools/singleton/singleton_test.go
No
Remove `GetXByY` methods in repositories, use `List` instead
No
=> Remove `GetXByY` methods in repositories

api/handlers/fake/cfservice_offering_repository.go, api/handlers/service_offering.go, api/handlers/service_offering_test.go, api/main.go, api/payloads/service_offering.go, api/payloads/service_offering_test.go, api/repositories/service_offering_repository.go, api/repositories/service_offering_repository_test.go
#3270 #3272
Enable service offering filtering by name
=> Enable filtering service offerings by name

api/handlers/fake/cfservice_plan_repository.go, api/handlers/service_plan.go, api/handlers/service_plan_test.go, api/main.go, api/payloads/service_plan.go, api/payloads/service_plan_test.go, api/repositories/service_offering_repository_test.go, api/repositories/service_plan_repository.go, api/repositories/service_plan_repository_test.go
#3271 $3273
Filter service plans by service offering guid
=> Enable service plan filtering by offering guid

api/repositories/app_repository.go, api/repositories/buildpack_repository.go, api/repositories/package_repository.go, api/repositories/role_repository.go, api/repositories/role_repository_test.go, api/repositories/service_offering_repository.go, api/repositories/service_offering_repository_test.go, api/repositories/service_plan_repository.go
No
Replace for loops with go-functional in repositories
=> Replace for loops with go-functional in repositories

tests/smoke/catalog_test.go, tests/smoke/logs_test.go
=> Fix smoke test

statefulset-runner/controllers/appworkload_to_stset.go
No.
Non-functional refactor.
No.
Automated tests.
N/A.
=> Carthatic refactor of some non-functional code

api/handlers/include/resolver.go, api/handlers/include/resolver_test.go, api/handlers/service_instance_test.go, api/handlers/service_offering.go, api/payloads/service_instance.go, api/payloads/service_instance_test.go, api/presenter/resource_test.go, api/presenter/service_instance.go, api/presenter/service_plan.go, api/presenter/shared.go, api/presenter/shared_test.go, api/repositories/relationships/fake/resource.go, api/repositories/relationships/repository.go, api/repositories/relationships/repository_test.go, api/repositories/service_broker_repository.go, api/repositories/service_instance_repository.go, api/repositories/service_instance_repository_test.go, api/repositories/service_offering_repository.go, api/repositories/service_plan_repository.go, model/included.go, model/included_test.go
#3290
- Implement service_plan.service_offering field for managed service instances
=> Implement service_plan.service_offering field for managed service instances

Makefile
Co-authored-by: Georgi Sabev <georgethebeatle@gmail.com>
#3459
Install and use local cf cli for smoke tests
=> Install cf cli under `bin/cf` and use it for smoke tests

docs/known-differences-with-cf-for-vms.md
No.
Fixing a small typo in the docs.
No
None
=> [docs] Fixing small typo

controllers/controllers/services/brokers/fake/broker_client.go, controllers/controllers/services/instances/managed/controller.go, controllers/controllers/services/instances/managed/controller_test.go, controllers/controllers/services/instances/managed/fake/broker_client.go, controllers/controllers/services/osbapi/client.go, controllers/controllers/services/osbapi/client_test.go, controllers/controllers/services/osbapi/clientfactory.go, controllers/controllers/services/osbapi/types.go
No
Use query parameters for service instance last operation
No
=> Use query parameters for service instance last operation

scripts/installer/install-korifi-kind.yaml
No
Smoother user experience for installer job
=> Installer retries connecting to local registry

INSTALL.md
Commit 01bfef3810269abe97ced558b74ab70ae91fda67 moved the location of the deployment config. This PR adjusts sources to changes.
No
=> Update API deployment config reference

scripts/run-tests.sh, tests/e2e/processes_test.go, tests/smoke/apps_test.go, tests/smoke/bind_service_test.go, tests/smoke/catalog_test.go, tests/smoke/logs_test.go, tests/smoke/run_task_test.go, tests/smoke/services_test.go, tests/smoke/suite_test.go
No
Run smoke tests in parallel
=> Run smoke tests in parallel

api/main.go, api/repositories/service_instance_repository.go, api/repositories/service_instance_repository_test.go, tests/e2e/e2e_suite_test.go, tests/e2e/service_plans_test.go, tests/smoke/bind_service_test.go, tests/smoke/services_test.go
fixes #3574
#3574
Error when creating service instances for disabled plan
No
=> Error when creating service instances for disabled plan

api/handlers/service_binding_test.go, api/handlers/service_instance_test.go, api/payloads/service_binding.go, api/payloads/service_binding_test.go, api/payloads/service_instance.go, api/payloads/service_instance_test.go, api/repositories/repositories_suite_test.go, api/repositories/service_binding_repository.go, api/repositories/service_binding_repository_test.go, api/repositories/service_instance_repository.go, api/repositories/service_instance_repository_test.go, controllers/api/v1alpha1/cfservicebinding_types.go, controllers/controllers/services/bindings/controller.go, controllers/controllers/services/bindings/controller_test.go
No
Filter service instances and bindings by plan guid
No
=> Filter service instances and bindings by plan guid

api/handlers/fake/stack_repository.go, api/handlers/stack.go, api/handlers/stack_test.go, api/main.go, api/presenter/stack.go, api/repositories/stack_repository.go, tests/e2e/stack_test.go
#1172
Adding endpoint /v3/stacks
No
Code is inspired by the buildpacks implementation.
As the issue states to only focus on providing the endpoint without any filters, I will work on implementing the filters after this one is merged
=> Add /v3/stacks endpoint; Fixes #1172

api/repositories/package_repository.go, api/repositories/package_repository_test.go, api/repositories/service_binding_repository.go, api/repositories/service_binding_repository_test.go, controllers/api/v1alpha1/appworkload_types.go, controllers/api/v1alpha1/builderinfo_types.go, controllers/api/v1alpha1/buildworkload_types.go, controllers/api/v1alpha1/cfapp_types.go, controllers/api/v1alpha1/cfbuild_types.go, controllers/api/v1alpha1/cfdomain_types.go, controllers/api/v1alpha1/cforg_types.go, controllers/api/v1alpha1/cfpackage_types.go, controllers/api/v1alpha1/cfprocess_types.go, controllers/api/v1alpha1/cfroute_types.go, controllers/api/v1alpha1/cfservice_offering_types.go, controllers/api/v1alpha1/cfservice_plan_types.go, controllers/api/v1alpha1/cfservicebinding_types.go, controllers/api/v1alpha1/cfservicebroker_types.go, controllers/api/v1alpha1/cfserviceinstance_types.go, controllers/api/v1alpha1/cfspace_types.go, controllers/api/v1alpha1/cftask_types.go, controllers/api/v1alpha1/doc.go, controllers/api/v1alpha1/groupversion_info.go, controllers/api/v1alpha1/runnerinfo_types.go, controllers/api/v1alpha1/taskworkload_types.go, controllers/controllers/workloads/packages/controller_test.go, controllers/controllers/workloads/processes/controller_test.go, model/services/doc.go
no
This PR introduces minor changes to the `controllers/api` package, to make it compatible with the https://github.com/kubernetes/code-generator project. This project can be used as an alternative for the `controller-gen`'s deepcopy generator. Also it brings missing features like generation of typed clients and `applyconfiguration`'s for proper SSA support.
no
=> Improve compatibility with the `code-generator` project

docs/custom-buildpacks.md
#2667 
This change adds a documentation on how to add custom buildpacks or use your own ClusterBuilder
No
None.
=> Add Custom Buildpacks Documentation; Fixes #2667

api/handlers/stack.go
No
Fixing a C & P issue with error messages
No
=> Fix Copy & Paste issues with Stack error message

controllers/controllers/services/bindings/controller_test.go, controllers/controllers/services/bindings/upsi/controller.go, controllers/controllers/services/instances/upsi/controller.go, controllers/controllers/services/instances/upsi/controller_test.go
#3520
Remove legacy secret reconcilation in instances and bindings 
No
=> Remove legacy secret

Makefile, controllers/controllers/services/instances/upsi/controller.go
No
fix instance last operation logic
No
=> Fix instance last operation logic

api/actions/manifest/applier.go, api/actions/manifest/applier_test.go, api/handlers/service_binding.go, api/handlers/service_binding_test.go, api/payloads/service_binding.go, api/payloads/service_binding_test.go, api/repositories/service_binding_repository.go, api/repositories/service_binding_repository_test.go, api/repositories/service_instance_repository_test.go, api/repositories/service_offering_repository_test.go, controllers/api/v1alpha1/cfservicebinding_types.go, controllers/api/v1alpha1/groupversion_info.go, controllers/api/v1alpha1/shared_types.go, controllers/controllers/services/bindings/controller.go, controllers/controllers/services/bindings/controller_test.go, controllers/controllers/services/bindings/managed/controller.go, controllers/controllers/services/bindings/sbio/servicebinding.go, controllers/controllers/services/bindings/sbio/servicebinding_test.go, controllers/controllers/workloads/apps/controller_test.go, controllers/controllers/workloads/build/buildpack/controller_test.go, controllers/controllers/workloads/env/vcap_services_builder_test.go, controllers/webhooks/finalizer/webhook_test.go, controllers/webhooks/relationships/webhook_test.go, controllers/webhooks/version/version_test.go, helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfservicebindings.yaml, tools/collections.go, tools/collections_test.go
#2320
Introduce service bindings of type `key`
@georgethebeatle @uzabanov @ddraganovv
=> Added service binding of type key

helm/korifi/kpack-image-builder/cluster-builder.yaml, helm/korifi/values.schema.json, helm/korifi/values.yaml
no
Make list of buildpacks in the `ClusterStore` configurable via Helm values
no
=> Disallow `ClusterStack` configuration

docs/experimental-uaa-authentication.md
No
Experimental UAA support documentation
=> Document experimental UAA support

api/repositories/process_repository.go, api/repositories/process_repository_test.go, api/repositories/repositories_suite_test.go
Kind of related to #3755
Improve process repository test
=> Improve process repository test

controllers/api/v1alpha1/cfserviceinstance_types.go, helm/korifi/controllers/crds/korifi.cloudfoundry.org_cfserviceinstances.yaml
#3808
Use camelcase in json annotations for CFServiceInstance
=> Use camelcase in json annotations for CFServiceInstance

api/Dockerfile, api/handlers/fake/cfservice_binding_repository.go, api/handlers/service_binding.go, api/handlers/service_binding_test.go, api/main.go, api/repositories/broker_parameters_client.go, api/repositories/service_binding_repository.go, api/repositories/service_binding_repository_test.go
[Issue](https://github.com/cloudfoundry/korifi/issues/3751)
This is 2 of 2 PRs related to the above issue. With this PR there is a new handler implemented to the service binding endpoints - "/v3/service_credential_bindings/{guid}/parameters"
No
=> Added GetServiceBinding to the broker client

statefulset-runner/main.go
No
Remove unneeded annotations
=> Remove redundant counterfeiter annotations

INSTALL.md
No
Remove servicebinding.io from install docs
=> Remove the servicebinding.io dependency from the install docs

docs/custom-buildpacks.md, helm/korifi/kpack-image-builder/cluster-builder.yaml, scripts/assets/templates/kind-builder.yml
-
The project decided to [move away from GCR](https://paketobuildpacks.slack.com/archives/C011S6EL49L/p1743078482582569). This change adapts all related links.
No.
-
-
=> Change paketo registry to dockerio

api/repositories/app_repository.go, api/repositories/droplet_repository.go, api/repositories/droplet_repository_test.go
#3920
Refactor list droplets message with klient list options
=> Refactor list droplets message with klient list options

api/presenter/service_instance.go, api/presenter/service_instance_test.go
#2362
Introducing the Service Plan Relationship for Service Instances.
No
```
cf create-service 
cf service --guid
cf curl /v3/service_instances/<guid>
```
should have a service_plan link now.
=> #2362 Introduce Service Plan Relationship

api/payloads/service_instance.go, api/payloads/service_instance_test.go
https://github.com/cloudfoundry/korifi/issues/3952
Here we simply add the missing field parameters for listing service instances 
No
=> Add missing field params for listing service instances

scripts/installer/run-locally.sh
No
- It takes a release version as an optional argument.
- If releases version is passed it will not build any images and will
simply apply the released installer for the given verion.
- If no version is passed it builds dev images and interpolates them
into the job definition and then applies the resulting dev definition
- It does not delete the kind cluster - this is left to the user
- This way testing migrations from old release versions to current dev
version is much easier and quicker
=> Improve scripts/installer/run-locally.sh

api/authorization/namespace_permissions.go, api/authorization/namespace_permissions_test.go, api/authorization/space_filtering_client.go, api/repositories/repositories_suite_test.go, api/repositories/space_repository.go, api/repositories/space_repository_test.go, controllers/api/v1alpha1/cfspace_types.go, controllers/controllers/workloads/spaces/controller.go, controllers/controllers/workloads/spaces/controller_test.go, controllers/webhooks/label_indexer/webhook.go, controllers/webhooks/label_indexer/webhook_test.go, helm/korifi/controllers/manifests.yaml, helm/korifi/migrations/post-upgrade-set-migrated-by.yaml
#3988
Use label selectors when filtering spaces on list
=> Use label selectors when filtering spaces on list

api/repositories/role_repository.go, api/repositories/service_offering_repository.go, api/repositories/service_offering_repository_test.go, api/repositories/shared.go, api/repositories/space_repository.go, controllers/api/v1alpha1/cfservicebinding_types.go, controllers/api/v1alpha1/shared_types.go, controllers/webhooks/label_indexer/webhook.go, controllers/webhooks/label_indexer/webhook_test.go, helm/korifi/migrations/post-upgrade-set-migrated-by.yaml
#3988
Purge offerings uses label selector to find related resources
=> Purge offerings uses label selector to find related resources

api/main.go
No. This is a fix for acceptance
Dynamically load certificates in server tls config
- In the server tls config provide a custom GetCertificate func that
fetches the correct cert (in its current state)
- This way we do not have to restart the apiserver when a cert is
reissued by cert manager
=> Watch both server certs in korifi api

api/main.go, api/repositories/image_repository.go, api/repositories/image_repository_test.go, api/repositories/log_repository.go, api/repositories/log_repository_test.go, api/repositories/metrics_repository.go, api/repositories/pod_repository.go, api/repositories/pod_repository_test.go, api/repositories/repositories_suite_test.go, tests/e2e/droplets_test.go
No
Use userClientFactory for non-korifi resources
=> Use userClientFactory for non-korifi resources

docs/architecture-decisions/0020-list-results-filter-sort-page.md
#3701
List filter, sort, page ADR
=> List filter, sort, page ADR

tests/smoke/list_test.go
#3701
Smoke test for GET /v3/routes/{guid}/destinations
=> Smoke test for GET /v3/routes/:guid/destinations

api/handlers/service_broker_test.go, api/payloads/service_broker.go, api/payloads/service_broker_test.go, api/repositories/service_broker_repository.go, api/repositories/service_broker_repository_test.go
#3701
Ordering for service brokers
=> Ordering for ServiceBrokers

api/handlers/fake/cfservice_plan_repository.go, api/handlers/service_instance_test.go, api/handlers/service_offering.go, api/handlers/service_plan.go, api/handlers/service_plan_test.go, api/payloads/service_offering_test.go, api/payloads/service_plan.go, api/payloads/service_plan_test.go, api/repositories/relationships/fake/service_plan_repository.go, api/repositories/relationships/repository.go, api/repositories/relationships/repository_test.go, api/repositories/service_plan_repository.go, api/repositories/service_plan_repository_test.go, tests/smoke/list_test.go
#3701
Paging and ordering for service plans
=> Paging and ordering for service plans

api/repositories/stack_repository_test.go
https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/26031
Fix repo test flake
=> Fix repo test flake

api/repositories/build_repository.go, api/repositories/build_repository_test.go
No
Fix ordering when getting the last app build
=> Fix ordering when getting the last app build

scripts/deploy-on-kind.sh
=> Fix deploy on kind

helm/korifi/README.md
No
Add a README.md to the helm chart. It is going to be displayed in artifacthub.io
=> Add a reamde in the helm chart
